### ISSUE TITLE
extras tab missing

### ISSUE THREAD

**Issue by MasteRehm** [Ericsson/exchangecalendar#100]
Hi,

as mentionend in https://github.com/Ericsson/exchangecalendar/issues/99 there should be an extras tab under preferences, but there isn't. As you can see:
![20150209](https://cloud.githubusercontent.com/assets/5485947/6104639/9c1e4128-b04f-11e4-800a-c296606479b4.png)

**Comment by bavincen** [comment]
Sorry for the trouble 😐 may I know which Language are you using in your thunderbird?

**Comment by MasteRehm** [comment]
I appreciate your help. Thx.
I using german as language in thunderbird.

**Comment by bavincen** [comment]
hi, seems fixed please check and update your locale language :)
