### ISSUE TITLE
Calendar fails to load under Thunderbird 36.0b1 / Lightning 3.8b1

### ISSUE THREAD

**Issue by ronjouch** [Ericsson/exchangecalendar#102]
Since upgrading to the latest official beta ([Tb build](https://ftp.mozilla.org/pub/mozilla.org/thunderbird/releases/36.0b1/), [Lightning build](https://ftp.mozilla.org/pub/mozilla.org/calendar/lightning/candidates/3.8b1-candidates/)), Exchange EWS Provider 3.3.1~rc2 fails to load my Exchange calendar, with the following error message:

    An error was encountered preparing the calendar located at https://auto/a51cc46f-8d65-4cf4-9b6c-ec88bb7162cb for use. It will not be available.
    Error code: 0xTypeError: redeclaration of var attendee
    Description: TypeError: redeclaration of var attendee

Am available to provide more debug information. Thanks for maintaining this addon!

**Comment by bavincen** [comment]
Hello ronjouch
We did not fix  that issue in latest release.
Please download zip file and use that which is working one



If  it is difficult for you in that case  y ou can also downgrade your lightning and use that  till our next release.

**Comment by ronjouch** [comment]
@bavincen sorry I don't understand what you mean by *"Please download zip file and use that which is working one"*. I'd be glad to test what you suggest.

Regarding your suggestion 2 (*"downgrade your lightning"*), note that because Lightning versions are tightly coupled to Thunderbird versions, that would require me to downgrade Tb too, which I'd rather avoid because I like to stay on the beta channel to report bugs.

**Comment by ronjouch** [comment]
Got it, you're saying this issue is fixed in master, which I can get by using the "Download as ZIP" feature of GitHub, then re-pack the zip to get rid of the nested folder, and install. It works! :+1: , thanks.

**Comment by ronjouch** [comment]
Was a dup of https://github.com/Ericsson/exchangecalendar/issues/98 , fixed by https://github.com/Ericsson/exchangecalendar/commit/be053f8598c1b04d0957831e090350959226e131

**Comment by meggersatmonsoon** [comment]
I'm getting this exact error. My calendar will not load.

**Comment by aoeftiger** [comment]
+1 meggersatmonsoon, I encounter exactly the same error after updating to the newest Thunderbird and Lightning. I tried reinstalling this extension via the github version and still got the same error...

**Comment by muthusuba** [comment]
@meggersatmonsoon : you would want to open a new bug, please?
Also, which version (of this plugin) worked for you?
