### ISSUE TITLE
3.3.1RC2 does not work with Thunderbird 36b1 / Lightning 3.8b1

### ISSUE THREAD

**Issue by brenboy** [Ericsson/exchangecalendar#104]
After Thunderbird upgraded to 36b1 and I manually upgraded Lightning to 3.8b1, my Exchange connected calendar created using the Exchange EWS Provider Add-on 3.3.1 RC2 and Lightning 3.6b3 is not recognised and I'm no longer able to create a new Exchange calendar. 

The Lightning developer believes it is an issue with the Exchange EWS Provider Add-on:

"It seem that the Exchange EWS provider extension has not been updated to the new behavior. From a first look the problem might be located in https://github.com/Ericsson/exchangecalendar/blob/v3.3.1-rc2/interfaces/exchangeBaseItem/mivExchangeBaseItem.js#L3811 because the variable attendee is already declared in https://github.com/Ericsson/exchangecalendar/blob/v3.3.1-rc2/interfaces/exchangeBaseItem/mivExchangeBaseItem.js#L3805 but there might be more incorrect usages.

Resolving as Invalid because this has to be fixed by the author of the Exchange EWS provider extension to support applications based on Gecko 35."

**Comment by brenboy** [comment]
![calendar_create_failure](https://cloud.githubusercontent.com/assets/11042234/6226263/85932650-b6e7-11e4-84d1-001ee55c958b.png)

**Comment by bavincen** [comment]
Hi We have already fixed this issue.
you can use our latest code.

**Comment by Dominique-2202** [comment]
Hi,
      
      Could you try to use the zip file here: 
      https://github.com/Ericsson/exchangecalendar/archive/master.zip
      It looks like the latest changes / corrections are not yet into
      the 3.3.1~RC2 version
      
      (I guess you know that you get the zip file, rename it to
      calendarexchange.xpi and then manually install this file in
      Thunderbird)
      Hope this helps....
      
        
        
        
          Best regards,
          
          Dominique 
      On 2/17/2015 10:57 AM, brenboy wrote:
    
    
      
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by brenboy** [comment]
Hi Dominique,

When I download the master zip file, rename it to calendarexchange.xpi and then manually install this file in Thunderbird, I get an error message saying "This add-on could not be installed because it appears corrupt".

I downloaded a few different times now. I running Thunderbird on Mac OS X 10.10.2.

Am I missing a step?

**Comment by Dominique-2202** [comment]
Mmm, I don't really know....
Try this:
download zip
extract file in zip
check if install.rdf file specifies your Tbird version, if not upadte it (any editor will do)
save install.rdf
compress the files and directory again into a zip file
change this file to an xpi extension
try to manually install it again

Hope this will work this time
Dominique

**Comment by brenboy** [comment]
Upgrading to 3.3.1RC3 fixed the issue. Thanks for your help

**Comment by muthusuba** [comment]
@Dominique-2202 Thank you!
@brenboy Thank you for confirming!
