### ISSUE TITLE
Delete calender entry on received cancellation mail

### ISSUE THREAD

**Issue by bonanza123** [Ericsson/exchangecalendar#106]
Hi, currently, it is the case then whenever I get a mail that a certain appointment has been canceled, the appointment is not deleted but a 'canceled: ' is prepended to the title. An option would be nice to automatically delete those cancelled appointments.

**Comment by bavincen** [comment]
you may check here.
https://github.com/Ericsson/exchangecalendar/wiki/Troubling-cancelled-events

**Comment by bonanza123** [comment]
Thanks for the link. Unfortunately, I cant find this option in the Thunderbird settings. Can you help me?

**Comment by bavincen** [comment]
Hi! 
RightClick on the calendar 
then click EWS settings 
select Auto Processing Tab
there you will find the check box to enable/disable
![calendar-ews-autoprocessing](https://cloud.githubusercontent.com/assets/8401561/6328595/0a76f3dc-bb8f-11e4-9d97-3256b1ba6a5d.png)
