### ISSUE TITLE
"check  for Updates"  doesn't seem to work

### ISSUE THREAD

**Issue by tfft** [Ericsson/exchangecalendar#107]
Hi, doing an update on the add-ons doesn't seem to pick-up the new RC's (I'm currently using 3.3.1-RC2 and there is a new RC3 out).  Even if you click on the package within the add-on page within Thunderbird and click on the "Check for Updates" no indicator of a new release (candidate or otherwise) is shown.  The process should at a min note that there is something new and leave it to the user to decide whether he/she would like to update.

This might be helpful to note to users that there is active development taking place and could potentially result in more testers.

Thanks !

**Comment by bavincen** [comment]
hi, i think you selected 'not to inform you about update' last time.
:)
you can change the preference value in thunderbird config :)

**Comment by bavincen** [comment]
Please follow this link.

https://github.com/Ericsson/exchangecalendar/wiki/How-to-enable-Auto-update

**Comment by tfft** [comment]
Hi, thank you for the update.  I had "extensions.1st-setup.others.checkForNewAddOnVersion" already set to 'True' but that didn't note that there was a new RC for me today when I checked even though there was a new release - doesn't that sound like a problem ?

I'll toggle "extensions.1st-setup.others.warnAboutNewAddOnVersion" from 'False' to 'True' for consistency though I see this variable as a 'running in the background' process to generate warnings.

In passing, on Windows to access those variables, one will have to,

Tools -> Options -> Advanced TAB -> General sub-TAB -> click on "Config Editor"

Regards.

**Comment by bavincen** [comment]
I guess the naming of  new addon affects alerting on new version when available. I mean mozilla addon service unable to find  release as new version.
Anyhow we are checking it 😊 thank you!


-----Original Message-----

**Comment by tfft** [comment]
If this issue being re-checked and a bug/problem possibly exists then this item should be re-opened.

Thanks.

**Comment by bavincen** [comment]
Hi please use wiki to enable update options.

please  grep ur log "updater" "onupdate"  to see error on startup
also set proxy in thunderbird if you are using one.

**Comment by bavincen** [comment]
@tfft please close this issue if it is resolved :)

**Comment by tfft** [comment]
Hi, now that there is a new release, RC5, the auto update isn't able to pick it up.  Both clicking on the tools wheel icon and selecting "Check for Updates" as well as the clicking on the "More" for the add-on and then clicking on the Automatic Updates "Check for Updates" results in nothing (ie. No updates found).

In short, the original problem is still there - auto update doesn't seem to be working as intended.  If I don't check the add-on's GitHub page I would never know that a new release exists.

**Comment by bavincen** [comment]
Hi @tfft
https://github.com/Ericsson/exchangecalendar/wiki/How-to-enable-Auto-update
That's a quick guide to enable auto update in the wxtension

-----Original Message-----

**Comment by tfft** [comment]
Hi, I already have the automatic check enabled along with those two values set to "true" yet the new RC5 is not being detected and thus no auto-update.  Do please revisit as I believe the problem is still there.

**Comment by bavincen** [comment]
Are you seeing the alert box? For updates


-----Original Message-----

**Comment by tfft** [comment]
No, nothing - even when I press on the check for updates within the Add-ons nothing new is noted.

**Comment by tfft** [comment]
Hi, I restarted Thunderbird (I don't do that often - maybe once a week) and got the pop-up dialog noting the existence of 3.3.1 but still when I click on the "Tools->Add-on->GEAR_WHEEL->Check for Updates" I get nothing.

This needs to be corrected, the bug certainly seems there in function !

**Comment by bavincen** [comment]
Hello
Actually checking it from add on page is working for us. Need to fix.

Btw  you have auto update options in preference 
Please refer wiki
On the next thunderbird restart you will be alerted

-----Original Message-----

**Comment by tfft** [comment]
Hi.  As noted, I have the settings per the WIki page and I am getting the alert upon a restart but I am NOT getting an indicator if I check for it manually.

I'm guessing you're confirming that the problem is indeed there if a manual check is made, if so do please re-open this bug to get it addressed.

Thanks.

**Comment by bavincen** [comment]
yes

**Comment by tfft** [comment]
BTW - this is no longer a question (with regard to the label on this issue) but a confirmed bug, right ?  If so, do please update the label accordingly.

Thanks.

**Comment by bavincen** [comment]
![screenshot from 2015-03-20 09 22 22](https://cloud.githubusercontent.com/assets/8401561/6745797/a70c50c8-cee2-11e4-9c6d-c0eec92e6fd0.png)

**Comment by bavincen** [comment]
hi this one needs a explicit download url in precious release.
something like <t:updateUrl - in install.rdf

git hub download url are different to versions.

**Comment by tfft** [comment]
What about using symbolic links and doing date checks maybe (have the notion of an ever evolving "latest" possibly) ?  How do the other add-ons deal with this as they seem to have figured out how to make this check happen seamlessly anytime one presses on the "Check for Updates" button.

**Comment by bavincen** [comment]
nope it is not possible. it works with mozilla addon repo.. 
rightly updates are happening through github 

Thanks

**Comment by tfft** [comment]
Why not upload the updates to mozilla's addon repo then ?  At a minimum include the non-beta releases...  This would reach a much wider/larger audience.

**Comment by bavincen** [comment]
You can help us in this.. @tfft
