### ISSUE TITLE
Can not edit server URL

### ISSUE THREAD

**Issue by UnitedMarsupials** [Ericsson/exchangecalendar#109]
I just installed the 3.3.1rc3 and tried to add my corporate account. After selecting "Exchange 2007/2010/2013", naming it, and picking my e-mail address, I got the screen with the form to fill-out.

However, the "Server URL" field in it is prepopulated with https://ews.example.com/ews/exchange.asmx, *which can not be edited*. Nothing I enter on the form unblocks the field. Attempts to run "autodiscovery" simply hang for ever.

Although the "Primary email address" field is also shown greyed-out originally, it can be edited -- and changes color to active, when edited. The URL-field can not and does not...
![transitions1](https://cloud.githubusercontent.com/assets/1486340/6253439/57e73d80-b76f-11e4-9f56-b78f1a036823.png)

**Comment by jdall** [comment]
What happens if you click in the "Server URL" text box and just start typing?

**Comment by UnitedMarsupials** [comment]
> What happens if you click in the "Server URL" text box and just start typing?

Well, I could not do this earlier... But now that I'm trying again, it is editable. How embarrassing... What must've confused me, was that I could not place the cursor anywhere other than at the beginning of the field, nor could I "select" the contents of it.

Now, if only I knew, what to type -- for office365.com? Shouldn't I be able to retain the valid parts of the example provided (such as /ews/exchange...)? Thank you!

**Comment by bavincen** [comment]
Hi
is it working now?

**Comment by UnitedMarsupials** [comment]
Yes, I got it to work. Thank you!
