### ISSUE TITLE
Missing calendar sort icon

### ISSUE THREAD

**Issue by tfft** [Ericsson/exchangecalendar#110]
Hi, I'm using 3.3.1-RC3 and the previously work (on RC2) calendar invite icon indicator seems to have vanished.  Please see attached image; the highlighted email is a meeting invite yet there the calendar icon is missing (note sort column).

Regards.
![capture](https://cloud.githubusercontent.com/assets/10126620/6261951/9b6970ca-b812-11e4-875f-8b0f60516571.PNG)

**Comment by bavincen** [comment]
We are not logging anything here. :)
are you getting the icons in rc2?

**Comment by tfft** [comment]
That particular invite I had to accept and so its gone (not sure where the email invites vanish to - they are not in the junk folder so I'm guessing they simply get sucked into the calendar and disappear).  I've had subsequent email invites from the same person and the icons are showing up - so I don't know if that was a glitch or a special invite or post laptop hibernation relic or ...  I'll certainly keep an eye out on any abnormalities on this topic and report back.

But as it stands now things seem to be working fine regarding this topic.

**Comment by muthusuba** [comment]
@tfft It takes a while to show up the icons and sync...so, I guess, it was just a delay...
Closing this then...please reopen if you see the problem again...Thanks!
