### ISSUE TITLE
Webex Integration ?

### ISSUE THREAD

**Issue by tfft** [Ericsson/exchangecalendar#111]
Hi, I'm sure this question will come-up sooner or later.  Have there been any thoughts and/or plans on adding Webex integration ?  I did a quick "webex" search in Mozilla's Add-on site and didn't find anything.  I'm not sure if this functionality could be part of this add-on or ought to be its own separate "package".

In outlook adding a webex link/details is as simple as clicking on a "include webex" dialog/box and it replaces part of the email body with its details once the email invite is sent out.  Similar integration would be ideal to have in Thunderbird.

Would love to hear what others think on this topic...

Regards.

**Comment by bararchy** [comment]
+1 for this.

**Comment by brenboy** [comment]
+1

**Comment by aledovsky** [comment]
:-1:

Let's keep this add-on doing what it is best at - allowing usage of Exchange calendar in Thunderbird.

**Comment by pdunbar-methods** [comment]
I agree with aledovsky.  I'd rather see a well-written webex add-on than see this project serve two masters.

**Comment by muthusuba** [comment]
I believe so as well! Closing this for now ....
