### ISSUE TITLE
Snooze only works intermittently

### ISSUE THREAD

**Issue by ermingol** [Ericsson/exchangecalendar#114]
Very often when I snooze a reminder, the snooze request does not "take". I can see in Thunderbird that a job is sent to Exchange server and that it is handled. But the reminder does not go away. I can repeat the snooze operation a gazillion number of times and it does not go away. But if I click in "dismiss" the reminder goes away...

**Comment by bavincen** [comment]
Okay! For your surprise we have already fixed this bug.. Hope you will not have it in next release 
Closing it.. 😊

**Comment by ermingol** [comment]
Excellent! :)
    
    /John
    
    On 2015-02-23 14:15, bavincen wrote:
    
    
      
      Okay! For your surprise we have already fixed this bug.. Hope
        you will not have it in next release Closing it.. 😊
      
      —
        Reply to this email directly or view
          it on GitHub.
