### ISSUE TITLE
Reminders opens in modal dialogs

### ISSUE THREAD

**Issue by ermingol** [Ericsson/exchangecalendar#115]
When a reminder pops up it is a modal dialog that is always on top of Thunderbird and that steals all focus. This is extremely annoying and needs to be changed so that I can move the reminder window to the back of other windows (like when I'm typing a mail and want to finnish that before dealing with the reminder).

**Comment by bavincen** [comment]
This is how lightning behaves.. 😊
Btw.. I am able to minimize.

**Comment by ermingol** [comment]
Ahhhh. Ok. Then I have to file this bug report towards Lightning
    then. Thanks!
    
    Minimizing works, but it still steals my focus! :@ ;)
    
    
    /John
    
    On 2015-02-23 14:13, bavincen wrote:
    
    
      
      This is how lightning behaves.. 😊Btw..
        I am able to minimize.
      —
        Reply to this email directly or view
          it on GitHub.
