### ISSUE TITLE
Not possible to close reminders in exchangecalendar 3.3.0

### ISSUE THREAD

**Issue by victoraleo** [Ericsson/exchangecalendar#117]
Hi,

It happens very often that a reminder windows can not be dismissed nor snoozedl. The pressing either "Dismiss All", "Dismiss", "Snooze for" or "Snooze All for" the windows it is not closed. The only way to solve this problem is to restart Thunderbird (v. 31.4.0) with exchangecalendar 3.3.1~rc3 (but the same problem can be reproduced on 3.3.0 as well).

Regards,

/Victor

**Comment by bavincen** [comment]
Hi @victoraleo
We have already fixed this one. Please wait for our next release or use our latest code. Please refer wiki page to use latest addon.
 closing it. Thanks

-----Original Message-----

**Comment by victoraleo** [comment]
Thanks for the quick answer!

I will wait until the next release then.

Regards,

/Victor
