### ISSUE TITLE
Cache gets disabled randomly

### ISSUE THREAD

**Issue by LunaticoCR** [Ericsson/exchangecalendar#120]
I've noticed that the exchange-cache option gets disabled every now and then, not sure what causes it.

Is it recommended to have the exchange-cache turned on?

**Comment by bavincen** [comment]
Hello  @daniel
Is this happening in rc4?

thanks

-----Original Message-----

**Comment by daniel** [comment]
Wrong Daniel :)

**Comment by LunaticoCR** [comment]
Hi @bavincen 
I only updated to rc4 yesterday... I'll keep an eye on it and I'll let you know if it happens again.

**Comment by LunaticoCR** [comment]
Hi,

This happened again. Today I checked and exchange-cache is disabled.
I'm running 3.3.1~rc4

Are there any logs that I could give you?

**Comment by bavincen** [comment]
The problem still occurs?
If you are often changing cache preference, please notice if any other task is happening in calendar

you can provide us log here or to our github mail id

before..
https://github.com/Ericsson/exchangecalendar/wiki/Logging-Calendar-with-options
 
please enable detailed log for all..

**Comment by LunaticoCR** [comment]
I've been running TB with logs turned on and the issue hasn't happened. I'm thinking the issue might be timing related as having the logs on slows down the application significantly.

**Comment by bavincen** [comment]
@LunaticoCR we fixed this issue already still, looking to get some feedback because some users facing the problem

https://github.com/Ericsson/exchangecalendar/commit/aea11da3944990b54a8b67878023fd007b253f60

**Comment by LunaticoCR** [comment]
Just to let you know that this happened again today, I'm using latest release of 3.3.1.
Unfortunately I had turned logging off.

**Comment by bavincen** [comment]
hi @LunaticoCR  Is that happened after you did some enabling or disabling in cache settings.

**Comment by LunaticoCR** [comment]
Hi @bavincen , I didn't enable or disable cache. But I think I did go into EWS properties and cleared cache. Some times I start getting a meeting notification and no matter how many times I click dismiss or I restart Thunderbird the meeting notification keeps popping up. The only way I've found to fix this is by clearing the cache and letting it load again and then dismiss that meeting notification once.
After I posted my last message here a couple of days ago I enabled cache again and today I noticed it's off, and this time I haven't done a clear cache.

**Comment by LunaticoCR** [comment]
I've enabled logging again, we'll see if it happens this time. The last time I had logging on it didn't happen.

**Comment by bavincen** [comment]
Hmm! did clearing cache removing db file you saying?

**Comment by LunaticoCR** [comment]
Hi @bavincen , no clearing the cache does not disable the exchange-cache.
Today cache got disabled again and this time I was able to grab logs. Where should I send this logs to?

**Comment by bavincen** [comment]
Please send to babu.Vincent@ericsson.com

-----Original Message-----

**Comment by bavincen** [comment]
@LunaticoCR Can we close this issue.. not happening for us

**Comment by bavincen** [comment]
Fixed.. please check cacheandperformancefix branch
Thanks

**Comment by LunaticoCR** [comment]
I'm not seen this on 3.3.2 either.
