### ISSUE TITLE
Calendar fails to load after restarting thunderbird

### ISSUE THREAD

**Issue by benjunmun** [Ericsson/exchangecalendar#121]
I can reproduce this issue in both 3.2.2 and 3.3.1 RC4.

I have no problems creating calendars connected to my server. All the events load and everything functions fine. However, any time I restart thunderbird, the calendar will fail to load. I get this error in the logs:

```
1st-setup:2015-1-3 11:27:30.500:2ad439b5-c317-43d5-9130-443a0cdc976c: : ExchangeRequest.loadstart
1st-setup:2015-1-3 11:27:30.599:2ad439b5-c317-43d5-9130-443a0cdc976c: : ExchangeRequest.error :error, readyState:4, status:0, lastStatus:0
1st-setup:2015-1-3 11:27:30.599:2ad439b5-c317-43d5-9130-443a0cdc976c: : ExchangeRequest.error :
1st-setup:2015-1-3 11:27:30.599:2ad439b5-c317-43d5-9130-443a0cdc976c: : xmlReq.getResponseHeader("Location") :null
1st-setup:2015-1-3 11:27:30.600:2ad439b5-c317-43d5-9130-443a0cdc976c: : ExchangeRequest.error : badCert going to check if it is a cert problem.
1st-setup:2015-1-3 11:27:30.600:mivExchangeAuthPrompt2: checkAndSolveCertProblem: waitingProblem:false, targetSite:https://mex06.emailsrvr.com/ews/exchange.asmx
1st-setup:2015-1-3 11:27:30.601:2ad439b5-c317-43d5-9130-443a0cdc976c: : ExchangeRequest.error : badCert no problem.
1st-setup:2015-1-3 11:27:30.601:2ad439b5-c317-43d5-9130-443a0cdc976c: exchangeRequest.isHTTPRedirect.xmlReq. xmlReq.readyState:4, xmlReq.status:0
1st-setup:2015-1-3 11:27:30.602:2ad439b5-c317-43d5-9130-443a0cdc976c: exchangeRequest.tryNextURL
1st-setup:2015-1-3 11:27:30.603:[Riorey] setProperty. aName:exchangeCurrentStatus, aValue:2147500037 (setProperty in mivExchangeCalendar.js:822)
1st-setup:2015-1-3 11:27:30.603:2ad439b5-c317-43d5-9130-443a0cdc976c: ecExchangeRequest.fail: aCode:-18, aMsg:Unknown error during communication with hostname 'undefined'. (0)
```

The `Unknown error during communication` message is also displayed if I mouse-over the calendar. 

However, sometimes connectivity with the calendar will be restored just by waiting. Sometimes entering the addon settings or viewing the EWS properties (without changing anything!) will also restore functionality. 

Any ideas, or is there anything else I can look at for debugging?

**Comment by bavincen** [comment]
Hi  
Can you use our latest add-on..
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon
Thanks

Please let us know the status..

**Comment by bavincen** [comment]
FYI 

https://cs.mailstore.com/index.php?/Knowledgebase/Article/View/92/4/ews-error-code-errormessagesizeexceeded

**Comment by benjunmun** [comment]
Unfortunately I'm still seeing the same issue with the official 3.3.1 build. 

I'm not sure I understand your link - do you think I may be running into a message size error with the calendar? I don't have a lot of control over the exchange server. It's hosted on Rackspace. I'm not sure that I can even check the logs, but I can try contacting their support for more details if you think there's an issue on their end.

**Comment by benjunmun** [comment]
Also, here's the full log from a session in case I've missed anything important: http://pastebin.com/4XJQ8t40

**Comment by benjunmun** [comment]
I tried using [mitmproxy](http://mitmproxy.org/) to see what requests were being sent, but I found something strange. If I send traffic through the proxy, it works perfectly, every time. If I stop sending it through the proxy, it goes right back to being broken, every time. I'm using thunderbird's internal proxy settings.

No idea what this means though. Race condition or an issue with SSL?

Here's a short log from a (bad session)[http://pastebin.com/DnVB2aMP] up to the first failure.
Here's a short log from a (good session)[http://pastebin.com/r8zKYwzy] (with proxy) up to the same point.

**Comment by bavincen** [comment]
yes i was just to reply to you..
its bad cert issue..
errror  i was saying before is not exactly
the error code returned from client is no server found you can see that message here

st-setup:2015-2-2 9:50:5.595:e5a01199-8ed8-4eb0-994a-bbc78af8f194: : ExchangeRequest.error : badCert going to check if it is a cert problem.
1st-setup:2015-2-2 9:50:5.595:mivExchangeAuthPrompt2: checkAndSolveCertProblem: waitingProblem:false, targetSite:https://mex06.emailsrvr.com/ews/exchange.asmx
1st-setup:2015-2-2 9:50:5.595:e5a01199-8ed8-4eb0-994a-bbc78af8f194: : ExchangeRequest.error : badCert no problem.
1st-setup:2015-2-2 9:50:5.596:e5a01199-8ed8-4eb0-994a-bbc78af8f194: exchangeRequest.isHTTPRedirect.xmlReq. xmlReq.readyState:4, xmlReq.status:0
1st-setup:2015-2-2 9:50:5.596:e5a01199-8ed8-4eb0-994a-bbc78af8f194: exchangeRequest.tryNextURL
1st-setup:2015-2-2 9:50:5.597:[Riorey] setProperty. aName:exchangeCurrentStatus, aValue:2147500037 (setProperty in mivExchangeCalendar.js:822)
1st-setup:2015-2-2 9:50:5.597:e5a01199-8ed8-4eb0-994a-bbc78af8f194: ecExchangeRequest.fail: aCode:-14, aMsg:Error during connection to hostname 'mex06.emailsrvr.com'. (STATUS_CONNECTED_TO)


i tried to check the status log once connecton made but that retuned me no url which means the client in thunderbird has got no url to communicate (actually it has)
1st-setup:2015-2-2 9:50:5.817:4ac69892-29c7-45d0-b1eb-7cc37972f5b2: ecExchangeRequest.fail: aCode:-18, aMsg:Unknown error during communication with hostname 'undefined'. (0)

here undefined is url value
and the error client returns 
ER_ERROR_UNKNOWN_CONNECTION: -18, // "Unknown error during communication with hostname 

something lost here.. need more digging..

**Comment by bavincen** [comment]
it can be SSL negotiation that takes a time between CONNECTED_TO and ER_ERROR_UNKNOWN_CONNECTION

l

**Comment by muthusuba** [comment]
Seems like the URL is being ignored because of https certificates - these are not verifiable?

**Comment by muthusuba** [comment]
Basically, with reference to:
1st-setup:2015-1-3 11:27:30.601:2ad439b5-c317-43d5-9130-443a0cdc976c: : ExchangeRequest.error : badCert no problem.
1st-setup:2015-1-3 11:27:30.601:2ad439b5-c317-43d5-9130-443a0cdc976c: exchangeRequest.isHTTPRedirect.xmlReq. xmlReq.readyState:4, xmlReq.status:0
1st-setup:2015-1-3 11:27:30.602:2ad439b5-c317-43d5-9130-443a0cdc976c: exchangeRequest.tryNextURL

**Comment by benjunmun** [comment]
I tried a brand new thunderbird profile, and now everything works fine. I'm going to look closer at my configuration - I must have a problem with SSL config somewhere. At this point though it looks like it's my setup and not the plugin. Thanks for your help with debugging.
