### ISSUE TITLE
Accepted Calendar Entries only appeared after restarting Thunderbird

### ISSUE THREAD

**Issue by brenboy** [Ericsson/exchangecalendar#122]
Hi Guys,

After upgrading to 3.3.1RC3 I noticed that after I have accepted an invite it does not appear in Lightning until I restart Thunderbird (the invite is visible in OWA immediately after accepting). This issue is also there with 3.3.1RC4 and is the same with the exchange-cache enabled or disabled. 

I'm using Thunderbird 36b1 and Lightning 3.8b1. I didn't see this issue with 3.3.1RC1 or RC2

**Comment by bavincen** [comment]
Hi @brenboy ,
Give us more info.
What is the status of event in EWS?

**Comment by brenboy** [comment]
Hi Bavincen,

How do I trace the status of the event in EWS? Do I need to enable some trace / debug logging somewhere?

**Comment by bavincen** [comment]
you can see that in OWA webapp

**Comment by brenboy** [comment]
I can't work out how to find the status of the EWS event in OWA.

**Comment by bavincen** [comment]
You can login to ews webpage,then calendar double-click to open event :)

**Comment by brenboy** [comment]
Ok :-). I thought you wanted some trace level debugging run. All events successfully appear as 'Accepted' in OWA they just didn't appear in Lightning. I've just upgraded to RC5. I'll let you know if it fixes it.
 

     On Tuesday, 10 March 2015, 20:18, bavincen <notifications@github.com> wrote:
   

 You can login to ews webpage,then calendar double-click to open event :)—

**Comment by tfft** [comment]
I too am seeing alot of events that simply don't appear unless Thunderbird is restarted.  A rescheduling of a meeting, for instance, doesn't seem to be rescheduled on the calendar map unless Thunderbird is restarted (meeting on the calendar at time A, get an email to make meeting at time B, accept, nothing happens on the calendar map, meeting still noted on time A - restart Thunderbird, meeting now at the correct time B time-slot).  I have 'exchange-cache' not selected (ie. off).

**Comment by brenboy** [comment]
This problem still exists with RC5

**Comment by muthusuba** [comment]
FYI: I see that too...but randomly...
When this happens, many of the exchangecalendar updates don't seem to work.

@brenboy can you start thunderbird from terminal and see if there is anything printed there when this happens, please? Thanks!

**Comment by muthusuba** [comment]
@tfft thanks! @brenboy is your exchange-cache turned off as well, please?

**Comment by enozkan** [comment]
Not sure if this needs re-confirming, but I observe this as well. Especially, if my laptop goes to sleep. This happens with new events created, or edits to existing events.

**Comment by brenboy** [comment]
My exchange-cache is off but I also saw the issue when the cache was on.

I've started Thunderbird from the terminal and collected the start logs. Where is a good place to send them (it's about 5MB) ?

**Comment by bavincen** [comment]
Please send it to github email address
Make sure to compress logs.


-----Original Message-----

**Comment by brenboy** [comment]
On Thursday, 12 March 2015, 11:56, bavincen <notifications@github.com> wrote:
   

 Please send it to github email address
Make sure to compress logs.


-----Original Message-----

**Comment by brenboy** [comment]
Logs sent to exchangecalendar@noreply.github.com

**Comment by bavincen** [comment]
Nope. That's not the one. Babu.Vincent@ericsson.com

**Comment by brenboy** [comment]
This issue still exists with Thunderbird 37b1 / Lightning 3.9b1 and Exchange provider add-on 3.3.1.

**Comment by brenboy** [comment]
This issue still exists with Thunderbird 38b1 / Lightning 4.0b1 and Exchange provider add-on 3.3.1.

**Comment by bavincen** [comment]
It doesnt look like common issue.. Maybe you can share the logs with us

Thanks

**Comment by brenboy** [comment]
I'm happy to share the logs. Please tell me which logs you would like

**Comment by bavincen** [comment]
before that would you mind using your new thunderbird profile and check if it is working..


You can send us to Github mail addresses Thanks

**Comment by bavincen** [comment]
@brenboy Can you check that in `cacheandperformacefix` branch..

**Comment by brenboy** [comment]
Please see my response to #175
