### ISSUE TITLE
Upon accepting a new event, exchangecalendar creates a new event

### ISSUE THREAD

**Issue by jlcenter** [Ericsson/exchangecalendar#123]
Hi,

I'm running 3.3.1rc3, on TB 31.4.0 on Ubuntu 14.04.  Some one sent me an invitiation to a meeting.  I clicked on Accept.  A new event was created in addition to the one I received originally.  The original event is still showing in both TB & Outlook as not accepted.  I left the folder the message was in & visited my Inbox.  When I returned to the folder, the accepted event now appears as though it was not accepted.  Please let me know if you need any additional information to address this issue.

Thanks.

    -John

**Comment by muthusuba** [comment]
Quick question: When you clicked accept did you use the same calendar or a different one (btw, multiple calendars are supported in the same calendar view by Lightning). If you accepted and placed the event on a different calendar (e.g. a local calendar) the original one is untouched.
