### ISSUE TITLE
Reschedule doesn't seem to reach server

### ISSUE THREAD

**Issue by tfft** [Ericsson/exchangecalendar#127]
Hi, using 3.3.1-RC4 - I created a meeting, an invitation gets sent, invitee replies noting that he'd like to have the meeting pushed back 1 hour, I click on the meeting in lightning (3.3.3) and changed the time, click on the "send update" dialog to invitee, he receives the email and accepts, I get the acceptance email - all great so far.

On the server though, the meeting continues to be set for the old time - as though the update never took place (in fact I get a notification noting the old time).  I was able to verify that the server's content had the old time by opening M$-Outlook and seeing the calendar there.

Thanks.

**Comment by bavincen** [comment]
Please reopened if the issue still exists
