### ISSUE TITLE
Link on Wiki Home page for latest code is incorrect

### ISSUE THREAD

**Issue by saper17** [Ericsson/exchangecalendar#130]
On the Home page of the wiki,
```
https://github.com/Ericsson/exchangecalendar/wiki
```
one finds
```
You can also get latest code from our github page https://github.com/Ericsson/exchangecalendar/releases
```
This is the same link as referenced earlier on the Home page and gives one instead the latest released version.  Surely the link for the latest code should instead be
```
https://github.com/Ericsson/exchangecalendar/archive/master.zip
```
as it was previously.  If not, then this last line can simply be removed.

Note that the Wiki page
```
https://github.com/Ericsson/exchangecalendar/wiki/Exchange-EWS-Provider
```
has the correct link.

**Comment by bavincen** [comment]
Thanks
