### ISSUE TITLE
Thunderbird update suggestions

### ISSUE THREAD

**Issue by Kidlike** [Ericsson/exchangecalendar#131]
Can you change the behaviour of this thunderbird plugin to suggest update only on new releases, and not release candidates ?
Or even better, make this configurable.

The main issue with the existing approach is that if you decide to update to a RC version it is more likely to introduce bugs (as it happened recently).
And an other less important issue, and more of a personal preference, is that the RC updates are very often. At least in this time period, but anyway...

Regards

**Comment by bavincen** [comment]
fixed

**Comment by Woi** [comment]
I can't find an configuration option to enable development updates (RC, Betas, ...)
I'm using SeaMonkey with v3.4.0-beta2. 
Is this a problem affecting SeaMonkey only or has this option not been implemented? In the later case I like to reopen this issue.

**Comment by bavincen** [comment]
Hello,
We blocked alerts for prerelease versions.

Update alerts will be shown only for stable


You can open new thread if users need that.. Lets do that

**Comment by bavincen** [comment]
![update-options](https://cloud.githubusercontent.com/assets/8401561/8249631/ef7f36b0-1689-11e5-8bde-fc12b6f45f25.jpg)

**Comment by bavincen** [comment]
![update-options](https://cloud.githubusercontent.com/assets/8401561/8249661/40399e60-168a-11e5-8fc0-859e094e279c.jpg)

**Comment by Woi** [comment]
Thanks for the quick patch. I just installed v3.4.0-beta3 to test it, but run into problems so I couldn't test your patch. Details in issue #246

**Comment by Woi** [comment]
The "others" tab in preferences is empty for me. I used master with commit c413e33 in SeaMonkey.

SM & Lightning versions:
Mozilla/5.0 (X11; Linux x86_64; rv:36.0) Gecko/20100101 SeaMonkey/2.33.1 Lightning/3.8b2

**Comment by bavincen** [comment]
Replied in #246
