### ISSUE TITLE
Calendar goes into read-only mode and stacks "running" jobs

### ISSUE THREAD

**Issue by sysadm-prs-de** [Ericsson/exchangecalendar#137]
This has been described in #126 but with more testing the following symptoms can be observed:
- all versions of add-on
- all versions of TB and Lightning
- mainly on Mac OS (all versions from 10.8.x onwards)
- only (!) if more than one exchange calendar configured

If there are more than one EWS calendars configured one of them eventually goes into read-only, leaving some number of queued jobs.
Letting the computer slide into power-save forces the problem.

The only way to salvage is to delete the calendar. A TB restart w/o deleting the calendar lets the exact number of jobs reappear, while the calendar remains in read-only mode. Clearing the read-only flag does not work.

If one deletes the r/o calendar, restarts TB, an recreates the (formerly r/o) calendar, it works for a while until either
- the machine goes into power-save
- TB is restarted
Once that has happened, the other (not recreated) calendar goes into read-only.

One of the calendars has many recurring events.

Any ideas ???

**Comment by muthusuba** [comment]
@sysadm-prs-de This information looks really useful. Thank you!

**Comment by sysadm-prs-de** [comment]
Please let me know if there is anything else I can do to help you fixing this problem once and for all :-)

**Comment by offlinehoster** [comment]
Same issue on a Linuxmint 17.1 (Rebecca). 

* Thunderbird 31.5.0
* Exchange EWS Provider 3.3.1
* Connected Exchange 2010 Calendar (just one)

Cheers
Christian

**Comment by offlinehoster** [comment]
After disabling the Exchange EWS Provider 3.3.1 plugin, we could set the gmail calendar as writeable. the Exchange calendar was disabled.

After restarting thunderbird and reactivated the plugin both calendars are active again, but the exchange calendar is still in read-only mode. The gmail calendar is now writeable again.

**Comment by offlinehoster** [comment]
Now we removed the Exchange calendar too.

After re-adding this one, everything looks fine and is working again.

**Comment by sysadm-prs-de** [comment]
Hello,
does this mean there is a fix in the wings-because it still doesn't work for me with more than one calendar!!!

**Comment by bavincen** [comment]
oops sorry

**Comment by bavincen** [comment]
please follow this #195.. this issue already got fixed and to be merged with master
