### ISSUE TITLE
Forwarding is not spelled correctly in forward invite success alert. 

### ISSUE THREAD

**Issue by ehlmnqc** [Ericsson/exchangecalendar#14]
1. Go to Calendar double click on an event.
   1. Now a seprate window will open up.
   2. Click on "forward invite" button , again a window will open which prompts the user to add the attendees 
2. Add the attendees and click on "OK" button. 

Observe an alert will open up "event forewarding successful!", it should forwarding instead of forewarding.

**Comment by scubbo** [comment]
This bug is still present if the forwarding is unsuccessful: see [here](https://github.com/Ericsson/exchangecalendar/blob/7cbb4edbb50b141cdbe05661926c6b9c86c00998/components/erForewardItem.js#L139).

**Comment by ehlmnqc** [comment]
Event forwarding is failing in the following scenarios
case1 : If user fails to add any attendees in "Invite Attendees" dialog 
case2: If invalid recipients is added in "Invite Attendees" dialog.
So i reckon the best possible solution for case1 is, don't let the user proceed further if "Invite Attendees" haven't got any attendees.
for case 2 the message seams to be alright.

**Comment by ehlmnqc** [comment]
"Forewarding" is now changed to "Forwarding", so i guess the typo is fixed now.
