### ISSUE TITLE
EWS preferences window icons too big

### ISSUE THREAD

**Issue by LunaticoCR** [Ericsson/exchangecalendar#140]
The EWS and Extras icons are not the right size, they're too big. Also, some strings go off the window.
At first it looks like this:
![image](https://cloud.githubusercontent.com/assets/2124383/6706621/472e31b2-cd57-11e4-8a82-6c699d6b3efa.png)
![image](https://cloud.githubusercontent.com/assets/2124383/6706662/89415cf0-cd57-11e4-828c-eda4d07c63eb.png)

After clicking Extras the icon shows complete, but still huge:
![image](https://cloud.githubusercontent.com/assets/2124383/6706637/64b642ce-cd57-11e4-979f-998f583865d7.png)
Also, after having gone into this tab the strings on the EWS tab get rearranged into the window.

**Comment by bavincen** [comment]
@daniel can you help us please? 😊😊 

-----Original Message-----

**Comment by LunaticoCR** [comment]
How can I help?

**Comment by bavincen** [comment]
Please resize and give us pull request :)

**Comment by muthusuba** [comment]
@bavincen Wondering if there is a way to size it according to the other icon sizes, please? I'm guessing so...?

**Comment by muthusuba** [comment]
@LunaticoCR Can you provide your platform/setup details, please?

**Comment by bavincen** [comment]
Resized to default size 32x32
