### ISSUE TITLE
"Extras" configuration menu not visible when using Seamonkey

### ISSUE THREAD

**Issue by Dominique-2202** [Ericsson/exchangecalendar#141]
The exchange calendar add-on is used both with Thunderbird and Seamonkey. 
The Seamonkey project ( http://www.seamonkey-project.org/ ) propose version of the software.
- When using Seamonkey + lightning + exchange calendar, the "Extras" configuration menu that is visible in Thunderbird is not present in the Seamonkey integration.

Side note: the Exchange calendar file "install.rdf" can also be bumped up to the version 2.36 of Seamonkey (tested ok with Windows and Seamonkey 2.33)

**Comment by bavincen** [comment]
Thanks @Dominique-2202  Screenshot would help a lot in this issue :) Please post extra tab screenshot Thanks..

2.36? is suppose to be max version for seamonkey?

**Comment by Dominique-2202** [comment]
Hi Bavincen,
        
        Yes, Seamonkey nightly is nowadays up to 2.36.
        I'll post the way exchange calendar settings appear in Seamonkey
        in the issue #141. You already know how it looks with
        Thunderbird.
      
    
      
      
      
        Best regards,
        
        Dominique
        
       
    On 3/19/2015 12:23 PM, bavincen wrote:
    
    
      Thanks @Dominique-2202
        Screenshot would help a lot in this issue :) Please post extra
        tab screenshot Thanks..
      2.36? is suppose to be max version for seamonkey?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Dominique-2202** [comment]
![ews-caching](https://cloud.githubusercontent.com/assets/2248966/6730138/d15ca1d8-ce39-11e4-8bd8-1366897660c9.jpg)
![ews-logging](https://cloud.githubusercontent.com/assets/2248966/6730139/d161cc8a-ce39-11e4-81de-d6218be84da1.jpg)
![ews-others](https://cloud.githubusercontent.com/assets/2248966/6730140/d16488bc-ce39-11e4-9e41-fb09e33c2767.jpg)
![seamonkey-preferences](https://cloud.githubusercontent.com/assets/2248966/6730141/d1672d4c-ce39-11e4-9cad-e388ec8009f5.jpg)

**Comment by Dominique-2202** [comment]
No other item corresponding to the "Extras" menu in the Thunderbird configuration panel.

**Comment by bavincen** [comment]
Thanks a lot will do that

-----Original Message-----

**Comment by bavincen** [comment]
here is that file contains preference: :)



https://github.com/Ericsson/exchangecalendar/blob/2ed0995ebcf869580b1f17805b3b08fdf4f63fbe/chrome/content/extra-priority-preferences.

**Comment by Dominique-2202** [comment]
Coming back to this issue, what am I supposed to do with the comment above, Bavincen ?
When opening this bug I expected:
- An upcoming release of the ExchangeCalendar.xpi containing an updated "install.rdf" file for the Seamonkey max version 
- An update to ensure that the "extra" menu items get shown in Seamonkey

I have not seen an update yet, I hope it is not too difficult to work these points.

Thanks

**Comment by Dominique-2202** [comment]
Hi Bavincen,
        
        I know where the prefs are located, the problem is that there is
        no UI for it when using SeaMonkey !
        
        BTW, there are numerous UI issues with SeaMonkey, specially when
        going to 3.3.2 and above !
        I can prepare a complete review of these issues and open a new
        case ? What do you prefer ?
      
    
      
      
      
        Best regards,
        
        Dominique
        
       
    On 6/12/2015 8:50 AM, bavincen wrote:
    
    
      Closed #141.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by bavincen** [comment]
Hi It is fixed.. please check our latest addon  :)

**Comment by Dominique-2202** [comment]
Hi Bavincen,
        
        Confirmed fixed !! thanks a lot !
      
    
      
      
      
        Best regards,
        
        Dominique 
        
       
    On 6/12/2015 12:02 PM, bavincen wrote:
    
    
      Hi It is fixed.. please check our latest addon :)
      —
        Reply to this email directly or view
          it on GitHub.
