### ISSUE TITLE
Cannot import calendar file

### ISSUE THREAD

**Issue by Physikuss** [Ericsson/exchangecalendar#143]
Hi,

I just connected Thunderbird with my Exchange-Account successfully. So thank you for this. I would like to import my local calender into the Exchange Cal. I exported the local one as ics-file and tried to import in into Lightning. But when in comes to select the calender in which the ics should be imported, the Exchange-Cal is shown in the list but can't be selected.

If try the same procedure with a csv-file I can select the Exchange-Cal. but nothing happens.

Am I doing anything wrong or is this an issue of the AddOn?

Thank in advance for your help.

**Comment by Mechtilde** [comment]
Hello

I guess you don't have rights to create a new calendar at the EWS
Server. You can import an calendar into lightning independent of the
exchangecalendar AddOn.

-- 
Mechtilde Stehmann

## PGP encryption welcome
## Key-ID 0x141AAD7F

**Comment by Physikuss** [comment]
My approach was to import an *.ics file into an existing Exchange calender. The latter was created before via OWA. Is there any alternative approach to get an ics file into an existing Exchange calendar?

**Comment by Mechtilde** [comment]
I testet it with the bank holidays *.ics file and it works. I did it
with the calendar import function.



-- 
Mechtilde Stehmann

## PGP encryption welcome
## Key-ID 0x141AAD7F
