### ISSUE TITLE
Changing machine timezone

### ISSUE THREAD

**Issue by hadiasghari** [Ericsson/exchangecalendar#147]
Hi,

I was recently travelling and changed my laptop's timezone. I then noticed that calendar entries where not displayed in the new timezone, but still in the old timezone. E.g. a meeting setup at 3PM would still should up as 3PM, although in the new timezone it should have shown up as 10AM. 

This is pretty easy to reproduce.

I am not sure if it is a bug with this plugin or with lightning.

Are there any workarounds or fixes? 

Thanks

**Comment by bavincen** [comment]
Hi 
I really not sure what calendar does when you change timezone. 
Is that timezone changed after restarting thunderbird?



-----Original Message-----

**Comment by hadiasghari** [comment]
Yes I restarted thunderbird

**Comment by bavincen** [comment]
Do you have cache enabled?
If yes can you please disable and restart?

Otherwise thanks for posting 😊 

-----Original Message-----

**Comment by hadiasghari** [comment]
Niether of checkboxes for "exchange-cache" and "offline-caching" were set.

**Comment by muthusuba** [comment]
@hadiasghari you can set the lightning timezone in "Preferences" ... hope that helps.

**Comment by hadiasghari** [comment]
ok thanks I will try next this

**Comment by bavincen** [comment]
fixed, Please check preference to change timezone automatically
