### ISSUE TITLE
'Delete' button icon disappears with add-on installed

### ISSUE THREAD

**Issue by gitman0** [Ericsson/exchangecalendar#149]
I have 'Delete' as one of the buttons in my main button panel. When I have this add-on installed, the red X icon for the Delete button does not appear. If I disable the add-on, the icon is restored after restarting.

I am using Thunderbird 17.0.4. (it's an old Fedora machine).

Thanks,

**Comment by bavincen** [comment]
Actually I am not getting where do you have 'delete button' can you please post that screenshot of window..

Thanks

**Comment by gitman0** [comment]
Sorry for the late reply.
The Delete button is at the top of the menu. The icon should be a graphic of a red "X", but with the add-on installed, the graphic goes missing.

![tbird-missing-delete-icon](https://cloud.githubusercontent.com/assets/3878017/7262500/21b9d088-e848-11e4-885d-85cca18a87e9.png)

I don't have this issue on Thunderbird 24 on my Fedora 18 laptop.

**Comment by muthusuba** [comment]
@gitman0 is this a problem in 3.3.2 as well, please? Do you have any other addon?

**Comment by bavincen** [comment]
Please check latest release we have css work there..give a pull request if that's not working for yiu
