### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by nicklasb** [Ericsson/exchangecalendar#150]
Hi,

I am just trying out this add-on, and I cannot make it work properly. The problem is likely that I don't know how to make it work. :-)
I am pushing all the buttons I can find, but isn't very sure about what I am doing.

It would be great if there was some documentation in the readme.md, just a step-by-step installation would do for now.

**Comment by bavincen** [comment]
We do have Wiki pages but its incomplete for some work guides are available.. we are expecting more contributors to write wiki  :)

**Comment by nicklasb** [comment]
Oh, sorry, I saw that now(there is normally a reference to documentation in the readme). 
Well, you know contributors like documentation. 
So I would start with that and then expect contributors. :-)

**Comment by bavincen** [comment]
we have update some basic information..hope it helps..
https://github.com/Ericsson/exchangecalendar/blob/master/README.md

**Comment by muthusuba** [comment]
@nicklasb Of course, we are writing more documentation and we need help with it as well!
Hopefully, more and better wiki in the coming days...

Thank you for your suggestion...

**Comment by nicklasb** [comment]
BTW, I wasn't trying to sound cocky or anything, I was merely pointing out how the project appeared to me as someone just waltzing in.

I just saw that you added stuff, looks much better now.

**Comment by muthusuba** [comment]
@nicklasb no worries...thank you for helping make the project better.
I'm guessing this can be closed now, please? :)

**Comment by nicklasb** [comment]
Yes, of course, sorry I should have done that myself.
