### ISSUE TITLE
Cannot resolve hostname even if it is an IP

### ISSUE THREAD

**Issue by nicklasb** [Ericsson/exchangecalendar#151]
Hi, 
I an getting a very strange error when trying to add an exchange calendar following the wiki instructions, except I am *not* using the autodiscovery function. 

In the "Create a new calendar" - "Exchange/Windows Active Directory settings", I am getting:
"Error during checking of server and mailbox: Error resolving hostname '192.168.0.205'. Did you type the right hostname. (STATUS_RESOLVING) (Code: -9)"

This is kind of strange, because not much resolving should need be applied to an IP-address. :-)

I have tried these combinations(and obviously a multitude more):
https://wsrv03.mydomain.se/EWS/exchange.asmx
https://192.168.0.205/EWS/exchange.asmx
(yes, EWS should be in capitals)

I can both ping and browse to the address(using firefox), and also, the normal EWS e-mail account works.

The setup is:
* Ubuntu 14.10
* Thunderbird 31.5.0
* Exchange calendar v3.3.1
* Exchange server 2013(on a local network)
* Exchange EWS provider v3.3.1 (where do that come from now? You seem to have taken over that project, can't find the source)

**Comment by jmwolfe** [comment]
I am having this same issue. Our Exchange server doesn't support auto-discovery, but we do have EWS enabled.  It's being used by Thunderbird Equilla plugin just fine for mail. I believe this is a defect and I hope it's fixed real soon! :+1:

**Comment by bavincen** [comment]
Is your exchange server supports auto discovery

**Comment by nicklasb** [comment]
I am not using the autodiscovery function.

**Comment by jmwolfe** [comment]
I don't think our server has that enabled. Equilla's auto-discovery did not work.

**Comment by Saxomania** [comment]
Hi,

not the same but similar problem here with one of our users. He gets "STATUS_WAITING_FOR" if he tries to add his personal calendar. On our exchange autodiscovery is enabled but we dont use it for TB/EWS.

I have this problem only for this user. I am not sure where it comes from (TB, EWS, Lightning or TB profile -> so much opportunities

His setup: One freemailer emailadress configured and one company emailadress. His TB profile was already existing before we deployed TB 31.6.0 with integrated addons (lightning 3.3.3 and EWS 3.3.1 in \TBprogrampath\distribution\bundles) - before we deployed default Thunderbird. If i create a new TB profile for that user adding calendar works fine. So for me it seems to be a problem within the user profile not really a DNS issue (which would lead to the system - imho).

EWS logfile with anonymized domain\username, exchangeservername and emailadress:

1st-setup:2015-4-3 11:46:25.477:  -- calendar-task-tree --
1st-setup:2015-4-3 11:46:28.767:mivExchangeAuthPrompt2: getPassword: A realm was specified:Exchange Web Service (_getPassword in mivExchangeAuthPrompt2.js:122)
1st-setup:2015-4-3 11:46:28.767:mivExchangeAuthPrompt2: getPassword: Going to see if there is one in the passwordManager. (_getPassword in mivExchangeAuthPrompt2.js:137)
1st-setup:2015-4-3 11:46:28.768:mivExchangeAuthPrompt2: passwordManagerGet: username=DOMAIN\USERNAME, aURL=https://wintmg01.*****.de/ews/exchange.asmx, aRealm=Exchange Web Service (_passwordManagerGet in mivExchangeAuthPrompt2.js:619)
1st-setup:2015-4-3 11:46:29.186:lightningAlertCallback.
1st-setup:2015-4-3 11:46:29.187:lightningAlertCallback: Not showing warning dialog:Please install the Lightning Add-on if you wish
to use the Exchange 2007/2010 Calendar and Tasks add-on.
1st-setup:2015-4-3 11:46:56.153:mivExchangeAuthPrompt2: passwordManagerGet found password for: username=DOMAIN\USERNAME, aURL=https://wintmg01.*****.de/ews/exchange.asmx, aRealm=Exchange Web Service (_passwordManagerGet in mivExchangeAuthPrompt2.js:628)
1st-setup:2015-4-3 11:46:56.155:mivExchangeAuthPrompt2: getPassword: There is a password stored in the passwordManager. (_getPassword in mivExchangeAuthPrompt2.js:140)
1st-setup:2015-4-3 11:46:56.156:mivExchangeAuthPrompt2: getPassword: password(1)=******** (_getPassword in mivExchangeAuthPrompt2.js:152)
1st-setup:2015-4-3 11:46:56.156:mivExchangeAuthPrompt2: getPassword: We have a password:******** (_getPassword in mivExchangeAuthPrompt2.js:250)
1st-setup:2015-4-3 11:46:56.157:70526886-9907-42ad-9fe1-8639654fdc74: : 1 ExchangeRequest.sendRequest : user=DOMAIN\USERNAME, url=https://wintmg01.*****.de/ews/exchange.asmx
1st-setup:2015-4-3 11:46:56.158:70526886-9907-42ad-9fe1-8639654fdc74: We have a prePassword: *******
1st-setup:2015-4-3 11:46:56.159:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.159:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.159:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.160:70526886-9907-42ad-9fe1-8639654fdc74: : sendRequest Sending: <?xml version="1.0" encoding="utf-8"?>
<nsSoap:Envelope xmlns:nsSoap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsSoap:Header><nsTypes:RequestServerVersion Version="Exchange2007_SP1"/><nsTypes:TimeZoneContext><t:TimeZoneDefinition Id="W. Europe Standard Time" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:nsSoap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"/></nsTypes:TimeZoneContext></nsSoap:Header><nsSoap:Body><nsMessages:SyncFolderItems xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:nsSoap="http://schemas.xmlsoap.org/soap/envelope/"><nsMessages:ItemShape xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsTypes:BaseShape>AllProperties</nsTypes:BaseShape><nsTypes:BodyType>Text</nsTypes:BodyType><nsTypes:AdditionalProperties><nsTypes:FieldURI FieldURI="item:Subject"/><nsTypes:ExtendedFieldURI DistinguishedPropertySetId="Common" PropertyId="4096" PropertyType="String"/></nsTypes:AdditionalProperties></nsMessages:ItemShape><nsMessages:SyncFolderId xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsTypes:DistinguishedFolderId Id="contacts" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages"><nsTypes:Mailbox xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsTypes:EmailAddress>F.LASTNAME@*****.de</nsTypes:EmailAddress></nsTypes:Mailbox></nsTypes:DistinguishedFolderId></nsMessages:SyncFolderId><nsMessages:MaxChangesReturned xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types">512</nsMessages:MaxChangesReturned></nsMessages:SyncFolderItems></nsSoap:Body></nsSoap:Envelope>

1st-setup:2015-4-3 11:46:56.161:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.162:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.168:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.169:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.169:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.170:70526886-9907-42ad-9fe1-8639654fdc74: : ExchangeRequest.loadstart
1st-setup:2015-4-3 11:46:56.194:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.194:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.196:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({e46d924d-c20f-4add-8cf5-1e1c817b2181})
1st-setup:2015-4-3 11:46:56.196:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({2b6d6fb6-ab28-4f4c-af84-bfdbb7866d72})
1st-setup:2015-4-3 11:46:56.197:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsIApplicationCacheContainer
1st-setup:2015-4-3 11:46:56.197:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.198:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.198:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.232:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsISecureBrowserUI
1st-setup:2015-4-3 11:46:56.233:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsIProgressEventSink
1st-setup:2015-4-3 11:46:56.234:b48419c1-b1df-4136-931d-22a2929dc36c:   --- ecnsIAuthPrompt2.onStatus: STATUS_WAITING_FOR of wintmg01.*****.de
1st-setup:2015-4-3 11:46:56.235:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.236:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({e46d924d-c20f-4add-8cf5-1e1c817b2181})
1st-setup:2015-4-3 11:46:56.237:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.237:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.237:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.238:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.239:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.239:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.240:b48419c1-b1df-4136-931d-22a2929dc36c: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-4-3 11:46:56.241:70526886-9907-42ad-9fe1-8639654fdc74: : ExchangeRequest.error :error, readyState:4, status:0, lastStatus:2152398858
1st-setup:2015-4-3 11:46:56.241:70526886-9907-42ad-9fe1-8639654fdc74: : ExchangeRequest.error :
1st-setup:2015-4-3 11:46:56.242:70526886-9907-42ad-9fe1-8639654fdc74: : xmlReq.getResponseHeader("Location") :https://wintmg01.*****.de/CookieAuth.dll?GetLogon?curl=Z2FewsZ2Fexchange.asmx&reason=0&formdir=1
1st-setup:2015-4-3 11:46:56.242:70526886-9907-42ad-9fe1-8639654fdc74: : ExchangeRequest.error : badCert going to check if it is a cert problem.
1st-setup:2015-4-3 11:46:56.242:mivExchangeAuthPrompt2: checkAndSolveCertProblem: waitingProblem:false, targetSite:https://wintmg01.*****.de/ews/exchange.asmx
1st-setup:2015-4-3 11:46:56.243:70526886-9907-42ad-9fe1-8639654fdc74: : ExchangeRequest.error : badCert no problem.
1st-setup:2015-4-3 11:46:56.243:70526886-9907-42ad-9fe1-8639654fdc74: exchangeRequest.isHTTPRedirect.xmlReq. xmlReq.readyState:4, xmlReq.status:0
1st-setup:2015-4-3 11:46:56.244:70526886-9907-42ad-9fe1-8639654fdc74: exchangeRequest.tryNextURL
1st-setup:2015-4-3 11:46:56.244:70526886-9907-42ad-9fe1-8639654fdc74: ecExchangeRequest.fail: aCode:-16, aMsg:Error during waiting for data of hostname 'wintmg01.*****.de'. (STATUS_WAITING_FOR)
1st-setup:2015-4-3 11:46:56.245:70526886-9907-42ad-9fe1-8639654fdc74: : ExchangeRequest.loadend
1st-setup:2015-4-3 11:46:56.246:70526886-9907-42ad-9fe1-8639654fdc74: : ExchangeRequest.loadend :loadend, readyState:4, status:0
1st-setup:2015-4-3 11:46:56.246:70526886-9907-42ad-9fe1-8639654fdc74: : ExchangeRequest.loadend :

**Comment by bavincen** [comment]
Please check you network settings.. we are able to add calendar using ip address

Thanks
