### ISSUE TITLE
adding global address book in thunderbird

### ISSUE THREAD

**Issue by Kidlike** [Ericsson/exchangecalendar#152]
Hi,

I have an issue when trying to add the global exchange address book to thunderbird.

The global address book is in a folder that I see as "Address Book" when I use the web outlook client.
If I search a name there, it finds it.
There is also a similar folder that I see as "Contacts"; but there, are being stored my saved contacts.

So if I want to search for a name that I have not added yet to my contacts, I need to use "Address Book".

*(here is the part that the plugin is involved)*
When I select Add Exchange contact folder, and fill in the details on the dialog, then I try to select "Folder Base".
In that list, "Address Book" is not included.
I can only see "Contacts", and a bunch of irrelevant stuff.

I don't know if I am not understanding some business logic here, but it feels like I should be able to do that, right ?
And of course I wouldn't want to download the global address book in my local Thunderbird (I don't know how these address books in thunderbird are being handled).

So what is the situation ? Is this a missing feature of this plugin, something that can't be done with Thunderbird, a bug ?

Thanks

**Comment by HuboAdmins** [comment]
@Kidlike 
I'm using v3.3.1 stable now (on Ubuntu), don't have any issues with our exchange global address list.
In "Address Book" => Add Exchange contact Folder
We're using Exchange Online, so your server URL might differt.
Server URL: https://outlook.office365.com/ews/exchange.asmx
username in x@domain format
Folder Base: Contacts Folder

Works fine here.

Kind regards

**Comment by Kidlike** [comment]
Sorry it was late when I was writing this, I forgot some information...
I edited the original post.

>When I select Add Exchange contact folder, and fill in the details on the dialog, then I try to select "Folder Base".
>In that list, "Address Book" is not included.

**Comment by HuboAdmins** [comment]
It should work when selecting "Contacts Folder" as folder base.
On the "Exchange Contact Settings", there's a mark for "Add global address list to search results".

**Comment by Kidlike** [comment]
Oh... damn.
Sometimes I forget I'm an end user :D
