### ISSUE TITLE
Don't search in GAL other language then english

### ISSUE THREAD

**Issue by dimania** [Ericsson/exchangecalendar#153]
In addressbook,  then I try search any person (example Dima03Дима)
If I write Dima03 - ALL OK
If I write Дима - Nothing find
So search on other lang then english not possible?
May be somoethink need tune.

**Comment by dimania** [comment]
Hi all!
I litle analyze source code and found what search string pass in GAL 
without decode.
I offer  follow patch:
------------------------------------------------
*** exchangeAbFolderDirectory.js	2015-04-06 14:57:51.000000000 +0300
--- old/exchangeAbFolderDirectory.js	2015-03-13 09:17:33.000000000 +0300
*************** exchangeAbFolderDirectory.prototype = {
*** 519,525 ****
  					 serverUrl: this.serverUrl,
  					 folderID: this.folderID,
  					 changeKey: this.changeKey,
! 					 ids: { name: decodeURI(wordToSearch) },
  					 searchScope: "ActiveDirectory",
   					 GALQuery: true,
  			 		 actionStart: Date.now()},
--- 519,525 ----
  					 serverUrl: this.serverUrl,
  					 folderID: this.folderID,
  					 changeKey: this.changeKey,
! 					 ids: { name: wordToSearch },
  					 searchScope: "ActiveDirectory",
   					 GALQuery: true,
  			 		 actionStart: Date.now()},
-----------------------------------------------

With patch all search in GAL fine.

**Comment by bavincen** [comment]
Hello
https://social.technet.microsoft.com/forums/exchange/en-US/9f8677a6-a352-40d4-99b0-dda45b5b2126/how-to-handle-multiple-languages-in-gal

Is that useful?

**Comment by dimania** [comment]
No!  I think bug in programm.
In address book.
In logs I see, that uri put encoded (type: %AA%BB%CC) for query in exchange.
But exchange don't understand it.
In autocomplete vise versa.

Excuse me for bad my english.

**Comment by muthusuba** [comment]
@Mechtilde need help to confirm if this is a problem for you as well, please? Thanks!

**Comment by dimania** [comment]
Hi!
What help you need?
I apply patches and now all work for me.
Patches I published to github in Issues.
I think you see ihtem.


2015-05-29 10:53 GMT+03:00 Muthu Subramanian <notifications@github.com>:

**Comment by bavincen** [comment]
exchange does not understand encoded text

**Comment by bavincen** [comment]
@dimania please give a pull request.. thanks a lot.. thats the better way to apply patch :)

**Comment by dimania** [comment]
Hi!
I very Young in Github!
That is pull request? And as I give it to You?
-:)

**Comment by dimania** [comment]
Ok! I Found It!
As possible I create Pull request.

**Comment by bavincen** [comment]
Fixed

**Comment by bavincen** [comment]
@dimania Thanks
