### ISSUE TITLE
Conflict with Provider for Google Calendar plugin

### ISSUE THREAD

**Issue by hubsonx** [Ericsson/exchangecalendar#157]
After I updated today to the 3.3.1 version, the add New Calendar feature for Provider for Google Calendar plugin was somehow overridden by your plugin. 

Before I updated the plugin to 3.3.1 (from 2.2.1 beta I believe), the same look when EWS provider is disabled:
![screen shot 04-07-15 at 04 13 pm](https://cloud.githubusercontent.com/assets/10629971/7025050/2deb3250-dd41-11e4-9a17-6f64d75bc66e.PNG)

After installing new version:
![screen shot 04-07-15 at 04 14 pm](https://cloud.githubusercontent.com/assets/10629971/7025114/a2627710-dd41-11e4-876e-d1ab926eecfc.PNG)

**Comment by bavincen** [comment]
fixed
