### ISSUE TITLE
Address book is empty

### ISSUE THREAD

**Issue by SergeyAnek** [Ericsson/exchangecalendar#167]
1. Add new Exchange contact folder
2. Enter valid parameters
3. Save folder

Actually result:
Inline contact search works well. Contact list is empty in Address book window(+GAL). 

EX:
Address book window contains Exchange contacts.

**Comment by switchninja** [comment]
Having the same problem, with office365.  It seems to only pull down the 'My contacts' contents, but nothing from the actual 'Directory'.

Enabling logging has the following shows useGAL:true so it's clearly trying.  

Also included in the logs, amongst other lines, are the following two, over and over:

1st-setup:2015-4-5 11:28:56.110:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({2b6d6fb6-ab28-4f4c-af84-bfdbb7866d72})
1st-setup:2015-4-5 11:28:56.764:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({e46d924d-c20f-4add-8cf5-1e1c817b2181})

**Comment by bavincen** [comment]
fixed. please checkout  `cacheandperformancefix` branch.

**Comment by bavincen** [comment]
Contacts are not added automatically you have to search then its added to addessbook :)

We are making it better.. look for update

Thanks
