### ISSUE TITLE
Adding new Exchange contact folder fails

### ISSUE THREAD

**Issue by SergeyAnek** [Ericsson/exchangecalendar#168]
1. Open address book
2. Edit - Remove Exchange contacts folder
3. Add Exchange contact folder
4. Enter vaild data
5. Save

AR:
Nothing

ER:
Exchange contact folder created

**Comment by ehlmnqc** [comment]
Could you please add some more information, if you have manage to save any log related stuff, please post it here :)
a)Which TB Version you are using ?
b) Lightning and Exchnage Versions ?
c)Which machine you are using Linux or Windows?

**Comment by SergeyAnek** [comment]
Okay. My enviroment:
0. Linux
1. Thunderbird 31.6
2. Lighting 3.3.3
3. exchangecalendar 3.3.2 rc2
4. Exchange server 2010

In thunderderbird log after "Save" button press:
1st-setup:2015-4-4 22:27:22.328:[contacts] new exchangeAbRootDirectory (exchangeAbRootDirectory in exchangeAbRootDirectory.js:45)
1st-setup:2015-4-4 22:27:22.328:[contacts] exchangeAbRootDirectory: init. aURI:exchWebService-contactRoot-directory://d277db1f-809d-4ca9-a83c-68885e34549a
 (_init in exchangeAbRootDirectory.js:460)
1st-setup:2015-4-4 22:27:22.328:[contacts] exchangeAbRootDirectory: this is a root:exchWebService-contactRoot-directory://d277db1f-809d-4ca9-a83c-68885e34549a (_init in exchangeAbRootDirectory.js:504)
1st-setup:2015-4-4 22:27:22.329:[contacts] exchangeAbRootDirectory: get isQuery (exchangeAbRootDirectory.prototype.isQuery in exchangeAbRootDirectory.js:445)
JavaScript strict warning: file:///home/serj/.thunderbird/i1vd58n1.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/exchangeAddressBook/exchangeAbRootDirectory/exchangeAbRootDirectory.js, line 64: reference to undefined property aParentDir.uuid

**Comment by ehlmnqc** [comment]
It's something that is really straight forward and  it has nothing to do with any specific versions of TB or EWS, i wish i wouldn't have bothered you for all the above details, anyways thank you for all the above information :)

**Comment by SergeyAnek** [comment]
Ok. How i can create Exchange contact folder again?

**Comment by bavincen** [comment]
Fixed

**Comment by cinic** [comment]
Ubuntu 16.04
TB 45.2.0
Exchange Calendar 3.8.0
Exchange Server 2010

After click on Save button, Contact folder not created.
