### ISSUE TITLE
Update event

### ISSUE THREAD

**Issue by LeoAzevedo0274** [Ericsson/exchangecalendar#171]
Does not save the event after amendment

**Comment by ehlmnqc** [comment]
Could you please add some more information, actually that will help us debuging the issue further.
a) Which TB Version you are using ?
b) Lightning and Exchnage Versions ?
c)Which machine you are using Linux or Windows?

**Comment by bavincen** [comment]
please check our latest code in cacheandperformancefix and let us know if it is working for you.
