### ISSUE TITLE
Postbox support?

### ISSUE THREAD

**Issue by modsuperstar** [Ericsson/exchangecalendar#172]
Is there anything on the roadmap about supporting Postbox for Mac(and I suppose PC) with this? I attempted to cludge in the compatibility in install.rdf by adding Postbox to the target applications, but when I try to install it I get the error "Postbox can only use the system dictionaries installed on your Mac.". Googling the error seems to resolve very little.

I'm not sure if Postbox is something you wish to support, but the Postbox website points to the old Thunderbird add-on that this add-on apparently succeeded, even though it's been abandoned for 3 years now.

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/issues/74
We don't support right now ..
Thanks
