### ISSUE TITLE
Can't add exchange calendar

### ISSUE THREAD

**Issue by lameventanas** [Ericsson/exchangecalendar#173]
I have problems with the exchange calendar plugin, I have tested with 3.3.1 and also from the master branch.
Whenever I try to add my AD calendar, I get an error message like this:

Error during checking of server and mailbox: Error during waiting for data of hostname '<server>'. (STATUS_WAITING_FOR) (Code: -16)

And I get these messages in the console:

1st-setup:2015-3-4 18:23:22.290:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({e46d924d-c20f-4add-8cf5-1e1c817b2181})
1st-setup:2015-3-4 18:23:22.290:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({2b6d6fb6-ab28-4f4c-af84-bfdbb7866d72})
1st-setup:2015-3-4 18:23:22.325:exchWebServicesCheckServerAndMailboxError: aCode:-16, aMsg:Error during waiting for data of hostname '<server>'. (STATUS_WAITING_FOR)

**Comment by Mechtilde** [comment]
Is it possible to change the mail adresses there to the actual ones?

**Comment by tinloaf** [comment]
Seems like I have the same problem. My setup is a v3.3.2 RC1 plugin and a Horde with ActiveSync support. I'll be happy to help in any way.

**Comment by tinloaf** [comment]
This is what I see in my webserver log:

    <my IP> - - [04/May/2015:00:47:09 +0200] "POST / HTTP/1.1" 302 672 "-" "exchangecalendar@extensions.1st-setup.nl Lightning/3.3.2"

That looks like it's not really hitting an API endpoint at all?

**Comment by muthusuba** [comment]
@tinloaf would you be able to help debugging with the code, please? Or would it be from the user's view?

Also, do you see any  filename/line number?

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon
please check this

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/commit/ca97609b20bb5c4b87f6eca4c7bb06da082d05ac
