### ISSUE TITLE
Activity Monitor and lost calendar items

### ISSUE THREAD

**Issue by Saxomania** [Ericsson/exchangecalendar#174]
We deploy now TB 31.6.0 with integrated addons "Lightning 3.3.3" and "EWS 3.3.1" per software distribution centrally within our company. We tested it before deploy mostly with a clean and new TB profile but some of our users already had an TB installation and a profile before (default TB without
any integrated addons - maybe user installed addons afterwards).

All thunderbird installations were upgraded to our specialized TB with integrated addons and now we are facing some problems. I am not sure if its really related to the update but its seems to be ;-(

1a. After the new installation some of our clients (afaik 2) have lost their calendar items. They are gone even if we check it per outlook or directly on the exchange server. We did a export to pst-file from the a backup point and will try to restore it but i am not sure why this happened. 

Both used TB to check their emails and added calendar items to exchange server with Outlook before - now functions are included but no items any more to see.

2b. On one client who added his exchange-calendar to TB we see in the activity monitor a lot of jobs nearly or more than 100 at one time. They will go away after some time but will appear even after some hours of TB running.

![05-05-_2015_13-17-02](https://cloud.githubusercontent.com/assets/11755505/7474659/159aded6-f343-11e4-9cca-192727fa7b4d.jpg)

3c. On my activity monitor i see a sync for calendar updates every 10 minutes but in Calendar -> right click -> "exchange EWS properties" 60 seconds are defined and in "properties" 30 minutes are defined. Why is the sync every 10 minutes? And for what are the other values related to?

Regards Sascha

If you need more informations or our tb and addon config please let me know.
Now i added file logging on my client in Exchange (EWS) menu also for communication with Exchange but i am not sure if i can read all that informations ;-)

**Comment by bavincen** [comment]
Hi
there is one option in ews addon. when there are cancelled items, they automatically removed. you can configure that by clicking on 'ews exchange properties'

**Comment by Saxomania** [comment]
Hi,

thanks for the answer what I have found out:

1a. Both users deleted all emails in mailbox\calendar so all items in exchange calendar were gone ;-)

2b. Similar case https://github.com/Ericsson/exchangecalendar/issues/105 so i have added my question to that issue.

3c. Still a question but also added to the case above.

So i will close this issue.

Regards Sascha
