### ISSUE TITLE
Tasks and Meetings in same Calendar?

### ISSUE THREAD

**Issue by reneglauser** [Ericsson/exchangecalendar#176]
I added an exchange-calendar successfully and can add new meetings. But in the same calendar I can not see my tasks. Is it correct, that I have to create a second calendar-connection, when I want to have access to my exchange-tasks? So I have always two connections, one for calendar and one for tasts?

**Comment by bavincen** [comment]
@anantks @muthusuba

**Comment by bavincen** [comment]
lightning doesnt support :)
