### ISSUE TITLE
Cannot see availabilty of others when creating an event

### ISSUE THREAD

**Issue by shinkicker** [Ericsson/exchangecalendar#179]
Hi,

I as per title, when I create an event and 'Invite Attendee's' everyone's time is shown as pink 'Not available'.

Is there an integration step that I missed somewhere to get this to work?

Regards,
Luke

**Comment by shinkicker** [comment]
Edit; Worked it out. If you close it and open it again, it updates. But that is more of a workaround at a guess.

**Comment by muthusuba** [comment]
Could be related to #195 (EWS Extension seems to get disconnected somehow from the server and doesn't connect back...its being looked at). Closing this for now.
