### ISSUE TITLE
Meetings that are cancelled are not removed

### ISSUE THREAD

**Issue by ewenans** [Ericsson/exchangecalendar#18]
When I receive a cancellation for a meeting it will only change the name of the meeting to "cancelled: name of meeting" instead of actually removing it.

**Comment by phemmer** [comment]
I too am having this issue. I have "Automatically remove cancelled events" checked, yet my calendar is littered with cancelled events.

Thunderbird 38.5.1 (OS-X)
Lightning 4.0.5.2
Exchange EWS Provider 3.5.0

**Comment by chrislong** [comment]
I have the exact issue @phemmer reports.

Thunderbird 36.6.0 (Linux)
Lightning 4.0.5.2
Exchange EWS Provider 3.5.0

I *think* this used to not happen (i.e., cancelled events were deleted), but I'm not positive. I've been using Exchange EWS Provider since July 2015. Maybe this is a regression?

**Comment by bavincen** [comment]
this may be issue because of lightning  4.0.5.2, test needed to find if that is occurring in lightning 4.0.2.
