### ISSUE TITLE
Event invitation automatically deleted after accepting

### ISSUE THREAD

**Issue by gitman0** [Ericsson/exchangecalendar#183]
I've noticed that accepting an event invitation causes the invitation message itself to get moved to my Deleted Items. Is it at all possible to disable this behavior? Or can the option be added?

The reason is that I often receive attachments within event invitations, and I like to refer to the message at some point later on (often during the event) to view those attachments.

Thanks

**Comment by bavincen** [comment]
@gitman0  Attachment can be opened in Event in Calendar tab..

**Comment by fongpwf** [comment]
I think the desktop outlook client has a setting for this.
I too would prefer to disable this behavior.
Quickly searching the code, it seems the setting "ecAutoRemoveInvitationResponse1" might be related to this?  I don't know how to change it though.
