### ISSUE TITLE
EWS Provider breaks new calendar wizard for Provider for Google Calendar

### ISSUE THREAD

**Issue by clokep** [Ericsson/exchangecalendar#184]
This breaks adding a calendaring using the GData provider, I had to disable it to add my calendar and then renable it.

With both enabled, the bar to enter a website address shows up when selecting a Google Calendar when it shouldn't (you're prompted for an email address on the next page). Note that I installed EWS before Google Calendar, if that matters.

Thunderbird 31.7.0
Lightning 3.3.3
Provider for Google Calendar 1.0.4
Exchange EWS Provider 3.3.2

**Comment by bavincen** [comment]
Install Google provider and Ews Provider in sequence.. Let us check if the issue really exist. We did a fix recently ..

**Comment by clokep** [comment]
Yes, the work around was to disable the EWS Provider, add my Google Calendar and then re-enable the EWS Provider. (As I stated above.)

**Comment by simulot** [comment]
I confirm the issue. It's not possible to add google calendars once EWS is installed. 

The workaroud works.

**Comment by bavincen** [comment]
Earlier users were unable to add google calendar ..

**Comment by bavincen** [comment]
#252  @clokep , confirm please if it is fixed or not

https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

**Comment by clokep** [comment]
This seems to have been fixed. Thanks! :+1:
