### ISSUE TITLE
Check server and mailbox never returns

### ISSUE THREAD

**Issue by bytemedwb** [Ericsson/exchangecalendar#186]
I have tried this with both 3.3.1 and 3.3.2.
I am looking to sync my Thunderbird calendar with my one on Office365.
I am running on MacOS 10.10.3
I am running 31.7.0 release of Thunderbird
Lightning is 3.3.3

Autodiscover does not work and returns and error about accounts with domain names.
So I enter this data:
Server URL: https://outlook.com/ews/exchange.asmx (I have also tried several other variants - same behavior but if I enter this address in my browser I get the web service response page)
Primary Email address: dboyd@incadencecorp.com
Username: dboyd@incadencecorp.com
Domain Name: Blank
Share Folder Id: Blank

I hit the Check server and mailbox button and it never returns.  Nothing happens, continue remains greyed out.

**Comment by bavincen** [comment]
Are  you using email address in case yes it happens.
 please check the latest code there is a fix for this

**Comment by bavincen** [comment]
check your proxy settings please clcosing it
