### ISSUE TITLE
System JS : ERROR (null):0 - too much recursion

### ISSUE THREAD

**Issue by pkolmann** [Ericsson/exchangecalendar#187]
I have Debian Thunderbird 31.6.0-1 (icedove) running with Iceowl 3.3.6 and exchange provider 3.3.2 and 3.4_beta1 on Linux.

I have a Master-Password set for my login data. I have 2 Exchange Calendars and the exchangecalendar plugin worked very fine. On startup I got 3 Master Password boxes but that's ok.

Then I added several google calendars as well and it worked first. But after a restart, I see a lot of 

System JS : ERROR (null):0 - too much recursion

errors on the console. With 3.3.2 I see thunderbird start but the master password boxes look different and won't allow me to enter a password at all. With 3.4.beta1 thunderbird doesn't even start :(

Can I help anyhow to debug this issue?
Thanks, Philipp

**Comment by pkolmann** [comment]
I tested it more. I have several calendars in gmail that I added. If I only add 6 of my gmail calendars, everything works. After I added the seventh calendar (doesn't matter which one) and restart thunderbird, I get this error message.

The Error disappears as soon as I remove the exchangecalendar extension from my Thunderbird profile.

**Comment by muthusuba** [comment]
@pkolmann thank you - it seems like there is some kind of a limit? That said, how many (gmail) calendars are you able to add without using Thunderbird EWS extension, please?

**Comment by bavincen** [comment]
This issue is quite similar to the one password issue. please check our master branch and let know if it is working for you

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

Please check latest update please?

**Comment by bavincen** [comment]
Can you please post the same bug in Lightning?

**Comment by bavincen** [comment]
This happend due to null value search in gloda. i can confirm this bug is fixed..

closing on next release.
