### ISSUE TITLE
After windows standby with TB opened, new events are not displayed anymore

### ISSUE THREAD

**Issue by Mer0me** [Ericsson/exchangecalendar#188]
After putting windows in standby-mode with TB opened, and resuming the session, if I add a new event to my Exchange Calendar, it doesn't appear in the agenda (all old events are visible but I can't modify them). However, the new invisible event is sent to the Exchange Server and I can see it in Outlook.
After restarting TB, the event is here and I can add new ones and see them.

TB 31.7.0
EWS 3.3.2
Lightning 3.3.3

**Comment by brenboy** [comment]
Similar to issue #122

**Comment by muthusuba** [comment]
issue 195 and this one are related.

**Comment by muthusuba** [comment]
@Mer0me Let's track this on #195 please? Thanks!

**Comment by Mer0me** [comment]
ok
