### ISSUE TITLE
Time zone not mapped correctly?

### ISSUE THREAD

**Issue by yaronf** [Ericsson/exchangecalendar#189]
Whenever I create a new event, the event's time zone is set to Africa/Abidjan (the first one in the table?). The correct time zone, which is set for Lightning is Asia/Jerusalem. 

The only suspicious thing in the error console is:
```
Warning: ReferenceError: reference to undefined property this.mSelectedInternal
Source file: chrome://global/content/bindings/menulist.xml
Line: 439
```
Then, when I try to change the time zone from the event dialog, I cannot save the modified event, and I get:
```
Error: exchTimeZone is null
Source file: resource://interfaces/exchangeEvent/mivExchangeEvent.js
Line: 389

Error: NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "exchTimeZone is null" {file: "resource://interfaces/exchangeEvent/mivExchangeEvent.js" line: 389}]'[JavaScript Error: "exchTimeZone is null" {file: "resource://interfaces/exchangeEvent/mivExchangeEvent.js" line: 389}]' when calling method: [mivExchangeEvent::updateXML]
Source file: file:///home/yaronf/.thunderbird/4r8j42vh.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/exchangeCalendar/mivExchangeCalendar.js
Line: 5321
```
Thanks!

**Comment by muthusuba** [comment]
Is this on 3.3.2, please?

**Comment by bavincen** [comment]
Hello
We are using Lightning timezone settings. It will be getting fixed in lightning.
You can disable the automatic timezone change in preference
Thanks

**Comment by yaronf** [comment]
Yes, it's on 3.3.2.

When Lightning is set to America/Los Angeles, things work fine. When it 
is set to Asia/Jerusalem, they don't. Could it be some kind of 
interaction with the time zone setting on Exchange?

I don't see any setting for automatic TZ change, not even in 
about:config (TB 31.7 on Ubuntu).

Thanks!

**Comment by bavincen** [comment]
lighting timezone set from operating system  by guessing

**Comment by bavincen** [comment]
you will get fix for this from lightning and us sooner.. closing it for now
