### ISSUE TITLE
Support for Thunderbird 38 beta

### ISSUE THREAD

**Issue by ekarlso** [Ericsson/exchangecalendar#192]
Is there support for this with Lightning 4.0 beta 3 ?

**Comment by muthusuba** [comment]
I thought so....can you try and let us know if it doesn't work, please?
If stable doesn't work - please check the master branch...Thanks!

**Comment by bavincen** [comment]
we do have.. are you seeing any error? please post the log error
thanks

**Comment by pubcoder** [comment]
Hi,
my thunderbird updated itself to 38.0.1 and came with preinstalled Lightning 4.0.0.1.
The Exchange calendars appear disabled.
When I try to re-add the calendars it fails with the following:

[Exception... "Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]"  nsresult: "0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE)"  location: "JS frame :: resource://calendar/modules/calUtils.jsm -> file:///home/path-to-thunderbird-profile/calendar-js/calCalendarManager.js :: cmgr_createCalendar :: line 440"  data: no]

I guess something changed with api..

**Comment by bavincen** [comment]
please wait for our next brelease or use 3.3.2 thanks

**Comment by zioalex** [comment]
Same problem here.

**Comment by pubcoder** [comment]
I just installed 3.4.0~beta7 -- works for me.
Thanks!

**Comment by zioalex** [comment]
Worked with latest stable 3.3.2 Great! Thanks.
