### ISSUE TITLE
Installing Latest update has broken Google Contacts Address Book provider

### ISSUE THREAD

**Issue by dlsutton** [Ericsson/exchangecalendar#193]
After installing the 3.3.2 provider the Google Contacts Address Book provider is no longer able to successfully log into my google accounts for contact management.  Was working wonderfully with prior version.  Now broken.

-dave

**Comment by bavincen** [comment]
is that working for you when disabling this addon

**Comment by dlsutton** [comment]
update:  In further research it appears that this is NOT related to the the latest update.  Apparently the changes to the Google Contacts API hit at the same time coincidentally and this broke the other plugin.  Sorry for the confusion!!
