### ISSUE TITLE
When I suspend and resume my system, my queue size is increasing automaticallly whereas I have less items in calendar. (master Branch)

### ISSUE THREAD

**Issue by vikas290691** [Ericsson/exchangecalendar#195]
When I suspend and resume my system, my queue size is increasing automaticallly whereas I have less items in calendar
![suspend and resume](https://cloud.githubusercontent.com/assets/11500779/7833546/4b4d385a-0485-11e5-9f7a-1299e2badf15.png)

**Comment by vikas290691** [comment]
I am facing the same issue when also, when I switch my system  lan to wifi.

**Comment by sysadm-prs-de** [comment]
Hi,
this looks very much like #137 - do you have one or more calendars in your configuration?
As stated in #137 having just one calendar doesn't let the problem occur (though it is still there...)

**Comment by Mer0me** [comment]
For #188 I have a single Exchange Calendar in TB.

**Comment by ehrenfeu** [comment]
I can confirm this behaviour. Contrary to what the (closed) issue #188 says, it is not related to Windows - the same happens on Linux as well...

**Comment by bavincen** [comment]
Please use this branch if you are checking out "cacheandperformancefix" ,


https://github.com/Ericsson/exchangecalendar/tree/cacheandperformancefix

**Comment by bavincen** [comment]
\

**Comment by bavincen** [comment]
reopen if issue exists

**Comment by bavincen** [comment]
reopen if issue exists

**Comment by cweickhmann** [comment]
Problem persists (for ages), deleting and re-creating calendars just isn't an option!
Configuration:
TB 45.1.1
EWS 3.8-beta3 (but also 3.7 stable)
Windows 7 64bit

**Comment by zaharcelac** [comment]
Problem exists. After every calendar sync it drops to read-only mode.
Xubuntu: 16.04 (latest updates installed)
TB: 52.2.1 (x64) with 3 add-ons only
- ExQuilla for Microsoft Exchange 52.3.1200
- Lightning 5.4
- ESW: 3.9.0

**Comment by normic** [comment]
@zaharcan : try using the current (and maintained) fork here: https://github.com/ExchangeCalendar/exchangecalendar/releases

I know the latest release 4.0.0-beta4 is running with current TB and Lightning on Win7, Ubuntu 16.04 and Mint 17.2 /3/4
Following discussions in https://github.com/ExchangeCalendar/exchangecalendar/issues there are probably a lot more combinations which are known to work.
