### ISSUE TITLE
Event pop up doesn’t get disappear using "Dismiss" and "Dismiss All" button.  (master Branch)

### ISSUE THREAD

**Issue by vikas290691** [Ericsson/exchangecalendar#196]
There used to be a pop-up for the event in exchange calendar as a reminder. When I try to dismiss it using "Dismiss" and "Dismiss All"  button. I am unable to do the same. The fauntionality is, pop-up should get disappear if we dismiss it. But the same functionality is not working.

**Comment by bavincen** [comment]
We are unable to reproduce
Acutal case if you not taking any action,first time, when the popup appear, next time it just snooze that event though the user is dismissing it.

any help to reproduce?

**Comment by bavincen** [comment]
please follow #138
