### ISSUE TITLE
While creating of google calendar, unable to do the same. (master Branch)

### ISSUE THREAD

**Issue by vikas290691** [Ericsson/exchangecalendar#197]
I try to create the google calendar using addons "Provider for Google Calendar" but I am unable to create the calendar. 
i use the below steps to create the calendar.
1. Click on New Calendar option.
2. then gave the location value for my private address of google caledar.
3. Click on next.
4. then there was one more next button, I clicked lot many times. But unable to proceed. 

Issue: Actually After this next click it should pop-up for username and passsword of your google account. But which is not happening.

**Comment by bavincen** [comment]
please provide screenshot. we are unable to reproduce.. 
Thanks
