### ISSUE TITLE
Snooze and snooze all buttons are not working for event pop up in calendar. (master Branch)

### ISSUE THREAD

**Issue by vikas290691** [Ericsson/exchangecalendar#198]
There used to be a pop-up for the event in exchange calendar as a reminder. When I try to snooze it using "Snooze" and "Snooze All"  button. I am unable to do the same. The fauntionality is, pop-up should get disappear and it should appear again for specific time what we have alloted, if we snooze it. But the same functionality is not working.

**Comment by bavincen** [comment]
Please check cacheandperformac
