### ISSUE TITLE
unable to delete the events from calendar. (master Branch)

### ISSUE THREAD

**Issue by vikas290691** [Ericsson/exchangecalendar#199]
There are some events in my calendar. i try to delete those event. I am unable to do the same. Even I try to Delete all the Occurances of event. The same functionality is not working. Event doesn't get disappear from exchange calendar.

**Comment by bavincen** [comment]
Could not reproduce the same

**Comment by psmears** [comment]
I am seeing this issue with 3.4.0~beta7. I can provide any diagnostics you request, if that will help investigate the issue?
