### ISSUE TITLE
can't create tasks in exchange calendar

### ISSUE THREAD

**Issue by mr-gosh** [Ericsson/exchangecalendar#202]
when i create new tasks - the exchange calendard (that is properly synced) doesn't show up in the list of selectable targets.

In the Overview there is written "Please select a calendar that supports tasks" next to the "New Task" Button when I select the exchange calendar...

What is wrong here?

**Comment by bavincen** [comment]
Please provide screen shot 
Thanks

**Comment by mr-gosh** [comment]
![bildschirmfoto von 2015-05-29 15 07 10](https://cloud.githubusercontent.com/assets/3028703/7883141/6f439e76-0614-11e5-801b-a0304c300556.png)
here the screenshot of the exchange calendar selected and no possibility...

**Comment by bavincen** [comment]
ok you need to add task calendar first of all..
you can follow the same steps that add calendar but select task folder before clicking finish..
