### ISSUE TITLE
3.4.0~beta1 and thunderbird - 3 queued jobs never finish

### ISSUE THREAD

**Issue by sloncho** [Ericsson/exchangecalendar#209]
After upgrading to 3.4.0~beta1, Thunderbird 31.7 keeps showing a spinner in the status bar with message "1 running & 3 queued jobs". This never ends. I tried restarting thunderbitd few time, and after a restart it starts crunching jobs for some time (the queued jobs shown vary between 50 and 120). It eventually succeeds to process the jobs (strange that the queued jobs number decreases, then suddenly increases, then it drops again), and stops at 3 queued, without future progress.

Any idea how to start investigating this?

**Comment by freongrr** [comment]
In my case, the number increases every time I hit the Synchronize button or when I try to dismiss a reminder. I looked into the error console but there is nothing.

**Comment by bavincen** [comment]
please go to  ews properties, offline cache clear it.. 

ebnable all logs, run Thunderbird in terminal to check logs, let us know what is getting stuck

**Comment by bavincen** [comment]
Is that working?

**Comment by bavincen** [comment]
fixed. wait for our next release 

please check it in our new release and reopen if it still .. please let us know ur configurations

**Comment by freongrr** [comment]
For reference, this is what I see in the log every time I press the "Dismiss" button.

    1st-setup:2015-5-4 17:3:48.219:[TS (Exchange)] modifyItem (_modifyItem in mivExchangeCalendar.js:1414)
    1st-setup:2015-5-4 17:3:48.220:[TS (Exchange)] 1 -- aOldItem.recurrenceInfo:RRULE:FREQ=WEEKLY;UNTIL=20150915T000000Z;BYDAY=TH
    , aNewItem.recurrenceInfo:RRULE:FREQ=WEEKLY;UNTIL=20150915T000000Z;BYDAY=TH
     (_modifyItem in mivExchangeCalendar.js:1449)
    1st-setup:2015-5-4 17:3:48.220:[TS (Exchange)] 1 -- aOldItem.recurrenceInfo.toString():RRULE:FREQ=WEEKLY;UNTIL=20150915T000000Z;BYDAY=TH
     (_modifyItem in mivExchangeCalendar.js:1450)
    1st-setup:2015-5-4 17:3:48.220:[TS (Exchange)] 1 -- aNewItem.recurrenceInfo.toString():RRULE:FREQ=WEEKLY;UNTIL=20150915T000000Z;BYDAY=TH
     (_modifyItem in mivExchangeCalendar.js:1451)
    1st-setup:2015-5-4 17:3:48.221:[TS (Exchange)] ModifyItem: it is an event. (_modifyItem in mivExchangeCalendar.js:1500)
    1st-setup:2015-5-4 17:3:48.222:[TS (Exchange)] getInvitedAttendee 2:mailto:foo@bar.com (_getInvitedAttendee in mivExchangeCalendar.js:2940)
    1st-setup:2015-5-4 17:3:48.222:[TS (Exchange)] getInvitedAttendee FOUND someonelse:Title of the event, attendee.id:mailto:foo@bar.com, attendee.participationStatus:NEEDS-ACTION (_getInvitedAttendee in mivExchangeCalendar.js:2948)
    1st-setup:2015-5-4 17:3:48.222:[TS (Exchange)] getInvitedAttendee 2:mailto:foo@bar.com (_getInvitedAttendee in mivExchangeCalendar.js:2940)
    1st-setup:2015-5-4 17:3:48.223:[TS (Exchange)] getInvitedAttendee FOUND someonelse:Title of the event, attendee.id:mailto:foo@bar.com, attendee.participationStatus:NEEDS-ACTION (_getInvitedAttendee in mivExchangeCalendar.js:2948)
    1st-setup:2015-5-4 17:3:48.223:[TS (Exchange)] getInvitedAttendee 2:mailto:foo@bar.com (_getInvitedAttendee in mivExchangeCalendar.js:2940)
    1st-setup:2015-5-4 17:3:48.223:[TS (Exchange)] getInvitedAttendee FOUND someonelse:Title of the event, attendee.id:mailto:foo@bar.com, attendee.participationStatus:NEEDS-ACTION (_getInvitedAttendee in mivExchangeCalendar.js:2948)
    1st-setup:2015-5-4 17:3:48.224:[TS (Exchange)] getInvitedAttendee 2:mailto:me@bar.com (_getInvitedAttendee in mivExchangeCalendar.js:2940)
    1st-setup:2015-5-4 17:3:48.224:[TS (Exchange)] getInvitedAttendee FOUND myself:Title of the event, attendee.participationStatus:ACCEPTED, aItem.myResponseType:Accept (_getInvitedAttendee in mivExchangeCalendar.js:2943)
    1st-setup:2015-5-4 17:3:48.225:[TS (Exchange)] getInvitedAttendee 2:mailto:foo@bar.com (_getInvitedAttendee in mivExchangeCalendar.js:2940)
    1st-setup:2015-5-4 17:3:48.225:[TS (Exchange)] getInvitedAttendee FOUND someonelse:Title of the event, attendee.id:mailto:foo@bar.com, attendee.participationStatus:NEEDS-ACTION (_getInvitedAttendee in mivExchangeCalendar.js:2948)
    1st-setup:2015-5-4 17:3:48.225:[TS (Exchange)] getInvitedAttendee 2:mailto:foo@bar.com (_getInvitedAttendee in mivExchangeCalendar.js:2940)
    1st-setup:2015-5-4 17:3:48.225:[TS (Exchange)] getInvitedAttendee FOUND someonelse:Title of the event, attendee.id:mailto:foo@bar.com, attendee.participationStatus:NEEDS-ACTION (_getInvitedAttendee in mivExchangeCalendar.js:2948)
    1st-setup:2015-5-4 17:3:48.226:[TS (Exchange)] getInvitedAttendee 2:mailto:foo@bar.com (_getInvitedAttendee in mivExchangeCalendar.js:2940)
    1st-setup:2015-5-4 17:3:48.226:[TS (Exchange)] getInvitedAttendee FOUND someonelse:Title of the event, attendee.id:mailto:foo@bar.com, attendee.participationStatus:NEEDS-ACTION (_getInvitedAttendee in mivExchangeCalendar.js:2948)
    1st-setup:2015-5-4 17:3:48.226:[TS (Exchange)] getInvitedAttendee 2:mailto:me@bar.com (_getInvitedAttendee in mivExchangeCalendar.js:2940)
    1st-setup:2015-5-4 17:3:48.226:[TS (Exchange)] getInvitedAttendee FOUND myself:Title of the event, attendee.participationStatus:ACCEPTED, aItem.myResponseType:Accept (_getInvitedAttendee in mivExchangeCalendar.js:2943)
    1st-setup:2015-5-4 17:3:48.227:[TS (Exchange)] 1 meOld.participationStatus=ACCEPTED, meNew.participationStatus=ACCEPTED (_modifyItem in mivExchangeCalendar.js:1518)
    1st-setup:2015-5-4 17:3:48.227:[TS (Exchange)] 1 aOldItem.status=CONFIRMED, aNewItem.status=CONFIRMED (_modifyItem in mivExchangeCalendar.js:1519)
    1st-setup:2015-5-4 17:3:48.227:[TS (Exchange)] The organizer is:mailto:foo@bar.com (_modifyItem in mivExchangeCalendar.js:1614)
    1st-setup:2015-5-4 17:3:48.236:[TS (Exchange)] onlySnoozeChanged Or reminder time before start. (_makeUpdateOneItem in mivExchangeCalendar.js:5351)
    1st-setup:2015-5-4 17:3:48.237:[TS (Exchange)] modifyItem: it is a event. aOldItem.CalendarItemType=:RecurringMaster (_modifyItem in mivExchangeCalendar.js:1669)
    1st-setup:2015-5-4 17:3:48.237:[TS (Exchange)]  Master changed:Title of the event (_modifyItem in mivExchangeCalendar.js:1673)
    1st-setup:2015-5-4 17:3:48.237:[TS (Exchange)]  ==1 invite=true (_modifyItem in mivExchangeCalendar.js:1678)
    1st-setup:2015-5-4 17:3:48.238:[TS (Exchange)] modifyItem: changed:<nsTypes:ItemChange xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsTypes:ItemId Id="AAMkAGQ3ZjIzYTNmLWUwMzYtNDBiYy1iN2NlLTQ4NTVjMmRhOWYzMQBGAAAAAACTagn5tKm3Q5d2iLwTLJRzBwCEeJOujuF6SKNyXoLBDenlAAAFnnAeAAAOOz9iJyOlSY8GQmhSMOrQAAB9MwiHAAA=" ChangeKey="DwAAABYAAAAOOz9iJyOlSY8GQmhSMOrQAAB9OLcP"/><t:Updates xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><t:SetItemField xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><t:ExtendedFieldURI DistinguishedPropertySetId="Common" PropertyId="34144" PropertyType="SystemTime"/><t:CalendarItem><t:ExtendedProperty><t:ExtendedFieldURI DistinguishedPropertySetId="Common" PropertyId="34144" PropertyType="SystemTime"/><t:Value>2015-06-18T08:00:00Z</t:Value></t:ExtendedProperty></t:CalendarItem></t:SetItemField></t:Updates></nsTypes:ItemChange> (_modifyItem in mivExchangeCalendar.js:1681)

The number of queued job increase by one, but nothing else happens.

My config is:
- ubuntu 15.05
- thunderbird 31.7.0
- Exchange EWS Provider 3.4.0-beta1 (built from master at about the same time as my first comment)

**Comment by bavincen** [comment]
You can see that is getting snozzed.. testing the same..

**Comment by freongrr** [comment]
I've installed the version with your patch and I'm not seeing any issue so far. I'll let it running for a while.

**Comment by bavincen** [comment]
Thank you so much..
Please make sure you are using this commit..

**Comment by bavincen** [comment]
Thank you so much..
Please make sure you are using this commit..
https://github.com/Ericsson/exchangecalendar/commit/f866ffae3691c74cdbb912d669513a42857a85d5

**Comment by sloncho** [comment]
With 3.4.0~beta2 I still see queued jobs increasing.

Looking at the logs, every 5 seconds I see:

```

1st-setup:2015-5-4 8:16:0.104:getEvents: *****@******.com
1st-setup:2015-5-4 8:16:0.111:mivExchangeAuthPrompt2: getPassword: A realm was specified:Exchange Web Service (_getPassword in mivExchangeAuthPrompt2.js:122)
1st-setup:2015-5-4 8:16:0.112:mivExchangeAuthPrompt2: getPassword: Going to see if there is one in the passwordManager. (_getPassword in mivExchangeAuthPrompt2.js:137)
1st-setup:2015-5-4 8:16:0.112:mivExchangeAuthPrompt2: passwordManagerGet: username=*********, aURL=https://************/EWS/exchange.asmx, aRealm=Exchange Web Service (_passwordManagerGet in mivExchangeAuthPrompt2.js:617)
1st-setup:2015-5-4 8:16:0.114:mivExchangeAuthPrompt2: passwordManagerGet found password for: username=*********, aURL=https://************/EWS/exchange.asmx, aRealm=Exchange Web Service (_passwordManagerGet in mivExchangeAuthPrompt2.js:626)
1st-setup:2015-5-4 8:16:0.115:mivExchangeAuthPrompt2: getPassword: There is a password stored in the passwordManager. (_getPassword in mivExchangeAuthPrompt2.js:140)
1st-setup:2015-5-4 8:16:0.115:mivExchangeAuthPrompt2: getPassword: password(1)=******** (_getPassword in mivExchangeAuthPrompt2.js:152)
1st-setup:2015-5-4 8:16:0.116:mivExchangeAuthPrompt2: getPassword: We have a password:******** (_getPassword in mivExchangeAuthPrompt2.js:250)
1st-setup:2015-5-4 8:16:0.116:94970aa3-adb6-4473-acab-c5c2775c0e67: : 1 ExchangeRequest.sendRequest : user=*********, url=https://************/EWS/exchange.asmx
1st-setup:2015-5-4 8:16:0.117:94970aa3-adb6-4473-acab-c5c2775c0e67: We have a prePassword: *******
1st-setup:2015-5-4 8:16:0.117:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.117:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.118:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.118:94970aa3-adb6-4473-acab-c5c2775c0e67: : sendRequest Sending: <?xml version="1.0" encoding="utf-8"?>
<nsSoap:Envelope xmlns:nsSoap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsSoap:Header><nsTypes:RequestServerVersion Version="Exchange2010_SP2"/><nsTypes:TimeZoneContext><t:TimeZoneDefinition Name="(UTC-06:00) Central Time (US &amp; Canada)" Id="Central Standard Time" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:nsSoap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"/></nsTypes:TimeZoneContext></nsSoap:Header><nsSoap:Body><nsMessages:GetEvents xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:nsSoap="http://schemas.xmlsoap.org/soap/envelope/"><nsMessages:SubscriptionId xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types">FwBtc3AwMWV4YzAxcC5jZnMtaW50LmNvbRAAAACjYO+X9+yqSpcZRmOoqREF9VjRD9930gg=</nsMessages:SubscriptionId><nsMessages:Watermark xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types">AQAAALTxAghh25xFtn4cqPF2JdeoQmoCAAAAAAE=</nsMessages:Watermark></nsMessages:GetEvents></nsSoap:Body></nsSoap:Envelope>

1st-setup:2015-5-4 8:16:0.119:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.119:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.119:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.120:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.120:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.121:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.121:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.122:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({e46d924d-c20f-4add-8cf5-1e1c817b2181})
1st-setup:2015-5-4 8:16:0.122:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({2b6d6fb6-ab28-4f4c-af84-bfdbb7866d72})
1st-setup:2015-5-4 8:16:0.122:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsIApplicationCacheContainer
1st-setup:2015-5-4 8:16:0.123:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.123:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.123:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.124:94970aa3-adb6-4473-acab-c5c2775c0e67: : ExchangeRequest.loadstart
1st-setup:2015-5-4 8:16:0.128:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsIProgressEventSink
1st-setup:2015-5-4 8:16:0.129:58c45d25-f3bd-4164-8529-9b80597a8ef5:   --- ecnsIAuthPrompt2.onStatus: STATUS_WAITING_FOR of *********
1st-setup:2015-5-4 8:16:0.129:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.130:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.130:58c45d25-f3bd-4164-8529-9b80597a8ef5: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-4 8:16:0.130:58c45d25-f3bd-4164-8529-9b80597a8ef5:   --- ecnsIAuthPrompt2.onStatus: STATUS_RECEIVING_FROM of *********
1st-setup:2015-5-4 8:16:0.131:58c45d25-f3bd-4164-8529-9b80597a8ef5:   --- ecnsIAuthPrompt2.onProgress: this is a nsIChannel
1st-setup:2015-5-4 8:16:0.131:58c45d25-f3bd-4164-8529-9b80597a8ef5:   --- ecnsIAuthPrompt2.onProgress:668 of 18446744073709552000
1st-setup:2015-5-4 8:16:0.131:58c45d25-f3bd-4164-8529-9b80597a8ef5:   --- ecnsIAuthPrompt2.onStatus: STATUS_RECEIVING_FROM of *********
1st-setup:2015-5-4 8:16:0.132:58c45d25-f3bd-4164-8529-9b80597a8ef5:   --- ecnsIAuthPrompt2.onProgress: this is a nsIChannel
1st-setup:2015-5-4 8:16:0.132:58c45d25-f3bd-4164-8529-9b80597a8ef5:   --- ecnsIAuthPrompt2.onProgress:680 of 18446744073709552000
1st-setup:2015-5-4 8:16:0.132:94970aa3-adb6-4473-acab-c5c2775c0e67: : ExchangeRequest.progress. loaded:1314, total:1314
1st-setup:2015-5-4 8:16:0.133:94970aa3-adb6-4473-acab-c5c2775c0e67: : ExchangeRequest.onLoad :load, readyState:4, status:200
1st-setup:2015-5-4 8:16:0.133:94970aa3-adb6-4473-acab-c5c2775c0e67: : ExchangeRequest.onLoad :Cache-Control: private
Transfer-Encoding: chunked
Content-Type: text/xml; charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
Server: Microsoft-IIS/7.5
X-AspNet-Version: 2.0.50727
X-Powered-By: ASP.NET
Date: Thu, 18 Jun 2015 13:15:59 GMT

1st-setup:2015-5-4 8:16:0.133:94970aa3-adb6-4473-acab-c5c2775c0e67: : ExchangeRequest.onLoad :<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="14" MinorVersion="3" MajorBuildNumber="224" MinorBuildNumber="2" Version="Exchange2010_SP2" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"/></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><m:GetEventsResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:GetEventsResponseMessage ResponseClass="Success"><m:ResponseCode>NoError</m:ResponseCode><m:Notification><t:SubscriptionId>FwBtc3AwMWV4YzAxcC5jZnMtaW50LmNvbRAAAACjYO+X9+yqSpcZRmOoqREF9VjRD9930gg=</t:SubscriptionId><t:PreviousWatermark>AQAAALTxAghh25xFtn4cqPF2JdeoQmoCAAAAAAE=</t:PreviousWatermark><t:MoreEvents>false</t:MoreEvents><t:StatusEvent><t:Watermark>AQAAALTxAghh25xFtn4cqPF2JdeoQmoCAAAAAAE=</t:Watermark></t:StatusEvent></m:Notification></m:GetEventsResponseMessage></m:ResponseMessages></m:GetEventsResponse></s:Body></s:Envelope>
1st-setup:2015-5-4 8:16:0.134:94970aa3-adb6-4473-acab-c5c2775c0e67: exchangeRequest.isHTTPRedirect.xmlReq. xmlReq.readyState:4, xmlReq.status:200
1st-setup:2015-5-4 8:16:0.137:getEventsOK:*****@******.com
1st-setup:2015-5-4 8:16:0.139:[work] setProperty. aName:exchangeCurrentStatus, aValue:0 (setProperty in mivExchangeCalendar.js:826)
1st-setup:2015-5-4 8:16:0.139:94970aa3-adb6-4473-acab-c5c2775c0e67: : ExchangeRequest.loadend
1st-setup:2015-5-4 8:16:0.140:94970aa3-adb6-4473-acab-c5c2775c0e67: : ExchangeRequest.loadend :loadend, readyState:4, status:200
1st-setup:2015-5-4 8:16:0.140:94970aa3-adb6-4473-acab-c5c2775c0e67: : ExchangeRequest.loadend :<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="14" MinorVersion="3" MajorBuildNumber="224" MinorBuildNumber="2" Version="Exchange2010_SP2" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"/></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><m:GetEventsResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:GetEventsResponseMessage ResponseClass="Success"><m:ResponseCode>NoError</m:ResponseCode><m:Notification><t:SubscriptionId>FwBtc3AwMWV4YzAxcC5jZnMtaW50LmNvbRAAAACjYO+X9+yqSpcZRmOoqREF9VjRD9930gg=</t:SubscriptionId><t:PreviousWatermark>AQAAALTxAghh25xFtn4cqPF2JdeoQmoCAAAAAAE=</t:PreviousWatermark><t:MoreEvents>false</t:MoreEvents><t:StatusEvent><t:Watermark>AQAAALTxAghh25xFtn4cqPF2JdeoQmoCAAAAAAE=</t:Watermark></t:StatusEvent></m:Notification></m:GetEventsResponseMessage></m:ResponseMessages></m:GetEventsResponse></s:Body></s:Envelope>

````

I have the calendar set to sync every 300 seconds, I do not know why it pings the server 5 seconds. I would guess that there is a job which never ends, and keep retrying, so any other new job scheduled - syncs or dismiss updates - is put queue and never gets executed.

**Comment by bavincen** [comment]
I will share small imformation. Get events are for mail syncing(tags etc).  You can check that latest additions in mater. We are keep fixing nor lightning 4.0 or greater. Please wait for our next working release

**Comment by sloncho** [comment]
What is the course of action for now? The way it is - it does not work for me. Should I downgrade? To what version?

**Comment by bavincen** [comment]
hmm yes..
you can downgrade to 3.2.2 works fine

u can use our latest addon. which works with recent bugs n fixed.  refer wiki for more thanks
