### ISSUE TITLE
Can't accept or decline meeting request after upgrading to 3.4.0-beta1

### ISSUE THREAD

**Issue by paulinster** [Ericsson/exchangecalendar#210]
When I receive an event request in my inbox, I do see the Accept/Tentative/Decline button, However when I click them it look like nothing happen. 

When I click a button Accept/Tentative/Decline button, the "This message contains an invitation to an event." bar disapear with buttons, and so his the email.

**Comment by bavincen** [comment]
fixed. wait for our next release
