### ISSUE TITLE
Works for a while and then keep runing updating event without any progress

### ISSUE THREAD

**Issue by EricV2** [Ericsson/exchangecalendar#212]
I had to downgrade to make it functionnal again

**Comment by bavincen** [comment]
we had bug which got fixed..

Please try this or u can wait for next release :)

https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

**Comment by EricV2** [comment]
Same bug has been reported for rc2, so reopen or merge...
