### ISSUE TITLE
SEVERE : EWS provider prevents display of mail in main window

### ISSUE THREAD

**Issue by awilkins** [Ericsson/exchangecalendar#213]
Installed 3.4.0-beta1

Mail bodies no longer show in the main window.

![with-ews](https://cloud.githubusercontent.com/assets/368399/8103267/08ba8b28-101f-11e5-9ca6-725d356c8441.png)

Disabled EWS plugin and mail bodies are restored
![without-ews](https://cloud.githubusercontent.com/assets/368399/8103272/0d343294-101f-11e5-9255-3f70d8af6fe0.png)

Workaround :

You can open mail in another window.

Have reverted to 3.3.2

Thunderbird 31.7.0
Lightning 3.3.7
Enigmail 1.7.2
Provider for Google Calendar 1.0.4
Ubuntu 14.04 amd64

**Comment by bavincen** [comment]
Fixed. please wait for next release :)
or you can use our latest version.

https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon
