### ISSUE TITLE
Message bodies are not displayed anymore

### ISSUE THREAD

**Issue by laclaro** [Ericsson/exchangecalendar#214]
Hello,

with the update to v3.4.0-beta1, message bodies in thunderbird are not displayed anymore. Downgrading to v3.3.2 helps.

Best regards,
Henning

**Comment by bavincen** [comment]
Hi @laclaro 

Fixed. please wait for next release :)
or you can use our latest version.

https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

please update us if u are able to use latest verison

**Comment by laclaro** [comment]
Solved by using the lastest version.

**Comment by Nomasan** [comment]
Hi,

Latest 3.4.0-b1 brought back the display, thanks.
By the way, is there a way to know the _actual_ version number?

**Comment by bavincen** [comment]
version number get change during release only...

**Comment by bavincen** [comment]
you can see them addon page :)
