### ISSUE TITLE
3.4.0-beta1 release - issues

### ISSUE THREAD

**Issue by Mephius** [Ericsson/exchangecalendar#215]
After updating to 3.4.0-beta1, message body in message pane is always empty. Opening message in new tab changes nothing — still empty body. Opening message in new window displays message body correctly.

Had to roll back to previous release.

**Comment by LeHack** [comment]
I can confirm the same problem. Disabling the extension fixes the problem.

**Comment by bavincen** [comment]
Fixed. please wait for next release :)
or you can use our latest version.

https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

please update us if u are able to use latest verison

**Comment by envycontent** [comment]
The 'Update Available' modal form is too long and I therefore can't get to the close button to close it or launch the update (or actually use Thunderbird in anyway at all).
Very grateful for the Add On though.

**Comment by carns** [comment]
envycontent: the trick to closing the update available dialog window on a small screen is to hold down the alt button, click somewhere in the window to drag it up until you can see the bottom, then release alt and drag the bottom edge of the window down until the buttons appear at the bottom.  (I would suggest declining the update until beta2 is out, by the way).

**Comment by envycontent** [comment]
Thanks. Alas, didn't work for me (on Macbook Air - so not exactly a small screen). However, I did find that if I waited for the dialog to appear and then went to Preferences and turned off Automatically Check and Show Warning, I got it to disappear.

**Comment by ez121sl** [comment]
I installed the fix earlier today. Message bodies are displayed properly now. Thanks!

**Comment by jburianek** [comment]
After upgrading to 3.4.0-beta1 I had the same issue with the message pane not displaying anything. Installing the latest version based off master fixed it.

**Comment by bavincen** [comment]
@envycontent  which means you will not be notified for next release

**Comment by robertbelgrave** [comment]
@bavincen installed the update from today's master and messages are now displaying properly in tabs and preview pane. Thanks.

**Comment by muthusuba** [comment]
Is this fixed in beta2, please?

**Comment by muthusuba** [comment]
Assuming this is fixed in beta2. Please reopen if otherwise. Thanks.
