### ISSUE TITLE
No more tags :-(

### ISSUE THREAD

**Issue by Hayholten** [Ericsson/exchangecalendar#219]
Hello everyone !

Since last update, I can't tag my mails anymore...

Any solution ?

Thanks ;-)

**Comment by muthusuba** [comment]
You mean beta2?

**Comment by Hayholten** [comment]
Oups, sorry !

I mean beta 1 (beta 2 still not downloaded)... Is that make a difference ?

**Comment by JeffBuckles** [comment]
I had the same problem with beta1.   Fixed in beta2.

**Comment by xaminmo** [comment]
Updating to beta2 didn't fix it for me until I updated TB from 31.7.0 to 38.0.1 and Lightning from 3.x to 4.0.1.

**Comment by muthusuba** [comment]
Closing this for now then...

@xaminmo: I guess, tagging happens on the server before showing it and hence the delay - we should probably open a separate enhancement issue for that...
