### ISSUE TITLE
EWS plugin lagging/hanging TB main process

### ISSUE THREAD

**Issue by xaminmo** [Ericsson/exchangecalendar#223]
During TB startup, EWS plugin fires off lots of processes (40ish), which are very choppy, hanging Thunderbird's main UI process for several seconds at a time.

Also, if an account is locked, then EWS plugin will slow tag updating to at most 1 message per second.

**Comment by muthusuba** [comment]
@xaminmo: Can you share logs, please? It could be because you have specified very low time interval between syncs?

**Comment by frettloeh** [comment]
Perhaps this is related, I constantly get the message displayed that there are running and queued jobs. This happens with both, v3.4.0-beta2 and v3.4.0-beta1:

![queuejobsinthunderbird](https://cloud.githubusercontent.com/assets/5808192/8156028/16b00acc-134a-11e5-846f-eec6a2f653a2.png)

I switched back to v3.3.2 and this is not an issue anymore.

If I can help, tell me how to provide logs, etc.

**Comment by bavincen** [comment]
this may be a temporary issue, if you want to know details about queued jobs.
you can 
Grep "syncFolderItemsOK"

**Comment by bavincen** [comment]
if #230 is fixed.. this issue?

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

Please check latest addon. 

Regards

**Comment by bavincen** [comment]
is this fixed in our master @xaminmo ??
