### ISSUE TITLE
Unable to create new calender 

### ISSUE THREAD

**Issue by rolftheunissen** [Ericsson/exchangecalendar#226]
Creating a new calender with 3.4.0-beta2 results in the following error:

1st-setup:2015-5-1 9:2:57.674:exchWebServicesConvertIDOK: user:, mailbox:my.name@some_domain.nl
1st-setup:2015-5-1 9:2:57.705:mivExchangeAuthPrompt2: getPassword: No username or URL specified. Aborting. (_getPassword in mivExchangeAuthPrompt2.js:98)
1st-setup:2015-5-1 9:2:57.706:4b2c52df-d7fc-4780-a3ba-579bfb4c0d41: : 1 ExchangeRequest.sendRequest : user=, url=https://webmail.some_domain.nl/EWS/Exchange.asmx
1st-setup:2015-5-1 9:2:57.707:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-1 9:2:57.707:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-1 9:2:57.708:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-1 9:2:57.709:4b2c52df-d7fc-4780-a3ba-579bfb4c0d41: : sendRequest Sending: <?xml version="1.0" encoding="utf-8"?>
<nsSoap:Envelope xmlns:nsSoap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsSoap:Header><nsTypes:RequestServerVersion Version="Exchange2007_SP1"/><nsTypes:TimeZoneContext><t:TimeZoneDefinition Id="W. Europe Standard Time" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:nsSoap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"/></nsTypes:TimeZoneContext></nsSoap:Header><nsSoap:Body><nsMessages:FindItem Traversal="Shallow" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:nsSoap="http://schemas.xmlsoap.org/soap/envelope/"><nsMessages:ItemShape xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsTypes:BaseShape>IdOnly</nsTypes:BaseShape></nsMessages:ItemShape><nsMessages:CalendarView StartDate="2011-01-30T11:34:00Z" EndDate="2011-01-30T11:35:00Z" MaxEntriesReturned="1" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"/><nsMessages:ParentFolderIds xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsTypes:DistinguishedFolderId Id="calendar" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages"><nsTypes:Mailbox xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsTypes:EmailAddress>my.name@some_domain.nl</nsTypes:EmailAddress></nsTypes:Mailbox></nsTypes:DistinguishedFolderId></nsMessages:ParentFolderIds></nsMessages:FindItem></nsSoap:Body></nsSoap:Envelope>

1st-setup:2015-5-1 9:2:57.710:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-1 9:2:57.710:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-1 9:2:57.710:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-1 9:2:57.711:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-1 9:2:57.712:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-1 9:2:57.714:4b2c52df-d7fc-4780-a3ba-579bfb4c0d41: : ExchangeRequest.loadstart
1st-setup:2015-5-1 9:2:57.718:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-1 9:2:57.720:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-1 9:2:57.721:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-1 9:2:57.721:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({e46d924d-c20f-4add-8cf5-1e1c817b2181})
1st-setup:2015-5-1 9:2:57.722:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({2b6d6fb6-ab28-4f4c-af84-bfdbb7866d72})
1st-setup:2015-5-1 9:2:57.723:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsIApplicationCacheContainer
1st-setup:2015-5-1 9:2:57.724:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-1 9:2:57.724:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-1 9:2:57.725:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-5-1 9:2:57.727:a3806b00-d25e-44bc-a7b8-8449946fc5c1: ecnsIAuthPrompt2.getInterface: Ci.nsIProgressEventSink
1st-setup:2015-5-1 9:2:57.729:a3806b00-d25e-44bc-a7b8-8449946fc5c1:   --- ecnsIAuthPrompt2.onStatus: STATUS_WAITING_FOR of webmail.some_domain.nl
1st-setup:2015-5-1 9:2:57.750:4b2c52df-d7fc-4780-a3ba-579bfb4c0d41: : ExchangeRequest.error :error, readyState:4, status:0, lastStatus:2152398858
1st-setup:2015-5-1 9:2:57.751:4b2c52df-d7fc-4780-a3ba-579bfb4c0d41: : ExchangeRequest.error :
1st-setup:2015-5-1 9:2:57.752:4b2c52df-d7fc-4780-a3ba-579bfb4c0d41: : xmlReq.getResponseHeader("Location") :null
1st-setup:2015-5-1 9:2:57.752:4b2c52df-d7fc-4780-a3ba-579bfb4c0d41: : ExchangeRequest.error : badCert going to check if it is a cert problem.
1st-setup:2015-5-1 9:2:57.753:mivExchangeAuthPrompt2: checkAndSolveCertProblem: waitingProblem:false, targetSite:https://webmail.some_domain.nl/EWS/Exchange.asmx
1st-setup:2015-5-1 9:2:57.753:4b2c52df-d7fc-4780-a3ba-579bfb4c0d41: : ExchangeRequest.error : badCert no problem.
1st-setup:2015-5-1 9:2:57.753:4b2c52df-d7fc-4780-a3ba-579bfb4c0d41: exchangeRequest.isHTTPRedirect.xmlReq. xmlReq.readyState:4, xmlReq.status:0
1st-setup:2015-5-1 9:2:57.754:4b2c52df-d7fc-4780-a3ba-579bfb4c0d41: exchangeRequest.tryNextURL
1st-setup:2015-5-1 9:2:57.755:4b2c52df-d7fc-4780-a3ba-579bfb4c0d41: ecExchangeRequest.fail: aCode:-16, aMsg:Error during waiting for data of hostname 'webmail.some_domain.nl'. (STATUS_WAITING_FOR)
1st-setup:2015-5-1 9:2:57.755:exchWebServicesCheckServerAndMailboxError: aCode:-16, aMsg:Error during waiting for data of hostname 'webmail.some_domain.nl'. (STATUS_WAITING_FOR)
1st-setup:2015-5-1 9:3:0.299:4b2c52df-d7fc-4780-a3ba-579bfb4c0d41: : ExchangeRequest.loadend
1st-setup:2015-5-1 9:3:0.300:4b2c52df-d7fc-4780-a3ba-579bfb4c0d41: : ExchangeRequest.loadend :loadend, readyState:4, status:0
1st-setup:2015-5-1 9:3:0.302:4b2c52df-d7fc-4780-a3ba-579bfb4c0d41: : ExchangeRequest.loadend :

**Comment by bavincen** [comment]
Please specify user name and/or domain when doing auto discovery..

**Comment by rolftheunissen** [comment]
First, i was not using auto discovery..., I get this error when pushing the "Check server and mailbox" button. 
Second, i get this error with username specified as email-address, specified as username and domain name, and not specified.

**Comment by bavincen** [comment]
if your username is email address, then domain is left empty

**Comment by rolftheunissen** [comment]
Of course, it is even possible to specify both the domain and the email address. I was just listen the 3 cases in which are possible, all fail.

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/commit/88e4417127a93212c29faaa72ed7c33e055509dd  https://github.com/Ericsson/exchangecalendar/commit/ca97609b20bb5c4b87f6eca4c7bb06da082d05ac https://github.com/Ericsson/exchangecalendar/commit/75b094736cefb715e50336795a1004aafc59c2d3
