### ISSUE TITLE
Random deletion of calendar entries etc

### ISSUE THREAD

**Issue by horsfielda** [Ericsson/exchangecalendar#228]
I have version 3.4.0~beta of the plugin.

I have had trouble in the past with pending jobs growing without limit. So I eventually deleted all calendar entries before January 2014 to see if that helped.

It did indeed fix that problem. So I then invited myself to a meeting using Outlook, and monitored what happened in Thunderbird. There was a job that kept running, but the entry in the calendar failed to appear. So I shut down Thunderbird and restarted it. The entry appeared.

I then tried to delete the new entry (an invitation to meet myself not being particularly useful). The entry did not go, so I tried again. After a few moments suddenly a number entries started to disappear ...

So I checked to see if they had disappeared in Outlook as well. They had. So I removed the exchange calendar immediately, and used a backup of my calendar to restore missing entries running into the future. I have now removed the plugin. It is just too dangerous at the moment ...

Later, using Outlook, I found the deleted entries in the Deleted Items folder and used that to restore all deleted entries.

For obvious reasons I am not going to repeat the experiment. I apologize that this means I cannot give better feedback. I still look forward to the day when it works reliably, and am very grateful for the work being done to make it fully functional.

**Comment by bavincen** [comment]
@horsfielda this cant happen.. our cache settings keeps the period of events kept in calendar. you can change that in ews settings..

**Comment by horsfielda** [comment]
Thank you for the email. The entries were definitely deleted. They appeared in the deleted items folder, from which I was able to restore them.

Andrew

--
*---------------------------------------------------*
  Andrew Horsfield        a.horsfield@imperial.ac.uk<mailto:a.horsfield@imperial.ac.uk>
   Department of Materials, Imperial College London,
     South Kensington Campus, London SW7 2AZ, U.K.
  Phone:+44-(0)20-7594-6753  FAX:+44-(0)20-7594-8175
*---------------------------------------------------*

**Comment by bavincen** [comment]
we have option to delete cancelled items that can be found in ews settings.

**Comment by horsfielda** [comment]
Some items were in the future, and so I am not sure why they would be viewed as cancelled. I suspect it was trying to delete everything.

**Comment by horsfielda** [comment]
I realize I omitted what may be a key fact in my initial description: I tried to delete the new entry before all the other entries started to be deleted. I have updated the initial entry.

**Comment by bavincen** [comment]
i tried that same it didnt delete any, my calendar is not changed at all

**Comment by horsfielda** [comment]
Glad it worked. I wish I could offer you more detailed information about what caused the problem in my case.
I am trying DavMail at the moment, and that is working well so far. Not as tidy a solution as yours, of course.

**Comment by bavincen** [comment]
@horsfielda you can try our next beta.will be neat..
lets give it a try
