### ISSUE TITLE
Latest Beta combined with latest release of lighning no longer immediately updates lightening calendar display, it doe correctly update EWS database on outlook server

### ISSUE THREAD

**Issue by bbeihoff** [Ericsson/exchangecalendar#235]

**Comment by tfft** [comment]
The same type of issue has been around for, seemingly, ages now - this is nothing new.  See bug reports #216, #175 and #122.  The later two reports were marked "closed" yet the problem doesn't seem to have been fixed and continues to linger...  I don't know why one has to restart TB to see the calendar properly, but that's what it seems like we have to do every hour or so.

In passing, "working for us" comments tell me that there might be a test/setup issue that we all collectively need to address.  Why is it that its working for you but not others ??  Can a more stringent debug/regression environment be setup to catch these (and other) things ?

**Comment by bavincen** [comment]
@tttf working for us too :)
Users with different version of tb sea monkey 🐵 facing issue..

**Comment by bavincen** [comment]
You cal close this issue. Found duplicate. We are working on it. Ofcourse very less contributors we have right now..

**Comment by pluto00987** [comment]
I've read over those other bug reports and I have to agree that they all sound like the same underlying issue. I'll add my experience here:

I was originally using Thunderbird 31.7.0 + Lightning 3.3.3 + EWS provider 3.3.1 and everything worked correctly.

I started having the problem after upgrading to Thunderbird 38.0.1 + Lightning 4.0.1. I did NOT change EWS provider version (at first) and still used 3.3.1.

The symptoms I see are:
1) Creating a new event: Event appears in OWA, does not appear in Thunderbird.
2) Reschedule an existing event: New date/time reflects in OWA, event does not 'move' to the new date/time in Thunderbird (it still shows at old date/time).
3) Deleting an event: Event is removed in OWA, event still shows in Thunderbird.

Note this has nothing to do with invitations, shared calendars, etc. I'm simply working with plain events on my own calendar.

To address the problem, I updated EWS provider to 3.3.2. This had no effect. I then reverted back to Thunderbird 31.7.0 + Lightning 3.3.3 and the PROBLEM WENT AWAY. I did NOT have to do anything to my profile, nor did I have to delete/recreate my calendars. Everything all just worked again with the old TB version.

This seems like a display refresh issue with the new Thunderbird/Lightning. I'd bet that EWS has the correct 'state' internally but that just isn't being reflected on-screen. That would explain why synchronizing calendars has no effect.

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

Can you provide us ur feedback on this..

Thanks

**Comment by sliwowitz** [comment]
I have the same problem with Thunderbird 31.7.0, Lightning 3.3.3, and EWS 3.4.0-beta2. Same problem happens on two different computers - different distros, different profiles, but same TB&EWS versions.

I didn't have the problem a couple weeks ago with older TB and EWS versions (I don't know which versions worked, but I know some of them did).

**Comment by sliwowitz** [comment]
Using latest GIT version 92798bf00fe65088e6963ee59bf60f9c6e552bd5, the calendar refreshes correctly on my work laptop

**Comment by bavincen** [comment]
if you are using 4.0 lightning, support is enabled now.. please confirm .. thanks

**Comment by tfft** [comment]
I just downloaded "master" and confirm that events are appearing and disappearing (when deleting calendar events) as expected.  Good job, keep up the fixes !!  Sounds like time for a beta-3 :-)
