### ISSUE TITLE
Tags not usable with addon activated

### ISSUE THREAD

**Issue by laclaro** [Ericsson/exchangecalendar#236]
Hello,

I have a mail account for which I setup a synced exchange calendar with this addon. However, now I cannot use the tag functionality anymore within this account. Please fix this, since in a professional workflow, tags are essential!

Best regards,
Henning

**Comment by Dominique-2202** [comment]
Looks like the same as issue
      #208
    
      
      
      
        Best regards,
        
        Dominique 
        
       
    On 6/17/2015 3:33 PM, laclaro wrote:
    
    
      Hello,
      I have a mail account for which I setup a synced exchange
        calendar with this addon. However, now I cannot use the tag
        functionality anymore within this account. Please fix this,
        since in a professional workflow, tags are essential!
      Best regards,
        Henning
      —
        Reply to this email directly or view
          it on GitHub.
