### ISSUE TITLE
Plugin Breaks Thunderbird Email Viewing

### ISSUE THREAD

**Issue by tdn120** [Ericsson/exchangecalendar#237]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1175141

Steps to reproduce:
On Ubuntu 14.04, Thunderbird 31.7.0, Lightning 3.3.3.
Try to read an email.

Actual results:
I am unable to view email bodies.  I receive emails fine, and see full subjects in the message pane, but the email pane is just blank.
I've confirmed that all other Thunderbird extensions allow me to read emails.  Then if I re-enable Exchange EWS Provider the issue returns.

Expected results:
I should still be able to read my emails.

Possible related errors:

Timestamp: 06/16/2015 02:46:58 PM
Error: TypeError: tab is undefined
Source File: chrome://messenger/content/tabmail.xml
Line: 1061

Timestamp: 06/16/2015 02:47:01 PM
Error: Please do not load stuff in the multimessage browser directly, use the SummaryFrameManager instead.
Source File: resource://gre/modules/summaryFrameManager.js
Line: 85

**Comment by bavincen** [comment]
3.4beta1 is having issues please use our stable versioins only. you can try beta2.. thanks

**Comment by tdn120** [comment]
beta2 looks good!  Thanks.
