### ISSUE TITLE
After accepting a meeting invitation, when we select the event invitation email, it still shows the accept button. (Master Branch))

### ISSUE THREAD

**Issue by vikas290691** [Ericsson/exchangecalendar#239]
Steps to reproduce:

1. Get some meeting invitation from your colleague.
2. Now select the email meeting invitation and try to accpet it.
3. You will be able to accept it and it get update in to the calendar.
4. Accroding to funcationality, the email invitation get disappear after accepting.
5. but It is not expected behaviour. Instead of that, when you select the event. It still shows the action event for accept and decline.

**Comment by bavincen** [comment]
ahh its a beta release bug. please use Master branch..
