### ISSUE TITLE
Dismiss recurring event reminder not possible

### ISSUE THREAD

**Issue by laclaro** [Ericsson/exchangecalendar#240]
Hi,

with the addon activated, you cannot dismiss ("close all" or "close") the reminder of an upcoming event. You can only tell thunderbird to remind you later. This leads to very many annoying reminders because they cannot be closed. Please fix this quickly!

I use the "latest version" (17/06/2015).

Best regards
Henning

**Comment by bavincen** [comment]
Thanks for update,. is that recurring event?

**Comment by laclaro** [comment]
Yes. Using the latest "latest version" now.

**Comment by bavincen** [comment]
Thanks for update.. is that happening for single event?

**Comment by laclaro** [comment]
You are right, seems _only_ to apply to recurring events.

**Comment by bavincen** [comment]
Ok thanks

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/tree/cacheandperformancefix
if this work for you? please...

**Comment by utkugenc** [comment]
No, I installed the latest content from cacheandperformancefix branch but I, still, can't dismiss recurring events.

**Comment by laclaro** [comment]
I _did not_ test it _without_ clearing the cache, but after deleting the contents of myProfile/exchange-data/, dismissing of event reminders work also for recurring events. Now it's only the tagging issue that remains for me. Thank you!

Best regards
Henning

**Comment by bavincen** [comment]
ok we will recheck before closing...

**Comment by laclaro** [comment]
This issue reoccured to me in the most recent version.

TB 38.4.0, Lightning 4.0.4.1, EWS 3.5.0-beta1

Best regards
Henning

**Comment by bavincen** [comment]
We are doing the fix for 4.0.4.1

**Comment by laclaro** [comment]
Works with Lightning 4.0.3.1. Thank's for the hint.
