### ISSUE TITLE
3.4.0-beta2 - Accepting meeting invite does not delete invite from Inbox

### ISSUE THREAD

**Issue by kiravi** [Ericsson/exchangecalendar#243]
Stable version did it.  Using latest stable build of thunderbird/lightning as of June 18th.

**Comment by bavincen** [comment]
#239 #224

**Comment by kiravi** [comment]
How do I test?  How do I generate the xpi file?  And where should I get this from?

**Comment by bavincen** [comment]
Please go to releases Beta3 is just got released

**Comment by kiravi** [comment]
Fixed
