### ISSUE TITLE
EWS 3.4.0-beta3 : cannot create new calendars with SeaMonkey

### ISSUE THREAD

**Issue by Dominique-2202** [Ericsson/exchangecalendar#245]
Unable to create new calendars or use existing one (from version 3.3.2) with SeaMonkey.
Win 8.1
SeaMonkey 2.38 (nightly)
Lightning 4.3a1 (nightly)
Provider for google calendar 2.2a1 (nightly)
Here are the screenshots of the errors:

![error3](https://cloud.githubusercontent.com/assets/2248966/8254795/9c95fff8-169b-11e5-9c09-0b445a733ac4.jpg)
![error2](https://cloud.githubusercontent.com/assets/2248966/8254793/9c75e4d4-169b-11e5-8522-92f18d1c11d1.jpg)
![error1](https://cloud.githubusercontent.com/assets/2248966/8254794/9c7b6346-169b-11e5-8efb-a00eb321f575.jpg)

**Comment by bavincen** [comment]
our support is for lightning 4.0 underbird 38.0 stable

**Comment by Dominique-2202** [comment]
same errors with SeaMonkey 2.35 and lightning 4.0.0.1 !!!
