### ISSUE TITLE
SeaMonkey: Calender broken after updating to v3.4.0-beta3

### ISSUE THREAD

**Issue by Woi** [Ericsson/exchangecalendar#246]
After updating from v3.4.0-beta2 to v3.4.0-beta3 I get the following error message at start up:
"Error providing calendar at [....]. I will not be available" (Translated by me, see attached screen shot for the original message.)
I also noticed that the "others" tab in settings is empty.
Reverting to v3.4.0-beta2 fixed it.

**Comment by Woi** [comment]
![ewsbug](https://cloud.githubusercontent.com/assets/5870628/8255209/97aa2f48-169e-11e5-97c3-01b86c453f9e.png)

**Comment by bavincen** [comment]
support till lightning stable version 4.0

**Comment by bavincen** [comment]
please use give a pull request with ur translation for  others tab

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/commit/931a976a7eae561a83a65832b035be986fa607aa

translation update

**Comment by Dominique-2202** [comment]
Same error when using SeaMonkey 3.35 and lightning 4.0.0.1

**Comment by bavincen** [comment]
please test which one is ok with beta3 ...

**Comment by bavincen** [comment]
i am asking you because of seamonkey

**Comment by bavincen** [comment]
@Dominique-2202 error details pls

**Comment by Dominique-2202** [comment]
![error3](https://cloud.githubusercontent.com/assets/2248966/8266570/6a151aba-1735-11e5-8a8f-52ce2fa002b2.jpg)
![error2](https://cloud.githubusercontent.com/assets/2248966/8266571/6a1fcea6-1735-11e5-969b-43f77996b49f.jpg)
![error1](https://cloud.githubusercontent.com/assets/2248966/8266572/6a24d572-1735-11e5-9841-f7480691c153.jpg)

**Comment by bavincen** [comment]
Fixed @Dominique-2202

**Comment by Woi** [comment]
My SeaMonkey starts with commit c413e3346 without the above error message. However preferences in  "others" is completely empty. Is this related or should I open an other bug? 

SM & Lightning versions:
Mozilla/5.0 (X11; Linux x86_64; rv:36.0) Gecko/20100101 SeaMonkey/2.33.1 Lightning/3.8b2

**Comment by bavincen** [comment]
@woi missing transllation, we have added for en-us. please give a patch with ur languae translation refer commit for files  https://github.com/Ericsson/exchangecalendar/commit/931a976a7eae561a83a65832b035be986fa607aa

**Comment by Woi** [comment]
Hey bavincen,

please see pull request 255: https://github.com/Ericsson/exchangecalendar/pull/255

**Comment by bavincen** [comment]
Merged Thanks

**Comment by Dominique-2202** [comment]
Hello,

This version works fine with SeaMonkey 2.35 and also with SeaMonkey 2.38 (nightly). 
Can be closed (for me...)

**Comment by bavincen** [comment]
@Dominique-2202 yes but let this open.. will close it once we release a new version :) 

is your tagging issue resolved?

**Comment by Dominique-2202** [comment]
OK for the issue closure at next
        release....
        
        My "regular" tagging issue is still not resolved. 
      
    
      
      
      
        Best regards,
        
        Dominique 
        
       
    On 6/22/2015 2:42 PM, bavincen wrote:
    
    
      @Dominique-2202
        yes but let this open.. will close it once we release a new
        version :) 
      is your tagging issue resolved?
      —
        Reply to this email directly or view
          it on GitHub.
