### ISSUE TITLE
Cosmetic Mistake in Event-Edit-Window (TB38, Lightning4, EWS 3.4.0, german, Win7 Aero Design)

### ISSUE THREAD

**Issue by mariolorenz** [Ericsson/exchangecalendar#250]
Dear Sirs,
i send two Screenshots to you. You see the different Event-editor-Windows: 1st: A Event via EWS Provider 2nd a Event via normal Lightning. In the red circles you see some icons, there are not on the right position. In the green circle you see,that the ews-provider have a wysiwyg-editor. Normal lightning has only a textarea. Is it possible, to configure the ews-plugin that they have a textarea too?

Thank you and regards,

Mario Lorenz

![lightning_event_ews](https://cloud.githubusercontent.com/assets/5525363/8268635/ba43bf6c-178c-11e5-8600-ab6b6d7803e3.png)
![lightning_event_normal](https://cloud.githubusercontent.com/assets/5525363/8268636/ba4a634e-178c-11e5-8069-40855446d002.png)

**Comment by bavincen** [comment]
@mariolorenz  may i know the reason why do you prefer text area than rich text editor.. no its not possible for us to remove rich text editor it helps many..

**Comment by mariolorenz** [comment]
Ok, no problem, but when you change in this editor-window the calendar to a normal Lightning calendar, the RTE does not change to a textarea, although the Lightning calendar RTE not supported.

What the matter with the red ellipse?

Regards, Mario

**Comment by bavincen** [comment]
1)the issue with rich text when you are editing non-exchange calendar?

2)can you translate please? i dont know german language :)

**Comment by bavincen** [comment]
hmm ok now i googled it it translated but both that means same??

**Comment by mariolorenz** [comment]
Sorry for my delay. Yes it means and do the same: "add" and "attachment". The icons maybe a helper for you to find the cosmetic problem.
And Yes, the popup-formular, does not change, when you change from a exchange-calendar to a non-exchange-calendar and in the other direction:
When you start from a non-exchange-calendar you have a textarea. Then change to a exchange-calendar in the popup-formular, you have the still the textarea.
When you start from a exchange-calendar you have a RTE. Then change to a exchange-calendar in the popup-formular, you have the still the RTE.
In my Opion the hole popup-formular have to change, but maybe it is to complicate.

**Comment by bavincen** [comment]
Are you sure is that happeing because of this addon , i have tried to find that translation but failed.

**Comment by mariolorenz** [comment]
Hm, i've no other lightning-extension ...

**Comment by bavincen** [comment]
Btw..  i am not able to find german translation in code.. could you help..

You can go to code in github itself

**Comment by mariolorenz** [comment]
Ok i'll try it. I can start on 	Wednesday.

**Comment by mariolorenz** [comment]
I found the translation here:
\locale\exchangecalendar\de\attachments-view.dtd
It is the variable: exchWebServie.add.attachment.button.label
And if i expected right, then you w'll find the position here:
\chrome\content\attachments-view.xul (Line 86)
Here you w'll find the code for showing the button
\chrome\content\attachments-view.js (Line 245-269)
But when i understand the code, there is everything Ok.
The problem is maybe only css:
\chrome\content\attachments-view.css
In the attachment you see the normal view and the hover-view. In the hover-view you see no icon, in the normal-view you see the mistake. I thing the "-moz-image-region: rect-coordinates" are not right.

![css-mistake](https://cloud.githubusercontent.com/assets/5525363/8453113/96da948e-1ff1-11e5-9993-1fa3470af973.png)

**Comment by mariolorenz** [comment]
In the hover-status of the attachment-Button should be show the icon too. Like the delete-button.

**Comment by bavincen** [comment]
@mariolorenz thats awesome.. please give a pull request with changes?

**Comment by mariolorenz** [comment]
Ok, i test something, and the problem is more difficult:
The CSS for the button "#exchWebService-add-attachment-button" is defined here:
\chrome\content\attachments-view.css
The code is an copy of the button-definition "#button-url" in the !lightning!-Addon here:
\chrome\skin\windows\calendar\win-classic\calendar-event-dialog.css
You see in the path that this is the definition for "win-classic".
I have win7 with Aero-Design. Lightning use for me this css:
\chrome\skin\windows\calendar\win-aero\calendar-event-dialog.css
When i use the CSS for the "#button-url" from this file as CSS for my button "#exchWebService-add-attachment-button", then everything looks perfect for me.

But this is not the solution for the grand problem. When you have a look at the lightning extension you can see, there are skins for osx, linux and windows. In windows you have styles for aero and win-classic.
The "exchange"-Addon have'nt such a skin-folder-structure.
And here is my problem that a have no idea to solve this issue. I know too little about Addon programming, so I cant settle a proper pull request.

What can we do?

**Comment by bavincen** [comment]
This how mozilla manifest file contains Css based on OS
sure this is what you are looking for :)

"content   xulschoolhello              content/
skin      xulschoolhello  classic/1.0 skin/unix/
skin      xulschoolhello  classic/1.0 skin/mac/ os=Darwin
skin      xulschoolhello  classic/1.0 skin/win/ os=WinNT
locale    xulschoolhello  en-US       locale/en-US/"

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/pull/283
