### ISSUE TITLE
Plugin causes TB to hang when unsubscribing from calendar or closing TB

### ISSUE THREAD

**Issue by vadimnehta** [Ericsson/exchangecalendar#253]
I installed the plugin on a new Thunderbird profile while trying to test my TB hanging on exit issues and found that after I added a calendar and tried to quit TB, it hung.

I also tried unsubscribing from the calendar, and TB hung as well.

If there's any information I can provide to help solve this issue, please let me know!

**Comment by muthusuba** [comment]
Version information, please?

**Comment by vadimnehta** [comment]
Here it is:

```
  Application Basics

    Name: Thunderbird
    Version: 31.7.0

  Extensions
    Exchange EWS Provider, 3.4.0~beta1, true, exchangecalendar@extensions.1st-setup.nl
```

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon
