### ISSUE TITLE
"401: Unauthorized URL" when creating new calendar (master)

### ISSUE THREAD

**Issue by dicer** [Ericsson/exchangecalendar#254]
I just installed the latest master and wanted to add a calendar. 

Thunderbird 38.0.1
Lightning 4.0.0.1
EWS: Master (tells me it is 3.4.0-beta1 though)

Creating a calendar without using autodiscovery:
https://owa.mydomain.de/EWS/Exchange.asmx
My Email
User and domain as I would use them with OWA or anything else in the domain

When I click "Check server and mailbox" I a required to input my password twice and then get a popup with:

Error during checking of server and mailbox: HTTP Client error 401: Unauthorized URL: https://owa.mydomain.de/EWS/Exchange.asmx (Code: -19)

**Comment by dicer** [comment]
I made a log: http://pastebin.com/ntbRzUcz 
Let me know if you need more info.

**Comment by dicer** [comment]
Needless to say: With an older Thunderbird (not sure if 37), Lightning 3.x and the last stable from 1st-setup, the same server worked fine.

**Comment by bavincen** [comment]
Error during checking of server and mailbox: Error during waiting for data of hostname 'server.server.com'. (STATUS_WAITING_FOR) (Code: -16)


is that message same when you are doing "perform folder check"

**Comment by dicer** [comment]
How do I "perform folder check"? You mean autodiscovery?

**Comment by bavincen** [comment]
sry  i mean  "Check server and mailbox"

**Comment by dicer** [comment]
Oh, no. Never seen that message. Only (Code: -19)

**Comment by bavincen** [comment]
Ok got it it says you are unauthorized. is taht because you are providing some wrong password? if so can you just tell the special chars in ur password please

**Comment by dicer** [comment]
No. Password is only alpha and numbers. Also played around a bit with the domain and username but they should be just fine that way. Well, it's what I use with OWA as well.
Can I test this in a browser somehow?

**Comment by dicer** [comment]
Just changed my password, went to https://owa.mydomain.de/EWS/Exchange.asmx in a browser and had to reenter the basic auth. Just my user name (no domain) and the password worked fine. Got redirected to https://owa.mydomain.de/EWS/Services.wsdl

**Comment by dicer** [comment]
Ok, this gave me the idea to just leave out the domain: Tadaa! Everything is working fine now. Weird that the domain would cause this.
Even stranger: When I go to https://owa.mydomain.de/EWS/Exchange.asmx in a browser and DO enter my domain like "mydomain\myuser" I can still auth just fine.

**Comment by bavincen** [comment]
Hmm i am not sure if it depends on server.
So are you using domain/username in Usernmae box?
left domain empty?

How did u try that before

**Comment by bavincen** [comment]
I doubt a bit its because of recent patch added by @b52

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/pull/203

**Comment by dicer** [comment]
No,. I leave domain field empty and username is just my username. No domain part in there. Then it works. When I add the domain to the domain field, it stops working. It also doesn't work, when I use "domain\user" in the userfield (just checked). It does work with "user@domain" though...

So in EWS Connector (Domain field needs to be empty all the time):
"user" - works
"user@domain" - works
"domain\user" - does not work

In the browser, I can use "domain\user" as well as "user" and it works. 

Regarding the patch: My domain in the email address and the auth domain are NOT the same. Maybe that is the reason?

**Comment by bavincen** [comment]
no, you have  to use forward slash always.. probably it works in Linux. and for windows try backward..

**Comment by UschiKlute** [comment]
this is still a problem.
The autodiscover configuration has not changed at our Exchange Server.
the addon cannot be used anymore. :-(

**Comment by arkitechtura** [comment]
I got this error after I had to change my AD domain password. It seems that somehow the extension is trying to use cached credentials and does not ask for a password if the login fails, and plainly issues a 401.

Can we get help here? The extension is unusable at this point. 

Is there a way to 'forget' the cached credentials?

**Comment by gtatgh** [comment]
Same problem for me. Calendar synchronization did not work. Tried to use suggestions wrote by @dicer without success.
