### ISSUE TITLE
can't add addressbook in b2 or b3.

### ISSUE THREAD

**Issue by dbharding** [Ericsson/exchangecalendar#256]
It seems to succeed but then no actual addressbook shows up.

**Comment by bavincen** [comment]
please use beta3 or https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

**Comment by dbharding** [comment]
I thought the "in b2 or b3" made it clear I tried b3 already.

**Comment by bavincen** [comment]
Please remove your existing exchange contact address book. and restart Thunderbird it will create address book for your exchange calendar automatically

**Comment by dbharding** [comment]
I have no existing exchange contact addressbook.

Derek
