### ISSUE TITLE
BETA4(3.4) is Released! Feedback

### ISSUE THREAD

**Issue by bavincen** [Ericsson/exchangecalendar#257]
You can provide us your feed back on 3.4 beta 4 here. It will help us to confirm the plugin is working on your system 
p.s make sure you are providing us right information about lightning version

Thanks for support and contribution

**Comment by Nomasan** [comment]
On 25/6/15 10:42, bavincen wrote:
>
> You can provide us your feed back on 3.4 beta here. It wil help us to 
> confirm the plugin is working on your system
> p.s make sure you are providing us right information about lightning 
> version
>
Nothing meaningful here but showing 3.5.0 beta 0.

Thanks for the daily hard work !

-- 

Nomad

**Comment by bavincen** [comment]
![updatedialog](https://cloud.githubusercontent.com/assets/8401561/8350901/fd525878-1b46-11e5-9a30-9bf2848f45c7.png)

Nope it showing correctly?

I guess you are using master..

**Comment by Nomasan** [comment]
On 25/6/15 11:03, bavincen wrote:
> I guess you are using master..
Yep ...

:-[

Sorry and thanks for the quick correction!

-- 

Nomad

**Comment by bavincen** [comment]
You can use our releases that master because thats very unstable .. releases are tested by our QA team which is somewhat trusted :) thanks

**Comment by Dominique-2202** [comment]
Beta 4 Works fine with SeaMonkey 2.35 / Lightning 4.0.0.1 and Provider for Google Calendar 1.9a1 (release train). However the "regular" message tagging in SeaMonkey does not work. 

Message tagging works with nightly versions of SeaMonkey (and nightly for lightning and Provider), although there are some other problems... (such as calendar sync problems)

**Comment by tfft** [comment]
Would be nice to get a changelog (or a listing of what functions/features have changed) with each release (including beta's) to possibly zero in on those areas beyond normal use...

Just a thought.

**Comment by Dominique-2202** [comment]
disabling EWS Beta 4 brings back the message tagging functionality.

**Comment by bavincen** [comment]
@Dominique-2202 Which version are you using btw..

**Comment by bavincen** [comment]
@tfft you can find that in releases (with beta-1) 
we are adding it in next stable

**Comment by Dominique-2202** [comment]
Hi Bavincen,

I am using:
SeaMonkey 2.35 (corresponding to TB38)
Lightning 4.0.0.1
Provider for Google Calendars 1.9a1
EWS Beta 4 (just released)

BR,
Dom,

**Comment by bavincen** [comment]
thanks

**Comment by laclaro** [comment]
I tried many versions of exchangecalendar, never got working the tagging functionality. Refer to bug https://github.com/Ericsson/exchangecalendar/issues/252

Best regards,
Henning

**Comment by bavincen** [comment]
@laclaro I can be slightly wrong sea monkey build is working with tagging, guess nightly doesn't

**Comment by laclaro** [comment]
Dominique is using standard SeaMonkey (corresponding to FF 38) and it does not work?! SeaMonkey nightly does work, though (but this version is not intended for regular users, I guess).

**Comment by bavincen** [comment]
@laclaro will check it .. where to download standard one that you are using now for Ubuntu?

Thanks

**Comment by laclaro** [comment]
I have not tested SeaMonkey, I was only summarizing Dominique's statements. I'm on windows right now using the standard 32-bit version of TB 38 (release-channel).

**Comment by brenboy** [comment]
3.4 beta 4 is working well for me - the first release in months that has worked without any issues.

OS X 10.10.4
Thunderbird 38.0.1
Lightning 4.0.0.1

**Comment by kiravi** [comment]
When this extension is going through its steps of refresh e.g. 15.. 14 .. 13 etc., if we open a compose message then the LDAP addresses do not fill up until the extension has finished refreshing.

**Comment by bavincen** [comment]
minimum cal sync is set 60 sec
