### ISSUE TITLE
3.4.0 beta2/beta4 disables Lighting reminders

### ISSUE THREAD

**Issue by danieltrentman** [Ericsson/exchangecalendar#258]
EWS disables TB Lightning's ability to add calendar reminders, for any calendar.  EWS 3.4.0beta4

"
Error: too much recursion
Error: NS_ERROR_FAILURE ... CachedCalendar.js line 865
"

Reproduceable at will.  Turn on or off EWS.  All add-ons were off when testing EWS.  All add-ons on makes no difference.  A bug in EWS or CachedCalendar?

**Comment by bavincen** [comment]
Can you please tell us the steps to reproduce

**Comment by danieltrentman** [comment]
All I have to do is turn on EWS and the problem exists.  TB 38.0.1
Only Lightning and EWS add-on

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon
Updates added

**Comment by danieltrentman** [comment]
problem remains with 3.5.0-beta0.  The problem is so easy to experience that if I am the only one seeing this, I need to debug more on my end.  Thanks.

**Comment by bjantzen** [comment]
I have opened a new issue which might be related:
[Cannot add custom reminder (alarm) to an event in any type of calendar when Exchange EWS Provider is active](https://github.com/Ericsson/exchangecalendar/issues/371)
