### ISSUE TITLE
no events show up since TB 38, Lightning 4.0 and EWS 3.4 oder 3.5

### ISSUE THREAD

**Issue by reinfried** [Ericsson/exchangecalendar#260]
Hi,

all old calenders are read only and don't show any events.
When I open calendar settings I can unselect the write protection, but it doesn't change the setting, it still remains write protected.
When I try to open EWS settings I get an error in chrome://exchangecalendar/content/exchangeSettings.xul line 48, row 1: <dialog xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul">:
<dialog xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" and TB hangs.
When I install a new calender I can sometimes change it to writeable and add new events, but even these don't show up and they are not synchronized to the server.
Thunderbird always shows 1 running and some queued jobs that never finish.

If I install a fresh Thunderbird profile everything works but I'd like to use my old profile.

<b>Solved in parts:</b> I deleted all lines with calendar-settings from prefs.js and installed the calendar new. <b>But</b> this is no solution for novice users (and we have a lot of them at university) <b>and</b> if I want to see some other calendars of colleagues they still stay empty

What do you mean with "clear cache temp issue"?
And I can't show more of the error line, because TB stops and I'm using german version.
![Uploading Bildschirmfoto 2015-06-29 um Mo., 29.06.15, 19.00.08.jpg…]()
Cache windows of EWS is not very readable ...

**Comment by mucke5** [comment]
Same here. Need urgent fix. Thanks in advance!

**Comment by bavincen** [comment]
Can please post complete log

**Comment by bavincen** [comment]
please clear cache temp issue,
closing it

**Comment by bavincen** [comment]
i dont see the whole error line :(

chrome://exchangecalendar/content/exchangeSettings.xul line 48, row 1: :
<dialog xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul

**Comment by bavincen** [comment]
what language are you using must be translation missing


<dialog xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"
	id="exchWebService_ExchangeSettings_dialog" title="&ecsettings.title; " buttons="accept,cancel"
	buttonlabelaccept="&label.acceptbutton;" buttonlabelcancel="&label.cancelbutton;"
	ondialogaccept="tmpOfflineCacheSettings.onSave();return tmpExchangeSettings.onSave();"
	onload="tmpExchangeSettings.onLoad();">

**Comment by reinfried** [comment]
Still don't know how to get it working ...

**Comment by mucke5** [comment]
@bavincen : I have sent you a mail with log event.

**Comment by bavincen** [comment]
ok thanks will check and get back

**Comment by bavincen** [comment]
@mucke5 what i see is your caledar is not created..

1st-setup:2015-5-2 12:13:12.721:[Arbeit] We are still creating this calendar. Ignore getItems for now. (_getItems in mivExchangeCalendar.js:2252)

**Comment by bavincen** [comment]
@mucke5 please leave this issue create a new one. unable to create calendar.
you can also try reinstalling thunderbird.. look some permission issue..

**Comment by mucke5** [comment]
I switched back to version 3.4beta2 and it's working like charm.

**Comment by reinfried** [comment]
same here!
Thank you!
Reinfried

**Comment by mucke5** [comment]
ur welcome!
