### ISSUE TITLE
Can't label mails since 3.4.0-beta1

### ISSUE THREAD

**Issue by mweirauch** [Ericsson/exchangecalendar#261]
I am not able to label mails via keyboard shorcuts (1,2,3,4,5 or 0) or via context menu.

Disabling the Thunderbird-Addon or going back to 3.3.2 fixes the issue. Side-effects with other addons ironed out as this was also tested with only the EC addon enabled.

3.3.2 => works
3.4.0-beta1 > beta4 => don't work

**Comment by bavincen** [comment]
You have to use 3.4.0 - beta 4 not 1, we had fixed your issue already

**Comment by mweirauch** [comment]
As I have written "3.4.0-beta1 > beta4" don't work. I just retried with 3.4.0-beta4 just to make sure and I can still reproduce the issue. You can't reproduce with 3.4.0-beta4?

**Comment by bavincen** [comment]
issue is
I am not able to label mails via keyboard shorcuts (1,2,3,4,5 or 0) or via context menu.
?

**Comment by bavincen** [comment]
tagging working for you if not used shotcuts?

**Comment by mweirauch** [comment]
As I have written, it does not work when using keyboard shortcuts and it also does not work when using the context menu. So both ways for labeling a mail don't work for me.

**Comment by bavincen** [comment]
Ok  can you please grep ewsTagger post log

**Comment by bavincen** [comment]
what is lightning version? is that showing any notification on top of it in addons page?

**Comment by mweirauch** [comment]
If you tell where I can find "ewsTagger post log" then I can provide you the info.

The Lightning-Addon version is 3.3.3 running with Thunderbird 31.7.0 on openSUSE 13.2

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/Logging-Calendar-with-options

FYI
 
You can also open OWA and tag some emails then check them

Tagging works only if you have had calendar for mail account

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/issues/261

Please use latest
