### ISSUE TITLE
v3.4.0-beta4 cache is loading duplicate entries

### ISSUE THREAD

**Issue by kiravi** [Ericsson/exchangecalendar#269]
Calendar shows duplicate entries from cache.

Clearing cache explicitly from exchange calendar's properties and/or resetting cache removes these duplicate entries.

**Comment by bavincen** [comment]
please give us more details on how happend

**Comment by kiravi** [comment]
Restarted Thunderbird after weekend. Calendar now adds 2 entries for every calendar event.  cache set to 3 months in the past/1 month in the future.  

Reset cache and now duplicate entries are gone.
