### ISSUE TITLE
Issues with spaces in password

### ISSUE THREAD

**Issue by reusch** [Ericsson/exchangecalendar#278]
Plugin Version: github master (726374a91f0d20dec97e340808d8eacd9bf51290), creates file named "exchangecalendar-3.5.0-beta0.xpi"

Even with this build from master I experienced problems with spaces in my password.

Steps to reproduce:
* change exchange password (e.g. via OWA) and include spaces (mine already did have some)
* freshly install the plugin built from github master branch 5min ago
* restart thunderbird
* add calendar, select network calendar, select exchange calendar
* enter name, choose colour
* enter
    * server url = https://sub.domain.tld/ews/exchange.asmx
    * primary email = username@domain.tld
    * username = userX
    * domain = 
        * \<empty>
        * \<empty> with username = userX@domain.tld
        * domain.tld
        * shortdomain
* press check server and mailbox
* enter password (which contains spaces)
    * => leads to "HTTP Client error 401: Unauthorized"

Cross-checked it:
* change password so that it does not contain spaces
* enter:
    * server url = https://sub.domain.tld/ews/exchange.asmx
    * primary email = userX@domain.tld
    * username = userX
    * domain = \<empty>
* press check server and mailbox
* enter password (which does not contain spaces)
    * => WORKS

Further, the plugin fills the error console with the following errors:
```
no element found
https://%5CuserX:Pass%20Word%20With%20Spaces@sub.domain.tld/ews/exchange.asmx
```
which contain the password in nearly plaintext (only spaces encoded as %20).
Version 3.4.0beta4 did not add the %5C before "userX", I think

I did not find another issue dealing with spaces in passwords so I opened this one (maybe overlooked it, then I am sorry).

Thanks in advance!

Cheers,
Thomas

**Comment by bavincen** [comment]
#220

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/commit/30f3e2644f8fdf8671df9cacc79a28bc4ec9ddb8
