### ISSUE TITLE
Is broken by update 38.1.0 of Thunderbird on Linux

### ISSUE THREAD

**Issue by xsteverobsonx** [Ericsson/exchangecalendar#280]
Thunderbird on my Linux machine helpfully updated itself to 38.1.0 today and after restarting TB, the calendar integration no longer works.  I have Lightning 4.0.1 and EWS 3.2.2 installed.
Rather than clutter this dialogue with things that I think might be helpful, please advise what logs or log sections, or other information, would be helpful.  Many thanks.

**Comment by bavincen** [comment]
please use 3.4.beta4 or https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon
