### ISSUE TITLE
Make ews tag synchronizing configurable

### ISSUE THREAD

**Issue by markuskeunecke** [Ericsson/exchangecalendar#281]
It would be helpful to make the EWS tag synchronizing configurable regarding being active or inactive.

1. It seems to be a performance hog, every few seconds thunderbird freezes completely
2. It seems to break local tagging of e-mails.

**Comment by bavincen** [comment]
the sync time is configurable right click on calendar then set ur interval..

**Comment by markuskeunecke** [comment]
I don't want to set an interval, I want to switch that feature off and on. Or can I do this with a magic number?

**Comment by bavincen** [comment]
the concept is mail account and calendar and the credential

you can not use other person mail account with ur credential in a straight way

**Comment by bavincen** [comment]
we are sorry that can be disabled. its working for many. we are fixing rest soon

**Comment by markuskeunecke** [comment]
Okay, just to explain: :) I can view another person's calendar with my credentials if that person has allowed me to access his mailbox on exchange. Maybe this screenshot of my EWS settings of another person's calendar shows what I mean:

![ews-settings](https://cloud.githubusercontent.com/assets/3355613/8750195/472dbbd4-2ca6-11e5-99d2-04e59f21ec0b.png)

Translation:
* Postfachname = mailbox
* Benutzername = username
* Hauptordner = main folder

**Comment by bavincen** [comment]
you can check that  ews sync tags by right clicking on mail.. it will tag if u have permission

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/commit/1bba4d869c7dddf80206725397b6e89e435ea4a0

Hope you like it
