### ISSUE TITLE
Downloading calendar data fails

### ISSUE THREAD

**Issue by Gribnif** [Ericsson/exchangecalendar#282]
I just installed 2e597ad, and now all of my calendars appear as read-only and any attempt to synchronize result in an endless "1 running and 8 queued jobs" status line. 3.4.0-beta1 worked fine. Looking at the log, it seems to retry every few seconds, but never gets any data.

See http://pastebin.com/jAqV9U92

(Domain and username have been redacted.)

**Comment by bavincen** [comment]
do you have percentage symbol in ur password?

**Comment by bavincen** [comment]
#220

**Comment by bavincen** [comment]
please grep ewstagger and post

**Comment by bavincen** [comment]
is your username is mail  address?

**Comment by Gribnif** [comment]
No, no % in my password.

The log doesn't contain ewstagger at all.

I have three calendars: I am using the same username to log-into all three of them, and that username is the same as my outgoing email. However, for two of the calendars, I am a delegate--I don't own the calendars.

I should note that I also went back to 3.4.0 beta 2, and it does not have this problem. I haven't had a chance to do a git bisect yet to narrow it down more.

**Comment by bavincen** [comment]
is your username is mail address?

**Comment by bavincen** [comment]
if yes,
 change  this.user = identity.username ;
to
this.user = identity.email; 
is that works

**Comment by Gribnif** [comment]
I don't quite understand your question, "is your username is mail address?" but I did try changing the line of code you suggested. It made no difference. I'm going to try a git bisect.

**Comment by bavincen** [comment]
No issues.. can y ou please check 3.4 beta5

**Comment by Gribnif** [comment]
I just finished a git bisect, and the problem seems to be caused by 10dc34e on June 18. I already tried 3.4 beta5, and it also fails.

**Comment by bavincen** [comment]
Which file please? Line? :)

Thanks

Sent from my Sprint phone.

----- Reply message -----

**Comment by Gribnif** [comment]
I don't know which file or line is the problem, as there are too many in that commit. If I have time later on, I can try removing each hunk that is changed, but it will take some time.

**Comment by bavincen** [comment]
Ok we will check. Please figure out if can be done

**Comment by Gribnif** [comment]
Found it! If I revert the change at line 1112 of components/ecExchangeRequest.js in 10dc34e, the problem goes away. It even works in master. I'll create a pull request.

**Comment by bavincen** [comment]
@Gribnif ilooks interesting, yes i modified to fix.. is that working fine, are you able to add new calendars too?

**Comment by bavincen** [comment]
if u are adding that you have to rekmove 
````javascript
var rm = xml2json.XPath(aResp,"/s:Envelope/s:Body/*/m:ResponseMessages/*[@ResponseClass='Error']");

**Comment by bavincen** [comment]
you can give pull request for that file only
