### ISSUE TITLE
Debugging output spamming logs

### ISSUE THREAD

**Issue by jconroy77** [Ericsson/exchangecalendar#284]
A uncommented dump() call on [line 138 of components/erSyncFolderItems.js](https://github.com/Ericsson/exchangecalendar/blob/master/components/erSyncFolderItems.js#L138) from commit aa029902ce8072cd79449b99eedc734c7b67984f has started to fill my system log files with massive amounts of debugging output.

**Comment by bavincen** [comment]
can you give me pull request roy.
grep dump components/*

**Comment by jconroy77** [comment]
Done - https://github.com/Ericsson/exchangecalendar/pull/285
