### ISSUE TITLE
Cannot create Exchange calendar in Thunderbird 38.1.0

### ISSUE THREAD

**Issue by ThomasMcA** [Ericsson/exchangecalendar#286]
I have 3.4.0~beta4 installed in Thunderbird 38.1.0 in 64bit Mageia Linux.

The New Calendar wizard does not have a drop-down to select an Exchange calendar.

I started Thunderbird from a console to capture any errors that contain "exchange":

JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/global/mivFunctions.js, line 231: TypeError: variable aBranch redeclares argument
JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/global/mivFunctions.js, line 232: TypeError: variable aName redeclares argument
JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/global/mivFunctions.js, line 235: TypeError: variable aCreateWhenNotAvailable redeclares argument
JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/global/mivFunctions.js, line 262: TypeError: variable aBranch redeclares argument
JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/global/mivFunctions.js, line 263: TypeError: variable aName redeclares argument
JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/global/mivFunctions.js, line 266: TypeError: variable aCreateWhenNotAvailable redeclares argument
JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/global/mivFunctions.js, line 293: TypeError: variable aBranch redeclares argument
JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/global/mivFunctions.js, line 294: TypeError: variable aName redeclares argument
JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/global/mivFunctions.js, line 297: TypeError: variable aCreateWhenNotAvailable redeclares argument
JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/global/mivFunctions.js, line 414: TypeError: variable aArg redeclares argument
JavaScript strict warning: chrome://exchangecalendar/content/lightningtimezoneOverlay.js, line 43: TypeError: variable self redeclares argument
JavaScript strict warning: resource://exchangecalendar/ecExchangeRequest.js, line 173: TypeError: variable aLevel redeclares argument
JavaScript strict warning: chrome://exchangecalendar/content/calendar-common-sets2.js, line 57: SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/updater/mivUpdater.js, line 374: TypeError: variable aBranch redeclares argument
JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/updater/mivUpdater.js, line 375: TypeError: variable aName redeclares argument
JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/updater/mivUpdater.js, line 378: TypeError: variable aCreateWhenNotAvailable redeclares argument
JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/updater/mivUpdater.js, line 404: TypeError: variable aBranch redeclares argument
JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/updater/mivUpdater.js, line 405: TypeError: variable aName redeclares argument
JavaScript strict warning: file:///home/user/.thunderbird/lsqi76kk.default/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/updater/mivUpdater.js, line 408: TypeError: variable aCreateWhenNotAvailable redeclares argument
1437308009690	addons.update-checker	WARN	Update manifest for exchangecalendar@extensions.1st-setup.nl did not contain an updates property

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon
can you check this...

**Comment by ThomasMcA** [comment]
That completely breaks the UI:

1) The rotating circle on the Add-Ons Manager tab never stops rotating
2) If I close the Add-Ons Manager tab and then reselect it from the 
menu, it never reopens
3) The first tab name (which normally says Inbox) is changed to Home, 
and the folder pane no longer works. Although I can see my accounts and 
folders in the folder pane, clicks on folders are ignored.

If I shut down Thunderbird, delete the 
exchangecalendar@extensions.1st-setup.nl folder, then restart 
Thunderbird, the above problems go away.

Tom

**Comment by bavincen** [comment]
Hi
can you disable other add-ons and check.

**Comment by bavincen** [comment]
pelase use beta5 and update us

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon
