### ISSUE TITLE
Client error 401 in Thunderbird 38.1.0 (MacOS 10.10.3)

### ISSUE THREAD

**Issue by chem455** [Ericsson/exchangecalendar#287]
Hi,

I used this addon for some time and just upgraded to the new Thunderbird release. Exchange calendar stopped working after upgrade of TB so I installed the current stable release and tried also the latest beta. With both it is not possible to establish a connection. I deleted all my calendars, installed latest Lightning addon, but still the same.
It is not an urgent problem but if I can get it back to work again it would be fine.

Thanks,
Chris

Here ist the log:
1st-setup:2015-6-1 8:50:20.258:  -- calendar-task-tree --
1st-setup:2015-6-1 8:50:21.133:Lightning is installed.
1st-setup:2015-6-1 8:50:21.133:Lightning was installed from:https://addons.mozilla.org/thunderbird/downloads/latest/2313/platform:3/addon-2313-latest.xpi?src=discovery-promo
1st-setup:2015-6-1 8:50:21.478:updaterCallBack: No new version available.
1st-setup:2015-6-1 9:54:44.476:++==--++
1st-setup:2015-6-1 9:54:50.477:-- ActivityManager available. Enabling it.
1st-setup:2015-6-1 9:54:50.478:Going to check calendar registry '4efeac3c-8472-4a46-9b28-3bffb6d77a36' if it needs to be updated.
1st-setup:2015-6-1 9:54:50.478:Going to check calendar registry 'c0ebba81-7872-ba4e-82f9-6ccaff967f36' if it needs to be updated.
1st-setup:2015-6-1 9:54:50.479:Going to check calendar registry '717a3f07-e695-af4b-ae4f-69c8d02a501d' if it needs to be updated.
1st-setup:2015-6-1 9:55:21.957:exchWebServicesConvertIDOK: user:xxx, mailbox:xxx
1st-setup:2015-6-1 9:55:22.149:479419a8-e359-1d43-bd16-8594c1cb03f2: : 1 ExchangeRequest.sendRequest : user=xxx, url=https://groupware.fau.de/EWS/Exchange.asmx
1st-setup:2015-6-1 9:55:22.150:479419a8-e359-1d43-bd16-8594c1cb03f2: We have a prePassword: *******
1st-setup:2015-6-1 9:55:22.151:479419a8-e359-1d43-bd16-8594c1cb03f2: : sendRequest Sending: <?xml version="1.0" encoding="utf-8"?>
<nsSoap:Envelope xmlns:nsSoap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsSoap:Header><nsTypes:RequestServerVersion Version="Exchange2007_SP1"/><nsTypes:TimeZoneContext><t:TimeZoneDefinition Id="W. Europe Standard Time" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:nsSoap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"/></nsTypes:TimeZoneContext></nsSoap:Header><nsSoap:Body><nsMessages:FindItem Traversal="Shallow" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:nsSoap="http://schemas.xmlsoap.org/soap/envelope/"><nsMessages:ItemShape xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsTypes:BaseShape>IdOnly</nsTypes:BaseShape></nsMessages:ItemShape><nsMessages:CalendarView StartDate="2011-01-30T11:34:00Z" EndDate="2011-01-30T11:35:00Z" MaxEntriesReturned="1" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"/><nsMessages:ParentFolderIds xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsTypes:DistinguishedFolderId Id="calendar" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages"><nsTypes:Mailbox xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsTypes:EmailAddress>xxx</nsTypes:EmailAddress></nsTypes:Mailbox></nsTypes:DistinguishedFolderId></nsMessages:ParentFolderIds></nsMessages:FindItem></nsSoap:Body></nsSoap:Envelope>

1st-setup:2015-6-1 9:55:22.151:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({69150b77-b561-43a2-bfba-7301dd5a35d0})
1st-setup:2015-6-1 9:55:22.152:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({f6a0d1e5-369f-4abc-81ae-d370d36e4006})
1st-setup:2015-6-1 9:55:22.153:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-6-1 9:55:22.153:479419a8-e359-1d43-bd16-8594c1cb03f2: : ExchangeRequest.loadstart
1st-setup:2015-6-1 9:55:22.182:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-6-1 9:55:22.187:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-6-1 9:55:22.258:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-6-1 9:55:22.263:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-6-1 9:55:28.307:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-6-1 9:55:28.342:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-6-1 9:55:28.401:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-6-1 9:55:28.407:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-6-1 9:55:32.515:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-6-1 9:55:32.574:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-6-1 9:55:32.633:479419a8-e359-1d43-bd16-8594c1cb03f2: : ExchangeRequest.onLoad :load, readyState:4, status:401
1st-setup:2015-6-1 9:55:32.634:479419a8-e359-1d43-bd16-8594c1cb03f2: : ExchangeRequest.onLoad :Server: Microsoft-IIS/7.5
Set-Cookie: exchangecookie=a0cafded89784dd6846c69ad19884d15; expires=Wed, 20-Jul-2016 07:55:33 GMT; path=/; HttpOnly
WWW-Authenticate: Negotiate
NTLM
X-Powered-By: ASP.NET
Date: Mon, 20 Jul 2015 07:55:33 GMT
Content-Length: 0

1st-setup:2015-6-1 9:55:32.634:479419a8-e359-1d43-bd16-8594c1cb03f2: : ExchangeRequest.onLoad :
1st-setup:2015-6-1 9:55:32.635:479419a8-e359-1d43-bd16-8594c1cb03f2: exchangeRequest.isHTTPRedirect.xmlReq. xmlReq.readyState:4, xmlReq.status:401
1st-setup:2015-6-1 9:55:32.635:479419a8-e359-1d43-bd16-8594c1cb03f2: : isConnError req.status=401: Unauthorized
URL:https://groupware.fau.de/EWS/Exchange.asmx

1st-setup:2015-6-1 9:55:32.635:479419a8-e359-1d43-bd16-8594c1cb03f2: ecExchangeRequest.fail: aCode:-19, aMsg:HTTP Client error 401: Unauthorized
URL:https://groupware.fau.de/EWS/Exchange.asmx

1st-setup:2015-6-1 9:55:32.635:exchWebServicesCheckServerAndMailboxError: aCode:-19, aMsg:HTTP Client error 401: Unauthorized
URL:https://groupware.fau.de/EWS/Exchange.asmx

1st-setup:2015-6-1 9:55:35.556:479419a8-e359-1d43-bd16-8594c1cb03f2: : ExchangeRequest.loadend
1st-setup:2015-6-1 9:55:35.556:479419a8-e359-1d43-bd16-8594c1cb03f2: : ExchangeRequest.loadend :loadend, readyState:4, status:401
1st-setup:2015-6-1 9:55:35.557:479419a8-e359-1d43-bd16-8594c1cb03f2: : ExchangeRequest.loadend :

**Comment by bavincen** [comment]
Any special charectors in password?

**Comment by chem455** [comment]
Due to our password policies I have to use special characters, in my case it is nothing exotic, just a -

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon
please try this..

Thanks

**Comment by chem455** [comment]
Thanks for your efforts. I tried it, but it keeps the same.

One thing I was curious about (don't know if it is relevant) is: If I select Exchange Calendar in the new calendar dialog, there is a prefilled address in the address field. I can't remember if it was the same, when I connected to Exchange for the first time. The address looks something like: https://auto/1c50b7db-....

**Comment by Kishi0815** [comment]
I have the same problem with Thunderbird 38.1.0 (on Linux). I'm using lastest the latest git checkout. Also seeing 401 Unauthorized with a Exchange 2013 Server. Password is just ASCII (no special characters, just a-Z0-9) with a length >16 characters.

**Comment by bavincen** [comment]
Please check beta5. Release today
Thanks

Sent from my Sprint phone.

----- Reply message -----

**Comment by Kishi0815** [comment]
Problem still exists with Thunderbird 38.1.0 (Linux) and 3.4.0~beta5. 

Login still fails with 401 Unauthorized:

1st-setup:2015-6-1 16:13:17.962:mivExchangeAuthPrompt2: asyncPromptAuth: channel.responseStatus=401 (_asyncPromptAuth in mivExchangeAuthPrompt2.js:447)
1st-setup:2015-6-1 16:13:17.962:mivExchangeAuthPrompt2: asyncPromptAuth: channel.responseStatusText=Unauthorized (_asyncPromptAuth in mivExchangeAuthPrompt2.js:448)

**Comment by chem455** [comment]
Same for me, just to let you know

**Comment by bavincen** [comment]
please enable show text password in log... is that same?

**Comment by chem455** [comment]
All logged passwords are the same and correct

**Comment by bavincen** [comment]
Can you try logging via  (web outlook)

**Comment by chem455** [comment]
you mean log in over Outlook Web Access? No problem with safari web browser.

**Comment by ViceIce** [comment]
I have the same problem on windows 8.1

**Comment by ViceIce** [comment]
Ok, found a solution. I have to use the internal domain and user name, not the upn,

Regards

**Comment by Kishi0815** [comment]
After downgrading to Thunderbird 31.8.0/Lightning 3.3.3 with 3.4.0~beta5 everything is working as expected (no errors, GAL/Calendar working fine). 
After upgrading back to Thunderbird 38.1.0/Lightning 4.0.1 with 3.4.0~beta5 the "401 Unauthorized" problem is back (GAL/Calendar not working at all. Password prompts pop up again unless canceled).

Tests done using <Domain>\<Username>. UPN not tested. Accessing "/ews/Exchange.asmx" with curl and any of the server announced authentication methods (Negotiate/NTLM) works fine as well (no 401 or any other error). 


Something seems to have broken with the update from Thunderbird 31 to Thunderbird 38 regarding authentication, i just have no clue what it could be.

**Comment by bavincen** [comment]
clearing saved password works?

can you try without domain during autodiscovery

**Comment by Kishi0815** [comment]
I confirm this is working as long as I do not specify a "Domain name" (with or without autodiscovery) on Thunderbird 38. Thunderbird 31 is working with a value given in the "Domain name" field.

**Comment by chem455** [comment]
It is working for me, too. Auto discovery is not set up in our network, but if I leave the domain field blank it works.
Thanks for all the help
