### ISSUE TITLE
Too many failed login attempts leading to account lock  

### ISSUE THREAD

**Issue by jeka** [Ericsson/exchangecalendar#288]
Yesterday I got my Thunderbird updated to 38.1.0. Maybe Lightning got updated in the process too I have no idea. Current version is 4.0.1. Before this update I was running EWS Provider 3.4.0-beta4 for  a while without issues. 
After update things went south as I got locked out from AD several times. Not so good experience if you have to call Windows centric IT support located on another continent, trying to explain situation and asking for account unlock. Anyway, after 4 such calls I managed to narrow down the problem to my Exchange calendar account. For some reason EWS plugin is trying to connect to Exchange too many times in a short timeframe without success and triggering account lock. Now, why was EWS plugin using wrong password I have no idea (for sure my AD password was not changed in meantime) but clearly there is some problem with managing failed login attempts.
My solution was to delete exchange calendar account and update to beta5. After re-adding my calendar things started working as expected again.

**Comment by bavincen** [comment]
Apologies. Btw why didn't you try beta5 this shouldn't have happened.. I think we need explore bit.. did u had password with spaces,%

**Comment by jeka** [comment]
I didn't try beta5 because I didn't know about it at the time. I was so frustrated to explain to support guy that he can't connect to my desktop via rdc and solve my problem and no, rebooting my linux os wouldn't solve the problem ... And because calendar is critical for me I just deleted account so I can use thunderbird (granted, I didn't think about just disabling calendar account) and resorted to web access for a while and when I got little free time I started reading issues :/

About password, no spaces but special characters. Its enforced by password rules here. The password with the problem was including '@' '#' + small + caps + digits. I usually use any of the special characters on 1st row (digits) on the keyboard.

And about debugging. I have changed my AD password many times till now while using EWS plugin and till now I haven't had such issues. All I can tell is that problem happens immediately after starting thunderbird. Last time I asked support guy to monitor my account status. And I was locked out almost immediately after start of Thunderbird.

**Comment by bavincen** [comment]
it already fixed .... in beta5

**Comment by bavincen** [comment]
are you able to add new calendar?

**Comment by bavincen** [comment]
clearing that works?

try ur only username without domain during auto discovery

**Comment by jeka** [comment]
yes, as I stated in initial report updating to beta5 and re-adding my calendar worked and I have no problems so far. And yes I noticed that I should leave domain field blank ...

**Comment by bavincen** [comment]
special char fixed.
no other issues except https://github.com/Ericsson/exchangecalendar/issues/279
