### ISSUE TITLE
Exchangecalendar always prompt password for AddressBook

### ISSUE THREAD

**Issue by Trim** [Ericsson/exchangecalendar#290]
Hello,

I've Thunderbird 31.0.7, Lightening 3.3.7 and tested with exchangecalendar 3.3.2 and 3.4.0~beta5.

I was able to configure exchange calendars (it seems I have Exchange 2007 SP1) with server url https://autodiscover.collaborationhost.net/ews/exchange.asmx and my complete mail address as login.

Now, I need to install address book. So I'm using same config than for calendars and I can discover public folders to retrive a shared Address Book.

Then I want to look for a contact in the adress book, so I run a search and now exchangecalendar spams me with authentication popups (even if I clik on "remember my password using password manager").

First, the spaming popup is a bit strange, because it asks me password for `\adrien.dorsaz@example-site.com` instead of `adrien.dorsaz@example-site.com` (the good one was the case for the calendar synchronization).

Then I've enabled logs and I found inside them the error message from this [line](https://github.com/Ericsson/exchangecalendar/blob/ec-3.4/interfaces/exchangeAuthPrompt2/mivExchangeAuthPrompt2.js#L176):
```getPassword: There was a password in cache or passwordManager and one on the channel. And they are the same. Going to ask user to provide a new password.```

I think that my issue comes from the popup, because when I read log I find:

```1st-setup:2015-6-2 22:44:12.405:46ecf50a-13b3-422c-b15a-3448201c4da7: : 1 ExchangeRequest.sendRequest : user=\adrien.dorsaz@example-site.com, url=https://autodiscover.collaborationhost.net/ews/exchange.asmx```

Indeed, the spam popup is just a way to ensure that a user enter a new password if there's a logon issue (if I've well understand).

So could be an issue with the way the AddressBook interface call the AuthProvider ?

PS: in my examples I've used "example-site.com" instead of "example.com", because my mail provider domain contains a `-`.

Edit: I've checked `about:config` and exchange parameters have good logins (without the `\` prefixed).

**Comment by bavincen** [comment]
please check saved passwords is that correct?

**Comment by bavincen** [comment]
clearing that works?

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon
