### ISSUE TITLE
3.4.0 beta5 hangs on getting events from calendar with only visibility rights

### ISSUE THREAD

**Issue by AndiMb** [Ericsson/exchangecalendar#291]
When creating a calendar which is "visible only" for the user the calendar add-on hangs during getting the events from the server with "1 running & XX queued jobs" in the status bar. If we create only full access (read and write) calendars anything works. If we use Exchange EWS Provider v3.3.2 this works (but other things not).

We use Thunderbird 38.1.0 with Lightning 4.0.1 the Exchange EWS Provider 3.4.0 beta5 and OpenSuSE 13.2 64bit.

**Comment by thedarb** [comment]
I had the same problem when I updated to 3.4.0 beta5.  The calendars I had for my boss and co-workers, which were "visible only", were hanging the plugin with the same "1 running & XX queued jobs".

I had to remove those calendars for my own and our globally writable time off calendars to load.

**Comment by bavincen** [comment]
Hello we have enabled caching by default.. it will be slow on first restart

**Comment by bavincen** [comment]
Closing it..

**Comment by Nick668** [comment]
I too have the same problem when I updated to 3.4.0 beta5. 

All the calendars I had  which were "read only", were hanging the plugin with the same "1 running & XX queued jobs".

I have left it running for a full work day and it just hung there and never loaded the calendar events, so I doubt it is an issue with caching.

Disabling the "read only" calendars and restarting at least allows my "full access" calendar to load.

This wasn't a problem in version 3.3.2.

**Comment by bavincen** [comment]
@Nick668 I think you need to clear cache and check.. check with admin you have write permission for calendar.. are you able to add write in OWA

**Comment by Nick668** [comment]
Just to help consolidate the two threads. My last reply on the now closed one.

>> is it hanging every time or first time??

> It is hanging on the first time so is never getting a chance to try a second time.
> 
> As some extra info, if I only have the "read only" calendars disabled at start time, it will successfully load events for the "read/write" calendars. If I then go and enable the "read only" calendars it will then hang and I lose all interaction with the "read/write" calendars.
> 
> Also to answer your question on the #291 thread
>> "@Nick668 I think you need to clear cache and check.. check with admin you have write permission for calendar.. are you able to add events in OWA"
> 
> If I disable all the "Read Only" calendars then I have full interaction (read/write) with calendars that I "own".
> 
> Deleting all the cache makes no difference.

**Comment by AndiMb** [comment]
Some additional information. It's not a read/write problem. This happens for calendars with "free busy only" permissions only. For calendars with more details but no write permissions, it also works.

I also think this is no caching problem.

Andreas

**Comment by thedarb** [comment]
AndiMb: Agreed.  That is what I was seeing also.  I haven't been able to respond to the thread for a while, but I was disappointed to see my account discounted.

**Comment by thedarb** [comment]
Has this been fixed in beta 6 or 7?

**Comment by Nick668** [comment]
I've just installed Beta 7 (5 minutes ago)  and so far it appears to be fixed. 

Thanks
