### ISSUE TITLE
Cannot connect since 3.4 Beta X - Exchange account gets blocked due to login attemps with wrong password

### ISSUE THREAD

**Issue by endzone** [Ericsson/exchangecalendar#292]
Hello,

me and multiple of my coworkers are getting their Exchange accounts blocked by the Calender plugin since about the upgrade to 3.4 Beta 1.

Access to calender items is not possible, a password prompt fires up every time. Entering the correct password does not solve the problem, the password prompt reappears.

After multiple connection attempt, the exchange account of the affected user is blocked due to multiple failed login attempts. Access to email is not possible for some time.

**Comment by bavincen** [comment]
Use Beat5 please. or https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

**Comment by bavincen** [comment]
also try clearing saved passwords

**Comment by endzone** [comment]
I am using Beta5 and cleared all passwords. Problem still persists.

**Comment by endzone** [comment]
I will try to attach a debug log of the authentication process with all username/passwords removed.

**Comment by endzone** [comment]
Please find the logs here: http://pastebin.com/3vtErQ14
They will expire in 1 month.

**Comment by reallumpi** [comment]
Slightly the same Issue here, but since some days i get to see a 401 in the Logfiles. If i try to manually connect to the Exchange.asmx Page the authentication works using my Username without local.domain\ prefix. I uploaded the Log here: http://pastebin.com/NgwCnsUJ (Latest TB on Debian Testing).

To be honest, i am not quite shure if the issue is really with the Plugin, it might also be a "we haven't changed a thing" Issue with our Microsoft guys so any hint in the right direction is appreciated.

**Comment by bavincen** [comment]
can you please clear the saved passwords and try

thanks

**Comment by reallumpi** [comment]
Yes, allready did that. Also tried it with a entirely fresh Install of TB and EWS Beta5 in a VM and still the same Issue.

**Comment by reallumpi** [comment]
Ok, just found the Issue, if we leave the local.domain Part out it works, so it really seems either an Exchange Update broke the Authentication or one of our Exchange guys changed the Authentication somehow. So at least it works for me now as long as i leave the Domain Part empty when subscribing to a calendar...

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/commit/88e4417127a93212c29faaa72ed7c33e055509dd  https://github.com/Ericsson/exchangecalendar/commit/ca97609b20bb5c4b87f6eca4c7bb06da082d05ac https://github.com/Ericsson/exchangecalendar/commit/75b094736cefb715e50336795a1004aafc59c2d3
