### ISSUE TITLE
Explicit reset cache needed in 3.4.0 beta 5

### ISSUE THREAD

**Issue by kiravi** [Ericsson/exchangecalendar#298]
1. Keeping Thunderbird open and restoring after computer sleeps.
2. A hard cache reset is needed to get new events sometimes.
3. A hard cache reset is needed to remove duplicate entries often.

**Comment by bavincen** [comment]
it seems to be internet issue at the time?

**Comment by kiravi** [comment]
Seems to be working in beta7, was not in beta5
