### ISSUE TITLE
3.4.0 beta5 hangs on getting events from calendar with only visibility rights issue #291

### ISSUE THREAD

**Issue by Nick668** [Ericsson/exchangecalendar#299]
I too have the same problem when I updated to 3.4.0 beta5 as listed in closed issue  #291.

All the calendars I had which were "read only", were hanging the plugin with the same "1 running & XX queued jobs" status.

I have left it running for a full work day and it just hung there and never loaded the calendar events, so I doubt it is an issue with caching.

Disabling the "read only" calendars and restarting at least allows my "full access" calendar to load.

This wasn't a problem in version 3.3.2.

**Comment by bavincen** [comment]
is it hanging every time or first time??

**Comment by Nick668** [comment]
It is hanging on the first time so is never getting a chance to try a second time.

As some extra info, if I only have the "read only" calendars disabled at start time, it will successfully load events for the "read/write" calendars. If I then go and enable the "read only" calendars it will then hang and I lose all interaction with the "read/write" calendars. 

Also to answer your question on the #291 thread 
"@Nick668 I think you need to clear cache and check.. check with admin you have write permission for calendar.. are you able to add events in OWA"

If I disable all the "Read Only" calendars then I have full interaction (read/write) with calendars that I "own".

Deleting all the cache makes no difference.

**Comment by muthusuba** [comment]
reopening the bug 291 and closing this one - its nicer to track the history there.
