### ISSUE TITLE
Memory leak in beta4 and beta5 with TB 38.1.0

### ISSUE THREAD

**Issue by torinaki** [Ericsson/exchangecalendar#301]
With disabled addon:

├───17.52 MB (14.27%) -- window-objects
│   ├──12.00 MB (09.77%) -- top(chrome://messenger/content/messenger.xul, id=3)

with enabled addon:

├───83.43 MB (35.00%) -- window-objects
│   ├──66.99 MB (28.11%) -- top(chrome://messenger/content/messenger.xul, id=3)

and its slowly grow all the time.

  Application Basics

    Name: Thunderbird
    Version: 38.1.0
    User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Thunderbird/38.1.0
    Profile Folder: Show Folder

              (Local drive)
    Application Build ID: 20150707103124
    Enabled Plugins: about:plugins
    Build Configuration: about:buildconfig
    Memory Use: about:memory

  Mail and News Accounts
    
    account2:
      INCOMING: account2, , (none) Local Folders, plain, passwordCleartext

    account3:
      INCOMING: account3, , (im) prpl-facebook, plain, 0

    account4:
      INCOMING: account4, , (im) prpl-gtalk, plain, 0

    account5:
      INCOMING: account5, , (imap) outlook.office365.com:993, SSL, passwordCleartext
      OUTGOING: mail.intechsystems.lv:587, alwaysSTARTTLS, passwordEncrypted, true

  Crash Reports
    http://crash-stats.mozilla.com/report/index/bp-5e5e68a4-4486-4a65-800f-551ce2150727 (27.07.2015)
    http://crash-stats.mozilla.com/report/index/bp-4a815cdd-417d-4d59-9420-c2f632150608 (08.06.2015)
    http://crash-stats.mozilla.com/report/index/bp-a05e0236-fd29-4304-95bc-913202150110 (10.01.2015)
    http://crash-stats.mozilla.com/report/index/bp-e9b91739-9ec7-4ae6-9068-7f2fd2141020 (20.10.2014)
    http://crash-stats.mozilla.com/report/index/bp-650611ef-7865-4d7f-bd50-c85512140811 (11.08.2014)

  Extensions

    Exchange EWS Provider, 3.4.0~beta5, true, exchangecalendar@extensions.1st-setup.nl
    Lightning, 4.0.1.2, true, {e2fda1a4-762b-4020-b5ad-a41df1933103}

  Important Modified Preferences

    Name: Value

      accessibility.typeaheadfind.flashBar: 0
      browser.cache.disk.capacity: 358400
      browser.cache.disk.smart_size_cached_value: 358400
      browser.cache.disk.smart_size.first_run: false
      browser.cache.disk.smart_size.use_old_max: false
      extensions.lastAppVersion: 38.1.0
      font.internaluseonly.changed: true
      font.name.monospace.el: Consolas
      font.name.monospace.tr: Consolas
      font.name.monospace.x-baltic: Consolas
      font.name.monospace.x-central-euro: Consolas
      font.name.monospace.x-cyrillic: Consolas
      font.name.monospace.x-unicode: Consolas
      font.name.monospace.x-western: Consolas
      font.name.sans-serif.el: Calibri
      font.name.sans-serif.tr: Calibri
      font.name.sans-serif.x-baltic: Calibri
      font.name.sans-serif.x-central-euro: Calibri
      font.name.sans-serif.x-cyrillic: Calibri
      font.name.sans-serif.x-unicode: Calibri
      font.name.sans-serif.x-western: Calibri
      font.name.serif.el: Cambria
      font.name.serif.tr: Cambria
      font.name.serif.x-baltic: Cambria
      font.name.serif.x-central-euro: Cambria
      font.name.serif.x-cyrillic: Cambria
      font.name.serif.x-unicode: Cambria
      font.name.serif.x-western: Cambria
      font.size.fixed.el: 14
      font.size.fixed.tr: 14
      font.size.fixed.x-baltic: 14
      font.size.fixed.x-central-euro: 14
      font.size.fixed.x-cyrillic: 14
      font.size.fixed.x-unicode: 14
      font.size.fixed.x-western: 14
      font.size.variable.el: 17
      font.size.variable.tr: 17
      font.size.variable.x-baltic: 17
      font.size.variable.x-central-euro: 17
      font.size.variable.x-cyrillic: 17
      font.size.variable.x-unicode: 17
      font.size.variable.x-western: 17
      gfx.direct3d.last_used_feature_level_idx: 0
      mail.openMessageBehavior.version: 1
      mail.winsearch.firstRunDone: true
      mailnews.database.global.datastore.id: 85c1824f-32b7-4255-9aba-5cba4669acd
      mailnews.database.global.indexer.enabled: true
      mailnews.database.global.views.conversation.columns: {"threadCol":{"visible":true,"ordinal":"1"},"flaggedCol":{"visible":true,"ordinal":"3"},"attachmentCol":{"visible":false…
      network.cookie.prefsMigrated: true
      network.predictor.cleaned-up: true
      places.database.lastMaintenance: 1438621310
      places.history.expiration.transient_current_max_pages: 104858
      plugin.importedState: true
      plugin.state.flash: 0

  Graphics

      Adapter Description: Intel(R) HD Graphics
      Vendor ID: 0x8086
      Device ID: 0x0152
      Adapter RAM: Unknown
      Adapter Drivers: igdumd64 igd10umd64 igd10umd64 igdumd32 igd10umd32 igd10umd32
      Driver Version: 9.17.10.2932
      Driver Date: 12-12-2012
      Direct2D Enabled: true
      DirectWrite Enabled: true (6.2.9200.17292)
      ClearType Parameters: ClearType parameters not found
      WebGL Renderer: false
      GPU Accelerated Windows: 1/1 Direct3D 11

      AzureCanvasBackend: direct2d 1.1
      AzureSkiaAccelerated: 0
      AzureFallbackCanvasBackend: cairo
      AzureContentBackend: direct2d 1.1

  JavaScript

    
      Incremental GC: 1
    

  Accessibility

    Activated: 0
    Prevent Accessibility: 0

  Library Versions

      Expected minimum version
      Version in use

      NSPR
      4.10.8
      4.10.8

      NSS
      3.19.2 Basic ECC
      3.19.2 Basic ECC

      NSS Util
      3.19.2
      3.19.2

      NSS SSL
      3.19.2 Basic ECC
      3.19.2 Basic ECC

      NSS S/MIME
      3.19.2 Basic ECC
      3.19.2 Basic ECC

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

please give us Ur feedback on latest 
thanks for work

**Comment by torinaki** [comment]
@bavincen thanks you. I have installed `master` and will give feedback soon

**Comment by torinaki** [comment]
@bavincen same problem

Explicit Allocations

1,821.62 MB (100.0%) -- explicit
├──1,437.44 MB (78.91%) -- window-objects
│  ├──1,433.04 MB (78.67%) -- top(chrome://messenger/content/messenger.xul, id=3)
│  │  ├──1,352.77 MB (74.26%) -- active
│  │  │  ├──1,351.17 MB (74.17%) -- window(chrome://messenger/content/messenger.xul)
│  │  │  │  ├────755.01 MB (41.45%) -- dom
│  │  │  │  │    ├──753.79 MB (41.38%) ── orphan-nodes
│  │  │  │  │    └────1.22 MB (00.07%) ++ (4 tiny)
│  │  │  │  ├────591.18 MB (32.45%) -- js-compartment([System Principal], about:blank)
│  │  │  │  │    ├──369.22 MB (20.27%) -- classes
│  │  │  │  │    │  ├──182.00 MB (09.99%) -- class(With)
│  │  │  │  │    │  │  ├──121.32 MB (06.66%) ── objects/gc-heap
│  │  │  │  │    │  │  └───60.68 MB (03.33%) -- shapes/gc-heap
│  │  │  │  │    │  │      ├──60.68 MB (03.33%) ── tree
│  │  │  │  │    │  │      └───0.00 MB (00.00%) ── base
│  │  │  │  │    │  ├───80.91 MB (04.44%) -- class(WithTemplate)
│  │  │  │  │    │  │   ├──80.91 MB (04.44%) ── objects/gc-heap
│  │  │  │  │    │  │   └───0.00 MB (00.00%) ++ shapes/gc-heap
│  │  │  │  │    │  ├───63.60 MB (03.49%) -- class(XULElement)
│  │  │  │  │    │  │   ├──39.70 MB (02.18%) -- objects
│  │  │  │  │    │  │   │  ├──30.07 MB (01.65%) ── gc-heap
│  │  │  │  │    │  │   │  └───9.64 MB (00.53%) ── malloc-heap/slots
│  │  │  │  │    │  │   └──23.89 MB (01.31%) ++ shapes
│  │  │  │  │    │  ├───34.05 MB (01.87%) -- class(Function)
│  │  │  │  │    │  │   ├──33.99 MB (01.87%) -- objects
│  │  │  │  │    │  │   │  ├──33.97 MB (01.87%) ── gc-heap
│  │  │  │  │    │  │   │  └───0.01 MB (00.00%) ── malloc-heap/slots
│  │  │  │  │    │  │   └───0.06 MB (00.00%) ++ shapes
│  │  │  │  │    │  └────8.66 MB (00.48%) ++ (12 tiny)
│  │  │  │  │    ├──128.06 MB (07.03%) ── compartment-tables
│  │  │  │  │    ├───93.63 MB (05.14%) -- scripts
│  │  │  │  │    │   ├──86.36 MB (04.74%) ── gc-heap
│  │  │  │  │    │   └───7.27 MB (00.40%) ── malloc-heap/data
│  │  │  │  │    └────0.27 MB (00.01%) ++ (4 tiny)
│  │  │  │  └──────4.98 MB (00.27%) ++ (3 tiny)
│  │  │  └──────1.59 MB (00.09%) ++ (3 tiny)
│  │  └─────80.27 MB (04.41%) -- js-zone(0xc7e3400)
│  │        ├──71.53 MB (03.93%) ── object-groups/gc-heap
│  │        └───8.74 MB (00.48%) ++ (6 tiny)
│  └──────4.40 MB (00.24%) ++ (8 tiny)
├────266.92 MB (14.65%) -- maildb
│    ├──266.84 MB (14.65%) ── database(imap://dmitry.balabka%40intexsys.lv@outlook.office365.com/INBOX)
│    └────0.08 MB (00.00%) ── database(mailbox:///C:/Users/DmitryB/AppData/Roaming/Thunderbird/Profiles/g1nxr6kj.default/Mail/Local%20Folders/Unsent%20Messages)
├─────76.63 MB (04.21%) -- js-non-window
│     ├──38.95 MB (02.14%) -- zones
│     │  ├──36.37 MB (02.00%) ++ zone(0x26cb800)
│     │  └───2.58 MB (00.14%) ++ (9 tiny)
│     ├──23.65 MB (01.30%) ++ runtime
│     └──14.03 MB (00.77%) ++ gc-heap
├─────57.83 MB (03.17%) -- xpconnect
│     ├──49.16 MB (02.70%) ── runtime
│     └───8.67 MB (00.48%) ++ (4 tiny)
├─────46.33 MB (02.54%) -- heap-overhead
│     ├──22.10 MB (01.21%) ── bin-unused
│     ├──20.43 MB (01.12%) ── bookkeeping
│     └───3.79 MB (00.21%) ++ (2 tiny)
└────-63.53 MB (-3.49%) -- (22 tiny) [?!]
     ├───17.78 MB (00.98%) ++ add-ons
     ├───13.22 MB (00.73%) ++ cycle-collector
     ├───12.00 MB (00.66%) ── dom/event-listener-managers-hash
     ├───11.78 MB (00.65%) ++ storage/sqlite
     ├────1.96 MB (00.11%) ++ workers/workers(chrome)/worker(resource://gre/modules/osfile/osfile_async_worker.js, 0xc7ebc00)
     ├────1.17 MB (00.06%) ── xpti-working-set
     ├────0.80 MB (00.04%) ++ startup-cache
     ├────0.66 MB (00.04%) ++ images
     ├────0.60 MB (00.03%) ++ atom-tables
     ├────0.55 MB (00.03%) ++ gfx
     ├────0.28 MB (00.02%) ++ layout
     ├────0.28 MB (00.02%) ++ xpcom
     ├────0.27 MB (00.01%) ── preferences
     ├────0.17 MB (00.01%) ── telemetry
     ├────0.17 MB (00.01%) ── icu
     ├────0.10 MB (00.01%) ── script-namespace-manager
     ├────0.05 MB (00.00%) ++ network
     ├────0.01 MB (00.00%) ── cookie-service
     ├────0.00 MB (00.00%) ── history-links-hashtable
     ├────0.00 MB (00.00%) ++ media
     ├────0.00 MB (00.00%) ── spell-check
     └──-125.40 MB (-6.88%) ── heap-unclassified [?!]

**Comment by torinaki** [comment]
@bavincen I have installed v3.4.0-beta7. Trying with newer version. FYI master version cannot be installed because it always say that addon is curreupted for some reason.

**Comment by torinaki** [comment]
@bavincen problem still appears with v3.4.0-beta7

**Comment by torinaki** [comment]
I will try suggested fix in https://github.com/Ericsson/exchangecalendar/issues/326#issuecomment-138993425

**Comment by torinaki** [comment]
Fix that was proposed in https://github.com/Ericsson/exchangecalendar/issues/326#issuecomment-138993425 do not help

**Comment by torinaki** [comment]
I'm closing this issue due to https://github.com/Ericsson/exchangecalendar/issues/326#issuecomment-144044810
