### ISSUE TITLE
bad feedback after password change

### ISSUE THREAD

**Issue by thoastbrot** [Ericsson/exchangecalendar#302]
if the password on the server changed, the calendars go into write protected mode instead of asking for the password. Even further - if you have multiple calendars, deleting the password entry for the host in thunderbird, it will only fix the first calendar you synchronize.

You can uncheck the read only flag, but it won't change anything and just be checked again.

**Comment by bavincen** [comment]
Thanks for info 
how do I reproduce

Sent from my Sprint phone.

----- Reply message -----

**Comment by thoastbrot** [comment]
have a calendar, change the password on the OWA... I expect this to trigger it. I had events shown which I couldn't dismiss and went into debugging the issue. I saw that there were no pending jobs and checked the calendar settings. Then I found the lock and the read-only flag on the calendars.

**Comment by bavincen** [comment]
have you tried beta7? please

**Comment by bavincen** [comment]
i am closing it as no response
