### ISSUE TITLE
Thunderbird freezing

### ISSUE THREAD

**Issue by msbdun** [Ericsson/exchangecalendar#308]
I have used Lightning with Thunderbird for a number of years and sync to Exchange. After the 38.1.0 update with Lightning 4.0.1.2 I have been experiencing issues with Thunderbird freezing. This is primarily when I try and dismiss certain reminders. It seems that the reminders that cause issues are repeating ones, potentially ones that have had one or more of the meetings changed at some point.

I also get this issue when I try and view September. This is when our daylight saving starts so potentially this is related.

I have upgraded to EWS3.4.0 beta5 and still have the issue.

Version of Exchange was 2010 but has just gone to 2013. Issue is the same for both.

Any ideas?

**Comment by bavincen** [comment]
plrase try beta7
