### ISSUE TITLE
Using EXquilla, Tagging in primary account is not woking

### ISSUE THREAD

**Issue by kdg1** [Ericsson/exchangecalendar#310]
Thunderbird 38.1.0
Lightning 4.0.1.2
Exchange EWS Provider 3.5.0-beta0
My primary account is a pop server, the tags are visbile via the dropdown but nothing happens when they are assigned to an email. I can remove pre-existing tags by using the 'remove all tags' option but not by un-selecting the actual tag currently assigned.
I have another pop account, an imap account, and local folders and tagging does work with each of these. I also have an exchange account which has rules to tag new mail in the inbox mail and move it to my primary account, which works, it tags them and moves them and I see these tags in my primary account.
If I disable Exchange EWS Provider, then tagging in the primary folder works well.

**Comment by kdg1** [comment]
This issue was reported on issue 270 before it was closed. It is directly related to the release of Lightning 4, and I tested each fix in this issue to see if it resolved the tagging problem. After a month of monitoring and testing the fixes, I reported that this was still a problem. The issue was subsequently closed and I was told to create a new issue.
It has been now been over 5 weeks, how long before this issue is addressed, since it was first reported in 270?

**Comment by bavincen** [comment]
@kdg1 sorry for late.. we will try to fix that in coming weeks.

**Comment by bavincen** [comment]
please post that log when you tagging mail.
Also please check if yuo are using any tagging related addons.
Are yuo using imap or pop ac?

**Comment by kdg1** [comment]
Primary account is POP server connected to my ISP. My Exchange account is used as follows
- ExQuilla is used to sync my email
- a Filer Rule to tags Exchange email and moves to Primary account folder (this works and nothing is left in the Exchange folder)
- EWS to sync the Exchange calendar in Lightning
- no contacts exist in Exchange and no syncing is required
When I tag an email in another folder (other than primary and Exchange), no log in created and the email is tagged correctly.
When I tag an email in my primary folder (regardless if it came through my ISP or came through Exchange), I 'think' the log says it tries to sync the tag on Exchange and fails, perhaps the reason it is not tagging it in the primary folder. It should not try to sync a non-Exchange folder.
I created a small log, below and a link to a full log
I am using tagSequenceArranger 0.1.95 but it is disabled until I solve this problem.

----------------- start of small log
1st-setup:2015-7-4 16:14:11.107:ewsTagger(ALLIANCE1\kgraham): Toggle tags on message id - <CAHj+3bKzbepC4XVwXnPDXtGMucmpFNJy4BMbr7s=2_3Rwhj+BQ@mail.gmail.com>
1st-setup:2015-7-4 16:14:11.114:erFindItemsRequest.execute 2:<nsMessages:FindItem xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types" Traversal="Shallow"><nsMessages:ItemShape><nsTypes:BaseShape>IdOnly</nsTypes:BaseShape></nsMessages:ItemShape><nsMessages:IndexedPageItemView MaxEntriesReturned="100" Offset="0" BasePoint="Beginning"/><nsMessages:Restriction><nsTypes:IsEqualTo><nsTypes:ExtendedFieldURI PropertyTag="0x1035" PropertyType="String"/><nsTypes:FieldURIOrConstant><nsTypes:Constant Value="&lt;CAHj+3bKzbepC4XVwXnPDXtGMucmpFNJy4BMbr7s=2_3Rwhj+BQ@mail.gmail.com&gt;"/></nsTypes:FieldURIOrConstant></nsTypes:IsEqualTo></nsMessages:Restriction><nsMessages:ParentFolderIds xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsTypes:FolderId Id="AAMkAGU3MTIyNzRlLThjYTMtNDM0NS1hYzlkLWUzNjI1ZTJkNjI1NwAuAAAAAAB5QvMZi5M3R7B4d4+PgyM6AQAlOpG6bAE4SI1S0xklce9xAAAAAAENAAA="/></nsMessages:ParentFolderIds></nsMessages:FindItem>

1st-setup:2015-7-4 16:14:11.123:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({69150b77-b561-43a2-bfba-7301dd5a35d0})
1st-setup:2015-7-4 16:14:11.126:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({f6a0d1e5-369f-4abc-81ae-d370d36e4006})
1st-setup:2015-7-4 16:14:11.128:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-7-4 16:14:11.214:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-7-4 16:14:11.270:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-7-4 16:14:11.333:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-7-4 16:14:11.395:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-7-4 16:14:11.475:erFindItemsRequest.execute 2: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="15" MinorVersion="0" MajorBuildNumber="1076" MinorBuildNumber="9" Version="V2_22" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><m:FindItemResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:FindItemResponseMessage ResponseClass="Success"><m:ResponseCode>NoError</m:ResponseCode><m:RootFolder IndexedPagingOffset="0" TotalItemsInView="0" IncludesLastItemInRange="true"><t:Items/></m:RootFolder></m:FindItemResponseMessage></m:ResponseMessages></m:FindItemResponse></s:Body></s:Envelope>

1st-setup:2015-7-4 16:14:11.479:ewsTagger(ALLIANCE1\kgraham): Toggle tags found items on server returned total - 0
1st-setup:2015-7-4 16:14:11.481:ewsTagger(ALLIANCE1\kgraham): Toggle tags not finding any items in server for Ids. "<CAHj+3bKzbepC4XVwXnPDXtGMucmpFNJy4BMbr7s=2_3Rwhj+BQ@mail.gmail.com>"
1st-setup:2015-7-4 16:14:11.483:[Alliance] setProperty. aName:exchangeCurrentStatus, aValue:0 (setProperty in mivExchangeCalendar.js:828)
------------------- end of log

Link to full log
https://gist.github.com/kdg1/9f9521e632a182a3f57c

**Comment by bavincen** [comment]
Hi @kdg1  I need you to grep "ewsTagger" And post the log...
This will be sufficient.
Thanks..

**Comment by kdg1** [comment]
As requested, ewsTagger lines from tagging action on primary account

1st-setup:2015-7-5 3:28:3.581:ewsTagger(ALLIANCE1\kgraham): Toggle tags on message id - <f1889a43-b949-4751-a862-1a5b142a0c1d@xtinmta1121.xt.local>
1st-setup:2015-7-5 3:28:5.125:ewsTagger(ALLIANCE1\kgraham): Toggle tags found items on server returned total - 0
1st-setup:2015-7-5 3:28:5.128:ewsTagger(ALLIANCE1\kgraham): Toggle tags not finding any items in server for Ids. "<f1889a43-b949-4751-a862-1a5b142a0c1d@xtinmta1121.xt.local>"
1st-setup:2015-7-5 3:28:6.630:ewsTagger(ALLIANCE1\kgraham): Toggle tags on message id - <f1889a43-b949-4751-a862-1a5b142a0c1d@xtinmta1121.xt.local>
1st-setup:2015-7-5 3:28:6.979:ewsTagger(ALLIANCE1\kgraham): Toggle tags found items on server returned total - 0
1st-setup:2015-7-5 3:28:6.982:ewsTagger(ALLIANCE1\kgraham): Toggle tags not finding any items in server for Ids. "<f1889a43-b949-4751-a862-1a5b142a0c1d@xtinmta1121.xt.local>"
1st-setup:2015-7-5 3:28:7.217:ewsTagger(ALLIANCE1\kgraham): Syncting TagItems now.
1st-setup:2015-7-5 3:28:7.221:ewsTagger(ALLIANCE1\kgraham): Already Running
1st-setup:2015-7-5 3:28:17.183:ewsTagger(ALLIANCE1\kgraham): Toggle tags on message id - <f1889a43-b949-4751-a862-1a5b142a0c1d@xtinmta1121.xt.local>
1st-setup:2015-7-5 3:28:17.540:ewsTagger(ALLIANCE1\kgraham): Toggle tags found items on server returned total - 0
1st-setup:2015-7-5 3:28:17.543:ewsTagger(ALLIANCE1\kgraham): Toggle tags not finding any items in server for Ids. "<f1889a43-b949-4751-a862-1a5b142a0c1d@xtinmta1121.xt.local>"
1st-setup:2015-7-5 3:28:27.217:ewsTagger(ALLIANCE1\kgraham): Syncting TagItems now.
1st-setup:2015-7-5 3:28:27.221:ewsTagger(ALLIANCE1\kgraham): Already Running
1st-setup:2015-7-5 3:28:47.217:ewsTagger(ALLIANCE1\kgraham): Syncting TagItems now.
1st-setup:2015-7-5 3:28:47.220:ewsTagger(ALLIANCE1\kgraham): Already Running

**Comment by bavincen** [comment]
please use beta7

**Comment by kdg1** [comment]
Downloading and installing the latest release has solved the issue. I appreciate your support. Thank you.
