### ISSUE TITLE
v3.4.0-beta6 repeatedly asks for password

### ISSUE THREAD

**Issue by KarelDemeyer** [Ericsson/exchangecalendar#312]
Since 3.4.0-beta6, the extensions keeps asking for my password and never succesfully connects anymore. Reverting to beta5 fixes this problem.

My password is quite long and contains a lot fo special characters.

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon
We found the issue..

it is already fixed
Please check this
