### ISSUE TITLE
3.4 is not working with thunderbird 31.8.0 and lightning 3.3.3 on ubuntu

### ISSUE THREAD

**Issue by montao** [Ericsson/exchangecalendar#314]
It is not possible to add a server url. The server url is greyed out and says ews.example.com. What can I do about it? When reading the installation instructions it look like the server url should be manually entered. 
![1](https://cloud.githubusercontent.com/assets/51189/9383083/78a2d202-4746-11e5-82c1-d59f32df1130.png)
![2](https://cloud.githubusercontent.com/assets/51189/9383084/7ac6613e-4746-11e5-86ee-f5a24d65a467.png)

**Comment by bavincen** [comment]
hello @montao server url can be entered.
secondly you can  also fill out the usename,domain perform auto discovery

**Comment by montao** [comment]
But how can I enter server url? The input field is greyed out and not writeable.
