### ISSUE TITLE
EWS calendar 3.4.beta7 works with 31.7 + lighning but not with 38.1

### ISSUE THREAD

**Issue by EricV2** [Ericsson/exchangecalendar#315]
Same config, authentication always fails

**Comment by EricV2** [comment]
The fix is to set network.auth.force-generic-ntlm-v1 true as suggested in https://bugzilla.mozilla.org/show_bug.cgi?id=1174159. I would advise to set this to true at install otherwise most people will complain upon upgrade as plugin will seems to fail while it in an ntlm v1 problem that has no security impact when used with https...

**Comment by bavincen** [comment]
thanks for nice info.. we try ntlm before password login

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/commit/e9b56f68d93b2f36de3c0bb81bd7ef94817242a1
