### ISSUE TITLE
MAIL THIS LINE TO log entry should point here

### ISSUE THREAD

**Issue by strobelight** [Ericsson/exchangecalendar#319]
1st-setup:2015-7-2 11:35:34.501:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})

1st-setup.nl responded to point me to this repo, but suggest fixing in the file that creates the log.

**Comment by bavincen** [comment]
we will do it later.

**Comment by muthusuba** [comment]
Reopening this to track...

**Comment by bavincen** [comment]
the line has been rewritten and changed to github issues page..
