### ISSUE TITLE
Thunderbird 38.2 with Lightning 4.0.2 always asks for password

### ISSUE THREAD

**Issue by hlili** [Ericsson/exchangecalendar#320]
after Thunderbird update to 38.2 (and Lightning 4.02) Exchange is asking for password again and again.
Testet an Ubuntu 14.04 and MacOS 10.10.5
![shot](https://cloud.githubusercontent.com/assets/13977482/9488198/5fa2c49c-4bd8-11e5-944f-21dcf4d300eb.jpg)

**Comment by bavincen** [comment]
Issue #306

**Comment by konturger** [comment]
Fallowing FIX worked for me, and seems to be a final simple fix:
set network.auth.force-generic-ntlm-v1 from FALSE to TRUE (under Prefernces | Advanced | General | Config Editor) - Be very careful within the config editor!

![fix thunderbirdv38lightning402_exchange_calender](https://cloud.githubusercontent.com/assets/10417066/9830932/8291eb14-5942-11e5-8f78-3db5f07c53fb.png)
