### ISSUE TITLE
No access on calendar with TB 38.2.0 / Lightning 4.0.2 and exchangecalendar 3.4.0~beta7

### ISSUE THREAD

**Issue by pic2base** [Ericsson/exchangecalendar#324]
OS: Ubuntu 14.04 LTS
TB 38.2.0
Lightning 4.0.2
exchangecalendar 3.4.0~beta7
Mailserver: MS Exchange 2007
Error: after automatic update TB 31.8 -> 38.2, Lightning 3.3.3 -> 4.0.2
Error: Fehler bei der Abfrage des Servers und des Postfachs:HTTP Client error 401: Unauthorized
URL:domainxy.de/EWS/Exchange.asmx
(Code: -19)

Can anybody help?

In der bisherigen Konfiguration TB 31.x, Lightning 3.1.1 und Exchange EWS Provider 3.2.0~beta77 war es problemlos möglich, auf freigegebene Kalender eines Exchange-Servers 2007 zuzugreifen.
Ein automatisches Update des TB auf Version 38.2.0 zog das Lightning-Update auf Version 4.0.4 nach sich, was zur Folge hatte, daß der Zugriff auf die o.g. Kalender nicht mehr möglich war.
Zunächst wurde der Fehler in dem exchangecalendar-AddOn vermutet, weshalb alle verfügbaren, aktuelleren Versionen bis zur 3.4.0~beta7 getestet wurden. Leider ohne Erfolg.
Die Fehlermeldung lautet:
Fehler bei der Abfrage des Servers und des Postfachs:HTTP Client error 401: Unauthorized
URL:domainxy.de/EWS/Exchange.asmx
(Code: -19)
Ist dieses Problem bereits bekannt und kennt jemand eine Lösung?

**Comment by kapshel** [comment]
I have the same problem with calendar on Exchange 2010 Server.
Calendar from Exchange 2013 mailbox works fine.

**Comment by bavincen** [comment]
Hi fyi if you are facing unauthorized error. Please add your calendar/task again. 

Thanks

**Comment by pic2base** [comment]
Hi,

first I removed all calendars (Kalender - abbestellen), then I tried to 
add them and got the error.

Klaus

Am 27.08.2015 um 15:24 schrieb bavincen:
>
> Hi fyi if you are facing unauthorized error. Please add your 
> calendar/task again.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Ericsson/exchangecalendar/issues/324#issuecomment-135426935>.
>

-- 
Mit freundlichen Grüßen

i. Auftrag

K. Henneberg

*********************************
Stiftung Dome und Schlösser in Sachsen-Anhalt
Treuhänderin für die unselbständigen Stiftungen Moritzburg Halle(Saale) und Kloster Michaelstein

Klaus Henneberg
Referatsleiter IT, Innere Dienste, Sicherheit
Michaelstein 15
38889 Blankenburg (Harz)
  
Telefon   03944 - 90 30 20
Fax:      03944 - 90 30 30
Funk:     0151-122 722 45
E-Mail:   klaus.henneberg@dome-schloesser.de
Internet: http://www.dome-schloesser.de
           http://www.kloster-michaelstein.de
*********************************
Diese e-Mail-Nachricht ist vertraulich und gegebenenfalls rechtlich vor Veröffentlichung
geschützt. Sofern Sie nicht der richtige Empfänger sind, benachrichtigen Sie uns bitte
per e-Mail oder Telefon und löschen die e-Mail sowie eventuell vorhandene angehängte Dokumente.
Es ist nicht gestattet, diese e-Mail und ihre Inhalte Dritten zugänglich zu machen, sofern
nicht anders angegeben oder vereinbart. Die Urheber- und Nutzungsrechte aller Inhalte dieser e-Mail
und der gegebenenfalls vorhandenen Anhänge verbleiben bei dem Absender, sofern nicht anders angegeben
oder vereinbart.
Hinweis:
Bezüglich der Berücksichtigung beider Geschlechter sind in den Formulierungen, sofern möglich,
Begriffe genutzt, die in einem Wort beide Geschlechter integrieren. Wenn eine doppelte Bezeichnung
notwendig gewesen wäre, wurde aus Gründen der Lesefreundlichkeit die männliche Form gewählt,
die aber den weiblichen Personenkreis mit einschließt.

**Comment by bavincen** [comment]
If you are using email Id as username should be entered in the formate of email..

**Comment by kapshel** [comment]
I change for Exchange 2010 ssl cert with sha-256 and problem was resolved

**Comment by watermark** [comment]
I have the same problem.  Everything worked fine before upgrading TB and Lighting.  Now I'm running TB 38.2, Lighting 4.0.2, and exchangecalendar 3.4.0~beta7.  Connecting to Exchange 2010.  It gives the error "Error during checking of server and mailbox: HTTP Client error 401: Unauthorized URL: https://webmail.myDomain.com/ews/exchange.asmx (Code: -19)".  Using my email address as the username produces the same error.  If I go directly to the "https://webmail.myDomain.com/ews/exchange.asmx" in a browser, I'm able to login and see the wsdl.  The cert being used on the Exchange server is a sha-2 cert, so not sure what kapshel is suggesting.

**Comment by bavincen** [comment]
@watermark  if your username same as email, otherwise you have to login using username and domain

**Comment by watermark** [comment]
@bavincen I've tried using both my email and the username/domain setup, both with the same result.  This was working with the older TB/Lightning, after upgrading my exchange calendars showed as offline.  I removed the calendars and tried to re-add and now it produces the authentication error.

**Comment by bavincen** [comment]
please post the log

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon
this helps?

before install
can you check this config value network.auth.force-generic-ntlm-v1

**Comment by watermark** [comment]
@bavincen That config value was set to false.  Changing it to true fixed the issue.  I didn't manually change it to "false".

**Comment by jconroy77** [comment]
Just dropping by to say that I ran into the same issue with using 3.4.0-Beta7 when upgrading to Thunderbird 38.2.0 with Lightning 4.0.2.

Setting the config value recommended above by @bavincen also worked for me:
**network.auth.force-generic-ntlm-v1 = true**

No other changes were required.

**Comment by bavincen** [comment]
If you are having similar issues also check #306

**Comment by konturger** [comment]
Fallowing FIX worked for me, and seems to be a final simple fix:
set network.auth.force-generic-ntlm-v1 from FALSE to TRUE (under Prefernces | Advanced | General | Config Editor) - Be very careful within the config editor!

![fix thunderbirdv38lightning402_exchange_calender](https://cloud.githubusercontent.com/assets/10417066/9830933/92476606-5942-11e5-87f0-d815036f64b7.png)
