### ISSUE TITLE
Thunderbird hangs with high constant CPU load (25%) and increasing memory usage (1GB+)

### ISSUE THREAD

**Issue by ermingol** [Ericsson/exchangecalendar#326]
When I try to dismiss a specific meeting invitation Thunderbird becomes unresponsive and starts consuming 23-26% of constant CPU and memory consumption goes immediately up from about 300MB to 1.0GB and then continue to raise until forcefully killed.

Thunderbird 38.2.0, Lightning 4.0.2, and Exchange EWS Provider 3.4.0~b7

I upgraded to b7 earlier today and it have worked flawlessly until a reminder for this specific meeting pop:ed up. Dismissals of other meetings have worked flawlessly until this one...

**Comment by josefbacik** [comment]
I'm getting the same problem, I was on 3.2.2 and went to b7 and suddenly nothing is responsive.

**Comment by bavincen** [comment]
please clear cache manually

**Comment by msbdun** [comment]
I am also experiencing this with TB 38.2.0, Lightning 4.0.2 and EWS 3.4.0 b5.

I have cleared the cache (and recreated the cache folder). When TB starts there are about 40 queue jobs. This reduces to (currently) 3 and then TB freezes. Before clearing the cache a repeating event would appear in the dismiss dialog and if I attempted to dismiss this one the freeze would also kick in. After clearing the cache I don't get this dialog but still get the freeze.

I have also progressively disabled the calendar connectors I have (EWS and Google). With just Lightning left I still get the queued items processing and consequently the dreaded freeze.

So is this a EWS issue or a Lightning issue?

**Comment by bavincen** [comment]
@josefbacik im using same as urs no prob..
we need more detail

**Comment by ermingol** [comment]
And today I decided to
      turn on logging before trying to dismiss the meeting invitation
      that causes Thunderbird to hang. I got a log file, but Thunderbird
      actually managed to dismiss the meeting! I have not cleared any
      cache nor changed any other settings or restarted TB since
      yesterday (it has been running over the night)...
      
      So, was it turning on the log file that in turn changed timing
      that caused it to actually work? Or has something changed on the
      server end (time-outs etc)?
      
      The log file is massive, 2985323 bytes and it contains sensitive
      information in the sense that there are lots and lots of email
      addresses... And this is just for dismissing this instance of a
      repeating meeting. I can share the file (if you are interested)
      provided it is not posted in public (log level has been set to "2"
      for almost everything).
    
    On 2015-08-27 18:50, bavincen wrote:
    
    
      
      please clear cache manually
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by msbdun** [comment]
I have been able to clear the cache manually. I had to do this by starting TB with all add-ons disabled and then renaming the cache folder. This temporarily fixed the problem in that I was able to get rid of an old notification. I could not turn off add-ons due to issue below.

Since then I have noticed some things by looking at the task manager on Windows. If I have EWS enabled, when I exit TB the application drops off the active list but (Win 10) puts in a TB process. The CPU load jumps up to round 50%. I note that there still seems to be some network activity and the CPU value does change a fraction. It seems that on quitting EWS is wanting to do some work but is not able to do so. In this state both Win 7 and 10 do close the TB window but dont end the process. I have to kill the process to restart TB. 

This morning I had a repeating event come up on schedule. I attempted to dismiss the reminder and now I'm in the frozen queue jobs situation.

I hope this info helps.

**Comment by ermingol** [comment]
I have now been running TB for 6 days (without restarting it) and have not experienced the reported problem again. I have not the faintest clue regarding what triggered it. :(

**Comment by CesarPagan** [comment]
I had the same problem with TB (25% CPU load and almost 4GB memory). I fixed this problem deleting the file "global-messages-db.sqlite" located in the C:\Users\[YourUsername]\AppData\Roaming\Thunderbird\Profiles\*.default directory. It will rebuilding the Global Database. See https://support.mozilla.org/en-US/kb/rebuilding-global-database for more info.

**Comment by torinaki** [comment]
Same behavior in #301.

**Comment by torinaki** [comment]
@CesarPagan unfortunatly fix do not work for me

**Comment by CesarPagan** [comment]
Try the follow:
1. Delete the file ""global-messages-db.sqlite" located in the C:\Users[YourUsername]\AppData\Roaming\Thunderbird\Profiles*.default directory".
2. Archive (message menu) part of their e-mails (for example, the oldest ones).
3. Then compact the folders (file menu).
4. Delete the file ""global-messages-db.sqlite" again.

**Comment by bavincen** [comment]
Are you using any other addon..

**Comment by CesarPagan** [comment]
The version is TB 38.2.0;
I am using Lightning 4.0.2 only.

Em 11/09/2015 01:55, bavincen escreveu:

**Comment by torinaki** [comment]
I'm using TB 38.2.0, Lightning 4.0.2, Exchange EWS Provider 3.4.0-rc1
Without Exchange EWS Provider problem does not appear.

**Comment by bavincen** [comment]
@torinaki, my Thunderbird using 150 MB Constantly

**Comment by torinaki** [comment]
@bavincen I found the real cause. It is not releated to EWS extension. Seems like memory leak is in Lightning extension:
https://bugzilla.mozilla.org/show_bug.cgi?id=753343
There are [a lot](https://bugzilla.mozilla.org/buglist.cgi?type1-0-0=substring;keywords=perf;keywords_type=allwords;list_id=3053868;field0-0-0=short_desc;type0-0-0=anywordssubstr;longdesc_type=allwordssubstr;type0-0-1=substring;field0-0-1=keywords;type1-0-1=allwordssubstr;resolution=---;classification=Client%20Software;classification=Components;query_format=advanced;longdesc=memory;field1-0-0=short_desc;product=Calendar;field1-0-1=short_desc) of such problems in Lightning.

After I have disabled my two iCal calendars(from iCloud and Asana) problem disappear.
![image](https://cloud.githubusercontent.com/assets/1269372/10163947/fa45c570-66be-11e5-87a2-f1cdb1479d52.png)

**Comment by bavincen** [comment]
Fine. Closing now

**Comment by Kisaure** [comment]
the delete "global-messages-db.sqlite" file worked for me, thanks to CesarPagan

**Comment by tggagne** [comment]
I'm having a similar problem with my mac.  I have LookOut 1.2.13 and Mail Redirect 0.8.7 addons to Thunderbird 38.5.1.  This only happens with invitations.  

When I attempt to read the invitation I get the spinner--endlessly.

**Comment by DougHughes** [comment]
I hit the same bug. It's definitely a problem with lightning. After adding a new google calendar in, thunderbird went insane. Goes to 30%+ of cpu (full core), and uses up memory until the machine runs out. I have about 1 minute to perform any action before it becomes completely unusable. Luckily, I was able to disable lightning within that time and so now I can get email. But, I really like the Lightning extension so was hoping somebody may have been working on this. I have Lightning 4.7.2 installed and this is new behavior. Removing "Global-messages-db.sqlite" does not solve the problem, but disabling Lightning does. I don't want that to be a long-term problem, though.

**Comment by scharf** [comment]
I had this bug, and it turns out that I had a `dead` google calendar in lightening. Removing this calendar reduced the CPU load form 25% to 3-5%
