### ISSUE TITLE
Exchange Tasks not available/ accessible from 3.4.0~beta7

### ISSUE THREAD

**Issue by markgbeckett** [Ericsson/exchangecalendar#327]
Dear Developers,

I have just discovered this add-on for Thunderbird, and have downloaded and installed the current beta version (3.4.0~beta7). However, while Calendar events are accessible as one would expect, I am unable to either view existing Task entries or create any new ones. When I switch to the Tasks pane, my Exchange account is visible (in the "Calendars List" view, which is usually on left-hand side of window) and can be selected. However, no tasks from my account are visible and the 'New Task' button is greyed out and can't be selected.

Keep up the good work,
George

**Comment by bavincen** [comment]
Please Create Task calendar..
