### ISSUE TITLE
Update on old problem with growing list of queued jobs

### ISSUE THREAD

**Issue by horsfielda** [Ericsson/exchangecalendar#328]
Having had trouble with the number of queued jobs growing without limit in the past, I am now using the exchange add-on (3.4.0~beta7) with only very occasional difficulties. It has been consistently stable for about a week now. The one time the number of queued jobs started to grow, I closed thunderbird and restarted, and all was well again.
The thing that has changed is the number of imap folders I have subscribed to on the exchange server. I now subscribe to only 8 folders, whereas I previously was subscribed to nearly 30, about 12 of which are large.

**Comment by bavincen** [comment]
this could be some local issue

**Comment by horsfielda** [comment]
Quite possibly -- the imap view of the sent folder is currently not correct. It shows many more emails than should be there. This is not a thunderbird problem, as alpine shows the same.
Subscribing to all folders, but not keeping a local cache with their contents, also seems to be stable. So the queuing seems to be related to synchronising multiple large folders to local cache.

**Comment by bavincen** [comment]
We are synchronized multiple folders

**Comment by horsfielda** [comment]
I have not tested this yet, but it may be just that I need to allow Thunderbird to support more connections to the exchange server. I had it set at 5 in the account settings for email. Does this seem possible?
