### ISSUE TITLE
Authenfication fails after updating to TB 38.2.0 and EWS Provider 3.4.0~7

### ISSUE THREAD

**Issue by monecke** [Ericsson/exchangecalendar#329]
Hi,

i update my Thunderbird to 38.2.0 and EWS Provider 3.4.0~7 on my Linux Machine. 
No i can't access my worklng exchange calendars anymore. EWS always asking me for a new password. 
Any hints?

I tried to clear the password manager. But this has no effect.

Above a part of the /tmp/exchangecalendar.log:
1st-setup:2015-8-3 7:44:5.871:mivExchangeAuthPrompt2: asyncPromptAuth: level=2 (_asyncPromptAuth in mivExchangeAuthPrompt2.js:448)
1st-setup:2015-8-3 7:44:5.871:mivExchangeAuthPrompt2: asyncPromptAuth: channel.status=0 (_asyncPromptAuth in mivExchangeAuthPrompt2.js:449)
1st-setup:2015-8-3 7:44:5.871:mivExchangeAuthPrompt2: asyncPromptAuth: channel.responseStatus=401 (_asyncPromptAuth in mivExchangeAuthPrompt2.js:451)
1st-setup:2015-8-3 7:44:5.871:mivExchangeAuthPrompt2: asyncPromptAuth: channel.responseStatusText=Unaumail2ized (_asyncPromptAuth in mivExchangeAuthPrompt2.js:452)
1st-setup:2015-8-3 7:44:5.872:mivExchangeAuthPrompt2: asyncPromptAuth: authInfo.authenticationScheme=ntlm (_asyncPromptAuth in mivExchangeAuthPrompt2.js:454)
1st-setup:2015-8-3 7:44:5.872:mivExchangeAuthPrompt2: asyncPromptAuth: authInfo.realm= (_asyncPromptAuth in mivExchangeAuthPrompt2.js:455)
1st-setup:2015-8-3 7:44:5.872:mivExchangeAuthPrompt2: asyncPromptAuth: authInfo.username= (_asyncPromptAuth in mivExchangeAuthPrompt2.js:456)
1st-setup:2015-8-3 7:44:5.872:mivExchangeAuthPrompt2: asyncPromptAuth: authInfo.password=************ (_asyncPromptAuth in mivExchangeAuthPrompt2.js:462)
1st-setup:2015-8-3 7:44:5.872:mivExchangeAuthPrompt2: asyncPromptAuth: authInfo.domain= (_asyncPromptAuth in mivExchangeAuthPrompt2.js:464)
1st-setup:2015-8-3 7:44:5.873:mivExchangeAuthPrompt2: asyncPromptAuth: aChannel.URL=https://mail2/ews/exchange.asmx, username=my-domain-b\my-user-name, password=******** (_asyncPromptAuth in mivExchangeAuthPrompt2.js:471)
1st-setup:2015-8-3 7:44:5.873:mivExchangeAuthPrompt2: asyncPromptAuth: authInfo.flags & AUTH_HOST (_asyncPromptAuth in mivExchangeAuthPrompt2.js:485)
1st-setup:2015-8-3 7:44:5.873:mivExchangeAuthPrompt2: asyncPromptAuth: authInfo.flags & NEED_DOMAIN (_asyncPromptAuth in mivExchangeAuthPrompt2.js:487)
1st-setup:2015-8-3 7:44:5.874:mivExchangeAuthPrompt2: asyncPromptAuth: NO Aumail2ization in request header!? (_asyncPromptAuth in mivExchangeAuthPrompt2.js:505)
1st-setup:2015-8-3 7:44:5.874:mivExchangeAuthPrompt2: asyncPromptAuth: Added request to queue[https://mail2/ews/exchange.asmx]. There are now '1' request in queue. (_asyncPromptAuth in mivExchangeAuthPrompt2.js:516)
1st-setup:2015-8-3 7:44:5.886:mivExchangeAuthProm/tmp/exchangecalendar.logpt2: asyncPromptAuthNotifyCallback: Removed request from queue[https://mail2/ews/exchange.asmx]. There are now '0' requests in queue left. (_asyncPromptAuthNotifyCallback in mivExchangeAuthPrompt2.js:282)
1st-setup:2015-8-3 7:44:5.886:mivExchangeAuthPrompt2: asyncPromptAuthNotifyCallback: Trying to detect username. (_asyncPromptAuthNotifyCallback in mivExchangeAuthPrompt2.js:306)
1st-setup:2015-8-3 7:44:5.887:mivExchangeAuthPrompt2: asyncPromptAuthNotifyCallback: username=my-domain-b\my-user-name (_asyncPromptAuthNotifyCallback in mivExchangeAuthPrompt2.js:319)
1st-setup:2015-8-3 7:44:5.887:mivExchangeAuthPrompt2: asyncPromptAuthNotifyCallback: WWW-Authenticate:Negotiate (_asyncPromptAuthNotifyCallback in mivExchangeAuthPrompt2.js:328)
1st-setup:2015-8-3 7:44:5.887:mivExchangeAuthPrompt2: asyncPromptAuthNotifyCallback: WWW-Authenticate:NTLM (_asyncPromptAuthNotifyCallback in mivExchangeAuthPrompt2.js:328)
1st-setup:2015-8-3 7:44:5.887:mivExchangeAuthPrompt2: getPassword: A realm was specified:Exchange Web Service (_getPassword in mivExchangeAuthPrompt2.js:122)
1st-setup:2015-8-3 7:44:5.888:mivExchangeAuthPrompt2: getPassword: There is no password in the passwordCache[my-domain-b\my-user-name|https://mail2/ews/exchange.asmx|Exchange Web Service] (_getPassword in mivExchangeAuthPrompt2.js:140)
1st-setup:2015-8-3 7:44:5.888:mivExchangeAuthPrompt2: getPassword: password(1)=******** (_getPassword in mivExchangeAuthPrompt2.js:146)
1st-setup:2015-8-3 7:44:5.888:mivExchangeAuthPrompt2: getPassword: There is no password in the cache. Going to see if there is one in the passwordManager. (_getPassword in mivExchangeAuthPrompt2.js:151)
1st-setup:2015-8-3 7:44:5.888:mivExchangeAuthPrompt2: passwordManagerGet: username=my-domain-b\my-user-name, aURL=https://mail2/ews/exchange.asmx, aRealm=Exchange Web Service (_passwordManagerGet in mivExchangeAuthPrompt2.js:621)
1st-setup:2015-8-3 7:44:5.889:mivExchangeAuthPrompt2: getPassword: There is no password stored in the passwordManager. (_getPassword in mivExchangeAuthPrompt2.js:159)
1st-setup:2015-8-3 7:44:5.889:mivExchangeAuthPrompt2: getPassword: password(2)=******** (_getPassword in mivExchangeAuthPrompt2.js:166)
1st-setup:2015-8-3 7:44:5.889:mivExchangeAuthPrompt2: getPassword: Going to ask user to provide a new password. (_getPassword in mivExchangeAuthPrompt2.js:216)

**Comment by condutor** [comment]
Same issue here. The password prompt keeps popping up. Tried downgrading to v3.3.1, the version I was using before, but the problem still occurs. Maybe something changed in Thunderbird 38.2.0?

**Comment by jjmr** [comment]
I have a similar problem. In my case, the error is:

Fecha y hora: 02/09/15 12:31:39
Error: no se encuentra elemento
Archivo de origen: https://juanjose%2Emartinrodriguez%40mydomain%2Ecom@outlook.office365.com/EWS/Exchange.asmx
Línea: 1 

Is it the same issue? Creating a new calendar is imposible too.

**Comment by theLogicJB** [comment]
I also have this problem.
After Thunderbird upgraded to 38.2.0 I had to upgrade Lightning to 4.0.2 but Exchange EWS Provider 3.3.2 was not working.
I then manually installed Exchange EWS Provider 3.4.0~beta7 from this github page.
Now I get the reappearing PW prompt even if I enter the correct password.

**Comment by webdevsHub** [comment]
same here: after upgrade (Thunderbird 38.2.0, Lightning 4.0.2) authentication fails (recurring PW prompt). Had to disable version 3.4.0~beta7.

I can provide logs or something if you tell me how.

**Comment by ajoscha** [comment]
same problem here: after upgrade (Thunderbird 38.2.0, Lightning 4.0.2), first the authentication fails (recurring PW prompt), then at one point it stopped, but now the calender has no entry, but there are still entries, when I am looking at the Outlook Web App (OWA). Creating a new calender is also impossible, I then get the error, which is described in Issue  #325.

**Comment by bavincen** [comment]
#306 #324

**Comment by monecke** [comment]
Setting  the config value ```network.auth.force-generic-ntlm-v1 = true``` recommended by @bavincen in #324 fix it for me. Thanks.
