### ISSUE TITLE
Tag syncing has vanished in beta7 or 3.4.0-RC1

### ISSUE THREAD

**Issue by robertbelgrave** [Ericsson/exchangecalendar#332]
Since updating from Beta4 -> Beta7 and now to 3.4.0-rc1, Tag syncing seems to have vanished.

There is no longer an option to 'Sync Tags' in the drop down tag menu, and it's not happening automatically either.

Is this a known issue or something I should investigate further my end? Happy to submit logs anad versions etc if it's helpful.

TIA

**Comment by bavincen** [comment]
Please enable it in email settings many users doesn't want it by default 

Sent from my Sprint phone.

----- Reply message -----

**Comment by robertbelgrave** [comment]
Appreciate the swing response @bavincen, would you mind giving me a point in the right direction?

Do you mean this dialogue box: ?
![image](https://cloud.githubusercontent.com/assets/2157562/9689182/32b18dbe-532c-11e5-829c-2a325572939f.png)

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/EWS-Mail-Settings

this will help you

**Comment by robertbelgrave** [comment]
I had already set this option before raising the issue and it seems I'm still having problems. It was working well in beta4 prior to the removal of the button in the drop down menu.

What can I provide to help debug this? I've set logging up and had a read through it but there's nothing obvious which stands out. Please let me know what I can do to help.

**Comment by bavincen** [comment]
Can you filter log "ewsTagger" .. post that please.

**Comment by robertbelgrave** [comment]
So after considerable investigation and log digging, I decided to try a clean install on a different PC.

Fresh Thunderbird, Lightning and EWS against the same account on the same Exchange server and everything works perfectly. Also the 'Sync EWS Tags' button is visible again.

Can you give me a steer on totally wiping my EWS config on the impacted machine (my laptop) to see if that helps resolve this for me?

Thanks again for your help with this.
