### ISSUE TITLE
I cannot add a new calendar.

### ISSUE THREAD

**Issue by serbring** [Ericsson/exchangecalendar#338]
I have just followed these instructions to add a new calendar:

https://github.com/Ericsson/exchangecalendar/wiki/How-to-Add-Your-Calendar-to-Thunderbird

Unfortunately I'm not able to add it because after the autocheck I get this message: 

Error during checking of server and mailbox: HTTP Client error 400: Bad request
URL:https://mail.unibo.it/EWS/Exchange.asmx
Cannot find the appropriate SOAP header or body.

How can I solve this error?

Thanks

**Comment by lameventanas** [comment]
Some problem here, the message I get is:
Error during checking of server and mailbox: Error during waiting for data of hostname '<server>'. (STATUS_WAITING_FOR) (Code: -16)

**Comment by bavincen** [comment]
Hi yes please enter correct username. also check if your server supporting auto discovery or not..
