### ISSUE TITLE
Thunderbird crashing with 3.4.0-RC1

### ISSUE THREAD

**Issue by gorpong** [Ericsson/exchangecalendar#341]
My TB has been crashing pretty consistently since I installed the 3.4.0-rc1 version of this plugin yesterday.  I deactivated the SoGo plug-in and it continued to crash.  I disabled the EWS calendar entries that I created and it hasn't crashed since.  By crash, I mean it pops up the "Oops, it died, do you want us to send a crash report to Mozilla."

It has crashed when I'm doing nothing with it (e.g., in another application or doing something else), when creating a new message, when reading a message, etc.  There doesn't seem to be any specific thing that triggers it.  I'm not convinced that it's THIS add-on, but given that it didn't crash before installing the plug-in last night; has crashed three times within 10 minutes of relaunching until I deactivated the EWS-based calendars (one personal calendar, one personal/Tasks version, one public folders shared calendar) and has been running for nearly an hour without a crash since, it's highly suspect, but it may just be a bad interaction with another add-on or something.

TB version is 38.2.0, OS is Windows 7 SP1 64-bit, using DavMail to access Exchange for one mailbox, Google accounts for three other Gmail accounts (one Gmail, two Google Apps).

What sort of logs can I gather for you that might help isolate it and how might I gather them?

I have the following add-ons in Thunderbird, so if you know of a bad interaction with one of them, please let me know:

![image](https://cloud.githubusercontent.com/assets/9598255/10024278/1cb04336-611c-11e5-8fd6-cc3e7b536e91.png)

Thanks!

**Comment by gorpong** [comment]
Okay, never mind.  It's got to be something else.  It just crashed again in the same way, this time when I was sending a message.

If there are no active EWS calendars, does the add-on *do* anything?  If not, then it's definitely not the add-on (although it does seem to exacerbate things so whatever it's doing certainly horks Thunderbird off). :-)

Thanks!

**Comment by gorpong** [comment]
Okay, for the last 4 hours after actually disabling the add-on (not just deactivating the calendars) I haven't had a crash.  I'll go in and re-enable the add-on without activating the calendars and see what happens.

**Comment by gorpong** [comment]
When I re-enabled it, it ended up turning all the calendars back on.  I've turned them off again and will stop/restart TB and see where we go.

**Comment by gorpong** [comment]
So far no crashes!  This may be a red herring.  If so, I'll close it with my apologies for wasting your time.  I had another add-on, the Inverse SOGO, which I actually removed because it was causing problems with the free-busy information in lightning, so it's very possible it was getting in the way of this add-on as well, even though it wasn't running.

I'll re-activate the calendars and see what happens.

**Comment by bavincen** [comment]
Master password is asked once.. second time it should be your calendar password or something else.  Try saving calendar password for now

**Comment by gorpong** [comment]
Yes, you're exactly right about the master password being asked once, it's once per destination and/or thing.  I have one being asked for access to my localhost IMAP account (using DavMail to access Exchange), once for accessing my Gmail account and calendar and then the third time for the Exchange EWS calendar.  This is the expected behavior and all is well with the world on that regard.

I also want to close this issue because after completely removing the Inverse SOGO and re-activating everything with this add-on, things are more stable.  So, even though the Inverse SOGO thing was deactivated, it must have been getting in the way of this add-on (as well as any others on the calendar) and causing enough instability that TB was regularly crashing.

Sorry for wasting your time.
