### ISSUE TITLE
Cannot add new calendar

### ISSUE THREAD

**Issue by jjmr** [Ericsson/exchangecalendar#350]
When I try to add a new calendar I always receive a 503 error and the log shows the following error:

```
Cannot find the element
Origin file: https://outlook.office365.com/EWS/Exchange.asmx
Line: 1
``` 

This url exists and if I browse it in a broser I can see a web with the text: "You have created a service" and more information about haow to use this service with a client application.
It also happens if I introduce my user successfully.

My thunderbird version is 38.3.0, lightning version is 4.0.2.1 and Exchange EWS provider 3.4.0-rc2

Any suggestion?

**Comment by bavincen** [comment]
Please use latest and reopen if not working

**Comment by jjmr** [comment]
Same error with version 3.4.0 and 3.5.0-beta1

**Comment by bavincen** [comment]
are you using correct user name, domain.
If you use email address as user name,  also try without domain.

**Comment by jjmr** [comment]
Even if I don't introduce the username or the domain, the response is
always a 503 instead of a 400/404. If I can help sending more log traces,
please, tell me how can i debug the code or get more data from logs.

2015-10-27 8:31 GMT+01:00 bavincen <notifications@github.com>:
