### ISSUE TITLE
Subscribing to other people's calendar

### ISSUE THREAD

**Issue by nklmilojevic** [Ericsson/exchangecalendar#351]
Hi, 

I don't know if I missed something - but how do I subscribe to other people's calendars, or a shared calendar? It isn't in the root folder of the folder Calendar.

Thanks,

N.

**Comment by bavincen** [comment]
I think option for adding shared calendar is available when you right click on the calendar, its called delegate calendar

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/Delegating-Calendar

Hope this will help
