### ISSUE TITLE
Can't create new calendar event on the latest build

### ISSUE THREAD

**Issue by LunaticoCR** [Ericsson/exchangecalendar#359]
Sing I upgraded to 3.4.0rc2 and now on the released 3.4.0 I can't create new calendar events. I just get a MODIFICATION_FAILED error.
![image](https://cloud.githubusercontent.com/assets/2124383/10391749/ecd9c03c-6e78-11e5-835f-23c0f5cefeba.png)

Please help! Let me know if there's anything I can do to help.

**Comment by bavincen** [comment]
hi,
 your calendar read-only..s
please ceck if internet connected..

please check lightning version should be less than 4.0.1

**Comment by LunaticoCR** [comment]
Thanks for your quick response. Lightning was upgraded to 4.0.3.1 and I didn't realize. I installed 4.0.1 and now it seems to be working.
Is 4.0.1 ok or would you recommend 4.0.0.1?
