### ISSUE TITLE
Updates get saved. Shown and then vanish :((

### ISSUE THREAD

**Issue by Tormen** [Ericsson/exchangecalendar#360]
Hi,

It's driving me crazy, especially as I never know if a change to an appointment got REALLY saved or will be lost and VANISH :((

My case : office365 hosted domain of my company. Using thunderbird 38.2.0 with this plugin v3.4.0 under linux (OpenSuse 13.2) and/or Chromium with office365 webaccess.

The problem: Not sure why / when exactly (but actually quite OFTEN now) : When editing an event that I created by pulling a timeslot in the calendar (lets say point your mouse to 10am and click + pull mouse to 12pm). Then double click to edit event. Invite people, change location, change subject, change description. Save.
Double click: See event but READ-ONLY in the way you want it.
Wait, Maybe choose "Synchronize Calendar" and BANG. Event will look like before and all your changes are GONE WITH THE WIND.

I think I saw a logging functionality. I will try to reproduce with logging enabled.
Otherwise not sure what you need ?

Tormen

**Comment by bavincen** [comment]
Ok what's the lightning version please

**Comment by Tormen** [comment]
Yes... just noticed that too ;) Lightning 4.0.2.1

**Comment by bavincen** [comment]
We have tested and it worked fine till 4.0.0.1

**Comment by Tormen** [comment]
I will downgrade and see.

**Comment by Tormen** [comment]
(can you then maybe bundle your release with the lightning version ?)

**Comment by bavincen** [comment]
We are trying our best.

**Comment by Tormen** [comment]
I know and don't get me wrong with this question. I LOVE the fact that you are enhancing the EWS integration addon !!! And I will do my best to help you in potentially helping me fixing this.

**Comment by bavincen** [comment]
Thanks for your support . We are making it compatible till latest lightning
that may be v4.0.2 something. We all know Mozilla has enabled code security
in LATEST TB and even lightning team is working on it

**Comment by Tormen** [comment]
I downgraded lightning unsubscribed the calendar, re-added it, but when changing weeks, the calendar does not get updated... and I can't recreate a new thunderbird profile at this point. So I'll go back to lightning 4.2.0.1, will avoid updates for lightning and will wait for an update of the EWS supporting 4.2.0.1.

**Comment by Tormen** [comment]
Back to 4.2.0.1 I have the same problem now.... I guess lightning did not like the downgrade :((
So my "week" calendar view is now effectively broken. Funnily : Day view, multiweek view works.
But in week view I can't display any other week then the current one. No matter what I try ;)
DOWNSIDE : I finally MUST redo my profile :((
UPSIDE : I will do it using lightning 4.0.0.1 :))

**Comment by bavincen** [comment]
Clearing cache in res settings will help?

**Comment by bavincen** [comment]
In ews settings

**Comment by Tormen** [comment]
Ah. That is good to know ( I always right-clicked on calendar and chose "Clear Calendar Cache" at this point, but not within the EWS settings.

It does not and I forgot to mention that even with a LOCAL calendar, I can't switch weeks, ... it is really the lightning itself that does not SHOW the week(s) ... not a problem of the weeks "content" ;)

**Comment by Tormen** [comment]
OK. I cleant up my addons and cleared the cache. Now it is working with lightning 4.0.0.1.

I'll come back if the problem reoccurs. For now things seem snappy and fine :)
