### ISSUE TITLE
Inviting attendees to meetings causes calendar to go read-only

### ISSUE THREAD

**Issue by andrewperrin** [Ericsson/exchangecalendar#361]
When using the "invite attendees" function on an event (new or edited), when I close the event, the calendar shows the lock icon and is read-only. Usually the event does not get added either, although rarely the event is added even though the calendar gets locked. I have a logfile and can send it if useful. Thanks for any ideas.

Using Thunderbird 38.3.0 under Debian linux, Lightning 4.0.3.1, EWS Provider 3.4.0-rc2.

**Comment by bavincen** [comment]
Can you try update to ews 3.4. Could be temporarily issuing

**Comment by advancingu** [comment]
This sounds like the same issue as #170

**Comment by bavincen** [comment]
How to reproduce please??

**Comment by andrewperrin** [comment]
I will try upgrading and see if it comes back.

**Comment by laerm** [comment]
Same problem here:

TBird 38.3.0
Lightning 4.0.3.1
EWS Provider 3.4.0
Ubuntu 14.04 LTS

Will gladly provide more info if needed.

**Comment by bavincen** [comment]
Please read our announcement we r not supporting lightning greater than
4.0.0.1

**Comment by bavincen** [comment]
Please use Lightning 4.0.0.1

**Comment by laerm** [comment]
I can confirm that reverting to Lightning 4.0.0.1 resolves the issue.

**Comment by logological** [comment]
@bavincen wrote:

> Please read our announcement we r not supporting lightning greater than 4.0.0.1

Is this announcement still valid?  Because [your `README.md` file instructs people to install the latest version of Lightning (currently 4.7.2)](https://github.com/Ericsson/exchangecalendar/blob/master/README.md#install-lightning).

If you are now supporting the latest version of Lightning, please reopen this bug.  I seem to be able to reliably reproduce it with Lightning 4.7.2.

If you don't support the latest version of Lightning, please update your `README.md` file so that it indicates what version(s) are supported.

**Comment by bavincen** [comment]
I wrote that comment at that time when lightning was not supported by our addon.
Please use Lightning lastest with 3.8.0 stable . if any issue post there.
regards.///

**Comment by logological** [comment]
Where is "there"?  And yes, I can reproduce the problem with 3.8.0 stable and Lightning 4.7.2.

**Comment by bavincen** [comment]
Are you using latest lightning with exchange calendar 3.8 stable

**Comment by bavincen** [comment]
By mistake "there"

**Comment by bavincen** [comment]
I I'll try with latest code . Will update

**Comment by andrewperrin** [comment]
FWIW this is NOT happening in my current setup (Thunderbird 45.2.0, 
Lightning 4.7.2, EWS provider 3.7.0).

**Comment by logological** [comment]
Yes, I am using Lightning 4.7.2, Exchange EWS Provider 3.8.0 (the final release, not a beta), and Thunderbird 45.2.

**Comment by bavincen** [comment]
unable to reproduce
works fine 
TB: 45.2
Lightning:4.7.4 stable
ews:3.8 stable

I have one office365 task and office365 calendar additionally  calendar connecting to hosted exchange

**Comment by logological** [comment]
Is there any logging/debugging information I could provide which would help determine the cause of the problem?

**Comment by bavincen** [comment]
Yes. Please check our wiki for enabling log.

**Comment by B-Digital** [comment]
Still having this issue.

Ubuntu 16.04 LTS
Thunderbird 45.4.0
Lightning 4.7.4
Exchange EWS Provider 3.8

I know this is closed but I don't believe it was fixed. I set the logging to be Extended information and looked through them with no indication there was an issue.
