### ISSUE TITLE
Cannot assign a different background color to each message priority

### ISSUE THREAD

**Issue by nualtunkaya** [Ericsson/exchangecalendar#362]
Using Thunderbird 38.3.0 and EWS Provider addon v3.4.0 (and v3.3.2 as well), in the Options->Extras tab, it's impossible to assign Highest priority a color different than High priority. Selecting a color for one immediately changes the other to the same color. Lowest and Low priority color selections also behave like this.

Color picker buttons for Highest and High both modify the same preference "extensions.extras.HighestColor", whereas Lowest and Low both modify "extensions.extras.LowestColor". There are no separate preferences listed in about:config for High and Low priorities (e.g. "extensions.extras.HighColor" and "extensions.extras.LowColor", respectively).

**Comment by bavincen** [comment]
Ews would not set high and highest separate, either low or high.. the
reason color priority is that way.

**Comment by bavincen** [comment]
What I think is you wanted to use this feature for all mail accounts

**Comment by nualtunkaya** [comment]
I haven't used either Outlook or an Exchange account for some time now, so I don't remember how they behaved exactly, but Thunderbird (and I'm sure some other mail clients) allow you to set X-Priority between 1 and 5 (lowest, low, normal, high, highest). Since the EWS Provider add-on applies this coloring to all e-mails and not just Exchange related stuff, I assumed it should be possible to set separate colors, and thought there's a bug with the Options GUI. Otherwise, there would be no need for individual color picker buttons.
