### ISSUE TITLE
I cannot see other people availaibility when creating a meeting

### ISSUE THREAD

**Issue by Mappy-team-LBS** [Ericsson/exchangecalendar#363]
Hello,

I don't know if it is a bug, but I don't know any other way to get help.

When I create a meeting and invite some people, I cannot see their availability in the time table.
I don't think it should be linked to calendar delegation.

Thanks for help.

**Comment by bavincen** [comment]
Hi
Invite attendees shows busy/free times

**Comment by Mappy-team-LBS** [comment]
No, that doesn't show anything.

**Comment by bavincen** [comment]
How you configured your calendar. Which folder your calendar is mapped to
in ews settings.
Any alert saying communication error?

**Comment by Mappy-team-LBS** [comment]
When I right click on the calendar and select Exchange Properties (EWS), I left the checkbox unchecked.

Next, I have, for the first tab : 
- http://...exchange.asmx
me@mycompany.com
mylogin
MYCOMPANYDOMAIN
<empty>
Calendar folder
/

I didn't touched anything for the other tabs.

Thanks for help.

**Comment by brtptrs** [comment]
I'm having the same Problem with version 3.4.0.
Everything seems to work, except free-busy information is not showing.

**Comment by liddellj** [comment]
I'm seeing the same thing. When creating a new event - no availability information is shown, every attendee is shown as completely free. I even tried adding a dummy event for myself to see if that slot would show up as unavailable for subsequent events - but it did not.

Thunderbird 38.3.0.
Exchange EWS Provider 3.4.0.

**Comment by bavincen** [comment]
What's your lightning version. Should be 4.0.0.1 or lesser

**Comment by Mappy-team-LBS** [comment]
Thunderbird 38.3.0
Lightning 4.0.3.1
Exchange EWS Provider 3.4.0

So I have to downgrade Lightning ?
Should I uninstall Exchange EWS Provider before ?

**Comment by liddellj** [comment]
I downgraded Lightning to version 4.0.0.1 by downloading the specific version from https://addons.mozilla.org/en-GB/thunderbird/addon/lightning/versions/ (without doing anything to the Exchange EWS Provider). I can confirm that this resolved the issue for me.

@bavincen - Appreciate your help with this. I see that you've closed this issue and tagged it as invalid. Is there a specific issue tracking whatever is blocking support for Lightning > 4.0.0.1 that we can subscribe to?

**Comment by liddellj** [comment]
I downgraded Lightning to version 4.0.0.1 by downloading the specific version from https://addons.mozilla.org/en-GB/thunderbird/addon/lightning/versions/ (without doing anything to the Exchange EWS Provider). I can confirm that this resolved the issue for me.

@bavincen - Appreciate your help with this. I see that you've closed this issue and tagged it as invalid. Is there a specific issue tracking whatever is blocking support for Lightning > 4.0.0.1 that we can subscribe to?

**Comment by bavincen** [comment]
Hi @liddellj  As for now, it is invalid for us. We are working on support. Not released so..

FYI: We have tested lightning 4.0.2 which worked without any issue.. You may try and update us

**Comment by Mappy-team-LBS** [comment]
I confirm it does work with Lightning 4.0.2.
Thanks to both.

**Comment by brtptrs** [comment]
The problem is solved with v3.5.0-beta1
Thanks!
