### ISSUE TITLE
IMPORTANT: FOR THUNDERBIRD USERS 38.3

### ISSUE THREAD

**Issue by bavincen** [Ericsson/exchangecalendar#366]
38.3 Users, Please use
https://github.com/Ericsson/exchangecalendar/releases/tag/3.5.0-beta1

**Comment by evamindbench** [comment]
Why exactly?

**Comment by bavincen** [comment]
Have added in release note

**Comment by evamindbench** [comment]
I found this: 

Supports Latest Thunderbird(38.3) and latest Lightning(4.0.2.1 or greater)

NB The 3.4 version was working for me, only needed to sync calendars before saving a new meeting request.

**Comment by bavincen** [comment]
some users facing issue when creating event. or/and unable to see free/busy..

**Comment by naevtamarkus** [comment]
Where are the release notes? I checked in history_en and there are only versions until 3.3.1

**Comment by bavincen** [comment]
Added to release description :
https://github.com/Ericsson/exchangecalendar/releases/tag/3.5.0-beta1

**Comment by bavincen** [comment]
contribute by maintaining it please?

**Comment by naevtamarkus** [comment]
The only description I see is this:

"Supports Latest Thunderbird(38.3) and latest Lightning(4.0.2.1 or greater)"

Do you mean that?

**Comment by bavincen** [comment]
:)

Release Note:
Fix  lightning 4.0.2.1

**Comment by naevtamarkus** [comment]
PR submitted

**Comment by i3lack0ut** [comment]
Thank you very much. The calendar locking up when i try to set up a meeting seems to be fixed.

**Comment by bavincen** [comment]
@naevtamarkus i dont see any PR
can you also add 3.4 release note

**Comment by i3lack0ut** [comment]
I noticed that if a mark an event as "whole day" the event shows up on the day it is planned and on the consecutive day. Anyone else?

**Comment by bavincen** [comment]
@i3lack0ut is that event marked repitative?
can you post screenshot please?

**Comment by i3lack0ut** [comment]
No it's not marked as repetitive. I am sorry at the moment i am not able to reconstruct it. No idea why. As soon as it happens again i will post a screen shot. And to specify it doesn't show up twice in the calendar itself but in the "today pane" on the right side.
