### ISSUE TITLE
Issue with special characters in password ... again

### ISSUE THREAD

**Issue by jeka** [Ericsson/exchangecalendar#368]
Sorry guys but there is again a problem if the password contains special characters. Namely '$' or '%'
I don't know which one is exactly the problem but I had bad time whole morning again ....

short description of the problem: I could manage to subscribe to calendar, but somewhere down the line something goes wrong (there was some password exception in the log file) and the callendar was set in read only mode and nothing was synced (there was some info about free/busy only sync actually).  
v3.5.0-beta1 (but the problem manifested itself even in 3.4.0)
lightning 4.0.3.1
tb 38.3.0

**Comment by bavincen** [comment]
We will fix this.. an issue already opened. Please close this one

**Comment by jeka** [comment]
OK, closing.
Somehow I ding manage to find already opened similar issue. Which one is it btw?

**Comment by bavincen** [comment]
#220
