### ISSUE TITLE
Tasks not available

### ISSUE THREAD

**Issue by jbeukelman** [Ericsson/exchangecalendar#369]
Any action within tbird having to do with tasks are unavailable.  Options for new task are greyed out in the menu items.  The button on the upper right hand side of the main window works, but takes me to a task screen that will not show me any existing tasks or allow me to add any.

Calendar works great!

plugin: 3.5.0-beta 1
tbird 38.3
Lightning 4.0.3.1
Using office365

Any assistance would be greatly appreciated.  

Thanks!

**Comment by avoidik** [comment]
Same problem here with same specs, except Exchange 2010. I've successfully linked EWS account, calendar and tasks, but can't create new task - calendar dropdown list doesn't show up my Exchange account, but can create Event.

**Comment by avoidik** [comment]
I've analyzed some logs and can't find anything useful, but this:
```
1st-setup:2015-9-4 11:41:6.876:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({69150b77-b561-43a2-bfba-7301dd5a35d0})
...
1st-setup:2015-9-4 11:41:6.877:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({f6a0d1e5-369f-4abc-81ae-d370d36e4006})
...
1st-setup:2015-9-4 11:41:6.878:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
```

**Comment by bavincen** [comment]
Hi
Which exchange server is configured to use in your task/calenda?
Are you seeing any error?

**Comment by avoidik** [comment]
Exchange Server 2010 SP3
AdminDisplayVersion : Version 14.3 (Build 123.4)

WBR, Вячеслав

2015-10-24 11:19 GMT+03:00 bavincen <notifications@github.com>:

**Comment by horsfielda** [comment]
I am also unable to see the exchange task list at present. I am using EWS Exchange Provider 3.4.0~beta7. I am not sure what version of Exchange is being used.

I have now dropped davmail as this add on is more convenient and is now very stable provided I do not keep local copies of large numbers of emails.

**Comment by jbeukelman** [comment]
No error messages here either.  The buttons are just greyed out with no explanation.  :/

I am using ExQuilla for mail.  Are the two compatible?

**Comment by bavincen** [comment]
@jbeukelman Does disabling Exquilla solve the issue?

**Comment by jbeukelman** [comment]
Unfortunately it does not.  :(

**Comment by avoidik** [comment]
I've updated my Exchange 2010 SP3 to latest roll-up 11 and problem still persist. Problem definitely in Exchange Calendar.

**Comment by bavincen** [comment]
@avoidik I understand. Can you delete and create the exchange task account.

**Comment by bavincen** [comment]
@jbeukelman Did you try recreating task account. this could be from upgradation to latest lightning

**Comment by avoidik** [comment]
@bavincen Ok, you suggestion helped me to find out why this happens. If we've linked EWS calendar into Tasks folder, then we can create Tasks, but not Events. And vice versa, if we've linked EWS calendar into Events folder, then we can create Events, but not Tasks.

**Comment by bavincen** [comment]
For task,  select Task Folder.
For calendar,  select Calendar Folder.

**Comment by jbeukelman** [comment]
avoidik had it right.  You have to create two calendars.  One for tasks and one for calendar events.  Once I created a task calendar, everything worked fine.  

Thanks for the assist!

**Comment by erihe251** [comment]
Can confirm that the above workaround gives you access to tasks. Of course, would be nice to have only one calendar, but I'm happy. :) Thanks for a nice plugin!

**Comment by horsfielda** [comment]
Two calendars works for me also

**Comment by jerry1970** [comment]
Ah, two calendars, that was it, thanks!
