### ISSUE TITLE
Incorrect exhortationto MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl

### ISSUE THREAD

**Issue by magjac** [Ericsson/exchangecalendar#373]
In the log I'm exhorted to MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl, which I did, but got the reply:

"Hi Magnus,

I no longer maintain this add-on. Please see https://github.com/Ericsson/exchangecalendar for the follow up.

Regards,

Michel Verbraak."

Please change this printout.

The messages were:

1st-setup:2015-9-4 10:39:27.556: >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({69150b77-b561-43a2-bfba-7301dd5a35d0})
1st-setup:2015-9-4 10:39:27.558: >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({f6a0d1e5-369f-4abc-81ae-d370d36e4006})
1st-setup:2015-9-4 10:39:27.558: >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
...
1st-setup:2015-9-4 10:40:27.745: >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({69150b77-b561-43a2-bfba-7301dd5a35d0})
1st-setup:2015-9-4 10:40:27.746: >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({f6a0d1e5-369f-4abc-81ae-d370d36e4006})
1st-setup:2015-9-4 10:40:27.747: >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})

**Comment by bavincen** [comment]
Thanks! and sorry for inconvenience
