### ISSUE TITLE
Running and Queued Jobs never finish

### ISSUE THREAD

**Issue by gschoenberger** [Ericsson/exchangecalendar#377]
Hi!
I am currently trying to setup your thunderbird extension under Ubuntu.
Software stack:
* Thunderbird 38.3.0
* Lightning 4.0.3.1
* EWS Provider 3.5.0-beta1

I can set up the network calendar as expected, I can also choose a custom calendar I have created (from the / folder). But after finishing the setup the running and queued jobs never finish (so the calendar is not synced I assume).

In the thunderbird error console I get the following error:
> Error: TypeError: a.addParentNameSpaces is not a function
> Source File: resource://interfaces/xml2jxon/mivIxml2jxon.js
> Line: 364

I also have enabled the debug log but I do not know which information to provide, as there is a lot in it. At a first glance I could not find any error in the log, but:
1st-setup:2015-10-3 17:11:8.980:[Xtx-Home] We got '0' events and  '0'  tasks from memory cache. (_getItemsFromMemoryCache in mivExchangeCalendar.js:2714)
1st-setup:2015-10-3 17:11:8.981:[Xtx-Home] We have a listener so going to inform it.(2) (_getItemsFromMemoryCache in mivExchangeCalendar.js:2716)
1st-setup:2015-10-3 17:11:8.981:[Xtx-Home] setProperty. aName:currentStatus, aValue:0 (setProperty in mivExchangeCalendar.js:828)
1st-setup:2015-10-3 17:11:8.981:[Xtx-Home] No dateChanged. Not going to request items from server. (_getItems in mivExchangeCalendar.js:2567)
1st-setup:2015-10-3 17:12:8.979:[Xtx-Home] refresh (_refresh in mivExchangeCalendar.js:2849)
1st-setup:2015-10-3 17:12:8.980:[Xtx-Home] weAreSyncing. So no refresh. (_refresh in mivExchangeCalendar.js:2857)

Any suggestions how I can debug why jobs are not finishing? Do I have to enable a specific setting on the exchange side?

Would be nice if you could help me,
cheers Georg

**Comment by bavincen** [comment]
Hi Please post screenshot of your ews settings for the calendar..

TY

**Comment by fromscratch-xx** [comment]
Sure, here we go!
![screenshot_2015-11-12_17-25-33](https://cloud.githubusercontent.com/assets/1648307/11123985/e642716a-8962-11e5-8cf9-8cb9515ae930.png)
![screenshot_2015-11-12_17-27-15](https://cloud.githubusercontent.com/assets/1648307/11123990/e96d12aa-8962-11e5-8ec7-3311acd69a5c.png)

**Comment by bavincen** [comment]
why is that  path /Home?

**Comment by fromscratch-xx** [comment]
That was a custom calendar I had created, it's the same with the default one.
Can anyone confirm syncing is working for him with the same software I mentioned above?

I have the following line in the log:
> 1st-setup:2015-10-6 16:36:44.879:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
>1st-setup:2015-10-6 16:38:44.811:[Xtx-Home] refresh (_refresh in mivExchangeCalendar.js:2849)
1st-setup:2015-10-6 16:38:44.812:[Xtx-Home] weAreSyncing. So no refresh. (_refresh in mivExchangeCalendar.js:2857)
>1st-setup:2015-10-6 16:39:44.251:[Xtx-Home] getItems 0:   aItemFilter, 196636  aCount, 0 aRangeStart,  2015/11/14 00:00:00 Europe/Vienna isDate=0 nativeTime=1447455600000000 aRangeEnd, 2016/11/14 00:00:00 Europe/Vienna isDate=0 nativeTime=1479078000000000 aListener , [object Object] (_getItems in mivExchangeCalendar.js:2196)
>1st-setup:2015-10-6 16:39:44.252:[Xtx-Home] getItems 2: aRangeStart:2015/11/14 00:00:00 Europe/Vienna isDate=0 nativeTime=1447455600000000 (_getItems in mivExchangeCalendar.js:2204)
>1st-setup:2015-10-6 16:39:44.253:[Xtx-Home] getItems 3: aRangeEnd:2016/11/14 00:00:00 Europe/Vienna isDate=0 nativeTime=1479078000000000 (_getItems in mivExchangeCalendar.js:2212)
>1st-setup:2015-10-6 16:39:44.256:[Xtx-Home] We received a getItems from repeatingInvitationsTimer function. Because this request if always for a full year it will consume a lot of memory when we have a lot of recurring events with no end date. So for now we only request the period we have in memory cache. startDate:null, endDate:null (_getItems in mivExchangeCalendar.js:2223)
>1st-setup:2015-10-6 16:39:44.256:[Xtx-Home] Events are requested by calendar. (_getItems in mivExchangeCalendar.js:2248)
>1st-setup:2015-10-6 16:39:44.257:[Xtx-Home] Tasks are requested by calendar. (_getItems in mivExchangeCalendar.js:2249)

But no events appear in the calendar.

![screenshot_2015-11-14_16-29-51](https://cloud.githubusercontent.com/assets/1648307/11164343/1f2ba6d6-8aee-11e5-963a-08d983855af6.png)

**Comment by fromscratch-xx** [comment]
I increased the exchange communication log, no I found an error in the log file:

>1st-setup:2015-10-6 16:44:22.845:b00c0c6d-581a-4215-9db8-12276be278cb: : ExchangeRequest.onLoad :<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorInvalidServerVersion</faultcode><faultstring xml:lang="de-DE">Die angegebene Serverversion ist ungültig.</faultstring><detail><e:ResponseCode xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">ErrorInvalidServerVersion</e:ResponseCode><e:Message xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">Die angegebene Serverversion ist ungültig.</e:Message></detail></s:Fault></s:Body></s:Envelope>
1st-setup:2015-10-6 16:44:22.845:b00c0c6d-581a-4215-9db8-12276be278cb: exchangeRequest.isHTTPRedirect.xmlReq. xmlReq.readyState:4, xmlReq.status:500
1st-setup:2015-10-6 16:44:22.846:b00c0c6d-581a-4215-9db8-12276be278cb:  ErrorInvalidServerVersion -> RequestServerVersion wrong:Exchange2010_SP1.
1st-setup:2015-10-6 16:44:22.846:b00c0c6d-581a-4215-9db8-12276be278cb: Going to retry with lower server version
1st-setup:2015-10-6 16:44:22.849:b00c0c6d-581a-4215-9db8-12276be278cb: : ExchangeRequest.loadend
1st-setup:2015-10-6 16:44:22.849:b00c0c6d-581a-4215-9db8-12276be278cb: : ExchangeRequest.loadend :loadend, readyState:4, status:500
1st-setup:2015-10-6 16:44:22.850:b00c0c6d-581a-4215-9db8-12276be278cb: : ExchangeRequest.loadend :<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorInvalidServerVersion</faultcode><faultstring xml:lang="de-DE">Die angegebene Serverversion ist ungültig.</faultstring><detail><e:ResponseCode xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">ErrorInvalidServerVersion</e:ResponseCode><e:Message xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">Die angegebene >Serverversion ist ungültig.</e:Message></detail></s:Fault></s:Body></s:Envelope>

Could this be the problem? Or is my local setting/timezone (Austria, Vienna) a problem?

**Comment by fromscratch-xx** [comment]
Any ideas for the ErrorInvalidServerVersion?

**Comment by bavincen** [comment]
The log is not complete

1st-setup:2015-10-6 16:44:22.850:b00c0c6d-581a-4215-9db8-12276be278cb: : ExchangeRequest.loadend :<?xml version="1.0" encoding="utf-8"?>a:ErrorInvalidServerVersionDie angegebene Serverversion ist ungültig.ErrorInvalidServerVersion/e:ResponseCodeDie angegebene >Serverversion ist ungültig./e:Message/s:Fault/s:Body/s:Envelope

**Comment by fromscratch-xx** [comment]
Do you need more?
>1st-setup:2015-10-2 8:4:35.366:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.366:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.366:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.367:d0245222-2ac8-4ddf-97e9-fbd16f2531cc: : sendRequest Sending: <?xml version="1.0" encoding="utf-8"?>
<nsSoap:Envelope xmlns:nsSoap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsSoap:Header><nsTypes:RequestServerVersion Version="Exchange2010_SP1"/><nsTypes:TimeZoneContext><nsTypes:TimeZoneDefinition Name="(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna" Id="W. Europe Standard Time"/></nsTypes:TimeZoneContext></nsSoap:Header><nsSoap:Body><nsMessages:SyncFolderItems xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsMessages:ItemShape><nsTypes:BaseShape>IdOnly</nsTypes:BaseShape></nsMessages:ItemShape><nsMessages:SyncFolderId xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types"><nsTypes:DistinguishedFolderId Id="calendar"><nsTypes:Mailbox><nsTypes:EmailAddress>g.schoenberger@XXX.com</nsTypes:EmailAddress></nsTypes:Mailbox></nsTypes:DistinguishedFolderId></nsMessages:SyncFolderId><nsMessages:MaxChangesReturned>512</nsMessages:MaxChangesReturned></nsMessages:SyncFolderItems></nsSoap:Body></nsSoap:Envelope>

>1st-setup:2015-10-2 8:4:35.367:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.367:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.367:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({69150b77-b561-43a2-bfba-7301dd5a35d0})
1st-setup:2015-10-2 8:4:35.367:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.368:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.368:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.368:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.368:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.368:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({f6a0d1e5-369f-4abc-81ae-d370d36e4006})
1st-setup:2015-10-2 8:4:35.369:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsIApplicationCacheContainer
1st-setup:2015-10-2 8:4:35.369:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.369:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.369:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-10-2 8:4:35.369:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.370:d0245222-2ac8-4ddf-97e9-fbd16f2531cc: : ExchangeRequest.loadstart
1st-setup:2015-10-2 8:4:35.370:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsIProgressEventSink
1st-setup:2015-10-2 8:4:35.370:384fb8ad-895a-45c4-8699-4e4a44ae0879:   --- ecnsIAuthPrompt2.onStatus: STATUS_WAITING_FOR of XXX.XXX.com
1st-setup:2015-10-2 8:4:35.417:updaterCallBack: No new version available.
1st-setup:2015-10-2 8:4:35.462:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.462:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.462:384fb8ad-895a-45c4-8699-4e4a44ae0879: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2015-10-2 8:4:35.463:384fb8ad-895a-45c4-8699-4e4a44ae0879:   --- ecnsIAuthPrompt2.onStatus: STATUS_RECEIVING_FROM of XXX.XXX.com
1st-setup:2015-10-2 8:4:35.463:384fb8ad-895a-45c4-8699-4e4a44ae0879:   --- ecnsIAuthPrompt2.onProgress: this is a nsIChannel
1st-setup:2015-10-2 8:4:35.463:384fb8ad-895a-45c4-8699-4e4a44ae0879:   --- ecnsIAuthPrompt2.onProgress:635 of -1
1st-setup:2015-10-2 8:4:35.512:d0245222-2ac8-4ddf-97e9-fbd16f2531cc: : ExchangeRequest.progress. loaded:635, total:0
1st-setup:2015-10-2 8:4:35.823:d0245222-2ac8-4ddf-97e9-fbd16f2531cc: : ExchangeRequest.onLoad :load, readyState:4, status:500
1st-setup:2015-10-2 8:4:35.823:d0245222-2ac8-4ddf-97e9-fbd16f2531cc: : ExchangeRequest.onLoad :Cache-Control: private
Transfer-Encoding: chunked
Content-Type: text/xml; charset=utf-8
Server: Microsoft-IIS/7.5
X-AspNet-Version: 2.0.50727
X-Powered-By: ASP.NET
Date: Tue, 17 Nov 2015 07:04:26 GMT

>1st-setup:2015-10-2 8:4:35.824:d0245222-2ac8-4ddf-97e9-fbd16f2531cc: : ExchangeRequest.onLoad :<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorInvalidServerVersion</faultcode><faultstring xml:lang="de-DE">Die angegebene Serverversion ist ungültig.</faultstring><detail><e:ResponseCode xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">ErrorInvalidServerVersion</e:ResponseCode><e:Message xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">Die angegebene Serverversion ist ungültig.</e:Message></detail></s:Fault></s:Body></s:Envelope>
1st-setup:2015-10-2 8:4:35.824:d0245222-2ac8-4ddf-97e9-fbd16f2531cc: exchangeRequest.isHTTPRedirect.xmlReq. xmlReq.readyState:4, xmlReq.status:500
1st-setup:2015-10-2 8:4:35.824:d0245222-2ac8-4ddf-97e9-fbd16f2531cc:  ErrorInvalidServerVersion -> RequestServerVersion wrong:Exchange2010_SP1.
1st-setup:2015-10-2 8:4:35.825:d0245222-2ac8-4ddf-97e9-fbd16f2531cc: Going to retry with lower server version
1st-setup:2015-10-2 8:4:35.828:d0245222-2ac8-4ddf-97e9-fbd16f2531cc: : ExchangeRequest.loadend
1st-setup:2015-10-2 8:4:35.828:d0245222-2ac8-4ddf-97e9-fbd16f2531cc: : ExchangeRequest.loadend :loadend, readyState:4, status:500
1st-setup:2015-10-2 8:4:35.828:d0245222-2ac8-4ddf-97e9-fbd16f2531cc: : ExchangeRequest.loadend :<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorInvalidServerVersion</faultcode><faultstring xml:lang="de-DE">Die angegebene Serverversion ist ungültig.</faultstring><detail><e:ResponseCode xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">ErrorInvalidServerVersion</e:ResponseCode><e:Message xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">Die angegebene Serverversion ist ungültig.</e:Message></detail></s:Fault></s:Body></s:Envelope>

**Comment by bavincen** [comment]
Are you using exchange2013 server? 


Providing log from "Your Log" file. paste the xml server error  (ErrorInvalidServerVersion)

**Comment by fromscratch-xx** [comment]
No it's Exchange 2010.
What xml server error do you need?

**Comment by gschoenberger** [comment]
I am providing the complete log as attachment. Do you need more debugging info? Can I inspect something on server side?
THX a lot, Georg
[ews.log.txt](https://github.com/Ericsson/exchangecalendar/files/36567/ews.log.txt)

**Comment by gschoenberger** [comment]
Did you have found some time to look at the log file?

**Comment by GonozalIX** [comment]
Just want to note that I have the same problem. Also using ubuntu....

**Comment by bavincen** [comment]
not happening in recent calendar versions. closing it..
