### ISSUE TITLE
Random 'important' tags added to other accounts

### ISSUE THREAD

**Issue by johnsjs** [Ericsson/exchangecalendar#378]
I have the following set up;

Windows 10 Pro
Thunderbird 38.3.0
Lightning 4.0.3.1
Exchange EWS Provider 3.5.0-beta1

Connecting to office365 with one account

Thunderbird has IMAP connections to the same office365 hosted domain, and 2 privately hosted IMAP mail servers, and one 1und1.de mail server.

Lightning is connecting to 7 calenders hosted on SOGo through CalDAV, and one on office365 through the Exchange EWS connector.

Problem:

Random (or at least I cannot spot the pattern, although there probably is one) messages in the IMAP folders belonging to the non office365 email accounts get the important tag set, and will not allow the tag to be unset.

Disabling the Exchange EWS addon allows the important tags to be cleared, and remain clear.

Re-enabling the addon immediately brings back the tag on a subset of the messages where it happened previously, and then chooses new ones over time to set to important.

I have one filter that copies outgoing emails to a folder, and sets a custom tag on them - but there seems to be no correlation with the 'important' tag.

I do not otherwise use tags, and messages without the behaviour are able to have the 'important' tag set and unset normally.

I am a new user of the addon, and it meets a need I have perfectly, great work guys.  Cheers. John

**Comment by bavincen** [comment]
ok.. so it is applied to non-ews account calendars too?

**Comment by johnsjs** [comment]
Not sure of your question so I'll answer both ways I can read it.  The EWS connector is only applied to the office365 calender.  The tags issue affects non office365 emails, 

To date it has not affected office365 emails at all.  I only use the EWS connector as a calender connector, we do not use hosted contacts or other exchange functionality at this time - my need for the connector is purely the calendar.

I have tried disabling all other addons except for lightning and EWS and the problem persists.

**Comment by bavincen** [comment]
You can disable this  marking mail as important. The preference is stored in EDIT->PREFERENCE->Extras

**Comment by johnsjs** [comment]
That worked.  Thank you. A curious default behaviour, but I've never used priority in email, so maybe it's just me.
