### ISSUE TITLE
Missing Busy info on Private Appointments 

### ISSUE THREAD

**Issue by smkillen** [Ericsson/exchangecalendar#381]
I have access to another persons (my boss) Office365 calendar with the ability to see the details of events. However, when they mark and event as 'Private' I am not able to see any details and it looks to me like they are free (nothing in their calendar). If I access this using the Web portal I see the event as "Busy" (with no details visible).

This used to work when we had onsite Exchange 2010/2013 but now we have migrated to 365 it is not working.  

Thanks

-- Sean

I am using Thunderbird 38.4, Lightning 4.0.4 and EWS Provider 3.5.0 beta 1 on CentOS 6

**Comment by bavincen** [comment]
Can you check the same in outlook please? is it working there. please provide screenshots..
