### ISSUE TITLE
Not compatible with password managers

### ISSUE THREAD

**Issue by naevtamarkus** [Ericsson/exchangecalendar#384]
Dear devels,

I have a small problem trying to integrate Firefox and KeePass (with KeeFox). Everything else works as expected (I manage passwords for all my accounts) but with your Exchange Provider I was not able to succeed. 

The problem is I believe that password managers need the URL in the password dialog and somehow this plugin does not do it properly. This is the error shown by KeeFox:
Tue Dec 15 2015 10:32:49 GMT+0100 (CET):WARN: Couldn't parse origin
Tue Dec 15 2015 10:32:56 GMT+0100 (CET):WARN: KeeFox failed to process the data submitted to a dialog. Exception: TypeError: url is undefined

The thing is that the dialog shown by this plugin shows the URL correctly INSIDE the window (e.g. "Enter password for username on https://mailserver.domain.com/EWS/Exchange.asmx" but it does not seem to be enough. I have looked at other password prompts and their messages vary in many shapes and forms, some use the title of the dialog, some use the text... I did not perceive an obvious mistake. Could it be that "url" is an internal field of the dialog and needs to be set by the plugin? Any other ideas?

Thanks for looking into this,
BR/Pablo

**Comment by naevtamarkus** [comment]
Hi,
This seems to require some adapting on the plugin itself. I am tracking this on their github account and they are asking for some extra info... would you be so kind as to answer in their Issue here:
https://github.com/luckyrat/KeeFox/issues/587

Thanks a lot!!

**Comment by bavincen** [comment]
Hello will take a look...

**Comment by bavincen** [comment]
closing it.

**Comment by naevtamarkus** [comment]
Is this really solved? I got the impression that they were not going to fix it...

**Comment by bavincen** [comment]
I had given sufficient information for identifying the password prompt in
ews. I don't know the status in
https://github.com/luckyrat/KeeFox/issues/587

**Comment by bavincen** [comment]
How can I help you here? Nobody contacted after that.
