### ISSUE TITLE
v3.5.0-beta1 compatibility issue with Fiefox 42.0

### ISSUE THREAD

**Issue by Ruudv9876** [Ericsson/exchangecalendar#387]
When I install v.3.5.0-beta1, or any older version, I get the message that it is not compatible with Firefox 42.0.
(If this is mentioned elswhere then sorry, I'm a newbee regarding calenders & TB & Exchange EWS provider.)

**Comment by ChristopheLux** [comment]
Hello Ruudv9876 this is to be installed in Thunderbird not in Firefox

**Comment by bavincen** [comment]
Yes Ruudv9876, it is a Thunderbird addon.

On 12/18/2015 10:25 AM, ChristopheLux wrote:
>
> Hello Ruudv9876 this is to be installed in Thunderbird not in Firefox
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Ericsson/exchangecalendar/issues/387#issuecomment-165722488>.
>

-- 

	
Bavincen
Programmer, Ericsson
p: m: a: IN
s: http.:/*.*/bavincen e: bavincen.in@gmail.com, 
babu.vincent@ericsson.com 
<mailto:bavincen.in@gmail.com,%20babu.vincent@ericsson.com>

**Comment by Ruudv9876** [comment]
Thanks.
I had some difiiculties finding how to install it in TB so apparently I did in FF.
