### ISSUE TITLE
Md5sum or SHA Hash

### ISSUE THREAD

**Issue by Mechtilde** [Ericsson/exchangecalendar#389]
Hello

To verify a correct download can yyou please publish a md5sum or a SHA Hash or something similar?

Kind regards

Mechtilde

**Comment by muthusuba** [comment]
Should be doable!
@bavincen Should we put in sha1sums of the downloads, please?

**Comment by bavincen** [comment]
@muthusuba will do..

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/releases/tag/v3.5.0

**Comment by bavincen** [comment]
This is Done..

https://github.com/Ericsson/exchangecalendar/releases/tag/v3.5.0


Thanks



Bavincen
Programmer, Ericsson
a: IN
s: http.:/*.*/bavincen e: bavincen.in@gmail.com, babu.vincent@ericsson.com


On Wed, Dec 23, 2015 at 9:23 PM, Muthu Subramanian <notifications@github.com

**Comment by muthusuba** [comment]
@bavincen Super! Thanks!

**Comment by muthusuba** [comment]
@Mechtilde Let us know if you need hashes for previous builds as well....Thanks!
