### ISSUE TITLE
Dismissing reminders locks Thunderbird

### ISSUE THREAD

**Issue by angiest** [Ericsson/exchangecalendar#392]
Environment:

Manjaro 15.12
Thunderbird 38.5.0-1 (installed from official repositories)
exchangecalendar 3.5.0-1 (installed from the AUR)
Lightning 4.0.4.1-2 (installed from the AUR)

When attempting to dismiss an Exchange meeting reminder, Thunderbird locks up completely, requiring a kill (brings up the DE's Force Quit dialog in both KDE and Gnome).

**Comment by bavincen** [comment]
Alright is that stable version of lightning ?
If not can use one?

**Comment by angiest** [comment]
As far as I can tell, it is.

On Wed, Dec 30, 2015 at 9:08 AM, Babu Vincent(bavincen) <
notifications@github.com> wrote:

> Alright is that stable version of lightning ?
> If not can use one?
>
> On Wed, Dec 30, 2015, 20:27 angiest <notifications@github.com> wrote:
>
> > Environment:
> >
> > Manjaro 1512
> > Thunderbird 3850-1 (installed from official repositories)
> > exchangecalendar 350-1 (installed from the AUR)
> > Lightning 4041-2 (installed from the AUR)
> >
> > When attempting to dismiss an Exchange meeting reminder, Thunderbird
> locks
> > up completely, requiring a kill (brings up the DE's Force Quit dialog in
> > both KDE and Gnome)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Ericsson/exchangecalendar/issues/392>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ericsson/exchangecalendar/issues/392#issuecomment-168016595>
> .
>



-- 

We shall not cease from exploration
And the end of all our exploring
Will be to arrive where we started
And know the place for the first time.
    - TS Eliot, "Little Gidding," from "Four Quartets"

**Comment by bavincen** [comment]
@angiest this problem is not happening for me ews-3.5 tb-38.5 lighting 4.0.5.
I feel you should also use 4.0.5
is there any special requirement to use 4.0.4 with TB 38.5

**Comment by bavincen** [comment]
closing it. reopen issue if the problem still there in your calendar...
