### ISSUE TITLE
Default 'home' and 'exchange' folders cannot be deleted

### ISSUE THREAD

**Issue by markgbeckett** [Ericsson/exchangecalendar#395]
Dear Exchange EWS Calendar team,

When connecting to my work Exchange service, from Thunderbird 38.5.0, using Exchange ESW Provider 3.5.0, I see two unexpected calendars named 'home' and 'Exchange', alongside my work calendar. I can delete and unsubscribe from these calendars, respectively. However, when I restart Thunderbird, they reappear (see 
![ews_screenshot](https://cloud.githubusercontent.com/assets/7847919/12114368/17885966-b3a1-11e5-9871-a374d6dfd895.jpg)
).

Does anyone know what I might be doing wrong? 

Keep up the good work, and thanks in advance for any suggestions,
George.

**Comment by bavincen** [comment]
I guess you have to ask this in lightning...

**Comment by markgbeckett** [comment]
Hi Babu,

Thanks, though these calendars only appear when I have the Exchange EWS Provider add-on installed -- or, at least, I didn't see the problem prior to installing the add-on.

Thanks again,
George.

**Comment by bavincen** [comment]
Something is corrupt. Delete the calendars from preferences files.

**Comment by bavincen** [comment]
Lightning, in 4.* , renamed some core preference that affected your old calendars.. this happend  long back..Please create your calendars again or downgrade to old version delete your cals. then create it in new version.. 

thanks for support. closing this issue.
