### ISSUE TITLE
Extra backslash added to username which leads to 401

### ISSUE THREAD

**Issue by oparoz** [Ericsson/exchangecalendar#396]
In my error console, I see something like this

> Timestamp: 05/01/2016 21:04:50
> Error: syntax error
> Source File: https://%5Cuser%40domain%2Ecom:secret@server.com/horde/rpc.php
> Line: 1, Column: 1
> Source Code:
> 401 Unauthorized

But my username is `user@domain.com` without the initial backslash.

Not sure where this is coming from, I can't see anything in the config editor.

This is on 3.5.0 with the latest stable Thunderbird

**Comment by bavincen** [comment]
Provide  screen shot of your auto discovery information

**Comment by oparoz** [comment]
OK, I'll try with another account, but I should have added that this happens when I enable/disable the calendar (trying to fix the read-only problem)
