### ISSUE TITLE
contacts : can't get more than 1000 contacts from address book

### ISSUE THREAD

**Issue by Trim** [Ericsson/exchangecalendar#398]
Hello,

Recently I've discovered that exchangecalendar cant' get all contacts from my company shared address book.
The address book contains around 1600 vcards and, after end of the synchronisation, Thunderbird shows me only 1k contacts.

I've looked the code of `components/erSyncContactsFolder.js` and I've found an error in [these lines](https://github.com/Ericsson/exchangecalendar/blob/master/components/erSyncContactsFolder.js#L175-L184):

```js
if (lastItemInRange == "false") {
	this.execute(syncState);
	return;
}
else {
	if (this.mCbOk) {
		this.mCbOk(this, this.creations, this.updates, this.deletions, syncState);
	}
	this.isRunning = false;
}
```

For me, the call of the callback function seems wrong for me, because in file `interfaces/exchangeAddressBook/exchangeAbFolderDirectory/exchangeAbFolderDirectory.js` the signature of the function [callback function](https://github.com/Ericsson/exchangecalendar/blob/master/interfaces/exchangeAddressBook/exchangeAbFolderDirectory/exchangeAbFolderDirectory.js#L1299) is:

```js
contactsFoundOk: function _contactsFoundOk(erFindContactsRequest, aContacts, aDistLists)
```

So I've fixed that code with this ugly temporary hack:

```js
	if (this.mCbOk) {
		this.mCbOk(this, [this.creations.contacts, this.updates.contacts, this.deletions.contacts]
				 [this.creations.distlists, this.updates.distlists, this.deletions.distlists]);
	}
```

I got 2 more contacts synchronised and 2 more distribution lists, but it miss still 600 contacts.

First I thought that the synchronisation between exchangecalendar and the exchange 2013 server was in error.
So I've used [Firefox to do a remote debug](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Thunderbird) with the developer tools and I had these results:

![Network tab](https://cloud.adorsaz.ch/index.php/s/cnS0NtLKe2ha9cR/download)

I've checked the POST requests with a "200" response and they seem to correctly retrieve all contacts from the exchange server according to the [Microsoft documentation](https://msdn.microsoft.com/en-us/library/office/aa563967%28v=exchg.150%29.aspx) : the first request is done without SyncState tag and then each request have the updated value for SyncState upto the 5th one which have the value of IncludesLastItemInRange to true in the response.

The following requests are to get details on some contacts and on the two distribution lists available with the address book.

Although, looking for contacts in the exchangecalendar log, I have only one logged server response and it seems that it received only 1000 contacts.

I'll try to investigate more tomorrow. For now, it seems that the code of `components/erSyncContactsFolder.js` does correctly all requests on the exchange server, but everything isn't called back to the callback of the `exchangeAbFolderDirectory.js` code. Maybe my ugly hack wasn't suffisant, or we reached the limits of javascript array size (some mega bits according to the network graph).

I think a possible solution is to rewrite interaction between the two piece of codes to give back results after each request instead of waiting to have all contacts. If I've read correctly the corresponding code of the Calendar part, it seems to work like that.

Maybe such solution could improve a bit the situation of bugs : #376 and #375 about freezes.

See you,
Adrien

**Comment by bavincen** [comment]
Can you create a patch please

**Comment by Trim** [comment]
I've just seen that I didn't check the right callback definition, sorry for this useless big report.
I'm checking error on the good callback function and I'll give you feedback.

**Comment by Trim** [comment]
I've found the issue: the code of [components/erFindContacts.js](https://github.com/Ericsson/exchangecalendar/blob/master/components/erFindContacts.js) isn't complete: it does only one request to the exchange server, even if the response indicates that it misses some items.

I'm trying to make a code according to [Microsoft example](https://msdn.microsoft.com/en-us/library/office/jj220498%28v=exchg.80%29.aspx).

**Comment by bavincen** [comment]
Thanks for patch
