### ISSUE TITLE
Tasks created in Outlook from Email Follow-Up Reminders do not show up.

### ISSUE THREAD

**Issue by muthusuba** [Ericsson/exchangecalendar#4]
This is probably a little complex one:
Michel's take on this: " This is a new feature. When you change an email into a task it stays and email item in the background. Only some task properties are added. The add-on knows about real task items and not about email items with task properties. Probably not hard to implement but will take time to develop and test. (3 days)"

**Comment by bavincen** [comment]
please check emailfollowuptask branch for this feature until we merge with master..
