### ISSUE TITLE
cannot cancel events as organizer from event dialog

### ISSUE THREAD

**Issue by Be-ing** [Ericsson/exchangecalendar#402]
Going to Options > Status > Canceled on the Edit Event dialog and clicking Save and Close does not cancel the event. It still shows up in Lightning and OWA. After canceling it in OWA, the event does not show up in Lightning anymore.

**Comment by bavincen** [comment]
Please post screenshots...

**Comment by Be-ing** [comment]
![cancel-screenshot-1](https://cloud.githubusercontent.com/assets/9455094/12432108/f088f072-bebe-11e5-8dd0-fa6fcd3d54ea.png)

I set an event as canceled using the menus shown at the top of the screenshot. After doing that, the status changes to Canceled as shown in the bottom right and still shows on the calendar (which it should not). However, after synchronizing the calendar, the status reverts to Confirmed. No notifications are sent out to event participants when I select the option to do so after clicking Save & Close.

**Comment by bavincen** [comment]
Hai,
 Wait for the calendar to sync.. No bug found..


Thanks..

**Comment by Be-ing** [comment]
How can you say "No bug found" when I clearly found a bug? Have you tested this? Syncing the calendar reverts the event back to Confirmed status.

I found another way to cancel events that does update the Exchange calendar. Deleting it by clicking on it on the calendar and pressing the Delete key or right clicking on it and selecting Delete Event works. It is confusing that this works but marking the event as Canceled does not.

**Comment by bavincen** [comment]
after saving it, click on synchronize button.
the status is changed
is it happening on all the events or particular event

**Comment by Be-ing** [comment]
This happens with all events.
