### ISSUE TITLE
Duplicate events

### ISSUE THREAD

**Issue by ancienttechie** [Ericsson/exchangecalendar#403]
At some point I started seeing duplicate events on my EWS calendars - one is correct and one just has the title followed by '(free)' or '(busy)'.  Not sure when this started.

TB 38.5.0/Lightning 4.0.5, EWS 3.5.0

**Comment by bavincen** [comment]
Screenshots needed. Please input your operating systems.
It will be easy for debugging and fixing for developers

**Comment by bavincen** [comment]
I would advise clearing cache .

**Comment by ancienttechie** [comment]
Must have been the cache - as mysteriously as it appeared, it's gone now.
