### ISSUE TITLE
ntlm-v1 enforced by default?

### ISSUE THREAD

**Issue by Langenscheiss** [Ericsson/exchangecalendar#410]
Correct me if I am wrong, but it seems to me like whenever this addon is enabled, the variable

network.auth.force-generic-ntlm-v1

is reset to true each time you restart thunderbird. Now, I know that some exchange servers do not let you authenticate with this set to false and that this has caused some trouble since thunderbird 38 has come out. However, apart from the fact that auto-enabling the insecure v1 method is questionable, this also causes problems. My exchange server explicitly DOES NOT allow you to authenticate with this method activated. This means that each time I restart my thunderbird, I have to manually set the above variable to false in order to authenticate to my exchange account. I would highly prefer an option that allows me to permanently set this variable to either true or false.

System: Ubuntu 12.04 LTS
Software: Thunderbird 38.5.1 + Lightning 4.0.5.2 + EWS Provider 3.5.0

**Comment by bavincen** [comment]
Yes we have enabled this by default.,
Whats the problem? pelase



Bavincen
Programmer, Ericsson
a: IN
s: http.:/*.*/bavincen e: bavincen.in@gmail.com, babu.vincent@ericsson.com

**Comment by bavincen** [comment]
What happens actually is.
the calendar plugin tries to authenticate using NTLM, if that fails  tries
to authenticate using normal password.
where do you think the problem is?

Thanks



Bavincen
Programmer, Ericsson
a: IN
s: http.:/*.*/bavincen e: bavincen.in@gmail.com, babu.vincent@ericsson.com

**Comment by eschkang** [comment]
The problem for my environment is that NTLM v1 and "normal" password is not allowed. We want the add-on to stop resetting the NTLMv1 to True.

**Comment by Langenscheiss** [comment]
Exactly. I though I had explained it well enough, but well. 
It is not about using NTLM, it is about auto-enabling ntlm !V1! . This breaks authentication in any environment in which the server rejects the insecure V1 protocol or normal password, but only accepts higher versions of ntlm. 
Again
- auto-enabling an INSECURE protocol is highly questionable. There is a reason why this option is only reachable via the config editor. It is only for those people that NEED ntlm-V1 because the exchange servers to which they connect use this outdated protocol.
- authentication to exchange servers that exclusively allow only higher ntlm versions requires to manually reset the variable to false each time you start thunderbird. 

If this is not problematic enough, I don't know???

**Comment by bavincen** [comment]
Why do we enable it by default?
Some users including me when trying to authenticate using normal password
the calendar addon looping prompt password though I enter right password.
This was not  happening after the  preferences was set true.

**Comment by Langenscheiss** [comment]
Ok. But again referring to my first post, what is the harm in introducing an extra option in the EWS provider preferences? The people that have problems with auto-enabled ntlm-v1 then at least can make your addon work again, by disabling this behavior. At the moment, EWS provider is essentially COMPLETELY BROKEN for a considerable amount of users, because setting the variable to false each time is simply too much to ask to a regular user, and extremely inconvenient. And I guarantee you that the relevant user base will increase, because more and more exchange server admins will disable ntlm-v1 authentication in the future.

So it all boils down to this: Do you want to spend a little bit of time in introducing an extra checkbox in your "preferences" tab in order to satisfy and convince more users of your addon, or not? It's your addon, and you can decide. As far as I am concerned, I have been a happy user of your tool until Christmas when the admin or the exchange server decided to deactivate ntlm-v1. Now, the provider is useless to me.

**Comment by bavincen** [comment]
need an extra preference set to enable ntlm-v1 on startup if the user having password issues.

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/commit/22850a80eb6a72bfbcb392ed384be971c98d42fe
