### ISSUE TITLE
Compatibility with Lightning 4.7b1

### ISSUE THREAD

**Issue by brenboy** [Ericsson/exchangecalendar#426]
Hi All,

Is Exchange Calendar 3.6b1 supported with Lightning 4.7b1? It doesn't look like it.

I cannot add a description or invitees to an event whilst running Calendar 3.6b1 with Lightning 4.7b1 unless I first also have a local non-EWS calendar. The formatting of the event is also messed up with all fields/boxes forced to be left justified.

The workaround is to highlight the local non-EWS calendar calendar before creating a new event and then once the event dialog box is open, switch to your EWS calendar in the Calendar drop-down box.

Exchange calendar version: 3.6b1
Lightning version: 4.7b1
Thunderbird version: 45.0b1
OS X version: 10.11.3

<img width="1131" alt="screen shot 2016-02-11 at 12 36 46 pm" src="https://cloud.githubusercontent.com/assets/11042234/12967603/7f198022-d0bc-11e5-9b34-34bf56395e48.png">

<img width="1134" alt="screen shot 2016-02-11 at 12 37 12 pm" src="https://cloud.githubusercontent.com/assets/11042234/12967616/94281f6e-d0bc-11e5-8584-26cd797595c3.png">

**Comment by bavincen** [comment]
We support 4.4

**Comment by brenboy** [comment]
Ok cool. Thanks.

When do you plan to support Lightning 4.7?

 The official Thunderbird 45 release is due out in the next couple of months and will only support Lightning 4.7.

**Comment by brenboy** [comment]
I've read that the official Thunderbird 45 version will be released this week and will only support Lightning 4.7. 

Is there a new Exchange calendar version being released soon that will support Lightning 4.7 because 3.6 does not?

**Comment by bavincen** [comment]
Yes we are planning to release soon

**Comment by Mechtilde** [comment]
Hello,

for Debian I build calendar-exchange-provider 3.6-beta1 against Icedove
45.0~b4 and iceowl 4.7~b2. It works.

I can't detect any problems. So please tell us, what are the problems to
use calendar-exchange-provider 3.6-beta1, Icedove
45.0~b4 and iceowl 4.7~b2 or the correspondent release versions.

Regards

Mechtilde

Am 10.04.2016 um 03:26 schrieb Babu Vincent(bavincen):
> Yes we are planning to release soon
> 
> On Sun, Apr 10, 2016, 06:54 brenboy <notifications@github.com> wrote:
> 
>> I've read that the official Thunderbird 45 version will be released this
>> week and will only support Lightning 4.7.
>>
>> Is there a new Exchange calendar version being released soon that will
>> support Lightning 4.7 because 3.6 does not?
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Ericsson/exchangecalendar/issues/426#issuecomment-207893596>
>>
> 
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Ericsson/exchangecalendar/issues/426#issuecomment-207893642
> 

-- 
Mechtilde Stehmann

## Apache OpenOffice
## Debian
## Look, calendar-exchange-provider, libreoffice-canzeley-client
## PGP encryption welcome
## Key-ID 0x141AAD7F

**Comment by Mechtilde** [comment]
Hello,

I inverstigate a little bit more.

the problem is that you can't activate the field for Description doing a
new evvent and already available events

The same field used for attachment and attendess work.

Regards

Mechtilde

Am 10.04.2016 um 03:26 schrieb Babu Vincent(bavincen):
> Yes we are planning to release soon
> 
> On Sun, Apr 10, 2016, 06:54 brenboy <notifications@github.com> wrote:
> 
>> I've read that the official Thunderbird 45 version will be released this
>> week and will only support Lightning 4.7.
>>
>> Is there a new Exchange calendar version being released soon that will
>> support Lightning 4.7 because 3.6 does not?
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Ericsson/exchangecalendar/issues/426#issuecomment-207893596>
>>
> 
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Ericsson/exchangecalendar/issues/426#issuecomment-207893642
> 

-- 
Mechtilde Stehmann

## Apache OpenOffice
## Debian
## Look, calendar-exchange-provider, libreoffice-canzeley-client
## PGP encryption welcome
## Key-ID 0x141AAD7F

**Comment by bavincen** [comment]
some issue with task calendar syncing  found.
Need to manually refresh after creating a new task.




Bavincen
Programmer, Ericsson
a: IN
s: http.:/*.*/bavincen e: bavincen.in@gmail.com, babu.vincent@ericsson.com

**Comment by brenboy** [comment]
Hi Guys,

Was release the new 3.6.0 meant to fix the original issues I described in my first post (and also seen by Mechtilde)? I still see the same original issue using the recently released Thunderbird 45, Exchange Calendar 3.6.0 and Lightning 4.7b3

**Comment by bavincen** [comment]
Guys will take it next. This fixes some task related issue

**Comment by bavincen** [comment]
Please check latest v3.7.0 guys.

@Mechtilde can you help me reproducing it.

**Comment by brenboy** [comment]
Hi bavincen,

I'm still seeing exactly the same issue with version 3.7.0. When creating a new event the fields are justified to the right and I can't add any text to the Description field (box is greyed out). See below.

I also noticed that when adding invitees to the event, the Enter key doesn't work and I can't add more than one invitee

Exchange calendar version: 3.7.0
Lightning version: 4.7b3
Thunderbird version: 45.0
OS X version: 10.11.4

<img width="934" alt="screen shot 2016-04-15 at 5 06 02 pm" src="https://cloud.githubusercontent.com/assets/11042234/14553871/76435426-032c-11e6-966d-d5494f754da0.png">

**Comment by xguse** [comment]
This is also happening to me. Same versions.

**Comment by enozkan** [comment]
I am experiencing the same problem. And, of course, this no longer an issue with 4.7.1 beta, but it is an incompatibility with the last stable release of Lightning (4.7). A change in title might be in order.

**Comment by enozkan** [comment]
In case it helps, these are the errors I am getting in the Console upon starting a new event:

Warning: ReferenceError: reference to undefined property this.mSelectedInternal
Source File: chrome://global/content/bindings/menulist.xml
Line: 439

Error: TypeError: attendeeRow is null
Source File: chrome://exchangecalendar/content/calendar-event-dialog.js
Line: 288

Warning: Expected end of value but found '93'.  Error in parsing value for 'font-family'.  Declaration dropped.
Source File: chrome://calendar/content/calendar-event-dialog.xul
Line: 0, Column: 21
Source Code:
font-family: Bauhaus 93 !important;
...
and about ten more font-related errors.

Interestingly, same errors show up even when a Google or Local calendar event is created. Not sure why an error from "Source File: chrome://exchangecalendar/content/calendar-event-dialog.js" would pop up for a local calendar event.
