### ISSUE TITLE
Support for Categories

### ISSUE THREAD

**Issue by mastier** [Ericsson/exchangecalendar#429]
I would really appreciate support for Exchange e-mail categories. At our company we use categories in common mailbox to flag which mail is taken by whom to process.

Is it possible to look that up on the Exchange server and view it as new column ? at best, not only get, but also to set the flags.

![screenshot from 2016-02-22 11-29-40](https://cloud.githubusercontent.com/assets/1609672/13215703/ad753990-d957-11e5-8a7e-b92e8a4ef1b5.png)

**Comment by bavincen** [comment]
Tagging? Please check wiki. It's called as remote tagger.

**Comment by mastier** [comment]
Wiki ? This [one](https://github.com/Ericsson/exchangecalendar/wiki) ?
I might be blind but I don't see it

**Comment by bavincen** [comment]
Ah ok . There is no page created for Tagging. You can find that settings in
ews settings..  just right click calendar created by you.

**Comment by bavincen** [comment]
Of course I found it. It's ews mail settings page in wiki

**Comment by mastier** [comment]
This is not what I meant. I though i can also fetch the mail categories, not only tags ?

It fetches the tags like "Important", but Categories is something different. It is like custom tags specified and kept on server side and you can easily create new one on the client.

**Comment by mastier** [comment]
Why the issue was closed?

**Comment by Sketterskt** [comment]
I to would like to know if this can be implemented, or if it is, why isn't it working?  If the tags is being referred to as marked important and so on, that isn't what is being asked.  It is specific to categories in Outlook.

Thanks

Edit:
I don't know what happened but this has started working.  Tags and Categories are now syncing.  This however wasn't happening before, but none the less I'm happy.
