### ISSUE TITLE
Only own calendars after update

### ISSUE THREAD

**Issue by J-Metsis** [Ericsson/exchangecalendar#43]
Hello!

I had previously the last version from 1st Setup and I just found this fork. There was no read me nor any other installation instructions as far as I could see, so I installed the new version (3.2.2) simply by dragging it on the extensions tab on TB 31.2.0 on MS Windows 8. It overwrote the previous version but now I can see only my own calendars, not of my co-workers. The queue at bottom right ran normally.

Any pointers to help appreciated.

**Comment by advancingu** [comment]
Confirming still not working with Thunderbird 31.5.0 on Ubuntu 14.10 with exchangecalendar release 3.3.1-rc4.

**Comment by HuboAdmins** [comment]
Bavincen,

Just gave release v3.3.1 stable a try, issue appears to be resolved? I've yet to test thoroughly, but so far all my calendars are showing. Thanks!

**Comment by advancingu** [comment]
@HuboAdmins Did you restart Thunderbird after installing? It usually only works directly after installation, then it stops once you restart Thunderbird.

**Comment by bavincen** [comment]
Thanks! Please close the issue if  it is  resolved .. 

-----Original Message-----

**Comment by HuboAdmins** [comment]
@advancingu Yes, I have restarted multiple times and it's still working so far. As I said though, I've only been running it for 10 minutes. Might just want to keep this issue open for a while longer.
Let me know how it works for you.

**Comment by HuboAdmins** [comment]
I've been using version v3.3.1 stable for a week now, haven't encountered any problems with multiple calendars yet. As far as I'm concerned, feel free to close the issue.

Kind regards

**Comment by advancingu** [comment]
Calendar content of shared calendars is still not showing for me with 3.3.1. I've deleted my entire Exchange calendar entry in Thunderbird and re-added it from scratch, just to make sure the connector doesn't use any cached data, etc. but it didn't fix it.

I did notice though that I can see the shared calendars in the "folder properties" view when opening the connector's ``Exchange (EWS) Properties`` window. It's just not showing their content in the calendar view. Below is a screenshot with the first shared calendar selected under ``Userid`` (I've blurred out the identifying parts).

Any ideas?

![folder-properties](https://cloud.githubusercontent.com/assets/130207/6993063/332bdc70-dab6-11e4-832c-f8c29a679459.png)

**Comment by HuboAdmins** [comment]
@advancingu 
How did you fill in server url, username, folder base,.. on the previous tab? (Exchange / Windows AD)?

**Comment by advancingu** [comment]
@HuboAdmins 
This is what I have on the ``Exchange/Windows AD`` tab:
![exchange-settings](https://cloud.githubusercontent.com/assets/130207/7077293/9210d1ac-dedd-11e4-9306-c41d81c17b18.png)

**Comment by HuboAdmins** [comment]
@advancingu 
primary e-mailaddress: full email address of the co-worker (i.e john.doe@mydom.com)
username: your username in accountname@domain.com format. (i.e johnf@mydom.com)
Can you confirm? Works fine here.

**Comment by advancingu** [comment]
@HuboAdmins Ah, finally. That really wasn't clear to me that I have to create multiple calendars and enter the other person's email address as primary email address. I thought the other calendars would be added automatically through my own calendar.

**Comment by HuboAdmins** [comment]
@advancingu 
Aha, that does explain your issues :). Glad it's resolved.
