### ISSUE TITLE
Cannot create new calendar anymore

### ISSUE THREAD

**Issue by wforumw** [Ericsson/exchangecalendar#439]
When I try to create a new calendar, the 'Create New Calendar' window appears but is totally empty. (see attachment). I can fill in nothing. The only buttons on the bottom are Cancel, Back and Finish.
Back and Finish doesn't do anything, Cancel let the windows disappear. (See image)

![calendar](https://cloud.githubusercontent.com/assets/12762849/13553662/c5fd2778-e390-11e5-8360-2af0b44b404b.png)

Before it was working without problems.

I tried it with v3.6-beta1 and v3.5.0.
I am using Icedove 38.6.0 (from Debian Stretch)

Without exchangecalendar its working fine

**Comment by Mechtilde** [comment]
Hello,

Du you use the exchangecalender from Debian too?

Regards

MEchtilde


Am 06.03.2016 um 11:48 schrieb wforumw:
> When I try to create a new calendar, the 'Create New Calendar' window appears but is totally empty. (see attachment). I can fill in nothing. The only buttons on the bottom are Cancel, Back and Finish.
> Back and Finish doesn't do anything, Cancel let the windows disappear. (See image)
> 
> ![calendar](https://cloud.githubusercontent.com/assets/12762849/13553662/c5fd2778-e390-11e5-8360-2af0b44b404b.png)
> 
> Before it was working without problems.
> 
> I tried it with v3.6-beta1 and v3.5.0.
> I am using Icedove 38.6.0 (from Debian Stretch)
> 
> Without exchangecalendar its working fine
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Ericsson/exchangecalendar/issues/439
> 

-- 
Mechtilde Stehmann

## Apache OpenOffice
## Debian
## Look, calendar-exchange-provider, libreoffice-canzeley-client
## PGP encryption welcome
## Key-ID 0x141AAD7F

**Comment by wforumw** [comment]
Hi,
No, I did not knew it was in Debian. I installed it from debian and now 
it works.
Thanks
