### ISSUE TITLE
Missing textual explanations and screenshots in "How to add..." wiki page

### ISSUE THREAD

**Issue by mikini** [Ericsson/exchangecalendar#444]
The text in the "How to Add Your Calendar to Thunderbird" wiki page at https://github.com/Ericsson/exchangecalendar/wiki/How-to-Add-Your-Calendar-to-Thunderbird refers to screen-shots in bullet points 2, 7, 8 and 10 which are all missing and doesn't provide any textual hints to what users are supposed to see and select. Especially 7 and 8 are very unclear.

Adding a calendar using v3.5.0 in Thunderbird v38.6.0 I got a dialog with text field "Share Folder Id" and a drop down "Folder base" with a lot of options that was confusing. The default blank folder id and "Calendar folder" base seems to work as expected.

Attaching some screen-shots of my procedure, feel free to use them in the wiki if you wish.

![screenshot from 2016-03-10 14-53-12](https://cloud.githubusercontent.com/assets/1330166/13672030/5ace3050-e6d3-11e5-856b-bc82d282ece4.png)
![screenshot from 2016-03-10 14-53-15](https://cloud.githubusercontent.com/assets/1330166/13672031/5ae18ba0-e6d3-11e5-92ef-d35536e11533.png)
![screenshot from 2016-03-10 14-53-43](https://cloud.githubusercontent.com/assets/1330166/13672033/5b02e9c6-e6d3-11e5-8842-fed9e6c5a407.png)
![screenshot from 2016-03-10 15-16-13](https://cloud.githubusercontent.com/assets/1330166/13672034/5b13432a-e6d3-11e5-9e1b-6e09437a89b5.png)
![screenshot from 2016-03-10 14-54-12](https://cloud.githubusercontent.com/assets/1330166/13672032/5af841c4-e6d3-11e5-8f03-a06be2f19a89.png)

**Comment by bavincen** [comment]
Thank you so much, Need help adding it in wiki page?

Regards

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Add-Your-Calendar-to-Thunderbird
