### ISSUE TITLE
Office365 calendar shows only event status and dates

### ISSUE THREAD

**Issue by mastier** [Ericsson/exchangecalendar#445]
My company switched to Office365, since that time I fetch all calendar events. However, in Title field only shows status like "(Busy)", "(Free)", "(Tentative)" and Start, End Date. Nothing more. EWS s 3.6.0-beta1, Lighting 4.0.5.2.

Can I do something about it ? Can I help you in the development ?

**Comment by ward0285** [comment]
To resolve this issue, I just set up a new calendar to point at the office365 server (enter https://outlook.office365.com/ews/exchange.asmx as the server id).  Works as expected now.

**Comment by bavincen** [comment]
Can you try with  v3.8

**Comment by mastier** [comment]
Now it works! But there was some issue, when I was switching to Office365, it was back switching to Hosted. I created a new one and it works. i believe that issue was on 3.8-beta4. I will check this out when I am back at the office.

Thank you very much for that!
