### ISSUE TITLE
Installation Instructions are not correct, Readme needs to be updates

### ISSUE THREAD

**Issue by hlaub** [Ericsson/exchangecalendar#448]
Hi, 

i was just installing the plugin on 2 machines these days and in the installation instructions are not completely correct. Just minor mistakes if one have a bit of experience. 

### Issue
After running git clone --recursive git://github.com/Ericsson/exchangecalendar.git

the folder name is "exchangecalendar"

Hence cd ./exchangecalendar_master; chmod +x ./build.sh; ./build.sh;

will not work. Also build.sh says i should specify an additional flag, e.g. "-u" for it to work. 

Maybe i am mistaken but i think the instructions need an small update?

**Comment by bavincen** [comment]
Yes it is mistaken

**Comment by tallship** [comment]
Hello Hans,

I'm not certain why the build and pull are required when there's a 
downloadable xpi file in the git repo already - have you tried using 
that and installing it into Thunderbird/Lightning?

**Comment by hlaub** [comment]
Hi Bradley, 

apparently I did not see the ready-made xpi but thought the instructions are for a new build. I got it working easily since it is still quite clear what to do

**Comment by tallship** [comment]
Good to know Hans!

I'm glad that it's working out for you :)

**Comment by bavincen** [comment]
Thanks for path closing,https://github.com/Ericsson/exchangecalendar/commit/5a9ebfb74115ee1ccf63036cc71a9b4a2384f975
