### ISSUE TITLE
Adding a new EWS account broken with 3.6-beta1

### ISSUE THREAD

**Issue by UnitedMarsupials** [Ericsson/exchangecalendar#450]
When I try to use "autodiscovery" (manually setting the URL is greyed out for some reason), I keep getting prompted for password -- until AD disables my account for trying too many times.

With 3.5 (latest _release_ at this time), there is not a problem and audodiscovery presents a URL, which just works. I get prompted for password -- once -- and after that things work.

Tried on two different computers -- something is not right with the beta1.

**Comment by bavincen** [comment]
please check with lastest
