### ISSUE TITLE
Unable to filter task by "Incomplete"

### ISSUE THREAD

**Issue by fmanco** [Ericsson/exchangecalendar#452]
Hello

Using the "Incomplete Tasks" filter isn't working, I consistently see the following output in the log when I select this option:

```
Timestamp: 31-03-2016 11:23:02
Error: NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "Could not extract integer from ":0"" {file: "resource://calendar/modules/ical.js" line: 92}]'[JavaScript Error: "Could not extract integer from ":0"" {file: "resource://calendar/modules/ical.js" line: 92}]' when calling method: [calIDateTime::icalString]
Source File: resource://calendar/modules/calUtils.jsm -> file:///usr/lib/thunderbird-trunk/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calUtils.js
Line: 19
```

I'm using `Thunderbird 41.0a1`, `Lightning 4.3a1` and the last version https://github.com/Ericsson/exchangecalendar/commit/5a9ebfb74115ee1ccf63036cc71a9b4a2384f975 of exchangecalendar. I also tried with the 3.5.0 release but doesn't work either.

**Comment by bavincen** [comment]
Hi
Please help me to reproduce,
Thanks

**Comment by fmanco** [comment]
Hi

This Thunderbird version wasn't working at all for me so I reverted to 38.6 (stable version on Ubuntu LTS) so that I could use this extensions.

Therefore I can't reproduce this nor help you debug this and I think we should close this.

Thanks
