### ISSUE TITLE
connected but no events showing

### ISSUE THREAD

**Issue by iceback** [Ericsson/exchangecalendar#454]
I have installed exchangecalendar-v3.5.0.xpi on ubuntu 14.04.4.  I have added an exchange calendar to thunderbird, given it a week to catch up, deleted and  re-added exchange-based calendar. The cursor-over pop-up says "The calendar <name> is connected to the exchange server."  Using the url directly in a browser I get a wsdl page.  I have several long standing meetings and a couple of recent ones (tests  from co-workers etc) and these are not showing.  Restarting Thunderbird generates a prompt for the exchange server.

We use PBIS for AD session transport.

One inconsistency with the instructions: I do not get asked twice for my password (and don't make it saved).

Should I just go to 3.6?

**Comment by hasues** [comment]
I'm not being prompted for a password either.  I was using 3.6.0 and I was not seeing events either.  I changed my root folder to being / instead of the Calender folder and I'm seeing events.  Instructions may need to be changed.

**Comment by bavincen** [comment]
Please try clearing cache. Retry with old settings.

You can also try creating calendar..

**Comment by hasues** [comment]
I tried clearing the cache and recreating the calender.  The only way I made this work was from what I listed.  The calender went from a working state to one where it would not write.  So I unsubscribed and did what I mentioned and it fixed it *shrug*

**Comment by iceback** [comment]
Clearing which cache exactly?

**Comment by iceback** [comment]
nm.  I think I found the clear cache button. no effect

**Comment by iceback** [comment]
Try for the "/" folder as hasues mentioned I settled for the drop down item for root of mail box (can't get back there for exact phrase) and an event I created earlier reappeared. But now folder properties are dead.
![image](https://cloud.githubusercontent.com/assets/364476/14512881/477d214a-01a0-11e6-8be3-df5d050a3d8e.png)

**Comment by bavincen** [comment]
![capture](https://cloud.githubusercontent.com/assets/8401561/14551186/6ae01900-02ed-11e6-82da-6ad66e2da8ce.PNG)


below you can find my settings

**Comment by hasues** [comment]
Right, see the Path below folder base?  Historically, one was to press the Browse button and go to the Calender folder.  Now, if I don't set it to "/" just as this dialog demonstrates, it will not work.  Contrast this to what the instructions as the user to do upon setup.

**Comment by iceback** [comment]
Pardon me!  No events were showing because no events were there to be shown.  I was pointing at the wrong exchange server.  I may have to go back to that one though as the one I want is not accepting my password.  the autodetection works, and accepts password, but the server it finds lets me try my password thrice and then errors out.  And the support staff refuses to dig in 'cause they're a windows shop'

I believe the tools is working as best it can.
