### ISSUE TITLE
Invite Attendees to events

### ISSUE THREAD

**Issue by HBonart** [Ericsson/exchangecalendar#459]
Create new event, invite attendees, nothing happens.
Error on cout: 
JavaScript error: chrome://calendar/content/calendar-event-dialog.xul, line 1: ReferenceError: exchWebService is not defined

Thunderbird 38.6.0 with Lightning 4.0.5.2 and Exchange EWS Provider 3.6.0 on Linux.

**Comment by jbond00747** [comment]
This appears to be fixed in the latest release (3.7.0). Does that fix the issue for you?

**Comment by HBonart** [comment]
Yes! Thanks!
