### ISSUE TITLE
Error opening Exchange (EWS) Settings - missing translations

### ISSUE THREAD

**Issue by scoopex** [Ericsson/exchangecalendar#46]
If i select "Exchange (EWS) Settings" from the list of my calendars in thunderbird/lightning i get a popup with the follwing message:

"XML-Verarbeitungsfehler: Nicht definierte Entität
Adresse: chrome://exchangecalendar/content/exchangeSettings.xul
Zeile Nr. 79, Spalte 4:			<tab label="&ecsettings.tab.autoprocessingproperties;" />
------------------------^"

Translated: "XML-proccessingerror: entity is not defined, adress: chrome://exchangecalendar/content/exchangeSettings.xul
line Nr. 79, row 4:			<tab label="&ecsettings.tab.autoprocessingproperties;" />

**Comment by bavincen** [comment]
Opened new one https://github.com/Ericsson/exchangecalendar/issues/265
