### ISSUE TITLE
New Event Dialog: Description window grayed out, not writeable

### ISSUE THREAD

**Issue by enozkan** [Ericsson/exchangecalendar#462]
After upgrading to *both* the latest Thunderbird/Lightning (versions 45.0/4.7) and Exchange Calendar (v 3.7.0), the Description window in the New Event dialog is grayed out. Nothing can be written there. Furthermore, the answers to "Title", "Location", "Category" and others are all pushed to the extreme right, and cannot be moved closer by resizing the window. Finally, the formatting options appear below the window, which seems weird, but this is minor and Google Calendars don't have these options (they are not crucial, really). See snapshot below:

![screen shot 2016-04-21 at 1 50 55 pm](https://cloud.githubusercontent.com/assets/1588035/14720951/76aabda4-07c9-11e6-80d8-9a2a45613039.jpg)

v.3.7.0 had correct behavior with older versions of TB/Lightning, and Google Calendars have correct behavior with latest TB/Lightning, so this appears to be an Exchangecalendar problem.

**Comment by brenboy** [comment]
This is exactly the same as the issue I reported here:

https://github.com/Ericsson/exchangecalendar/issues/426

**Comment by enozkan** [comment]
Sorry, I missed that. This is indeed a duplicate, so I'll close it.
