### ISSUE TITLE
Event form display bug in Thunderbird 45.0

### ISSUE THREAD

**Issue by mbacou** [Ericsson/exchangecalendar#464]
Hi,
I recently upgraded to **Thunderbird 45.0** with EWS 3.7.0 (on Windows 7) and noticed the new/edit event form is garbled:

EWS event form
![image](https://cloud.githubusercontent.com/assets/260325/14774056/930d34a0-0a7f-11e6-9ec0-c1e3b6763124.png)

Normal calendar event form
![image](https://cloud.githubusercontent.com/assets/260325/14774069/bab41f5a-0a7f-11e6-8d8b-da560a5fc7fc.png)

**Comment by mbacou** [comment]
Similar problem on xubuntu 16.04:

![screenshot_2016-04-25_01-57-02](https://cloud.githubusercontent.com/assets/260325/14774903/0a6fd6ac-0a89-11e6-89c9-b0f443614f69.png)

**Comment by enozkan** [comment]
This is the same bug as #426 and #462. Long standing issue now. At least you seem to be able to write in the Description window; that one is grayed out for me. I am on a Mac (OS X 10.11).

**Comment by mbacou** [comment]
Thanks!

**Comment by Timberwolf76275** [comment]
I found a fix 
https://github.com/Ericsson/exchangecalendar/issues/468#issuecomment-235841417

**Comment by bavincen** [comment]
This was fixed in code  @Timberwolf76275, this releases were affected by lightning new layout.
