### ISSUE TITLE
Using with egroupware

### ISSUE THREAD

**Issue by Kruemelino** [Ericsson/exchangecalendar#467]
Hi everybody,

For some doay I try to use the Exchange EWS Provider (3.8.0-beta2) together with egroupware, which provides ActiveSync. But it does'n work. I can't connect to the calendar.
- First of all I'm using Lightning 4.7 together with Thunderbird 45.0.
- The Autodiscovery does not work: Fehler bei Autodiscovery:autodiscoverOk error getting ewsUrls from:https://autodiscover.FQDN/autodiscover/autodiscover.xml (-200)
- I found a Testtool (EAS – MD MobilityDojo.net). With this Tool I'm able to check something. Every connectivity test passes successfully and even sync-Test are successfull. But the autodiscover does not work: I get the error:

```
Testing following Autodiscover address:
https://autodiscover.FQDN/autodiscover/autodiscover.xml
Status: PASS

<BODY>
<h3>Error</h3><p>
There was a problem processing the <i></i> command from your PDA.
<p>Here is the debug output:<p><pre>
</pre>
</BODY>
```
- I think autodiscover does not work with egroupware. Ok thats not your fault. But it would be great if I could use your tool to connect to egroupware. 

How can I connect to egroupware? How can I Help you to debug? 

Thanks for your work.

Edit: I forgot: We tried several mobile devices (Android, iOS Windows): all could connect and sync successfull.

**Comment by bavincen** [comment]
did you enter endpoint url?
is it working without autodiscovery
