### ISSUE TITLE
Canceled events are not removed in Office365 EWS

### ISSUE THREAD

**Issue by interj** [Ericsson/exchangecalendar#469]
Hi, ever since my mailbox was migrated to use Office365 exchange from https://outlook.office365.com/EWS/Exchange.asmx auto-remove option for canceled calendar events doesn't seem to work. Also removing events by one seems unreliable - it doesn't always work, sometimes you have to repeat it. Removal of all occurrences of event works fine.

**Comment by bavincen** [comment]
that i found,  not only from office365 also in other way it doesn't work. problem not found yet. once fixed, i will release a beta

**Comment by bavincen** [comment]
Fixed release 3.8

**Comment by interj** [comment]
Looks like it's working properly, thanks.
