### ISSUE TITLE
No Exchange contextual menu with 3.3.0 - missing translations

### ISSUE THREAD

**Issue by klint** [Ericsson/exchangecalendar#47]
Hi
Just installed the 3.3.0 version (thanks for it :) ), and the contextual menus on a Exchange calendar have gone. No way to define  a OoO message anymore, for instance.
Has it been moved elsewhere?
Thanks
Olivier

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/issues/265 New issue is opened
