### ISSUE TITLE
Cannot forward accepted invites

### ISSUE THREAD

**Issue by brenboy** [Ericsson/exchangecalendar#473]
Exchange calendar version: 3.8.0 b2
Lightning version: 4.7
Thunderbird version: 45.0
OS X version: 10.11.4

Forwarding accepted invites is not possible with the latest version of Exchange Calendar because attendees cannot be added to the dialog box after selecting 'Forward Event'.

Very easy to reproduce:
1) Accept invite
2) Right click on accepted invite and select 'Forward Event'
3) Try to add attendees in the dialog box that opens

**Comment by sektorcap** [comment]
Same issue here with all invites (accepted and not accepted).
Exchange calendar version: 3.8.0 b3
Lightning version: 4.0.5.2
Thunderbird version: 38.7.2
Ubuntu: 14.04 LTS

**Comment by Giuse69** [comment]
yes, the forward only works if the invitation is made by me

**Comment by dmolin93** [comment]
Can confirm, had this issue aswell. I rolled back to v3.5.0 and it now works.

**Comment by viktorgunnarson** [comment]
Same issue for me.

Exchange calendar version: 3.8.0 b2
Lightning version: 4.0.8
Thunderbird version: 38.8.0
Ubuntu: 14.04.4 LTS

**Comment by bavincen** [comment]
Fixed release 3.8
