### ISSUE TITLE
Cancelled events not removed from Calendar

### ISSUE THREAD

**Issue by brenboy** [Ericsson/exchangecalendar#474]
Exchange calendar version: 3.8.0 b2
Lightning version: 4.7
Thunderbird version: 45.0
OS X version: 10.11.4

In my Exchange Calendar set up I have the following:

<img width="760" alt="screen shot 2016-05-06 at 10 58 25 am" src="https://cloud.githubusercontent.com/assets/11042234/15061490/82b5b91c-1379-11e6-8beb-9f1381708751.png">

However, when I receive a cancellation for an event, the event Title is simply renamed to "Cancelled: .." and the event remains in my calendar. This has been happening for a few releases of Exchange Calendar but I don't know if it is an Exchange issue or an issue with the add-on. 

In OWA, the cancellation has a 'Remove from Calendar' option and it is not automatically removed from the OWA calendar either.

<img width="316" alt="screen shot 2016-05-06 at 11 08 29 am" src="https://cloud.githubusercontent.com/assets/11042234/15061634/ee074644-137a-11e6-9764-38777e338f98.png">

**Comment by bavincen** [comment]
yes found bug :)

**Comment by userrl** [comment]
To add to this, if the cancelled event is a series and you manually right-click one of the events and choose "Delete Event", only that single event is deleted.  Is there a way to make this delete the entire series if the name starts with "Canceled: "?  Alternatively, is there a way to intercept any event delete and pop up a dialog asking if the user wants to delete a single event or the entire series?

**Comment by bavincen** [comment]
53d533b7a67aeccb7bfef309edb9a9887ac8980c

**Comment by bavincen** [comment]
c6836f400ffe32fd15da729e53547599890e292c
