### ISSUE TITLE
Exchange inbox folder can not be deleted

### ISSUE THREAD

**Issue by nmaarse** [Ericsson/exchangecalendar#475]
I was able to succesfully add a folder in the Thunderbird inbox and it showed in my Outlook. Both connect to the Exchangeserver.

However deleting the folder results in the following error:
![image](https://cloud.githubusercontent.com/assets/7762028/15172410/28af8ab6-1756-11e6-9aa2-6e3c27a7c398.png)

The folder is not deleted in Exchange. I was able to delete the folder in my outlook but the changes did not propagate back to Thunderbird. Only after i started to work offline and than reconnected i was able to delete the folder in thunderbird.

Also from the 5 folder in my inbox of exchange (where 1 has subfolder ) only 2 are shown in thunderbird. Maybe that is related to this bug.

**Comment by Mechtilde** [comment]
Hello,


Am 11.05.2016 um 08:57 schrieb nmaarse:
> I was able to succesfully add a folder in the Thunderbird inbox and it showed in my Outlook. Both connect to the Exchangeserver.
> 
> However deleting the folder results in the following error:
> ![image](https://cloud.githubusercontent.com/assets/7762028/15172410/28af8ab6-1756-11e6-9aa2-6e3c27a7c398.png)
> 
> The folder is not deleted in Exchange. I was able to delete the folder in my outlook but the changes did not propagate back to Thunderbird. 
> 
> Also from the 5 folder in my inbox of exchange (where 1 has subfolder ) only 2 are shown in thunderbird. Maybe that is related to this bug.
> 

this seems to be a problem between your thunderbird installation and
your Exchange account.

I don't know what "thunderbirdsAreGo" is.

The Add-On exchangecalender doesn't support mail only the calender and
tasks at the exchangeserver.

Regards

Mechtilde
