### ISSUE TITLE
No attendees displayed

### ISSUE THREAD

**Issue by trourance** [Ericsson/exchangecalendar#482]
Hello,

I'm using TB 45.1, Lightning 4.7.1 and Exchange EWS Provider 3.7.0. 
I synchronize my calendar with Exchange Server 2013.
I can see the meetings, but when I want to see the detail, I can't see the required attendees, nor the optional attendees. Their names are not displayed.

![capture du 2016-06-01 16-28-07](https://cloud.githubusercontent.com/assets/6951977/15713317/41998bdc-2816-11e6-8939-02f07dd627ff.png)

**Comment by bavincen** [comment]
Please update to 3.8 beta 3

**Comment by fluancefg** [comment]
I have installed the 3.8 beta3 version, but I still have the same problem

**Comment by bavincen** [comment]
Font color and background color creates the problem?

**Comment by fluancefg** [comment]
How can I confirm that ?

**Comment by bavincen** [comment]
Are you using any custom theme?
Disable it for now and restart tb

**Comment by fluancefg** [comment]
No, I use the default one

**Comment by bavincen** [comment]
why said i can see yellow dots and green ticks.  looks like default theme is over ridden try reinstalling thunderbird

**Comment by AdnanHodzic** [comment]
I have this same problem. Using 3.8.0, and I don't use any custom themes. Yesterday I even remove my whole whole Thunderbird profile to start over in hope this problem would be fixed. However, without nothing changed. 

I'm using Debian Linux (Stretch) with Icedove (Thunderbird) 45.2 if that helps.

**Comment by trourance** [comment]
Reinstalling TB does not fix the problem

**Comment by AdnanHodzic** [comment]
It also might be noting that same problem doesn't exist on Ubuntu GNOME 16.04. With same Thunderbird version and same settings as well extensions and their versions.

**Comment by bavincen** [comment]
Guess this issues occurred due to different locale.

Can you check with default locale (English) are you facing any issues?

**Comment by keforbes** [comment]
I see the same thing, though for me it's an issue with XFCE themes.  Are you guys also using XFCE?

**Comment by bavincen** [comment]
what is your TB language ? @keforbes

**Comment by keforbes** [comment]
I'm using english.  en_US.

**Comment by trourance** [comment]
I'm using cinnamon and fr_CH locale.

**Comment by AdnanHodzic** [comment]
I'm using en_US for language (also have nl_NL enabled for formats: dates/numbers/measurements/etc...) on GNOME 3.20

**Comment by Zlopez** [comment]
I have the same issue in TB 45.2.0 EWS 3.8.0 on Fedora 24. My language is en_US and I'm using Gnome 3.20.4.

**Comment by Zlopez** [comment]
I have the same issue in TB 45.2.0 EWS 3.8.0 on Fedora 24. My language is en_US and I'm using Gnome 3.20.4.
Here is output from error console, when I open event details:
onStateChange: aStateFlags:(65537),STATE_START,STATE_IS_REQUEST, aStatus:0
onStateChange: aStateFlags:(65552),STATE_STOP,STATE_IS_REQUEST, aStatus:2152398850
onStateChange: aStateFlags:(983041),STATE_START,STATE_IS_REQUEST,STATE_IS_DOCUMENT,STATE_IS_NETWORK,STATE_IS_WINDOW, aStatus:0
onStateChange: aStateFlags:(786448),STATE_STOP,STATE_IS_NETWORK,STATE_IS_WINDOW, aStatus:0
onStateChange: aStateFlags:(65537),STATE_START,STATE_IS_REQUEST, aStatus:0
onStateChange: aStateFlags:(65552),STATE_STOP,STATE_IS_REQUEST, aStatus:0
onLocationChange: aLocation.spec:file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html, aFlags:(0)
onSecurityChange: aState:(4),STATE_IS_INSECURE
onStateChange: aStateFlags:(65537),STATE_START,STATE_IS_REQUEST, aStatus:0
Security Error: Content at file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html may not load or link to about:blank.
onStateChange: aStateFlags:(196612),STATE_TRANSFERRING,STATE_IS_REQUEST,STATE_IS_DOCUMENT, aStatus:0
onProgressChange: aCurSelfProgress:7437, aMaxSelfProgress:7437, aCurTotalProgress:7437, aMaxTotalProgress:7437
onStateChange: aStateFlags:(65552),STATE_STOP,STATE_IS_REQUEST, aStatus:0
Timestamp: 24.8.2016 11:52:41
Warning: Unknown descriptor 'panose-1' in @font-face rule.  Skipped to next declaration.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 13, Column: 9
Source Code:
 panose-1:5 0 0 0 0 0 0 0 0 0;}
Timestamp: 24.8.2016 11:52:41
Warning: Unknown descriptor 'panose-1' in @font-face rule.  Skipped to next declaration.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 16, Column: 9
Source Code:
 panose-1:2 4 5 3 5 4 6 3 2 4;}
Timestamp: 24.8.2016 11:52:41
Warning: Unknown descriptor 'panose-1' in @font-face rule.  Skipped to next declaration.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 19, Column: 9
Source Code:
 panose-1:2 15 5 2 2 2 4 3 2 4;}
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'mso-fareast-language'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 26, Column: 21
Source Code:
 mso-fareast-language:EN-US;}
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'mso-style-priority'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 28, Column: 20
Source Code:
 {mso-style-priority:99;
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'mso-style-priority'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 32, Column: 20
Source Code:
 {mso-style-priority:99;
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'mso-style-name'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 36, Column: 16
Source Code:
 {mso-style-name:msonormal;
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'mso-margin-top-alt'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 37, Column: 19
Source Code:
 mso-margin-top-alt:auto;
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'mso-margin-bottom-alt'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 39, Column: 22
Source Code:
 mso-margin-bottom-alt:auto;
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'mso-style-type'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 44, Column: 16
Source Code:
 {mso-style-type:personal-compose;
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'mso-style-type'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 48, Column: 16
Source Code:
 {mso-style-type:export-only;
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'mso-fareast-language'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 51, Column: 21
Source Code:
 mso-fareast-language:EN-US;}
Timestamp: 24.8.2016 11:52:41
Warning: Expected '{' to begin declaration block but found 'WordSection1'.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 52, Column: 6
Source Code:
@page WordSection1
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'page'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 56, Column: 6
Source Code:
 {page:WordSection1;}
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'text-autospace'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 0, Column: 14
Source Code:
text-autospace:none
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'mso-margin-top-alt'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 0, Column: 18
Source Code:
mso-margin-top-alt:3.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:16.0pt;line-height:125%;text-autospace:none
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'text-autospace'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 0, Column: 113
Source Code:
mso-margin-top-alt:3.0pt;margin-right:0cm;margin-bottom:12.0pt;margin-left:16.0pt;line-height:125%;text-autospace:none
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'text-autospace'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 0, Column: 34
Source Code:
margin-bottom:2.0pt;text-autospace:none
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'mso-fareast-language'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 0, Column: 79
Source Code:
font-size:14.0pt;border:solid windowtext 1.0pt;padding:0cm;mso-fareast-language:CS
Timestamp: 24.8.2016 11:52:41
Warning: Unknown property 'text-autospace'.  Declaration dropped.
Source File: file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html
Line: 0, Column: 52
Source Code:
margin-bottom:10.0pt;line-height:115%;text-autospace:none
Security Error: Content at file:///home/mkonecny/.thunderbird/zpvzc20f.default/exchange-data/tmp/3a8ff8e0-eeb6-425d-88bf-3b382590cc24.html may not load or link to about:blank.
onStateChange: aStateFlags:(65552),STATE_STOP,STATE_IS_REQUEST, aStatus:0
onStateChange: aStateFlags:(65537),STATE_START,STATE_IS_REQUEST, aStatus:0
onStateChange: aStateFlags:(65537),STATE_START,STATE_IS_REQUEST, aStatus:0
onStateChange: aStateFlags:(65552),STATE_STOP,STATE_IS_REQUEST, aStatus:0
onStateChange: aStateFlags:(65552),STATE_STOP,STATE_IS_REQUEST, aStatus:0
onStateChange: aStateFlags:(131088),STATE_STOP,STATE_IS_DOCUMENT, aStatus:0
onStateChange: aStateFlags:(786448),STATE_STOP,STATE_IS_NETWORK,STATE_IS_WINDOW, aStatus:0
onStateChange: aStateFlags:(65537),STATE_START,STATE_IS_REQUEST, aStatus:0
onStateChange: aStateFlags:(65540),STATE_TRANSFERRING,STATE_IS_REQUEST, aStatus:0
onProgressChange: aCurSelfProgress:823, aMaxSelfProgress:823, aCurTotalProgress:0, aMaxTotalProgress:0
onStateChange: aStateFlags:(65537),STATE_START,STATE_IS_REQUEST, aStatus:0
onStateChange: aStateFlags:(65552),STATE_STOP,STATE_IS_REQUEST, aStatus:0
onStateChange: aStateFlags:(65552),STATE_STOP,STATE_IS_REQUEST, aStatus:0
onStateChange: aStateFlags:(65537),STATE_START,STATE_IS_REQUEST, aStatus:0
onStateChange: aStateFlags:(65552),STATE_STOP,STATE_IS_REQUEST, aStatus:0

**Comment by keforbes** [comment]
Update.  This problem no longer occurs for me.  I'm not sure what changed or what package updated but I can view attendees now.

**Comment by bavincen** [comment]
Can you try to change update options in Preference.'
I would suggest Clearing cache..
Regards

**Comment by trourance** [comment]
I have installed the latest 3.9.0 version, but I can't see any update options in preferences. I had to manually clear the cache. All the attendees are displayed now for the previous meetings, but I don't know for the future one, I'll to wait to receive a new meeting invitation.

**Comment by trourance** [comment]
Ok, with the latest version I can see the attendees again.
