### ISSUE TITLE
Event edit form broken by exchangecalendar

### ISSUE THREAD

**Issue by fthommen** [Ericsson/exchangecalendar#485]
When exchangecalendar (v 3.7) is enabled (all other add-ons disabled), the event edit form is broken (TB 45.1.1 on Mac OS X 10.9.5).

**Editor with add-on enabled:** Form fields wrongly placed, no description can be entered: 
![event_edit_with_exchangecalendar](https://cloud.githubusercontent.com/assets/279232/16133073/51045b36-3416-11e6-81bf-188c195a13eb.png)

**Editor with add-on disabled;**
![event_edit_wo_exchangecalendar](https://cloud.githubusercontent.com/assets/279232/16133071/50b1542c-3416-11e6-8f58-be8af2e51f38.png)

**Comment by brenboy** [comment]
This has been discussed previously:
https://github.com/Ericsson/exchangecalendar/issues/426
https://github.com/Ericsson/exchangecalendar/issues/462

The fix is to upgrade to the latest 3.8 beta release

**Comment by bavincen** [comment]
Please use latest release. This issue already fixed

**Comment by Mechtilde** [comment]
It is fixed in version 3.8-beta3. This version is prepared to Debian Experimental.

**Comment by fthommen** [comment]
v3.8-beta3 fixed the issue.  Thx
