### ISSUE TITLE
SHA1SUM not updated

### ISSUE THREAD

**Issue by canepan** [Ericsson/exchangecalendar#491]
Hi, the SHA1SUM for 3.8.0-beta3 is the same as for beta2.
Can you update it?

I assume it's for the .xpi, not for the sources, correct?

Thank you

**Comment by pstieber** [comment]
It looks like this is a cut & paste error. I'm getting the correct value for v3.8-beta2 .xpi file, but 63c367ae201c1bff26bdf41b7a1573d872ddaf2f for v3.8-beta3.

**Comment by bavincen** [comment]
openssl sha1 <file>

found error checksum in 3.8.0-beta3 update now. please check
