### ISSUE TITLE
Line submission from output

### ISSUE THREAD

**Issue by MarkSRobinson** [Ericsson/exchangecalendar#492]
1st-setup:2016-6-2 9:50:17.545:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})

1st-setup:2016-6-2 9:50:18.122:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({69150b77-b561-43a2-bfba-7301dd5a35d0})

1st-setup:2016-6-2 9:50:18.123:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({f6a0d1e5-369f-4abc-81ae-d370d36e4006})

So I'm getting many of these lines in my console output.

**Comment by bavincen** [comment]
if u are using any different authentication method. if u have any issues with calendar.
what is your calendar type btw?..

Thanks

**Comment by MarkSRobinson** [comment]
I have an exchange calendar and it seems to work fine, more or less.

I'm also using ExQuilla to access my mail in Thunderbird and that's handling the authentication to EWS.

**Comment by bavincen** [comment]
closing
