### ISSUE TITLE
*All* releases are corrupted, and *none* validate their checksum

### ISSUE THREAD

**Issue by samandiriel** [Ericsson/exchangecalendar#493]
Something has seriously corrupted every downloadable XPI from the latest beta down to at least v3.6.0

**Comment by pstieber** [comment]
It looks like there is a cut & paste error in the sha1sum for v3.8-beta3 because it is identical to the one for v3.8-beta2.  I'm getting the correct value for v3.8-beta2, but 63c367ae201c1bff26bdf41b7a1573d872ddaf2f for v3.8-beta3.

**Comment by samandiriel** [comment]
My downloads didn't match the checksum for any version, and trying to 
install them produced errors in tbird saying that they were corrupt :/

**Comment by bavincen** [comment]
openssl sha1 <file>

found error checksum in 3.8.0-beta3 update now. please check
