### ISSUE TITLE
Can't create new calendar

### ISSUE THREAD

**Issue by mdev34** [Ericsson/exchangecalendar#496]
First off, great tool!
I just upgraded my OS to OpenSuSE 13.2 (kernel 3.16.7-35-desktop) and installed Thunderbird 45.2 with Lightning 4.7.2. When I tried to add our company's Exchange calendar, Exchange Provider 3.8.0 beta 4 blocks me at the configuration page. No matter what I enter the "Next" button remains greyed out. Installing Provider 3.8.0 beta 3 fixed the problem and all works fine. We're not using Office 365.

**Comment by bavincen** [comment]
Hello
Please post a screenshot of beta4 issue
It will help for fixing

Thanks

**Comment by mdev34** [comment]
![details](https://cloud.githubusercontent.com/assets/20532630/16942744/0bcbe6e2-4d98-11e6-9bd9-30f8814a6af9.png)
Note that I can't manually enter the exchange server URL (can't type in "URL" box), and autodiscovery seems to work (suggests correct URL and finds calendar folder) but the contents of the "server URL" box remain greyed out. The "Next" button is permanently greyed out.

**Comment by kohlerm** [comment]
Same here, same Thunderbird version, RHEL 7.2 OS

**Comment by kohlerm** [comment]
Apparently  3.8.0 beta 3 also only works with "autodiscovery"

**Comment by bavincen** [comment]
f9b326d79a91137c769d4c91a3b71d5674fad9a2

**Comment by mdev34** [comment]
That fixed it, the modified beta 4 version works with my config. Thanks!
