### ISSUE TITLE
Feature request: Show calender on appointment requests

### ISSUE THREAD

**Issue by scoopex** [Ericsson/exchangecalendar#501]
Thanks for writing this great thunderbird extension.

It would be great to have a convenient possibility to review a certain calendar day if a appointment request is received. 

A appointment request should provide a overview of the day of the appointment or a button "show in calendar"  to ease the decision to deny, accept or tentatively accept the appointment.

**Comment by bavincen** [comment]
How about ews propose new time feature?
The attendee will be allowed to suggest a new time for event.
Btw. Accepting , declining is part of calendar item it can't be manipulated by event time

**Comment by scoopex** [comment]
Outdated, obsolete.
