### ISSUE TITLE
XUL guide mentioned in the readme.md

### ISSUE THREAD

**Issue by iselind** [Ericsson/exchangecalendar#515]
The XUL guide referenced in readme.md
https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions/XUL_School

Start with a big warning box:
We are planning to deprecate the use, in Firefox, of the techniques described in this document.

Don't use these techniques to develop new add-ons. Use WebExtensions or the Add-on SDK instead.

If you maintain an add-on which uses the techniques described here, consider migrating it to use WebExtensions or the SDK instead.
[...]

Are these changes something that is planned for this extension?

**Comment by rkent** [comment]
Thunderbird is not Firefox. There are no current plans to eliminate
XUL-based addons from Thunderbird, though if they are truly eliminated
from the core Mozilla code it would make our continuing support very
difficult.

Kent James

**Comment by iselind** [comment]
I think these kind of things might start with Firefox and with time propagate to other apps...
