### ISSUE TITLE
Error while checking server settings

### ISSUE THREAD

**Issue by Markko** [Ericsson/exchangecalendar#523]
Calendar stopped syncing on updating to thunderbird 49.0 and lightening 5.1b1
when adding a new calender an error pops up with 

```
Error during checking of server and mailbox: HTTP Client error 401: Unauthorized
URL:https://[REDACTED].com/EWS/Exchange.asmx
 (Code: -19)
```

the error console shows the following    -> 

```
Timestamp: 09/20/2016 04:21:03 PM
Error: SyntaxError: missing ] after element list
Source File: chrome://exchangecalendar/content/msgHdrUtils.js
Line: 219, Column: 21
Source Code:
let toAdd = [x.key for each ([, x] in Iterator(newTagList))
    if (!(x.key in oldTags))];
```

**Comment by guikcd** [comment]
Same issue for me, removing/reinstalling the plugin does the same.

Thunderbird : 45.3.0+build1-0ubuntu0.16
Lightning : 4.7
Exchange EWS Provider : 3.8.0

**Comment by Markko** [comment]
@guikcd  I was able to work around this by _fixing_ the syntax error, then in the error console, clicking on the link for "resource not found" which then would prompt me to login. when I save my password that way, the plugin works intermittently

**Comment by guikcd** [comment]
@Markko i confirm that doing what you suggest "fix" the issue.

**Comment by bavincen** [comment]
#531

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/releases/tag/v3.9-beta1
