### ISSUE TITLE
Office365 calendar no longer prompts for new password

### ISSUE THREAD

**Issue by jlcenter** [Ericsson/exchangecalendar#525]
I just changed my password for Office365 & my EWS calendar can no longer sync with it.  I don't get prompted for a new password.  I tried to remove, then recreate the calendar, but I get the same error:

Error during checking of server and mailbox: HTTP Client error 401: Unauthorized
URL:https://outlook.office365.com/EWS/Exchange.asmx

 (Code: -19)

I was never prompted for a password when I recreated the calendar.

I'm running TB 49 on Ubuntu 16.04, with Exchange EWS Provider v3.8.0.

**Comment by jlcenter** [comment]
I was eventually able to force the password change by removing the email address & only filing in the username.  I was then prompted for the new password.  This still failed, but I next put in the email address & checked again.  This time the calendar configuration completed.

**Comment by bavincen** [comment]
found the bug fixing in next release

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/releases/tag/v3.9-beta1

**Comment by reiabreu** [comment]
Hello. I've experienced this bug with  Exchange EWS Provider v3.9.0. Reverted to v3.9-beta1 and it works
