### ISSUE TITLE
Tasks with dates are not showed in the calendar view in TB 31.3.0 in MacBook Pro Retina 10.9.5

### ISSUE THREAD

**Issue by lukaszp** [Ericsson/exchangecalendar#53]
Tasks with dates are not showed in the calendar view in TB 31.3.0 in MacBook Pro Retina 10.9.5. Tasks are only shown for a moment after creation and disappear after doing simple actions like switching to different view and back.

I am a programer and am offering my help in fixing it if someone points me to the place in the code where it is broken.

Thanks

**Comment by bavincen** [comment]
closing it for now..
please repopen if it exists

**Comment by ghost** [comment]
I've the same problem TB 52.2.1 on linux (Ubuntu 16.04) with Lightning 5.4
