### ISSUE TITLE
Can not add an Office 365 Calendar nor AddressBook

### ISSUE THREAD

**Issue by mccaan** [Ericsson/exchangecalendar#530]
Every time I try to add a new Office 365 Calendar, I get the following error:

Error during checking of server and mailbox: HTTP Server error 503: Service unavailable
URL:https://outlook.office365.com/EWS/Exchange.asmx

 (Code: -19)

**Comment by mccaan** [comment]
The error is only with version 3.8.0, with 3.7.0 works fine

**Comment by bavincen** [comment]
#531

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/releases/tag/v3.9-beta1
