### ISSUE TITLE
Password not being accepted when trying to add a Calendar

### ISSUE THREAD

**Issue by andymwood** [Ericsson/exchangecalendar#531]
I've been following the instructions on this page: https://github.com/Ericsson/exchangecalendar/wiki/How-to-Add-Your-Calendar-to-Thunderbird

At step 5, after clicking 'Check server and mailbox', a pop-up appears requesting my password. Each time I enter my password, the pop-up immediately re-opens to request it again. It doesn't spend any time even trying to connect. After four attempts at this I get another pop-up with the message "Error during checking of server and mailbox: HTTP Client error 401: Unauthorized
URL:https://outlook.office365.com/ews/exchange.asmx  (Code: -19)"

**Comment by dholm** [comment]
I got this error when using Thunderbird 50.0b1.  After I downgraded to 45.3.0 it started working again and the "401: Unauthorized" error went away.

**Comment by bavincen** [comment]
#531 fixed c0de9f89572f8d02b1643f59365d79393e459c3b

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/releases/tag/v3.9-beta1

**Comment by Markko** [comment]
I am still receiving this error. 
I get a password prompt, but it does not authorize.

**Comment by tyldum** [comment]
I have the same:
1st-setup:2016-9-1 13:36:5.750:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({70d2b4fe-a552-48cd-8d93-1d8437a56b53})
1st-setup:2016-9-1 13:36:5.762:1e873fc2-fb6e-483b-a35f-4f2b924531e4: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2016-9-1 13:36:5.772:ffe1972d-ef88-4026-a3a4-30a7f9537f41: : ExchangeRequest.loadstart
1st-setup:2016-9-1 13:36:5.788:1e873fc2-fb6e-483b-a35f-4f2b924531e4: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2016-9-1 13:36:5.797:1e873fc2-fb6e-483b-a35f-4f2b924531e4: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2016-9-1 13:36:5.812:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({1040ebe3-6ed1-45a6-8587-995e082518d7})
1st-setup:2016-9-1 13:36:5.826:1e873fc2-fb6e-483b-a35f-4f2b924531e4: ecnsIAuthPrompt2.getInterface: Ci.nsIApplicationCacheContainer
1st-setup:2016-9-1 13:36:5.839:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
