### ISSUE TITLE
this.details[aURL] not defined

### ISSUE THREAD

**Issue by jobisoft** [Ericsson/exchangecalendar#544]
Fresh install of 3.9.0-beta1

1. Adding new EWS addressbook
2. Performimg "Server and Account Check"
3. Get prompted for password

TypeError: this.details[aURL] is undefined
/extensions/exchangecalendar@extensions.1st-setup.nl/interfaces/exchangeAuthPrompt2/mivExchangeAuthPrompt2.js
Line: 237

Something needs to be done about line 206.

**Comment by jobisoft** [comment]
In the released xpi for 3.9.0-beta1, line 206 in that file is commented out. This is not the case in master branch or the ec3.9.0. The file in this repo has not been touched for a year.

Very odd.

**Comment by tyldum** [comment]
Same here. Running Earlybird (plain Thunderbird uses 100% CPU and freezes, even with clean profile).

**Comment by bavincen** [comment]
issue Fixed
