### ISSUE TITLE
Not working after Update to SM 2.46/Lightning 5.1b1/EWS Provider 3.9.0b2

### ISSUE THREAD

**Issue by joalbach** [Ericsson/exchangecalendar#555]
After Updating Seamonkey, access to the Exchange Calendar is broken.

I tested the following Versions:
SM 2.46/Lightning 5.1b1/EWS Provider 3.9.0b2
SM 2.46/Lightning 5.1b1/EWS Provider 3.8.0
SM 2.47/Lightning 5.2b1/EWS Provider 3.9.0b2
(all on Windows 32)

Error Message: Dialog Box when setting up a new calendar:
Fehler bei der Abfrage des Servers und des Postfachs: HTTP Client error 401: Unauthorized
URL:https://ex-nlb.uni-giessen.de/EWS/Exchange.asmx
(Code: -19)

Last working version:
SM 2.40/Lightning 4.5b1/EWS Provider 3.5.0b1

**Comment by bavincen** [comment]
f7454c6
