### ISSUE TITLE
Missing buttons on meeting invitations

### ISSUE THREAD

**Issue by tfft** [Ericsson/exchangecalendar#56]
Hi, I'm using TB-31.3.0, Lightning-3.3.1 and Exchange-EWS-3.3.0 on windows-7 (64-bit) and will constantly not see any buttons (workflow - accept, reject, ...) on my meeting invitations unless I restart TB.  Its as though Ex-EWS doesn't see the invitation unless the application is reloaded even though I do get the light blue banner that says "This message contains an invitation to an event" but I'm simply unable to do anything about it and the invite doesn't show-up on the calendar at all (not even as a tentative grayed-out meeting).

In passing, I'm using the following as Extension add-ons,
 - Account Colors 8.2
 - Change quote and reply format 0.8.6 
 - CompactHeader 2.0.9
 - Extra Folder Columns 1.1.5
 - Forward 0.18
 - Header Tools Lite 0.5.2
In case there are any potential cross-add-on interference(s).

Let me know what other information is needed in order to properly debug this pesky issue.

Thanks.

**Comment by tfft** [comment]
The problem is still there on 3.3.1-RC2 - see attached image (no buttons on that blue'ish banner on the right).  Note that I don't get any errors in the error console for the invite email !

![capture1](https://cloud.githubusercontent.com/assets/10126620/6096627/6348bea4-afb5-11e4-9e64-231ac3d44c6e.png)

**Comment by bavincen** [comment]
We have commited a chenge, please reopen if issues exist
Thank you!

**Comment by aledovsky** [comment]
Finally! This has bugged me for a long time :+1: 
Can confirm that buttons do appear for new invitations.
