### ISSUE TITLE
Error attempting to respond to meeting requests

### ISSUE THREAD

**Issue by davidilieberman** [Ericsson/exchangecalendar#57]
I have a calendar configured to use the Office365 EWS service. My account is configured to send iCal format messages through IMAP. When I attempt to respond to a message containing an invitation, I get a pop-up error: "Error on getting erGetMeetingRequestByUIDRequest: ErrorExceededFindCountLimit (-8).

**Comment by dcolascione** [comment]
I still see this error constantly

**Comment by ilmari** [comment]
@bavincen Why was this closed? Your comment isn't very informative.
I'm still seeing this error, with Exchange EWS Provider 3.7.0 and Thunderbird 38.7.0

**Comment by bavincen** [comment]
Hi the enhancement patch was applied by me sometimes ago. Seems it's not
working fine with office365
Will check. Please reopen

**Comment by ilmari** [comment]
I am not using Office365, but an on-premises Exchange server. The Outlook Web App's "About" page reports the following:

Version: 14.2.390.1
Client Access server version: 14.2.247.0
Mailbox server Microsoft Exchange version: 14.2.247.0
