### ISSUE TITLE
Can't accept invitation to meetings

### ISSUE THREAD

**Issue by trourance** [Ericsson/exchangecalendar#579]
Hi, I'm using the latest 3.9.0 version. 
I can't confirm my participation to meetings anymore without sending a reply.
I'm forced to edit the answer before sending it, or it's not sent at all and the status keeps in temporary.
But even when I do that, the meeting appears in the calendar, but the invitations stays in my email as if I had not answered.

**Comment by tjbwyk** [comment]
The same..

**Comment by jdkloe** [comment]
confirmed on my side as well.

**Comment by kstripp** [comment]
Seems to be the same behavior that I started getting this week after our IT did a "service update".  (They of course didn't specify anything more detailed than that)

Might be duplicate of #542

**Comment by jdbarnesusc** [comment]
same problem here. what logs/files can we attach to this to help? it is the worst with multiple meeting requests.
