### ISSUE TITLE
Invite doesn't show on calendar

### ISSUE THREAD

**Issue by tfft** [Ericsson/exchangecalendar#58]
Hi, I'm using TB-31.3.0, Lightning-3.3.1 and Exchange-EWS-3.3.0 on windows-7 (64-bit) -- I get a meeting invite, I accept, the email message vanishes yet nothing appears on the lightning calendar (I do know that the meeting made it to exchange server cause I'm able to see it on my phone using "Touchdown" - when I accept I tend NOT to send an acknowledgement email).  A couple of comments,

 1. Why do I need to restart TB to have the meeting show-up in lightning ?  Why doesn't it show-up automatically once the invite is accepted ?
 2. Is there a way to control whether the invite vanishes or not ?  Can a variable be added (default to do whatever it does now) to give the user the ability to possibly keep the invite in the mailbox maybe marked as "Processed !" ?

I am not using "exchange-cache" in case that matters.  I also have refresh set to "Every 15 minutes" though I'd expect upon an event a forced refresh would be in order (btw: the above is still there an hour into the invite acceptance).  If I select my calendar and select synchronize, nothing changes and my accepted meeting still doesn't show-up.

At this point - no email invitation is there (it vanished upon acceptance) and no event in the TB lightning calendar - so no track record of the invite which is a bit concerning unless I restart the application.

Thanks.

**Comment by bavincen** [comment]
Hello, Can u please check our latest code and update..

**Comment by aledovsky** [comment]
On latest (f3ff6a2e59) self-built XPI this is unfortunately present.
I can replicate it every time when click on newly received meeting "Accept" button that was fixed in #56 (and also choosing e-mail confirmation). Only TB restart helps

**Comment by bavincen** [comment]
Hi 🙋 
Please check, is your cache enabled.
If you are manually updating, disable cache and enable again. This creates new data in cache

If your using auto-update(probably not working for now because of naming of addon which we are checking )

Or I'm not sure if u had forwarded similar event from more than one Time this problem occurs.

One question is that happening frequently?


-----Original Message-----

**Comment by aledovsky** [comment]
> Please check, is your cache enabled.


![screen shot 2015-02-18 at 15 05 53](https://cloud.githubusercontent.com/assets/2079110/6247650/aca8527c-b77f-11e4-831a-4c66ec2e2838.png)
Probably this means that it is disabled.

> If your using auto-update(probably not working for now because of naming of addon which we are checking )

I do have "Automatically check for a new addon version..." checkbox active, but that can't be the culprit as __I've built extension from GitHub source__. That is, I run latest available code.

> Or I'm not sure if u had forwarded similar event from more than one Time this problem occurs.
> One question is that happening frequently?

Yes, it happens every time when I receive new invite and press "Accept" button & send confirmation.

I previously didn't have logging enabled, but for next occurrence I will check what is present there

**Comment by bavincen** [comment]
I see. Are you using mac osx?

-----Original Message-----

**Comment by aledovsky** [comment]
@bavincen Yes, OS X 10.10.2. Also Thunderbird  is on version 31.4.0 and Lightning is 3.3.3

**Comment by bavincen** [comment]
@aledovsky  We are unable to check that bug. Detail log will help us to find the problem. Thank!

**Comment by aledovsky** [comment]
@bavincen
 
I must revert my previous claim that it happens _every time_. It took quite some time to be able to witness it happening again. Also, once got logs (supposedly containing info on this bug) truncated after Thunderbird restart.

As you understand, these logs contain sensitive information, so before publicly posting it I need to scrub and anonymize all tricky data.

**Comment by bavincen** [comment]
Yes! I understand. If you are developer you may help us to resolve bugs related to macos.  😊
We can share knowledge  about the bugs and resolve it.
Sorry to say our environment is not mac.

**Comment by bavincen** [comment]
this is fixed with latest version please use beta5
