### ISSUE TITLE
ExchangeCalendar error on lightning nightly and aurora (now on release SeaMonkey too - 2.32)

### ISSUE THREAD

**Issue by Dominique-2202** [Ericsson/exchangecalendar#59]
Hello,

I a using exchangecalendar with the following setup:
Windows desktop 8.1
Seamonkey nightly (2.34a1) or Aurora (2.33a2)
Nightly: ftp://ftp.mozilla.org/pub/seamonkey/nightly/latest-comm-central-trunk/
Aurora: ftp://ftp.mozilla.org/pub/seamonkey/nightly/latest-comm-aurora/
(note: Seamonkey http://www.seamonkey-project.org/ is a suite combining Firefox and Thunderbird, along with a composer and an IRC client. Seamonkey is based on code from FF and TBird).

Lightning nightly (3.9a1) or Aurora (3.8a2)
Nightly: ftp://ftp.mozilla.org/pub/mozilla.org/calendar/lightning/nightly/latest-comm-central/
Aurora: ftp://ftp.mozilla.org/pub/mozilla.org/calendar/lightning/nightly/latest-comm-aurora/

I use exchangecalendar on an Exchange corporate system, for tasks and calendaring. I have two subscribed calendars in my setup.

With the latest 3.3.0 or the current github version of exchangecalendar, I get the following errors when starting Email (no error for my other calendars, either on Gmail or else). These errors appear within a small window each:

First error:

An error was encountered preparing the calendar located at https://auto/<alpha-num-string> for use. it will not be available.

Details

error Code: 0x80570015
Description: [Exception... "Component returned failure code: 0x80570015
(NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createinstance]" nsresult: "0x80570015 (NS_ERROR_XPC_CI_TETURNED_FAILURE)" location:
"JS frame :: resource//calendar/modules/calUtils.jsm -> file///c:/users/<name>/AppData/Roaming/Mozilla/Seamonkey/Profiles/xyz12345.default/extensions/  /calendar.js/CalCalendarManager.js :: cmgr_createCalendar :: line 440" data:no]

Second error:

An error was encountered preparing the calendar located at https://auto/<<alpha-num-string> for use. it will not be available.

Details:
Error code: 0x TypeError: redeclaration of var attendee
Description: TypeError: redeclaration of var attendee

**Comment by Dominique-2202** [comment]
Hello,
Still the same problem now that the version of Seamonkey bumped up. 
Bavincen, I am not sure what to do with your comment above, copied here:

let calendar = Components.classes["@mozilla.org/calendar/calend ar;1?type=" + type]
Line no: 441 .createInstance(Components.interfaces. calICalendar);

'
In lightning file we are getting the error
will update!

**Comment by Woi** [comment]
I was hit by the very same problem updating SeaMonkey with Lightning from 2.30/2.5b1 to 2.32/27b1 on Linux.

Error message is:
An error was encountered preparing the calendar located at https://auto/d07ef1ca-0364-47ac-8655-e1947f659c98 for use. It will not be available.
Error code: 0xTypeError: redeclaration of variable attendee
Description: TypeError: redeclaration of variable attendee

**Comment by bavincen** [comment]
We need to wait for lightning team to fix it.. nothing to be done with `ews provider`

**Comment by Dominique-2202** [comment]
Mmm, OK... then we must open a bug to Lightning regarding the error trigger here:

let calendar = Components.classes["@mozilla.org/calendar/calend ar;1?type=" + type]
Line no: 441 .createInstance(Components.interfaces. calICalendar);

Please advise if there is something particular to include in the bug and I will open it.
thanks
Dom,

**Comment by bavincen** [comment]
There are couple of bugs opened.. please search mozilla bugzilla. thanks

**Comment by Dominique-2202** [comment]
Hi Bavincen,

Please check this bug and comments :  https://bugzilla.mozilla.org/show_bug.cgi?id=1130002
I am afraid I am not able to judge it the comments here are relevant or not.
thanks

**Comment by martinwhitaker** [comment]
I was able to work round this with the following patch
```
--- interfaces/exchangeBaseItem/mivExchangeBaseItem.js.orig	2015-02-07 18:33:31.258124415 +0000
+++ interfaces/exchangeBaseItem/mivExchangeBaseItem.js	2015-02-07 18:40:03.028574331 +0000
@@ -3808,7 +3808,7 @@
 		return attendee;
 
 		let mbox = aElement.getTag("t:Mailbox");
-		let attendee = cal.createAttendee();
+		var attendee = cal.createAttendee();
 
 		if (!aType) {
 			aType = "REQ-PARTICIPANT";
```
although it looks like this is dead code (note the return statement at the start of the patch).

**Comment by Dominique-2202** [comment]
Excellent,
          
          That works well for me (3.3.1~RC2) !
          Thanks again, that solves the issue and my Exchange calendars
          and tasks work fine.
        
      
        
        
        
          Best regards,
          
          Dominique 
          
         
      On 2/7/2015 8:16 PM, martinwhitaker wrote:
    
    
      I was able to work round this with the following patch
      --- interfaces/exchangeBaseItem/mivExchangeBaseItem.js.orig 2015-02-07 18:33:31.258124415 +0000
+++ interfaces/exchangeBaseItem/mivExchangeBaseItem.js  2015-02-07 18:40:03.028574331 +0000
@@ -3808,7 +3808,7 @@
        return attendee;

        let mbox = aElement.getTag("t:Mailbox");
-       let attendee = cal.createAttendee();
+       var attendee = cal.createAttendee();

        if (!aType) {
            aType = "REQ-PARTICIPANT";

      although it looks like this is dead code (note the return
        statement at the start of the patch).
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by bavincen** [comment]
great!  thanks @martinwhitaker

**Comment by bavincen** [comment]
ExchangeCalendar error on lightning nightly and aurora

**Comment by Woi** [comment]
Problem still exists for me after installing 3.3.1~rc2 from https://github.com/Ericsson/exchangecalendar/releases (OT: Auto update wasn't working)
Any suggestions?

**Comment by Dominique-2202** [comment]
For now, only the manual update (edition of the file..) will work, or you can download the zip file from here: https://github.com/Ericsson/exchangecalendar/archive/master.zip and then rename it to exchangecalendar.xpi or something and do a manual update of your add-on.

**Comment by Woi** [comment]
Thx for your quick reply Dominique. Work's for me after editing 3.3.1~rc2.
Keep up the good work & support

**Comment by muthusuba** [comment]
@martinwhitaker Thank you!

**Comment by pmabres** [comment]
@martinwhitaker Thanks a lot
