### ISSUE TITLE
thunderbird 52.1.1 plus ews 3.9.0 : calendar gui weird

### ISSUE THREAD

**Issue by umesh3034** [Ericsson/exchangecalendar#596]
Hi,

latest update with thun 52.1.1. plus ews 3.9.0 is not showing the gui right. Also the calendars are not shown in the left side pane. attached screen shot. Let me know if any debugs are needed and how to get those too.

--Umesh
![screenshot from 2017-05-22 10 54 13](https://cloud.githubusercontent.com/assets/18500461/26293867/5ac19878-3edd-11e7-8ff7-bc9f16a14dc6.png)

**Comment by ppoilbarbe** [comment]
Same as #595 and #580. Password seems to not been sent (seen with Wireshark analysis).

**Comment by camypaj** [comment]
hint: #580  seems to be resolved now, so please try with the latest beta version of the addon from there?
