### ISSUE TITLE
Auth problem by connecting to MS exchange server

### ISSUE THREAD

**Issue by sibergDFKI** [Ericsson/exchangecalendar#597]
1st-setup:2017-4-1 17:19:13.859:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({70d2b4fe-a552-48cd-8d93-1d8437a56b53})
1st-setup:2017-4-1 17:19:13.859:91d62e81-bb4d-4e1c-8b41-576d48ec5105: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2017-4-1 17:19:13.860:64604f13-4800-47f4-8773-01aee907e6b6: : ExchangeRequest.loadstart
1st-setup:2017-4-1 17:19:13.864:91d62e81-bb4d-4e1c-8b41-576d48ec5105: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2017-4-1 17:19:13.866:91d62e81-bb4d-4e1c-8b41-576d48ec5105: ecnsIAuthPrompt2.getInterface: Ci.nsILoadContext
1st-setup:2017-4-1 17:19:13.867:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({1040ebe3-6ed1-45a6-8587-995e082518d7})
1st-setup:2017-4-1 17:19:13.868:91d62e81-bb4d-4e1c-8b41-576d48ec5105: ecnsIAuthPrompt2.getInterface: Ci.nsIApplicationCacheContainer
1st-setup:2017-4-1 17:19:13.868:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})

**Comment by hawkeyese** [comment]
I think I experience the same issue. I get lines like these in my log:

1st-setup:2017-4-2 9:44:24.111:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({70d2b4fe-a552-48cd-8d93-1d8437a56b53})
1st-setup:2017-4-2 9:44:24.113:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({1040ebe3-6ed1-45a6-8587-995e082518d7})
1st-setup:2017-4-2 9:44:24.114:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})

**Comment by sibergDFKI** [comment]
If I try https://domain%5cuser@servername/EWS/exchange.asmx I get the service page with login.

If I try it with the Calendar Provider using 
https://servername/EWS/exchange.asmx
user: name
domain: domain name

I got the HTTP Client error 401: Unauthorized
URL:https://servername/EWS/exchange.asmx
 (Code: -19)

**Comment by hawkeyese** [comment]
Reading up a bit... this a duplicate of #580. Installing the xpi provided in a late comment of #580 resolved the issue for me.

**Comment by sibergDFKI** [comment]
Problem fixed with commented workaround --> see issue #580
