### ISSUE TITLE
[Feature] Calendar items should look different from the normal mails

### ISSUE THREAD

**Issue by muthusuba** [Ericsson/exchangecalendar#6]
Unlike the other mail clients Tunderbird shows the calendar items in the _inbox_ same as any other mail, which makes it difficult to find the invites/calendar items.
A better way is to show them with different colored rows and probably with an 'invite' icon.

**Comment by bavincen** [comment]
df1de3e64b5466240edd2498e46bea74a58d8ecd

**Comment by bavincen** [comment]
![screenshot from 2015-01-22 16 07 49](https://cloud.githubusercontent.com/assets/8401561/5854173/18d1d9c6-a251-11e4-9a39-4b2fbc0e4291.png)

**Comment by eamripa** [comment]
Emails are not selected when user clicks on the icon. We need to click outside the icon to select aan email.
