### ISSUE TITLE
Error after upgrading thunderbird and Lightning: Error during checking of server and mailbox: HTTP Client error 401: Unauthorized URL

### ISSUE THREAD

**Issue by unni10286** [Ericsson/exchangecalendar#601]
Hi, 

I've recently upgraded Thunderbird to version **52.0** from **45.8** and Lightening from **4.7** to **5.4**. My Outlook calender is NOT visible after that. When tried to do  "Check Server and MailBox" from AWS properties option in Lightening, it gave an error as follows

```
Error during checking of server and mailbox: HTTP Client error 401: Unauthorized
URL:https://xxx-owa.xxxxx.xxxxxx.xx/xxxx/Exchange.asmx
 (Code: -19)
```
EWS plugin version: 3.3.2. Tried upgrading to version  3.9. But, that didn't help.

PS: Downgrading Thunderbird (to 45.8) and Lightening (to 4.7) again started working without any change in settings. But the new versions are not.

**Comment by n0v3xx** [comment]
https://github.com/ExchangeCalendar/exchangecalendar/releases/tag/v4.0.0-beta1

**Comment by unni10286** [comment]
It helped. Thanks for the quick response
