### ISSUE TITLE
Offline cache does not work

### ISSUE THREAD

**Issue by qsantos** [Ericsson/exchangecalendar#607]
Hello,

I am using EC 3.9.0 (same issue with 4.0.0-beta1 built from the ec-4.0 branch), Lightning 4.7.8 and Thunderbird 45.8.0-3 on Debian testing (stretch / 9).

The calendar works very well except for one thing: when starting Thunderbird without a connexion to the Exchange server, the calendar shows up as empty. The expected behavior is to be able to at least see (read-only) the events from the calendar that were cached in the previous session.

I have checked Thunderbird `Advanced` preferences for caching, `Exchange (EWS)` Preferences, as well as the specific calendar `Properties` and `Exchange Properties`. In the last case, the tab `Offline cache` shows a grayed but checked box for `Cache` and does say that there are events in the offline cache. However, if I close Thunderbird, disconnect the network device, and start Thunderbird again, the calendar shows up as empty (as an addition, the "Offline cache" tab, now only show a grayed and unchecked box for "Cache").

My current settings have ±1 month in the calendar `EWS Properties` and ±999 days in the Cache tab of `Exchange (EWS)` preferences.

Does anyone have any suggestion?

**Comment by Mechtilde** [comment]
Hello,

please test the calendar-exchange-provider from Debian repository.

Thanks

Am 21.06.2017 um 11:23 schrieb Quentin Santos:
> Hello,
> 
> I am using EC 3.9.0 (same issue with 4.0.0-beta1 built from the ec-4.0 branch), Lightning 4.7.8 and Thunderbird 45.8.0-3 on Debian testing (stretch / 9).
> 
> The calendar works very well except for one thing: when starting Thunderbird without a connexion to the Exchange server, the calendar shows up as empty. The expected behavior is to be able to at least see (read-only) the events from the calendar that were cached in the previous session.
> 
> I have checked Thunderbird `Advanced` preferences for caching, `Exchange (EWS)` Preferences, as well as the specific calendar `Properties` and `Exchange Properties`. In the last case, the tab "Offline cache" shows a grayed but checked box for `Cache` and does say that there are events in the offline cache. However, if I close Thunderbird, disconnect the network device, and start Thunderbird again, the calendar shows up as empty (as an addition, the "Offline cache" tab, now only show a grayed and unchecked box for "Cache").
> 
> My current settings have ±1 month in the calendar `EWS Properties` and ±999 days in the Cache tab of `Exchange (EWS)` preferences.
> 
> Does anyone have any suggestion?
> 

-- 
Mechtilde Stehmann
## Debian Developer
## Loook, calender-exchange-provider, libreoffice-canzeley-client
## PGP encryption welcome
## Key-ID 0x141AAD7F

**Comment by qsantos** [comment]
Thanks for the suggestion. I had completely overlooked the existence of a package for EC.

However, after replacing the XPI-installed add-on with `calendar-exchange-provider` (either =3.9.0-4 from testing or =4.0.0~beta2-1 from unstable), the problem remains.

**Comment by Zwen23** [comment]
Hi, same Problem here. Installed Version v4.0.0-beta4 on Ubuntu 16.04.
When starting TB with no network connections calendar is empty!
