### ISSUE TITLE
Calendar not synchronizing

### ISSUE THREAD

**Issue by denisrouleau** [Ericsson/exchangecalendar#608]
Not sure what else to say besides I have just changed my password in my Windows domain and email is still working but not my calendar :(

Submitting lines as requested.

1st-setup:2017-5-4 9:36:34.393:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({70d2b4fe-a552-48cd-8d93-1d8437a56b53})
1st-setup:2017-5-4 9:36:34.395:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({1040ebe3-6ed1-45a6-8587-995e082518d7})
1st-setup:2017-5-4 9:36:34.397:  >>>>>>>>>>> SUBMIT THIS LINE TO https://github.com/Ericsson/exchangecalendar/issues: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})

**Comment by denisrouleau** [comment]
I forgot to mention my setup:

Ubuntu 14.04
Thunderbird 52.1.1 (64-bit)

Issue started after upgrading thunderbird AND changing my password although I'm not sure which of the two actions broke it.

**Comment by naibaf0** [comment]
See related issues #580 and #599.

Installing [version 4.0.0-beta2](https://github.com/ExchangeCalendar/exchangecalendar/releases/tag/v4.0.0-beta2) fixed it for me.

**Comment by ferpega** [comment]
Version 4.0.0-beta2 from @naibaf0 is running fine on my Windows 10 + Thunderbird 52.2.1.

Please could it be integrated ASAP into official repository.
Regards.

**Comment by denisrouleau** [comment]
version 4.0.0-beta2 fixed it. Thanks!

**Comment by leonadler** [comment]
@denisrouleau close the issue?
