### ISSUE TITLE
Solved: EWS Office 365: Can't see even details

### ISSUE THREAD

**Issue by solitaryangler** [Ericsson/exchangecalendar#621]
Hi,

thanks for this great product! I am using it regularly, but have an issue with Office 365 EWS calendar.
When I first subscribed to a new EWS calendar (at work), I could view all details in every calendar event/meeting/appointment. However after closing Thunderbird and starting again, I can see the events and their title but cannot access the details (messages, links) from the events making it very difficult to use the Calendar.
Temporary hacky workaround: Unsubscribe from the EWS calendar and re-create it as a new calendar. Then I can see all the details until I am forced to shut down Thunderbird. If I restart, then follow this procedure again.
Details:
Thunderbird 52.6.0 (64-bit), Lightning 5.4.6, Exchange EWS Provider 3.9.0 on Debian Stretch 64 bits. Also using ExQuilla for MS Exchange 52.3.1200.

Kindly help.
Sincerely,

**Comment by aivantsov** [comment]
https://github.com/Ericsson/exchangecalendar/issues/610

**Comment by solitaryangler** [comment]
Wonderful thank you!
