### ISSUE TITLE
Thunderbird becomes unresponsive on reply/forward

### ISSUE THREAD

**Issue by r-verma** [Ericsson/exchangecalendar#64]
When replying to a message (or forwarding) Thunderbird beomes unresponsive while trying to type in an address and has to be killed.
TB Version: 31.3
Lightning Version 3.3.3
Plugin Verision 3.3.0
Reproducable: Always

Appears to be a problem in autocompletion of email addresses.

**Comment by bavincen** [comment]
Please reopen if you find this bug again
