### ISSUE TITLE
Versioning of Calendar

### ISSUE THREAD

**Issue by Mechtilde** [Ericsson/exchangecalendar#66]
Hello 

I'm not sure understandingyour versioning right.

https://github.com/Ericsson/exchangecalendar/releases

Does it means version 3.3.0 comes in future?

Or are you working on version 3.4?

I want to package this software for Debian. So I have to understand the right versioning

Kind regards

Mechtilde

**Comment by Mechtilde** [comment]
When do you plan to release with a new numbering? Or ... When do you plan to release version 3.3.0?

**Comment by muthusuba** [comment]
In the next few days - one of the features needs a slight fix, which should be done soon...

**Comment by muthusuba** [comment]
@Mechtilde : Expect some more delay on this, please? There was the feature merge which we wanted - but it has a small bug - but a blocker. I'll have to package this early next week :(

**Comment by muthusuba** [comment]
@Mechtilde Would rc1 be ok, please? E.g. exchangecalendar-3.3.0-rc1

**Comment by awilkins** [comment]
It's the tilde that's the important bit in Debian version numbers

e.g. 
exchangecalendar-3.3.0~rc1

Everything after the tilde sorts before versions without a tilde ; which means that 

exchangecalendar-3.3.0

will be "greater than" the rc1 and thus replace it

**Comment by muthusuba** [comment]
@awilkins oh...ok...thank you!

**Comment by muthusuba** [comment]
Released it here: https://github.com/Ericsson/exchangecalendar/releases/tag/3.3.0-rc1
[though the filename is ~rc1 it seems like github replaces the tilde with a dot - fyi]

Please confirm if things are fine, please? Thanks!

**Comment by Mechtilde** [comment]
I will try next days

Am 03.02.2015 um 16:27 schrieb Muthu Subramanian:
> Released it here: https://github.com/Ericsson/exchangecalendar/releases/tag/3.3.0-rc1
> [though the filename is ~rc1 it seems like github replaces the tilde with a dot - fyi]
> 
> Please confirm if things are fine, please? Thanks!
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Ericsson/exchangecalendar/issues/66#issuecomment-72669715
> 

-- 
Mechtilde Stehmann

## PGP encryption welcome
## Key-ID 0x141AAD7F

**Comment by tfft** [comment]
The latest test release should be renamed to be 3.3.1-rc1 as 3.3.0 has already been released.  Please see PR #92.  Release candidates denote a release that has not yet been fully published; 3.3.0 has already been released as '3.3.0' (meaning full release) which might confuse users who might thing this RC1 is a version "before" 3.3.0 which it clearly isn't...

**Comment by muthusuba** [comment]
Done :)
