### ISSUE TITLE
UX error when saving Out of Office

### ISSUE THREAD

**Issue by SockThief** [Ericsson/exchangecalendar#67]
When saving an Out of Office message, the alert box uses a red-exclamation mark type icon, which is inappropriate for a successful notification. Simillarly the alert-tone used is more related to error than ok

**Comment by andrelaszlo** [comment]
It's not possible to change the icon when calling [`alert`](http://dev.w3.org/html5/spec-preview/user-prompts.html#simple-dialogs). IMO, modals should be avoided completely unless something actually goes wrong (then the "alert" and :exclamation: semantics is still appropriate).

**Comment by bavincen** [comment]
you may check this updated popup notification

**Comment by bavincen** [comment]
![screenshot from 2015-01-08 09 33 16](https://cloud.githubusercontent.com/assets/8401561/5657723/67e4b738-9719-11e4-8f07-e188696b1a74.png)

**Comment by SockThief** [comment]
i like that change :) much better

**Comment by Mechtilde** [comment]
Where caqn I find the string "Out of Office" for translation

**Comment by bavincen** [comment]
This is title of window

**Comment by bavincen** [comment]
locale/exchangecalendar/en-US/oofSettings.dtd
`title.oofsettings` for english please find your respective folder and edit it .. thanks :)

**Comment by muthusuba** [comment]
Similar dialog seems to appear after successfully forwarding an event.

**Comment by bavincen** [comment]
updated
