### ISSUE TITLE
Exchange EWS causes Thunderbird to hang on logout

### ISSUE THREAD

**Issue by saper17** [Ericsson/exchangecalendar#70]
My exchange Calendar is working fine but when logging out I get a window from Thunderbird: "Info  Unknown error during communication with hostname 'undefined'.(0)    OK" and Thunderbird hangs with a spinning rainbow ball.  I need to force quit Thunderbird to proceed.  This occurs every time.

If I choose to quit Thunderbird directly the problem does not occur; it only occurs when logging out or shutting down the computer.  If I disable Exchange EWS Provider, then the problem does not occur at all.

My setup is:

Mac OS X 10.10.1, MacBook Air (early 2014)
Thunderbird 31.4.0
Exchange EWS Provider 3.3.3
Lightning 3.3.2

**Comment by bavincen** [comment]
please post your logs when exiting.. you can set a log file edit->preference->EWS

**Comment by saper17** [comment]
Below is the basic log (from shortly after issuing "log out" to the time of force quit):

1st-setup:2015-0-4 13:30:24.367:[Duke Calendar] ModifyItem: it is an event. (_modifyItem in mivExchangeCalendar.js:1495)
1st-setup:2015-0-4 13:30:24.368:[Duke Calendar] Did not find meOld (_modifyItem in mivExchangeCalendar.js:1499)
1st-setup:2015-0-4 13:30:24.368:[Duke Calendar] Did not find meNew (_modifyItem in mivExchangeCalendar.js:1506)
1st-setup:2015-0-4 13:30:24.369:[Duke Calendar] The organizer is:mailto:leslie.saper@duke.edu (_modifyItem in mivExchangeCalendar.js:1609)
1st-setup:2015-0-4 13:30:24.369:[Duke Calendar] modifyItem: it is a event. aOldItem.CalendarItemType=:RecurringMaster (_modifyItem in mivExchangeCalendar.js:1664)
1st-setup:2015-0-4 13:30:24.370:[Duke Calendar]  Master changed:Nathan's Birthday (_modifyItem in mivExchangeCalendar.js:1668)
1st-setup:2015-0-4 13:30:24.370:[Duke Calendar]  ==1 invite=false (_modifyItem in mivExchangeCalendar.js:1673)
1st-setup:2015-0-4 13:30:24.371:[Duke Calendar] modifyItem: No changes for master. (_modifyItem in mivExchangeCalendar.js:1698)
1st-setup:2015-0-4 13:30:24.371:[Duke Calendar] getRemovedOccurrence (_getRemovedOccurrence in mivExchangeCalendar.js:3066)
1st-setup:2015-0-4 13:30:24.371:[Duke Calendar] getRemovedOccurrence: oldCount.value=0 (_getRemovedOccurrence in mivExchangeCalendar.js:3075)
1st-setup:2015-0-4 13:30:24.371:[Duke Calendar] getRemovedOccurrence: newCount.value=0 (_getRemovedOccurrence in mivExchangeCalendar.js:3076)
1st-setup:2015-0-4 13:30:24.371:[Duke Calendar] getRemovedOccurrence: oldCount.value=0 (_getRemovedOccurrence in mivExchangeCalendar.js:3102)
1st-setup:2015-0-4 13:30:24.372:[Duke Calendar] getRemovedOccurrence: newCount.value=0 (_getRemovedOccurrence in mivExchangeCalendar.js:3103)
1st-setup:2015-0-4 13:30:24.372:[Duke Calendar] getRemovedOccurrence: we DID NOT FIND our removed occurrence or exception (_getRemovedOccurrence in mivExchangeCalendar.js:3123)
1st-setup:2015-0-4 13:30:24.378:[exchangeLoadBalancer] serverQueue:https://outlook.office365.com/EWS/Exchange.asmx: Started timer for new job. (_notify in mivExchangeLoadBalancer.js:258)
1st-setup:2015-0-4 13:30:24.461:[exchangeLoadBalancer] 0290a37b-3b10-694c-a310-8cff302b7322:https://outlook.office365.com/EWS/Exchange.asmx:jobObject:notify: starting exchangeRequest. (setTimeout_notify in mivExchangeLoadBalancer.js:53)
1st-setup:2015-0-4 13:30:24.496:f8098b37-952f-2f46-9e2e-8fd5f0528e5b: : 1 ExchangeRequest.sendRequest : user=saper@duke.edu, url=https://outlook.office365.com/EWS/Exchange.asmx
1st-setup:2015-0-4 13:30:24.496:f8098b37-952f-2f46-9e2e-8fd5f0528e5b: We have a prePassword: *******
1st-setup:2015-0-4 13:30:24.497:f8098b37-952f-2f46-9e2e-8fd5f0528e5b: : ExchangeRequest.loadstart
1st-setup:2015-0-4 13:30:24.525:f8098b37-952f-2f46-9e2e-8fd5f0528e5b: : ExchangeRequest.error :error, readyState:4, status:0, lastStatus:0
1st-setup:2015-0-4 13:30:24.526:f8098b37-952f-2f46-9e2e-8fd5f0528e5b: : ExchangeRequest.error : badCert going to check if it is a cert problem.
1st-setup:2015-0-4 13:30:24.526:f8098b37-952f-2f46-9e2e-8fd5f0528e5b: : ExchangeRequest.error : badCert no problem.
1st-setup:2015-0-4 13:30:24.526:f8098b37-952f-2f46-9e2e-8fd5f0528e5b: exchangeRequest.isHTTPRedirect.xmlReq. xmlReq.readyState:4, xmlReq.status:0
1st-setup:2015-0-4 13:30:24.526:f8098b37-952f-2f46-9e2e-8fd5f0528e5b: exchangeRequest.tryNextURL
1st-setup:2015-0-4 13:30:24.526:f8098b37-952f-2f46-9e2e-8fd5f0528e5b: ecExchangeRequest.fail: aCode:-18, aMsg:Unknown error during communication with hostname 'undefined'. (0)
1st-setup:2015-0-4 13:30:24.527:[exchangeLoadBalancer] 0290a37b-3b10-694c-a310-8cff302b7322:https://outlook.office365.com/EWS/Exchange.asmx:jobObject:onRequestError. arg2:-18, arg3:Unknown error during communication with hostname 'undefined'. (0) (_onRequestError in mivExchangeLoadBalancer.js:86)
1st-setup:2015-0-4 13:30:24.527:[Duke Calendar] whichOccurrencegetOccurrenceIndexError:(-18)Unknown error during communication with hostname 'undefined'. (0) (_whichOccurrencegetOccurrenceIndexError in mivExchangeCalendar.js:5529)
1st-setup:2015-0-4 13:30:24.552:[exchangeLoadBalancer] serverQueue:https://outlook.office365.com/EWS/Exchange.asmx: Removing stopped job. (_notify in mivExchangeLoadBalancer.js:202)
1st-setup:2015-0-4 13:30:24.552:[exchangeLoadBalancer] 0290a37b-3b10-694c-a310-8cff302b7322:https://outlook.office365.com/EWS/Exchange.asmx:jobObject:clear. (_clear in mivExchangeLoadBalancer.js:97)
1st-setup:2015-0-4 13:30:24.552:[exchangeLoadBalancer] serverQueue:https://outlook.office365.com/EWS/Exchange.asmx: Started timer for new job. (_notify in mivExchangeLoadBalancer.js:258)
1st-setup:2015-0-4 13:30:24.603:[exchangeLoadBalancer] 58a63098-11d2-de4c-947f-05926667293e:https://outlook.office365.com/EWS/Exchange.asmx:jobObject:notify: starting exchangeRequest. (setTimeout_notify in mivExchangeLoadBalancer.js:53)
1st-setup:2015-0-4 13:30:24.609:bbd57435-35bc-794a-bef8-1874f2901919: : 1 ExchangeRequest.sendRequest : user=saper@duke.edu, url=https://outlook.office365.com/EWS/Exchange.asmx
1st-setup:2015-0-4 13:30:24.610:bbd57435-35bc-794a-bef8-1874f2901919: : ExchangeRequest.loadstart
1st-setup:2015-0-4 13:30:24.611:bbd57435-35bc-794a-bef8-1874f2901919: : ExchangeRequest.error :error, readyState:4, status:0, lastStatus:0
1st-setup:2015-0-4 13:30:24.611:bbd57435-35bc-794a-bef8-1874f2901919: : ExchangeRequest.error : badCert going to check if it is a cert problem.
1st-setup:2015-0-4 13:30:24.612:bbd57435-35bc-794a-bef8-1874f2901919: : ExchangeRequest.error : badCert no problem.
1st-setup:2015-0-4 13:30:24.612:bbd57435-35bc-794a-bef8-1874f2901919: exchangeRequest.isHTTPRedirect.xmlReq. xmlReq.readyState:4, xmlReq.status:0
1st-setup:2015-0-4 13:30:24.612:bbd57435-35bc-794a-bef8-1874f2901919: exchangeRequest.tryNextURL
1st-setup:2015-0-4 13:30:24.612:bbd57435-35bc-794a-bef8-1874f2901919: ecExchangeRequest.fail: aCode:-18, aMsg:Unknown error during communication with hostname 'undefined'. (0)
1st-setup:2015-0-4 13:30:24.612:[exchangeLoadBalancer] 58a63098-11d2-de4c-947f-05926667293e:https://outlook.office365.com/EWS/Exchange.asmx:jobObject:onRequestError. arg2:-18, arg3:Unknown error during communication with hostname 'undefined'. (0) (_onRequestError in mivExchangeLoadBalancer.js:86)
1st-setup:2015-0-4 13:30:24.613:[Duke Calendar] whichOccurrencegetOccurrenceIndexError:(-18)Unknown error during communication with hostname 'undefined'. (0) (_whichOccurrencegetOccurrenceIndexError in mivExchangeCalendar.js:5529)
1st-setup:2015-0-4 13:30:24.622:[exchangeLoadBalancer] serverQueue:https://outlook.office365.com/EWS/Exchange.asmx: Removing stopped job. (_notify in mivExchangeLoadBalancer.js:202)
1st-setup:2015-0-4 13:30:24.622:[exchangeLoadBalancer] 58a63098-11d2-de4c-947f-05926667293e:https://outlook.office365.com/EWS/Exchange.asmx:jobObject:clear. (_clear in mivExchangeLoadBalancer.js:97)
1st-setup:2015-0-4 13:30:24.623:[exchangeLoadBalancer] serverQueue:https://outlook.office365.com/EWS/Exchange.asmx: Started timer for new job. (_notify in mivExchangeLoadBalancer.js:258)
1st-setup:2015-0-4 13:30:24.673:[exchangeLoadBalancer] 72789689-37b3-f14d-b553-96b02c62889e:https://outlook.office365.com/EWS/Exchange.asmx:jobObject:notify: starting exchangeRequest. (setTimeout_notify in mivExchangeLoadBalancer.js:53)
1st-setup:2015-0-4 13:30:24.683:07f68c7a-9605-304a-9b55-af466d9067eb: : 1 ExchangeRequest.sendRequest : user=saper@duke.edu, url=https://outlook.office365.com/EWS/Exchange.asmx
1st-setup:2015-0-4 13:30:24.684:07f68c7a-9605-304a-9b55-af466d9067eb: : ExchangeRequest.loadstart
1st-setup:2015-0-4 13:30:24.685:07f68c7a-9605-304a-9b55-af466d9067eb: : ExchangeRequest.error :error, readyState:4, status:0, lastStatus:0
1st-setup:2015-0-4 13:30:24.685:07f68c7a-9605-304a-9b55-af466d9067eb: : ExchangeRequest.error : badCert going to check if it is a cert problem.
1st-setup:2015-0-4 13:30:24.686:07f68c7a-9605-304a-9b55-af466d9067eb: : ExchangeRequest.error : badCert no problem.
1st-setup:2015-0-4 13:30:24.686:07f68c7a-9605-304a-9b55-af466d9067eb: exchangeRequest.isHTTPRedirect.xmlReq. xmlReq.readyState:4, xmlReq.status:0
1st-setup:2015-0-4 13:30:24.686:07f68c7a-9605-304a-9b55-af466d9067eb: exchangeRequest.tryNextURL
1st-setup:2015-0-4 13:30:24.686:07f68c7a-9605-304a-9b55-af466d9067eb: ecExchangeRequest.fail: aCode:-18, aMsg:Unknown error during communication with hostname 'undefined'. (0)
1st-setup:2015-0-4 13:30:24.687:[exchangeLoadBalancer] 72789689-37b3-f14d-b553-96b02c62889e:https://outlook.office365.com/EWS/Exchange.asmx:jobObject:onRequestError. arg2:-18, arg3:Unknown error during communication with hostname 'undefined'. (0) (_onRequestError in mivExchangeLoadBalancer.js:86)
1st-setup:2015-0-4 13:30:24.687:[Duke Calendar] whichOccurrencegetOccurrenceIndexError:(-18)Unknown error during communication with hostname 'undefined'. (0) (_whichOccurrencegetOccurrenceIndexError in mivExchangeCalendar.js:5529)
1st-setup:2015-0-4 13:30:24.695:[exchangeLoadBalancer] serverQueue:https://outlook.office365.com/EWS/Exchange.asmx: Removing stopped job. (_notify in mivExchangeLoadBalancer.js:202)
1st-setup:2015-0-4 13:30:24.695:[exchangeLoadBalancer] 72789689-37b3-f14d-b553-96b02c62889e:https://outlook.office365.com/EWS/Exchange.asmx:jobObject:clear. (_clear in mivExchangeLoadBalancer.js:97)
1st-setup:2015-0-4 13:30:24.696:[exchangeLoadBalancer] serverQueue:https://outlook.office365.com/EWS/Exchange.asmx: Stopping server queue timer. (_notify in mivExchangeLoadBalancer.js:266)
1st-setup:2015-0-4 13:30:24.696:[exchangeLoadBalancer] serverQueue:https://outlook.office365.com/EWS/Exchange.asmx: Timer stopped. (_notify in mivExchangeLoadBalancer.js:269)

**Comment by bavincen** [comment]
no response from server?

**Comment by bavincen** [comment]
(-18)Unknown error during communication with hostname 'undefined'. (0)

**Comment by saper17** [comment]
This is correct: the popup message when Thunderbird hangs says
```
Info Unknown error during communication with hostname 'undefined'.(0)
```
and this error is several times in the log as well.  I don't think it is a failure of internet connectivity, since it only occurs when I log out (and when Thunderbird hangs in this way, other programs can still access the internet).  I also don't think it is a problem with the server: again it only occurs on log out or shutdown, and in any case, I tried accessing the server from another machine while this occurred with no difficulty.

Why is EWS reporting the hostname as 'undefined'?

Having said all this, just this morning the problem disappeared after consistently occurring for over a month.  The only relevant thing that has changed is that yesterday afternoon I tried to dismiss all reminders that could be dismissed; this was part of my trying to debug Issue #60.  Even though 3 reminders could not be dismissed (including the reminder mentioned in the log above), Thunderbird/EWS is no longer hanging on logout.

**Comment by vadi2** [comment]
I don't get any error messages, but my Thunderbird does freeze when quitting after a recent EWS update while using one cpu to 100% on Ubuntu. Nothing is written to the log though with all loggers on 2, does that mean the problem isn't with EWS?

**Comment by saper17** [comment]
After writing two weeks ago that the "hanging on logout" problem had ceased, it re-occurred and has been frequently occurring during the past two weeks, though not every time.  Since then I have upgraded to Exchange EWS Provider 3.3.1~rc2 and to Mac OS X 10.10.2.

It should be noted that I using Exchange EWS on three machines to access the same calendar: two on Scientific Linux machines and one on Mac OS X.  I am only experiencing the problem on the Mac however it may be that the presence of more that one Exchange EWS running may affect the problem.

Any suggestions of steps I can take to help track down the problem would be appreciated.

**Comment by bavincen** [comment]
It would be great if someone helps us in mac osx. thanks

**Comment by LunaticoCR** [comment]
I use Thunderbird and EWS daily at work on OSX 10.10.2. Will install 3.3.1~rc2 and report back.

**Comment by saper17** [comment]
As an experiment, I quit Thunderbird (and hence EWS server) on both of my Linux machines.  I then restarted the Mac twice.  I then logged into the Mac, waited for Thunderbird to automatically start, waited for EWS to process the 15 or so queued jobs, and then tried to log out.  Thunderbird again hung with the error message
```
Info Unknown error during communication with hostname 'undefined'.(0)
```

I note there are still 3 undismissable reminders in the reminder alert window; I don't know if the problems are related.

**Comment by Shellmaster** [comment]
Hi,

I have a very similar problem, plugin syncs and hags Thunderbird, log is empty and nothing appears when it hangs apart from standard logging. CPU usage for Thunderbird process jumps to 100% and nothing happens.

Thunderbird: 31.4.0
Lighting: 3.3.3 ( I have tried with older versions as well)
EWS Provider: 3.3.1 ( I have also tried with older versions)

Always the same issue, it just hangs.

I also noticed that after restart I am "un-subscribed" from Exchange's calendar. When I try to subscribe again it hangs Thunderbird. When I uninstalled all the plugins, deleted all the files from the home folder (.Thunderbird) and set up everything again, the result was the same)

OS: Debian 7 (64 bit) + Xfce (I have tried different kernels and result was the same)

If you need more info please let me know.

strace finishes on these lines:

madvise(0x7f4f83577000, 24576, MADV_DONTNEED) = 0
madvise(0x7f4f83502000, 266240, MADV_DONTNEED) = 0
clone(child_stack=0x7f4f8d576f70, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f4f8d5779d0, tls=0x7f4f8d577700, child_tidptr=0x7f4f8d5779d0) = 9471
futex(0x7f4f83cff6cc, FUTEX_CMP_REQUEUE_PRIVATE, 1, 2147483647, 0x7f4f83cff668, 2) = 1
futex(0x7f4fba45808c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7f4fba458088, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7f4fba45808c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7f4fba458088, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7f4fba4db110, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7f4fba4db110, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f4fba4db110, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7f4fba4db110, FUTEX_WAKE_PRIVATE, 1) = 0


and the last two lines are repeating every 1 second or so.

I hope this info is helpful to solve this problem.

Cheers,
Rafal.

**Comment by bavincen** [comment]
Thanks for the log

**Comment by bavincen** [comment]
Please us latest beta looks fixed.. open new one if not
