### ISSUE TITLE
Event start date cannot be modified if repeating schedule

### ISSUE THREAD

**Issue by patricktokeeffe** [Ericsson/exchangecalendar#73]
Using 3.2.0-Beta77: 

1. Modify the start date of an event which repeats weekly until a specified date
2. Save and close.
3. Open, observe unchanged start date.
4. Modify the start date AND remove repeat schedule. 
5. Save and close.
6. Success.

Did not observe this behavior on local calendar.

**Comment by bavincen** [comment]
![screenshot from 2015-01-28 17 49 24](https://cloud.githubusercontent.com/assets/8401561/5937481/064b469c-a716-11e4-9bae-08b6ee665ae7.png)
