### ISSUE TITLE
Postbox 3.0.11

### ISSUE THREAD

**Issue by jasonfearon** [Ericsson/exchangecalendar#74]
Hello - I can't install this extension, as it isn't compatible with Postbox 3.0.11.

Is this something in the works, or am I in the wrong place?

Thanks!

**Comment by muthusuba** [comment]
Assuming Postbox 3.0.11 is based on Thunderbird, it might be possible.
But then, it seems to be a paid software, which would make it difficult for us to support :(

**Comment by muthusuba** [comment]
*paid = paid and closed source/proprietary i.e.

**Comment by jasonfearon** [comment]
Thanks - I wouldn't have asked, but the Postbox site lists 'Provider for Exchange' as an approved/suggested/recommended extension. And the 'Provider for Exchange' page says it is no longer in development, but that development has moved to this extension.
