### ISSUE TITLE
FW: Leftover drafts of meeting response e-mails

### ISSUE THREAD

**Issue by Mechtilde** [Ericsson/exchangecalendar#76]
forward from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=758848

When choosing a response to a meeting invitation, a 'How do you want to react'
dialogue pops up. If I choose 'Don't send a response', the e-mail corresponding
to the response to the meeting invitation is left in the Drafts folder.

This problem was found in 3.2.0~beta53-1 and still exists.

Kind regards

Mechtilde

**Comment by bavincen** [comment]
hi @Mechtilde Mechtilde :)
EWS behaves in similar way. if you can also choose `dont not send` option which will just sync the status with ews server.

**Comment by Mechtilde** [comment]
After syncing the response should leave from the draft folder

**Comment by bavincen** [comment]
There are two option when responding to a meeting

 SendToAllAndSaveCopy   OR
 SaveOnly  
 

 I am closing it for now. we don't have any other option right now :)
