### ISSUE TITLE
Seamonkey 2.32 + Lightning 3.7

### ISSUE THREAD

**Issue by pleappleappleap** [Ericsson/exchangecalendar#78]
Previous versions of Lightning appear to be incompatible with Seamonkey 2.32.  The latest 3.7 version is compatible, but when I try to use the latest EWS provider to attach my Office 365 calendar, I get:

Error code:    0x80570015
Description:    [Exception... "Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]"  nsresult: "0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE)"  location: "JS frame :: resource://calendar/modules/calUtils.jsm -> file:///home/sridhar/.mozilla/seamonkey

The only relevant resource I found was https://www.1st-setup.nl/bugzilla/show_bug.cgi?id=132 at the Bugzilla repository for the old project.

**Comment by Dominique-2202** [comment]
This problem is already logged as issue
        #59
      
        
        
        
          Best regards,
          
          Dominique Fillon
          
          
         
      On 1/22/2015 5:26 PM, Tripp Kinetics wrote:
    
    
      Previous versions of Lightning appear to be incompatible with
        Seamonkey 2.32. The latest 3.7 version is compatible, but when I
        try to use the latest EWS provider to attach my Office 365
        calendar, I get:
      Error code: 0x80570015
        Description: [Exception... "Component returned failure code:
        0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE)
        [nsIJSCID.createInstance]" nsresult: "0x80570015
        (NS_ERROR_XPC_CI_RETURNED_FAILURE)" location: "JS frame ::
        resource://calendar/modules/calUtils.jsm ->
        file:///home/sridhar/.mozilla/seamonkey
      The only relevant resource I found was https://www.1st-setup.nl/bugzilla/show_bug.cgi?id=132
        at the Bugzilla repository for the old project. 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by bavincen** [comment]
#59
