### ISSUE TITLE
Affect startups on latest released thunderbird 31.4.0

### ISSUE THREAD

**Issue by kiravi** [Ericsson/exchangecalendar#79]
If you start up with this extension disabled the screens load fast.
when I enable the extension the main frame freezes for sometime on loading TB.

**Comment by bavincen** [comment]
thanks! we will check it again, may i know approx. number of calendar appointments and to-dos

**Comment by kiravi** [comment]
About 30-40 meeting requests per month, with about 10-15 repeated weekly

**Comment by bavincen** [comment]
Please enable exchange-cache option in properties ( you can right click on your calendar to get properties ) and please post the difference.

**Comment by bavincen** [comment]
Fixed! please keep exchange-cache enabled it will  help you to load faster when internet is off
if cache is not enables it will wait for connection till timeout...
