### ISSUE TITLE
Unable to connect to calendar on server mail.rwth-aachen.de

### ISSUE THREAD

**Issue by aweinert** [Ericsson/exchangecalendar#80]
I am trying to connect to the exchange server at https://mail.rwth-aachen.de. When checking server and mailbox, the following error message appears: "Error during checking of server and mailbox: Error during waiting for data of hostname 'mail.rwth-aachen.de'. (STATUS_WAITING_FOR) (Code: -16)"

Program versions: Thunderbird 31.4.0, Lightning 3.3.2, both ExchangeProvider 3.3.0 and 3.2.2.

Steps to reproduce:
1. 'Create New Calendar' -> 'On the network' -> 'Next' -> 'Microsoft Exchange 2007/2010/2013' -> check 'Use offline cache' -> 'Next'
2. Enter some name -> 'Next'
3. Server URL: 'https://mail.rwth-aachen.de', Primary email address: arbitrary, Username: 'foobar@rwth-aachen.de' -> 'Check Server and Mailbox'

What happens: After a couple of seconds an error message pops up, saying: "Error during checking of server and mailbox: Error during waiting for data of hostname 'mail.rwth-aachen.de'. (STATUS_WAITING_FOR) (Code: -16)"

What I expect to happen: A form should pop up asking me for my password.

Additional information: The same login information works for connecting my phone to the same exchange server.

**Comment by Mechtilde** [comment]
https://doc.itc.rwth-aachen.de/display/EML/Exchange-Kalender+in+Thunderbird+einbinden

This URL is a bit different from yours. Please try this one

**Comment by aweinert** [comment]
Great, that works for me. I was sure that I tried that one out earlier and it didn't work... this is a little embarrassing. Any idea though why it works on my phone with only "https://mail.rwth-aachen.de"?

**Comment by muthusuba** [comment]
@Mechtilde Thank you!
@aweinert Would it be ok to close this one, please?
