### ISSUE TITLE
No meeting invitations/updates sent in some circumstances

### ISSUE THREAD

**Issue by hamarituc** [Ericsson/exchangecalendar#85]
When I add a new meeting to an exchange calendar, the meeting invitation will only be sent out by the exchange server if I add the meeting by clicking the "New Event" button in the top toolbar. But when I add the meeting just by clicking directly into the calendar view, no meeting invitation will be sent out to the attendees. Although the attendees are correctly added to the event (I am able to confirm this by using the CalDAV gateway davmail or the Outlook Web App).

Furthermore when I add additional attendes to an existing event, no meeting updates will be sent, too. When deleting a meeting in my calendar, the cancelation messages are sent out correctly.

This problem is specific to calendars managed by the EWS Provider plugin. It would be nice to investigate and fix this issue. Thanks in advance.

We have tested under the following conditions:

Plattform: Linux
Thunderbird: v31.4.0
Lightning: v3.3.2 as well as v3.3.3
EWS Provider: v3.2.2 as well as v3.3.0
Exchange Server: 2013 CU6

**Comment by bavincen** [comment]
Hi is it happening very occasionally? Did you noticed any slow INTERNET connection?

Thanks

**Comment by bavincen** [comment]
Unable to reproduce.. please check our latest code and reopen if that issue happens

**Comment by hamarituc** [comment]
The problem still persists (Thunderbird 31.7.0, Lightning 3.3.3, EWS provider 3.3.2, Exchange 2013 CU8 [15.0.1076.9]). The internet connection is not an issue. The Exchange server and the Thunderbird client are in the same local network.

Lets assume the personal Exchange calendar of user 'A' was already added to Thunderbird via EWS plugin. Try the following steps to reproduce the problem:

1. Open Thunderbird and switch to calendar view.
2. Click "+ Event" in the menu bar to add a new event.
3. Enter a title.
4. Click "Invite Antendees".
5. Enter the email address of user 'B' (which must be an Exchange user too) below the line of user 'A'.
6. Choose a date and time.
7. Click "OK".
8. In the message window click "Save and Close".
9. Open Outlook Web App and login as User 'B'.

Result: User 'B' received an invitation. Everything is fine. Now perform the following steps:

1. Open Thunderbird an switch to calendar view.
2. Add an event to the calendar of user 'A' by dragging with the mouse
3. Enter a title, press ENTER and open the event by double clicking on it
4.-9. Same as above

Result: In this case user 'B' doesn't receive an invitation mail and has no meeting request in his personal calendar. When performing the above steps with a local calendar instead of an Exchange calendar an invitation in both cases.

Furthermore, no meeting updates are sent out. To reproduce perform the following steps:

1. In Thunderbird open the event of the first case from above by double clicking it.
2. Modify date and/or time of the meeting (for example by shifting it one hour).
3. Login to Outlook Web App as user 'B'.

Result: The event is still scheduled at the original time. No meeting update mail was received.
