### ISSUE TITLE
Add calendar : 404 Error

### ISSUE THREAD

**Issue by grahamevens** [Ericsson/exchangecalendar#86]
Hi Everyone, 

Please can you help me to troubleshoot why adding a calendar gives a 404 error.

Error during checking of server and mailbox: HTTP Client error 404: Not found
URL:https://outlook.office365.com/ews/exchange.amsx
 (Code: -19)

The server URL is : https://outlook.office365.com/ews/exchange.amsx

Which I thought was 'standard' for connecting Lightning to an Office365 account.

I am using : 
Lightning v3.3.2
Exchange EWS Provider 3.2.2

Many thanks for any assistance.
Graham

**Comment by grahamevens** [comment]
Please note that the same error is received when a case sensitive address is used also.

URL:https://outlook.office365.com/EWS/Exchange.amsx

**Comment by Mechtilde** [comment]
Hello,

> Error during checking of server and mailbox: HTTP Client error 404: Not found
> URL:https://outlook.office365.com/ews/exchange.amsx
>  (Code: -19)
> 
> The server URL is : https://outlook.office365.com/ews/exchange.amsx

Do you have access via browser? Can you login there?
-- 
Mechtilde Stehmann

## PGP encryption welcome
## Key-ID 0x141AAD7F

**Comment by grahamevens** [comment]
Hi, 

If I enter this URL into a browser : https://outlook.office365.com/ews/exchange.amsx

An .htaccess (style) authentication box pops up.

I enter my Office365 username / password and the authentication is accepted.

However, once authenticated, then browser then goes through to a 'The webpage cannot be found' page, suggesting a 404 error.

This is odd, as several web pages offering setup guides for the exchangecalendar Thunderbird extension suggest that this is the URL to use when adding a Office365 calendar.

I have not yest successfully added a calendar in Thunderbird using this extension as the error comes up each time.

When using the URL : 
 
http://<my-company>/EWS/Exchange.asmx

(where <my-company> is my Office365 domain name) 

I get the following error :

Error during checking of server and mailbox: Error during waiting for data of hostname 'www.eccotours.net'. (STATUS_WAITING_FOR) (Code: -16)

Which was why I was trying to use the 'generic' URL : 
https://outlook.office365.com/ews/exchange.amsx

As suggested on several web sites.

**Comment by bavincen** [comment]
please reopen if that issue still exists

**Comment by kacer** [comment]
I have the same issue. I'm using Outlook.com on custom domain, when I put the correct password, i get 404:
```
Error during checking of server and mailbox: HTTP Client error 404: Not found
URL:https://outlook.office365.com/EWS/Exchange.amsx


 (Code: -19)
```

**Comment by gomezalberto** [comment]
I have the same issue.. any news/updates?

**Comment by grahamevens** [comment]
I no longer use this URL and get to the Exchange Admin screen from the link on my Admin panel.
