### ISSUE TITLE
Correction of Mail Addresses

### ISSUE THREAD

**Issue by Mechtilde** [Ericsson/exchangecalendar#90]
in the files
components/ecExchangeRequest.js
components/erBrowseFolder.js
interfaces/exchangeAuthPromptProvider/mivExchangeAuthPromptProvider.js

There is the old mail address for sending bug reports.

How is the mal adress to this issue tracker?

**Comment by muthusuba** [comment]
@Mechtilde we do not currently have anyone helping us there :( Would be great if you could handle it for us, please? Since you are very good in QA... 
Thank you in advance!

**Comment by Mechtilde** [comment]
I would replace the old one with
https://github.com/Ericsson/exchangecalendar/issues

Is it ok?

**Comment by muthusuba** [comment]
Should be good! Thanks!

**Comment by muthusuba** [comment]
Just a note: It will then not be an email but a link...
