### ISSUE TITLE
3.3.0 RC1 should be called 3.3.1 RC1

### ISSUE THREAD

**Issue by tfft** [Ericsson/exchangecalendar#92]
Hi, not to nit-pick but this Release Candidate (ie. RC) should be for 3.3.1 as the previous version, 3.3.0, has already been released. I suggest you make the correction to name it 3.3.1-RC1 in order not to confuse people.

Keep the great work coming - looking forward to testing the latest code !!

**Comment by muthusuba** [comment]
Done :)
