### ISSUE TITLE
Calendar Invite Sort/Icons

### ISSUE THREAD

**Issue by tfft** [Ericsson/exchangecalendar#93]
Hi, I'm using/testing 3.3.1-RC1 and have the following observation.  The sorting (ie. by clicking on the 'Calendar Invite' sort icon) doesn't seem to work properly in that 'Calendar Invites' are not listed or sorted - not sure what is being sorted or how things are being listed.

I would also suggest using the default calendar icons in lieu of what is there now ![new_odd](https://cloud.githubusercontent.com/assets/10126620/6038952/5de4abe0-ac7b-11e4-915f-b4457d81ac0d.PNG).  In other words, I'd replace the new icons with the stock circular ones (the red "do not enter" sign ![dne](https://cloud.githubusercontent.com/assets/10126620/6038935/1bfa690e-ac7b-11e4-9140-6e7d0c7d9c14.PNG), the green "check mark" ![gok](https://cloud.githubusercontent.com/assets/10126620/6038937/22c3488c-ac7b-11e4-9c0a-e03a9c025eb4.PNG), etc) as they are much clearer and simpler to comprehend.

Thanks for all your hard work !

**Comment by bavincen** [comment]
it would be great if you provide us all the icons :) thanks!

**Comment by tfft** [comment]
What is there now, if the background calendar were to be removed, for each of the icons (ie. accepted.png, cancelled.png, declined.png, tentative.png, updated.png) is fine.  For instance, for cancelled.png it should just be the "do not enter" sign without the background calendar and the two black dots on the left, etc - again, since these icons are small its hard to see too much detail and so its best to keep them very simple.

Do please confirm that sorting is not working as intended.

**Comment by muthusuba** [comment]
Yes, sorting seems to be a problem :( We should get that fixed soon...
[Regarding the icons, I would probably let it be the way it is for now and wait for people to try and comment...hope that is fine, please?]
