### ISSUE TITLE
Meeting request's attachments dissapear for some users

### ISSUE THREAD

**Issue by igalvit** [Ericsson/exchangecalendar#95]
We have installed the 3.3.0 version with Thunderbird 31.3 connected to a Exchange 2013 CU6 platform.
 
Some of my users are claiming that sometimes, when they receive a meeting request with attachments, they are not incluided in the request.  The weirdest issue ocurred yesterday when one of the users sent the same request two times, and nobody could see the attachments, but when she sent the cancellation request, suddenly all the users saw the attachments in the calendar.

Testing the problem, I have found that Thunderbird is sending two emails when you create the meeting request, one without the attachments and the other with them. I don't know if this is the expected behavior, but it seems that this may cause that Lightning is getting mixed up processing them.

**Comment by bavincen** [comment]
please check our lattest addon

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon
