### ISSUE TITLE
Update to 3.3.1 breaks Provider for Google Calendar's Task Functionality

### ISSUE THREAD

**Issue by enozkan** [Ericsson/exchangecalendar#96]
Upon updating to 3.3.1 (rc1 or rc2), the ability of syncing Tasks with Gmail calendars breaks (part of Lightning + Provider for Google Calendar addons). The Error Console shows several warnings that don't show up with older versions of the addon:

Warning: ReferenceError: reference to undefined property this.mSelectedInternal
Source File: chrome://global/content/bindings/menulist.xml
Line: 439

Warning: Expected end of value but found '3'.  Error in parsing value for 'font-family'.  Declaration dropped.
Source File: chrome://calendar/content/calendar-event-dialog.xul
Line: 0, Column: 23
Source Code:
font-family: Wingdings 3 !important;

and several other font-related warnings.

As a result, the New Task window for Google Calendars appear to have inappropriate options, and one cannot create new tasks. Local/non-Google tasks can still be created. I am happy to report a bug for Provider for Google Calendar/Lightning if the issue cannot be fixed here.

Engin

**Comment by enozkan** [comment]
This bug appears to have alleviated with 3.3.1 rc5. I no longer get the font-related errors. What happens, however, is that adding a Google task overrides the regular Google task window, springs the full-blown task window, and includes many options Google tasks do not allow (and that can cause issues, see below), but it works.

(Adding a Google task does break if you have no 'default reminders' specified, and have that option on, so heads up for that.)

Anyway, it is workable now. Thank you.

**Comment by bavincen** [comment]
Hello
Thanks for confirmation
Would you please check the issue already opened related to google provider
If not that please open a issue

Yes its a bug you are unable to add google calendar 
We are fixing it next

Thanks 

-----Original Message-----
