### ISSUE TITLE
Email highlights - Important tag

### ISSUE THREAD

**Issue by tfft** [Ericsson/exchangecalendar#97]
Hi, prior to 3.3.1 (rc1 or rc2) emails coming in with an 'important' tag would be displayed like all other emails (they didn't look any different) with the recent RC's the email is heavily highlighted (red foreground text and orange'ish background).  Would it be possible to give the user the ability to control on how these 'tagged' emails are supposed to be shown ?  For instance, I don't like the background orange color, can I turn it off ?

Here's an image of what I'm talking about just in case.
![tag_highlight](https://cloud.githubusercontent.com/assets/10126620/6078242/8012fc3a-ae10-11e4-8fad-1822c1eb962c.PNG)

**Comment by bavincen** [comment]
Hi we have added preference to enable/disable or choose color.. please check `extras` tab  in 


edit->preferences  

thanks

**Comment by bavincen** [comment]
![screenshot from 2015-02-06 12 19 32](https://cloud.githubusercontent.com/assets/8401561/6078563/6d36bc98-adfa-11e4-8e26-123bc926d959.png)
