### ISSUE TITLE
v3.3.1 RC2 tags serveral of my emails

### ISSUE THREAD

**Issue by MasteRehm** [Ericsson/exchangecalendar#99]
Hi,

I never tag my mails in thunderbird. After the upgrade from EWS Provider 3.3.0 to 3.3.1-rc2 via auto update, some of my mails are tagged, but in very strange behavior:
- Some mails are marked orange. I can't recognize a pattern, why exactly these mails are marked orange. The complete line is marked orange, not only the selected email.
- If I select one of these mails it's automatically tagged red as "important". I can't remove the tag. If I press "1" (shortcut) to remove the label, thunderbird show it as removed, but after select the mail again, it's tagged important again.

As I mentoined, I never tag my mails. So I can't be an old tag or something like that. I decided to downgrade to Ver. 3.3.0 and now it's all fine again.
I'm using thunderbird Ver. 31.4.0 under linux. A colleague of mine using a similiar workstation setup and after upgrading to v3.3.1-rc2 he doesn't have this issue.

I don't know what is triggering this issue/bug, but it's present with rc2 ;)

*Update*
Ahh, this is very similiar to https://github.com/Ericsson/exchangecalendar/issues/97. Sorry, I didn't search the first time under closed issues.
And now I get it: If someone send an email with an "Importance: high" in the header, the mail is marked with the color. 
Unlike my first statement about my colleague, he also have these kind of mails, but less "Importance: high" mails (lucky guy ;) ).

So this isn't a bug, it's a feature ;)

But..., neither my colleague nor I  find the extras tab under preferences. How can we activate it? The Exchange (EWS) tab is visible.

**Comment by bavincen** [comment]
hi
can you please use edit-preference->extras in thunderbird to enable/disable feature.. auto- tagging works on priority mails

**Comment by bavincen** [comment]
its same as #97
